Repository juspay/hyperswitch-control-center, pull requests merged in 2023-12, with the labels that each got.

#61 fix: 3ds code refactor and bugfixes
  .githooks/commit-msg
  .prettierignore
  public/hyperswitch/module.js
  public/hyperswitch/wasm/euclid.d.ts
  public/hyperswitch/wasm/euclid.js
  public/hyperswitch/wasm/euclid_bg.wasm
  public/hyperswitch/wasm/euclid_bg.wasm.d.ts
  src/libraries/Window.res
  src/screens/HyperSwitch/Routing/RoutingUtils.res
  src/screens/HyperSwitch/RoutingRevamp/AdvancedRouting.res
  src/screens/HyperSwitch/RoutingRevamp/AdvancedRoutingUIUtils.res
  src/screens/HyperSwitch/RoutingRevamp/AdvancedRoutingUtils.res
  src/screens/HyperSwitch/RoutingRevamp/Previewers/RulePreviewer.res
  src/screens/HyperSwitch/ThreeDSFlow/HSwitchThreeDS.res
  src/screens/HyperSwitch/ThreeDSFlow/ThreeDSUtils.res
Labels: S-waiting-on-author

#65 fix: commit-msg file changes & README.md file updated.
  .githooks/commit-msg
  .github/PULL_REQUEST_TEMPLATE.md
  .gitignore
  README.md
  src/entryPoints/hyperswitch/EntryPointUtils.res
  src/entryPoints/hyperswitch/Provider/GlobalProvider.res
  src/entryPoints/hyperswitch/Provider/ProviderHelper.res
  src/entryPoints/hyperswitch/Provider/ProviderTypes.res
Labels: S-waiting-on-review

#60 fix: top 5 errors fix
  src/screens/HyperSwitch/Analytics/AnalyticsTypes.res
  src/screens/HyperSwitch/Analytics/ErrorReasons.res
  src/screens/HyperSwitch/Analytics/PaymentsAnalytics/PaymentAnalyticsEntity.res
Labels: S-waiting-on-review

#72 fix: SDK code refactoring and return URL addition
  package.json
  src/screens/HyperSwitch/SDKPayment/SDKPage.res
  src/screens/HyperSwitch/SDKPayment/SDKPaymentTypes.res
  src/screens/HyperSwitch/SDKPayment/SDKPaymentUtils.res
  src/screens/HyperSwitch/SDKPayment/TestPayment.res
Labels: enhancement, S-waiting-on-review

#68 chore: response warnings removed
  src/entryPoints/hyperswitch/WooCommerce/WooCommerce.res
  src/entryPoints/hyperswitch/WooCommerce/WooCommerceUIUtils.res
  src/hooks/ListHooks.res
  src/screens/HyperSwitch/APIUtils/APIUtils.res
  src/screens/HyperSwitch/Analytics/DownloadReportModal.res
  src/screens/HyperSwitch/Analytics/HomePageOverview/HomePageOverviewComponent.res
  src/screens/HyperSwitch/Analytics/SystemMetrics/SystemMetricsAnalytics.res
  src/screens/HyperSwitch/Connectors/ConnectorAccountDetails.res
  src/screens/HyperSwitch/Connectors/ConnectorPreview.res
  src/screens/HyperSwitch/Connectors/Wallets/ApplePayWalletIntegration.res
  src/screens/HyperSwitch/Developer/APIKeys/KeyManagement.res
  src/screens/HyperSwitch/FraudAndRisk/FRMIntegrationFields.res
  src/screens/HyperSwitch/FraudAndRisk/FRMSummary.res
  src/screens/HyperSwitch/HSMixPanel.res
  src/screens/HyperSwitch/HSwitchUtils.res
  src/screens/HyperSwitch/Home/CommonConnectorFlow/ConfigureConnector.res
  src/screens/HyperSwitch/Home/CommonConnectorFlow/QuickStartConnectorFlow.res
  src/screens/HyperSwitch/Home/CommonConnectorFlow/SetupConnector.res
  src/screens/HyperSwitch/Home/DelayedVerificationBanner.res
  src/screens/HyperSwitch/Home/HomeUtils.res
  src/screens/HyperSwitch/Home/HomeV2.res
  src/screens/HyperSwitch/Home/ProdIntent/ProdIntentForm.res
  src/screens/HyperSwitch/Home/ProdIntent/ProdVerifyModal.res
  src/screens/HyperSwitch/Home/QuickStart/GoLive.res
  src/screens/HyperSwitch/Home/QuickStart/IntegrateYourApp/IntegrateYourAppLanding.res
  src/screens/HyperSwitch/Home/QuickStart/IntegrateYourApp/IntegrationDocsPage.res
  src/screens/HyperSwitch/Hooks/EnumVariantHook.res
  src/screens/HyperSwitch/Order/ShowOrder.res
  src/screens/HyperSwitch/Recon/Recon.res
  src/screens/HyperSwitch/Routing/ActiveRouting.res
  src/screens/HyperSwitch/Routing/PriorityRouting.res
  src/screens/HyperSwitch/Routing/RoutingUtils.res
  src/screens/HyperSwitch/Routing/VolumeSplitRouting.res
  src/screens/HyperSwitch/RoutingRevamp/AdvancedRouting.res
  src/screens/HyperSwitch/SDKPayment/TestPayment.res
  src/screens/HyperSwitch/SelfServe/HSwitchProdOnboarding/HSwitchAgreementScreen.res
  src/screens/HyperSwitch/SelfServe/HSwitchProdOnboarding/LiveEndpointsSetup.res
  src/screens/HyperSwitch/SelfServe/HSwitchProdOnboarding/ProdOnboardingLanding.res
  src/screens/HyperSwitch/SelfServe/HSwitchProdOnboarding/ProdOnboardingUIUtils.res
  src/screens/HyperSwitch/SelfServe/HSwitchProdOnboarding/SetupConnectorCredentials.res
  src/screens/HyperSwitch/SelfServe/HSwitchSandboxOnboarding/UserOnboarding.res
  src/screens/HyperSwitch/SelfServe/HSwitchSandboxOnboarding/UserOnboardingUIUtils.res
  src/screens/HyperSwitch/Settings/BusinessMapping/BusinessProfile.res
  src/screens/HyperSwitch/Settings/HSwitchProfileSettings.res
  src/screens/HyperSwitch/SetupAccount/HSwitchSetupAccount.res
  src/screens/HyperSwitch/StripePlusPaypal/StripePlusPaypalUIUtils.res
  src/screens/HyperSwitch/SwitchMerchant/SwitchMerchant.res
  src/screens/HyperSwitch/ThreeDSFlow/HSwitchThreeDS.res
  src/screens/HyperSwitch/UserManagement/HSwitchInviteUsers.res
  src/screens/HyperSwitch/UserManagement/HSwitchShowUserData.res
  src/screens/HyperSwitch/Utils/HSwitchVerticalStepper.res
  src/screens/login/HSwitchLoginFlow/HyperSwitchAuth.res
  src/screens/login/HSwitchLoginFlow/HyperSwitchAuthTypes.res
  src/utils/DateTimeUtils.res
  src/utils/DownloadUtils.res
  src/utils/HSwitchGlobalVars.res
Labels: S-waiting-on-review

#46 feat: new connector Icons and Searchbar for connector
  public/hyperswitch/Gateway/ACI.svg
  public/hyperswitch/Gateway/ADYEN.svg
  public/hyperswitch/Gateway/AIRWALLEX.svg
  public/hyperswitch/Gateway/AUTHORIZEDOTNET.svg
  public/hyperswitch/Gateway/BAMBORA.svg
  public/hyperswitch/Gateway/BANKOFAMERICA.svg
  public/hyperswitch/Gateway/BITPAY.svg
  public/hyperswitch/Gateway/BLUESNAP.svg
  public/hyperswitch/Gateway/BRAINTREE,.svg
  public/hyperswitch/Gateway/BRAINTREE.svg
  public/hyperswitch/Gateway/CASHTOCODE.svg
  public/hyperswitch/Gateway/CHECKOUT.svg
  public/hyperswitch/Gateway/COINBASE.svg
  public/hyperswitch/Gateway/CRYPTOPAY.svg
  public/hyperswitch/Gateway/CYBERSOURCE.svg
  public/hyperswitch/Gateway/DLOCAL.svg
  public/hyperswitch/Gateway/FISERV.svg
  public/hyperswitch/Gateway/FORTE.svg
  public/hyperswitch/Gateway/GLOBALPAY.svg
  public/hyperswitch/Gateway/GLOBEPAY.svg
  public/hyperswitch/Gateway/GOCARDLESS.svg
  public/hyperswitch/Gateway/IATAPAY.svg
  public/hyperswitch/Gateway/KLARNA.svg
  public/hyperswitch/Gateway/MOLLIE.svg
  public/hyperswitch/Gateway/MULTISAFEPAY.svg
  public/hyperswitch/Gateway/NEXINETS.svg
  public/hyperswitch/Gateway/NMI.svg
  public/hyperswitch/Gateway/NOON.svg
  public/hyperswitch/Gateway/NUVEI.svg
  public/hyperswitch/Gateway/OPENNODE.svg
  public/hyperswitch/Gateway/PAYME.svg
  public/hyperswitch/Gateway/PAYPAL.svg
  public/hyperswitch/Gateway/PAYU.svg
  public/hyperswitch/Gateway/POWERTRANZ.svg
  public/hyperswitch/Gateway/PROPHETPAY.svg
  public/hyperswitch/Gateway/RAPYD.svg
  public/hyperswitch/Gateway/SHIFT4.svg
  public/hyperswitch/Gateway/STAX.svg
  public/hyperswitch/Gateway/STRIPE.svg
  public/hyperswitch/Gateway/TRUSTPAY.svg
  public/hyperswitch/Gateway/TSYS.svg
  public/hyperswitch/Gateway/VOLT.svg
  public/hyperswitch/Gateway/WORLDLINE.svg
  public/hyperswitch/Gateway/WORLDPAY.svg
  public/hyperswitch/Gateway/ZEN.svg
  src/components/priority-logics/AddPLGateway.res
  src/screens/HyperSwitch/Connectors/ConnectorAccountDetails.res
  src/screens/HyperSwitch/Connectors/ConnectorList.res
  src/screens/HyperSwitch/Connectors/ConnectorPaymentMethod.res
  src/screens/HyperSwitch/Connectors/ConnectorPreview.res
  src/screens/HyperSwitch/Connectors/ConnectorWebhooks.res
  src/screens/HyperSwitch/HSwitchRemoteFilter.res
  src/screens/HyperSwitch/Utils/HSwitchGlobalSearchBar.res
  src/utils/LogicUtils.res
Labels: S-waiting-on-review

#74 fix: SDK Go to payment fix in Success Status
  src/components/PaginationRevamp.res
  src/components/RemoteFilter.res
  src/screens/HyperSwitch/Home/CommonConnectorFlow/ConfigureConnector.res
  src/screens/HyperSwitch/SDKPayment/SDKPage.res
  src/screens/HyperSwitch/SDKPayment/TestPayment.res
  src/screens/HyperSwitch/UserManagement/HSwitchInviteUsers.res
  src/screens/HyperSwitch/UserManagement/HSwitchUserManagementUtils.res
  src/screens/HyperSwitch/UserManagement/HSwitchUserRoleShowData.res
  src/utils/LogicUtils.res
Labels: S-waiting-on-review

#76 chore: User Management File Changes
  src/entryPoints/hyperswitch/HyperSwitchApp.res
  src/screens/HyperSwitch/UserManagement/InviteUsers.res
  src/screens/HyperSwitch/UserManagement/ShowUserData.res
  src/screens/HyperSwitch/UserManagement/UserManagementUtils.res
  src/screens/HyperSwitch/UserManagement/UserRoleEntity.res
  src/screens/HyperSwitch/UserManagement/UserRoleEntry.res
  src/screens/HyperSwitch/UserManagement/UserRoleShowData.res
Labels: S-waiting-on-review

#77 fix: Payment settings added under developers
  src/entryPoints/hyperswitch/HyperSwitchApp.res
  src/entryPoints/hyperswitch/SidebarValues.res
  src/entryPoints/hyperswitch/WooCommerce/WooCommerce.res
  src/screens/HyperSwitch/Developer/PaymentSettings/PaymentSettings.res
  src/screens/HyperSwitch/Developer/PaymentSettings/PaymentSettingsList.res
  src/screens/HyperSwitch/Developer/PaymentSettings/PaymentSettingsListEntity.res
  src/screens/HyperSwitch/SelfServe/HSwitchSandboxOnboarding/UserOnboardingUIUtils.res
  src/screens/HyperSwitch/Settings/BusinessMapping/BusinessMappingEntity.res
Labels: S-waiting-on-review

#81 fix: hide connector sr
  src/screens/HyperSwitch/Analytics/PaymentsAnalytics/PaymentAnalytics.res
  src/screens/HyperSwitch/Analytics/PaymentsAnalytics/PaymentAnalyticsEntity.res
Labels: S-waiting-on-review

#83 feat: refunds search based on refunds id
  src/screens/HyperSwitch/Refunds/Refund.res
Labels: S-waiting-on-review

#85 fix: Recoil value for feature flag updated
  src/entryPoints/hyperswitch/HyperSwitchApp.res
  src/entryPoints/hyperswitch/HyperSwitchEntry.res
  src/entryPoints/hyperswitch/HyperswitchAtom.res
  src/screens/HyperSwitch/Analytics/Analytics.res
  src/screens/HyperSwitch/Analytics/HomePageOverview/HomePageOverviewComponent.res
  src/screens/HyperSwitch/Analytics/PaymentsAnalytics/PaymentAnalytics.res
  src/screens/HyperSwitch/Connectors/ConnectorAccountDetails.res
  src/screens/HyperSwitch/Connectors/ConnectorAccountDetailsHelper.res
  src/screens/HyperSwitch/Connectors/ConnectorList.res
  src/screens/HyperSwitch/Connectors/ConnectorPreview.res
  src/screens/HyperSwitch/Disputes/Disputes.res
  src/screens/HyperSwitch/FraudAndRisk/FRMConfigure.res
  src/screens/HyperSwitch/FraudAndRisk/FRMIntegrationFields.res
  src/screens/HyperSwitch/HSMixPanel.res
  src/screens/HyperSwitch/Home/CommonConnectorFlow/SetupConnector.res
  src/screens/HyperSwitch/Home/HomeUtils.res
  src/screens/HyperSwitch/Home/HomeV2.res
  src/screens/HyperSwitch/Order/OrderUIUtils.res
  src/screens/HyperSwitch/Order/Orders.res
  src/screens/HyperSwitch/Order/ShowOrder.res
  src/screens/HyperSwitch/Refunds/Refund.res
  src/screens/HyperSwitch/SelfServe/HSwitchProdOnboarding/SetupConnectorCredentials.res
  src/screens/HyperSwitch/Settings/HSwitchSettings.res
  src/screens/HyperSwitch/Utils/HSwitchGlobalSearchBar.res
  src/screens/login/HSwitchLoginFlow/HyperSwitchAuth.res
  src/screens/login/HSwitchLoginFlow/HyperSwitchAuthScreen.res
  src/screens/login/HSwitchLoginFlow/HyperSwitchAuthUtils.res
Labels: S-waiting-on-review

#82 fix: Added configure return url after business profile
  src/screens/HyperSwitch/Settings/BusinessMapping/BusinessMappingUtils.res
  src/screens/HyperSwitch/Settings/BusinessMapping/BusinessProfile.res
Labels: S-in-progress

#88 fix: SDK Processing - Go to payments not working fix
  src/screens/HyperSwitch/SDKPayment/TestPayment.res
Labels: S-waiting-on-review

#89 feat: Identity file changes in Codebase.
  src/components/CustomCharts/HighchartHorizontalBarChart.res
  src/components/CustomCharts/HighchartPieChart.res
  src/components/CustomCharts/HighchartTimeSeriesChart.res
  src/components/CustomExpandableTable.res
  src/components/DynamicTableUtils.res
  src/components/LocalFilters.res
  src/components/RemoteFilter.res
  src/components/SelectModal.res
  src/components/Table.res
  src/components/Table.resi
  src/components/TableUtils.res
  src/components/TableUtils.resi
  src/components/form/SelectBoxCard.res
  src/components/priority-logics/AddPLGateway.res
  src/components/priority-logics/PriorityLogicUtils.res
  src/entities/analytics/IntegrationsEntity.res
  src/genericUtils/DOMUtils.res
  src/genericUtils/Identity.res
  src/hooks/AuthHooks.res
  src/libraries/Jose.res
  src/screens/HyperSwitch/Analytics/Analytics.res
  src/screens/HyperSwitch/Analytics/DownloadReportModal.res
  src/screens/HyperSwitch/Analytics/HSAnalyticsUtils.res
  src/screens/HyperSwitch/Connectors/ConnectorAccountDetails.res
  src/screens/HyperSwitch/FraudAndRisk/FRMIntegrationFields.res
  src/screens/HyperSwitch/FraudAndRisk/FRMPaymentMethods.res
  src/screens/HyperSwitch/FraudAndRisk/FRMUtils.res
  src/screens/HyperSwitch/HSwitchUtils.res
  src/screens/HyperSwitch/Order/OrderUIUtils.res
  src/screens/HyperSwitch/Refunds/RefundUtils.res
  src/screens/HyperSwitch/Routing/RoutingStack.res
  src/screens/HyperSwitch/RoutingRevamp/AddRuleGateway.res
  src/screens/HyperSwitch/RoutingRevamp/AdvancedRouting.res
  src/screens/HyperSwitch/RoutingRevamp/AdvancedRoutingUIUtils.res
  src/screens/HyperSwitch/RoutingRevamp/AdvancedRoutingUtils.res
  src/screens/HyperSwitch/SDKPayment/SDKPage.res
  src/screens/HyperSwitch/SDKPayment/TestPayment.res
  src/screens/HyperSwitch/SDKPayment/WebSDK.res
  src/screens/HyperSwitch/ThreeDSFlow/HSwitchThreeDS.res
  src/screens/HyperSwitch/ThreeDSFlow/ThreeDSUtils.res
  src/screens/analyticsScreens/AnalyticsCommonComponents.res
  src/server/Server.res
  src/utils/FullscreenUtils.res
Labels: S-waiting-on-review

#90 feat: Webhook Section Update - In Connector Preview
  public/hyperswitch/icons/solid.svg
  src/screens/HyperSwitch/Connectors/ConnectorAccountDetails.res
  src/screens/HyperSwitch/Connectors/ConnectorHome.res
  src/screens/HyperSwitch/Connectors/ConnectorPreview.res
  src/screens/HyperSwitch/Connectors/ConnectorTypes.res
  src/screens/HyperSwitch/Connectors/ConnectorUtils.res
  src/screens/HyperSwitch/Connectors/ConnectorWebhooks.res
  src/screens/HyperSwitch/FraudAndRisk/FRMConfigure.res
  src/screens/HyperSwitch/FraudAndRisk/FRMInfo.res
  src/screens/HyperSwitch/FraudAndRisk/FRMIntegrationFields.res
  src/screens/HyperSwitch/FraudAndRisk/FRMSummary.res
  src/screens/HyperSwitch/Home/CommonConnectorFlow/SetupConnector.res
Labels: S-waiting-on-review

#91 feat: Identity file changes
  src/components/ButtonGroupIp.res
  src/components/CsvFileUpload.res
  src/components/CustomCharts/HighchartBarChart.res
  src/components/CustomCharts/LineChartUtils.res
  src/components/DatePicker.res
  src/components/DistributionDonut/DistributionDonut.res
  src/components/ExportTable.res
  src/components/HSwitchSingleStatWidget.res
  src/components/HighchartFunnelChart.res
  src/components/InputFields.res
  src/components/InputFields.resi
  src/components/RedirectSearchInput.res
  src/components/SelectBox.res
  src/components/SelectBox.resi
  src/components/form/MultipleTextInput.res
  src/components/form/SelectBoxCard.res
  src/entities/analytics/EulerAnalyticsLogUtils.res
  src/genericUtils/Identity.res
  src/libraries/Highcharts.res
  src/libraries/SankeyHighcharts.res
  src/screens/HyperSwitch/Analytics/Analytics.res
  src/screens/HyperSwitch/RoutingRevamp/AdvancedRouting.res
  src/screens/HyperSwitch/RoutingRevamp/AdvancedRoutingUIUtils.res
  src/screens/HyperSwitch/SDKPayment/SDKPage.res
  src/screens/HyperSwitch/ThreeDSFlow/HSwitchThreeDS.res
  src/screens/analyticsScreens/AnalyticsCommonComponents.res
Labels: S-waiting-on-review

#92 refactor: dead code removal.
  src/components/MultiLineInputBox.res
  src/components/NProgressIndicator.res
  src/components/Navbar.res
  src/components/NewCalendarList.res
  src/components/NewDateRangePicker.res
  src/components/NewPagination.res
  src/components/NoDataFound.res
  src/components/NoteUI.res
  src/components/Pagination.res
  src/components/PaginationRevamp.res
  src/components/PopOver.res
  src/components/RedirectSearchInput.res
  src/components/RemoteFiltersUtils.res
  src/components/RouterTabs.res
  src/components/SDKFunnelChart.res
  src/components/SankeyUtils.res
  src/components/SectionAccordion.res
  src/components/ServerComponent.res
  src/components/SidebarStyleUtils.res
  src/components/StagedProgressBar.res
  src/components/StaticTable.res
  src/components/SynchronizedCharts.res
  src/components/ThemeSelector.res
  src/components/ThemeToggle.res
  src/components/TimeInput.res
  src/components/TimeRangeInput.res
  src/components/TimeRangeInputUtils.res
  src/components/Timer.res
  src/components/TopActions.res
  src/components/UploadImage.res
  src/entryPoints/hyperswitch/HyperSwitchApp.res
  src/genericUtils/AtomsStorage.res
  src/genericUtils/BreadCrumbNavigation.res
  src/genericUtils/UseEvent.res
  src/hooks/AnalyticsHooks.res
  src/hooks/AuthHooks.res
  src/hooks/DateRefreshHooks.res
  src/hooks/ModalsState.res
  src/hooks/NewThemeHooks.res
  src/screens/analyticsScreens/AnalyticsCommonComponents.res
Labels: S-waiting-on-review

#93 feat: Routing back to Integration Fields if Connector Label already exist.
  src/screens/HyperSwitch/Connectors/ConnectorPaymentMethod.res
Labels: S-waiting-on-review

#56 feat: sub steps
  package-lock.json
  src/screens/HyperSwitch/Home/QuickStart/IntegrateYourApp/IntegrateFromScratch.res
  src/screens/HyperSwitch/Home/QuickStart/IntegrateYourApp/IntegrateYourAppUtils.res
  src/screens/HyperSwitch/Home/QuickStart/IntegrateYourApp/MigrateFromStripe.res
  src/screens/HyperSwitch/Home/QuickStart/QuickStartTypes.res
  src/screens/HyperSwitch/Home/QuickStart/QuickStartUtils.res
  src/screens/HyperSwitch/Hooks/EnumVariantHook.res
Labels: S-waiting-on-review

#84 feat: default id for connector label
  public/hyperswitch/icons/solid.svg
  src/components/tooltip/ToolTip.res
  src/screens/HyperSwitch/Connectors/ConnectorAccountDetails.res
  src/screens/HyperSwitch/Connectors/ConnectorAccountDetailsHelper.res
  src/screens/HyperSwitch/Connectors/ConnectorTableUtils.res
Labels: S-waiting-on-review

#94 feat: Refund enable for Partially Captured Payments
  src/screens/HyperSwitch/Order/HSwitchOrderUtils.res
  src/screens/HyperSwitch/Order/OrderEntity.res
  src/screens/HyperSwitch/Order/ShowOrder.res
Labels: S-waiting-on-review

#95 fix: connector label and profile id default value fix
  src/screens/HyperSwitch/Home/CommonConnectorFlow/ConfigureConnector.res
  src/screens/HyperSwitch/Home/CommonConnectorFlow/SetupConnector.res
  src/screens/HyperSwitch/SelfServe/HSwitchProdOnboarding/SetupConnectorCredentials.res
Labels: S-waiting-on-review

#96 feat: getDescriptionCategory function added.
  public/hyperswitch/module.js
  public/hyperswitch/wasm/euclid_bg.wasm
  src/libraries/Window.res
  src/screens/HyperSwitch/Connectors/ConnectorUtils.res
  src/screens/HyperSwitch/Connectors/Wallets/Wallet.res
  src/utils/LogicUtils.res
  src/utils/MapTypes.res
Labels: S-waiting-on-review

#98 refactor: Refactoring key errors
  src/components/ButtonGroupIp.res
  src/components/Chip.res
  src/components/CollapsableTableRow.res
  src/genericUtils/BreadCrumbNavigation.res
  src/screens/HyperSwitch/Routing/AdvancedRouting/RoutingPreviewer.res
  src/screens/HyperSwitch/RoutingRevamp/AddRuleGateway.res
  src/screens/HyperSwitch/RoutingRevamp/AdvancedRoutingUIUtils.res
  src/screens/HyperSwitch/SwitchMerchant/SwitchMerchant.res
  src/screens/HyperSwitch/ThreeDSFlow/HSwitchThreeDS.res
  src/screens/HyperSwitch/Utils/HSSelfServeSidebar.res
Labels: S-waiting-on-review

#100 refactor: Refactoring key errors
  src/components/CustomExpandableTable.res
  src/components/DynamicSingleStat.res
  src/components/SelectBox.res
  src/components/Table.res
  src/components/tooltip/ToolTip.res
  src/screens/HyperSwitch/Connectors/ConnectorAccountDetailsHelper.res
  src/screens/HyperSwitch/FraudAndRisk/FRMPaymentMethods.res
  src/screens/HyperSwitch/FraudAndRisk/FRMSummary.res
  src/screens/HyperSwitch/RoutingRevamp/AdvancedRouting.res
  src/screens/HyperSwitch/Settings/BusinessDetails.res
Labels: S-waiting-on-review

#103 feat: Show Orders Enhancements & sidebar value changes
  src/entryPoints/hyperswitch/SidebarValues.res
  src/screens/HyperSwitch/Order/OrderEntity.res
  src/screens/HyperSwitch/Order/OrderTypes.res
  src/screens/HyperSwitch/Order/ShowOrder.res
  src/screens/HyperSwitch/SDKPayment/TestCredentials.res
Labels: S-waiting-on-review

#97 feat: group-drop-down-component-changes
  src/components/InputFields.res
  src/components/InputFields.resi
  src/components/SelectBox.res
  src/components/SelectBox.resi
Labels: S-waiting-on-review

#112 feat: added path and api method in audit logs
  src/screens/HyperSwitch/PaymentLogs/PaymentLogs.res
Labels: S-waiting-on-review

#87 fix: oss build url change
  src/components/HSwitchFeedBackModal.res
  src/entryPoints/hyperswitch/FeatureFlagUtils.res
  src/entryPoints/hyperswitch/HyperSwitchApp.res
  src/entryPoints/hyperswitch/WooCommerce/WooCommerceUIUtils.res
  src/screens/HyperSwitch/APIUtils/APIUtils.res
  src/screens/HyperSwitch/APIUtils/APIUtilsTypes.res
  src/screens/HyperSwitch/HSwitchUtils.res
  src/screens/HyperSwitch/Home/CommonConnectorFlow/ConfigureConnector.res
  src/screens/HyperSwitch/Home/CommonConnectorFlow/QuickStartConnectorFlow.res
  src/screens/HyperSwitch/Home/HomeUtils.res
  src/screens/HyperSwitch/Home/HomeV2.res
  src/screens/HyperSwitch/Home/ProdIntent/ProdIntentForm.res
  src/screens/HyperSwitch/Home/ProdIntent/ProdVerifyModal.res
  src/screens/HyperSwitch/Home/QuickStart/GoLive.res
  src/screens/HyperSwitch/Home/QuickStart/IntegrateYourApp/IntegrationDocsPage.res
  src/screens/HyperSwitch/Home/QuickStart/QuickStartTypes.res
  src/screens/HyperSwitch/Home/QuickStart/QuickStartUIUtils.res
  src/screens/HyperSwitch/Home/QuickStart/QuickStartUtils.res
  src/screens/HyperSwitch/Routing/ActiveRouting.res
  src/screens/HyperSwitch/SelfServe/HSwitchProdOnboarding/ProdOnboardingUtils.res
  src/screens/HyperSwitch/SelfServe/HSwitchSandboxOnboarding/IntegrationDocs.res
  src/screens/login/HSwitchLoginFlow/HyperSwitchAuth.res
Labels: S-in-progress

#114 feat: new wasm changes
  public/hyperswitch/wasm/euclid.d.ts
  public/hyperswitch/wasm/euclid.js
  public/hyperswitch/wasm/euclid_bg.wasm
  public/hyperswitch/wasm/euclid_bg.wasm.d.ts
  public/hyperswitch/wasm/package.json
Labels: S-waiting-on-review

#102 feat: dropdown grouping added in routing
  src/screens/HyperSwitch/RoutingRevamp/AdvancedRoutingUIUtils.res
Labels: S-waiting-on-review

#116 fix: Signout API removed.
  src/screens/HyperSwitch/APIUtils/APIUtils.res
  src/screens/HyperSwitch/Home/HomeUtils.res
  src/screens/HyperSwitch/Sidebar/Sidebar.res
Labels: S-waiting-on-review

#115 fix: Connector files changes for paypal onboarding
  src/screens/HyperSwitch/Connectors/ConnectorAccountDetails.res
  src/screens/HyperSwitch/Connectors/ConnectorAccountDetailsHelper.res
  src/screens/HyperSwitch/Connectors/ConnectorTableUtils.res
  src/screens/HyperSwitch/Connectors/ConnectorTypes.res
  src/screens/HyperSwitch/Connectors/ConnectorUtils.res
  src/screens/HyperSwitch/FraudAndRisk/FRMIntegrationFields.res
  src/screens/HyperSwitch/Home/CommonConnectorFlow/SetupConnector.res
  src/screens/HyperSwitch/SelfServe/HSwitchProdOnboarding/SetupConnectorCredentials.res
Labels: S-waiting-on-review

#117 fix: metadata field issue fix
  src/screens/HyperSwitch/RoutingRevamp/AdvancedRoutingUIUtils.res
  src/screens/HyperSwitch/RoutingRevamp/Previewers/RulePreviewer.res
Labels: S-waiting-on-review

#119 fix: refunds reports end point change
  src/screens/HyperSwitch/Analytics/Analytics.res
  src/screens/HyperSwitch/Analytics/DownloadReportModal.res
  src/screens/HyperSwitch/Analytics/PaymentsAnalytics/PaymentAnalytics.res
  src/screens/HyperSwitch/Analytics/RefundsAnalytics/RefundsAnalytics.res
Labels: S-waiting-on-review

#121 feat: Resend Invite Removal
  src/screens/HyperSwitch/APIUtils/APIUtils.res
  src/screens/HyperSwitch/UserManagement/ShowUserData.res
Labels: S-waiting-on-review

#126 feat: Sidebar expansion close
  src/screens/HyperSwitch/Sidebar/Sidebar.res
Labels: S-waiting-on-review

#120 fix: Removed Sublevel remote link type & Pageloader CSS fixes.
  src/screens/HyperSwitch/Sidebar/Sidebar.res
  src/screens/HyperSwitch/Sidebar/SidebarTypes.res
  src/screens/HyperSwitch/Utils/HSwitchGlobalSearchBar.res
  src/screens/HyperSwitch/Utils/PageLoaderWrapper.res
Labels: S-waiting-on-review

#101 chore: Auth page UI changes
  cypress/e2e/auth/auth.cy.js
  package-lock.json
  public/hyperswitch/icons/juspay-logo-dark.svg
  src/components/form/FormRenderer.res
  src/screens/login/HSwitchLoginFlow/HyperSwitchAuth.res
  src/screens/login/HSwitchLoginFlow/HyperSwitchAuthScreen.res
  src/screens/login/HSwitchLoginFlow/HyperSwitchAuthUtils.res
Labels: S-waiting-on-review

#129 feat: Table wrap changes & sidebar version removed
  src/components/TableUtils.res
  src/screens/HyperSwitch/APIUtils/APIUtils.res
  src/screens/HyperSwitch/HSwitchUtils.res
  src/screens/HyperSwitch/Order/OrderEntity.res
  src/screens/HyperSwitch/Sidebar/Sidebar.res
  src/screens/HyperSwitch/UserManagement/UserRoleEntry.res
Labels: S-waiting-on-review

#125 Refactor: remove dead code
  src/components/Carousel.res
  src/components/ChangePassword.res
  src/components/DeletePopUpConfirm.res
  src/components/DetailsEntity.res
  src/components/DistributionDonut/DistributionDonut.res
  src/components/DonutProgress.res
  src/components/DownloadSelectModal.res
  src/components/DynamicTableUtils.res
  src/components/EntityDetails.res
  src/components/EntityScaffold.res
  src/components/FloatingActionButton.res
  src/components/FloatingElement.res
  src/components/FullscreenOverlay.res
  src/components/HighchartFunnelChart.res
  src/components/InputFields.resi
  src/components/IntersectionObserver.res
  src/components/JsonUploadFile.res
  src/components/MakeRuleFieldComponent.res
  src/components/MultiImageViewer.res
  src/components/NewThemeUtils.res
  src/components/NewThemeUtils.resi
  src/components/RedirectSearchInput.res
  src/components/RestrictedWidthInput.res
  src/components/SankeyCharts.res
  src/components/SelectBox.resi
  src/components/Tag.res
  src/components/form/ComboInputField.res
  src/components/form/FormRenderer.res
  src/components/form/ObjectArrayEditor.res
  src/components/form/OtpInput.res
  src/components/form/PasswordStrengthInputAsChips.res
  src/components/form/SelectBoxCard.res
  src/context/AuthInfoProviderForBeckn.res
  src/context/ChartContext.res
  src/context/DashboardModeContext.res
  src/context/DashboardViewContext.res
  src/context/RestrictedWidthProvider.res
  src/context/SaveViewContext.res
  src/context/TempContext.res
  src/context/WizardContext.res
Labels: S-waiting-on-review

#130 fix: Warnings removed
  src/components/InputFields.res
  src/components/SelectBox.res
Labels: S-waiting-on-review

#122 refactor: apiUtils file to use the apiPrefix once only
  src/screens/HyperSwitch/APIUtils/APIUtils.res
  src/screens/HyperSwitch/APIUtils/APIUtilsTypes.res
Labels: S-waiting-on-review

#132 fix: fixedPageWidth Changes
  public/hyperswitch/icons/solid.svg
  src/components/TableUtils.res
  src/entryPoints/hyperswitch/HyperSwitchApp.res
  tailwindHyperSwitch.config.js
Labels: S-waiting-on-review

#134 feat: README.md PR title changes
  README.md
Labels: S-waiting-on-review

#135 fix: APIUtils changes
  src/screens/HyperSwitch/APIUtils/APIUtils.res
  src/screens/HyperSwitch/APIUtils/APIUtilsTypes.res
Labels: S-waiting-on-review

#136 fix: API fix and radio icon changes
  public/hyperswitch/icons/solid.svg
  src/screens/HyperSwitch/APIUtils/APIUtils.res
Labels: S-waiting-on-review

#137 fix: Page scroll issue fix and connector card css fix
  src/screens/HyperSwitch/Analytics/Analytics.res
  src/screens/HyperSwitch/Analytics/SystemMetrics/SystemMetricsAnalytics.res
  src/screens/HyperSwitch/Analytics/UserAnalytics/UserJourneyAnalytics.res
  src/screens/HyperSwitch/Connectors/ConnectorList.res
  src/screens/HyperSwitch/Developer/APIKeys/KeyManagement.res
  src/screens/HyperSwitch/HSwitchUtils.res
  src/screens/HyperSwitch/Refunds/Refund.res
  src/screens/HyperSwitch/Routing/RoutingStack.res
Labels: S-waiting-on-review

#139 fix: Stripe Paypal Profile Issue
  src/screens/HyperSwitch/Home/CommonConnectorFlow/SetupConnector.res
  src/screens/HyperSwitch/SelfServe/HSwitchProdOnboarding/SetupConnectorCredentials.res
  src/screens/HyperSwitch/StripePlusPaypal/StripePlusPaypalUIUtils.res
Labels: S-waiting-on-review

#144 fix: Removed console log form prod
  src/components/AdvancedSearchComponent.res
  src/components/DynamicSingleStat.res
  src/components/SelectModal.res
  src/hooks/TimeZoneHook.res
  src/screens/HyperSwitch/Routing/VolumeSplitRouting.res
  webpack.prod.js
Labels: S-waiting-on-review

#140 feat: Sentry Removal & Error Boundary Added
  package-lock.json
  package.json
  src/components/ErrorBoundary.res
  src/entryPoints/hyperswitch/EntryPointUtils.res
  src/libraries/Sentry.res
Labels: S-waiting-on-review

#143 chore: package removal
  .gitignore
  package-lock.json
  package.json
  src/components/BaseDonutProgress.res
  src/libraries/Jose.res
  src/libraries/RSADecryptor.res
  src/libraries/ReactFlameGraph.res
  src/libraries/ReactQrCode.res
  src/libraries/ReactQrCodeLogo.res
  src/libraries/UAParser.res
Labels: S-waiting-on-review

#149 fix: Enabled invite users
  src/screens/HyperSwitch/UserManagement/UserRoleEntry.res
Labels: S-waiting-on-review

#150 fix: connnector status UI changes
  src/screens/HyperSwitch/Connectors/ConnectorPreview.res
  src/screens/HyperSwitch/Connectors/ConnectorTableUtils.res
Labels: S-waiting-on-review

#151 fix: Text overlap issue fix
  src/components/TableUtils.res
Labels: S-waiting-on-review
