Repository juspay/hyperswitch-control-center, pull requests merged in 2024-11, with the labels that each got.

#1635 refactor: resource-access-added
  src/Recoils/HyperswitchAtom.res
  src/container/MerchantAccountContainer.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/SidebarValues.res
  src/screens/APIUtils/APIUtils.res
  src/screens/Developer/APIKeys/KeyManagement.res
  src/screens/Developer/PaymentSettings/PaymentSettingsList.res
  src/screens/GenerateReports/GenerateReport.res
  src/screens/Hooks/GroupACLHooks.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/Processors/ProcessorCards.res
  src/screens/Settings/BusinessDetails.res
  src/screens/Settings/BusinessMapping/BusinessProfile.res
  src/screens/UserManagement/UserRevamp/UserManagementTypes.res
  src/utils/Mappers/GroupACLMapper.res
Labels: core

#1681 Refactor: Invite user api restructure v2
  src/screens/APIUtils/APIUtils.res
  src/screens/UserManagement/UserRevamp/NewUserInvitationForm.res
  src/screens/UserManagement/UserRevamp/UserManagementTypes.res
  src/screens/UserManagement/UserRevamp/UserUtils.res
Labels: core

#1679 feat: enable comparison filter in new analytics
  cypress/e2e/connector/connector.cy.js
  src/components/DateRangeCompareFields.res
  src/components/DateRangeField.res
  src/screens/NewAnalytics/NewAnalyticsTypes.res
  src/screens/NewAnalytics/PaymentAnalytics/FailedPaymentsDistribution/FailedPaymentsDistribution.res
  src/screens/NewAnalytics/PaymentAnalytics/FailedPaymentsDistribution/FailedPaymentsDistributionUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycle.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycleUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSection.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionHelper.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRate.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRateUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistribution.res
  src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistributionUtils.res
Labels: analytics

#1676 fix: remove dispute stage col
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/Disputes/DisputeTableEntity.res
  src/screens/Disputes/DisputeTypes.res
  src/screens/Disputes/DisputesEntity.res
  src/screens/Disputes/DisputesUtils.res
Labels: S-waiting-on-review

#1671 fix: analytics sessionizer bugs
  src/screens/Analytics/PaymentsAnalytics/PaymentAnalytics.res
  src/screens/Analytics/PaymentsAnalytics/SmartRetryAnalytics.res
  src/screens/NewAnalytics/NewAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRate.res
Labels: S-waiting-on-review, bug

#1651 chore: TwoFa restriction after multiple failed attempts after logging in
  src/entryPoints/AuthModule/Common/CommonAuthTypes.res
  src/entryPoints/AuthModule/Common/CommonAuthUtils.res
  src/entryPoints/AuthModule/TwoFaAuth/TotpSetup.res
  src/entryPoints/AuthModule/TwoFaAuth/TwoFaLanding.res
  src/screens/Settings/HSwitchProfile/TwoFaSettings/ModifyTwoFaSettings.res
  src/screens/Settings/HSwitchProfile/TwoFaSettings/RegenerateRC.res
  src/screens/Settings/HSwitchProfile/TwoFaSettings/ResetTotp.res
  src/screens/Settings/HSwitchProfile/TwoFaSettings/TwoFaHelper.res
Labels: chore

#1677 test: verification of search in payment operations page using cypress
  cypress/e2e/connector/connector.cy.js
Labels: hacktoberfest, hacktoberfest-accepted

#1657 chore: disable cookies from frontend
  src/hooks/AuthHooks.res
  webpack.dev.js
Labels: S-waiting-on-review, core

#1692 fix: compare filter date display fix to ISO format
  src/components/DateRangeCompareFields.res
  src/components/DateRangeHelper.res
Labels: S-waiting-on-review, analytics

#1691 feat: analytics payment processed currency conversion
  src/screens/NewAnalytics/Graphs/LineGraph/LineGraphTypes.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionTypes.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedTypes.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
Labels: S-waiting-on-review, analytics

#1649 refactor: cluttered package json refactor
  package-lock.json
  package.json
  src/server/health.mjs
Labels: S-waiting-on-review

#1703 fix: analytics revamp bug fixes
  src/screens/NewAnalytics/Graphs/LineGraph/LineGraphTypes.res
  src/screens/NewAnalytics/Graphs/LineGraph/LineGraphUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionHelper.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionTypes.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedTypes.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRateUtils.res
Labels: S-waiting-on-review, bug, analytics

#1695 feat: sanky flow chart change
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycle.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycleUtils.res
Labels: S-waiting-on-review, analytics

#1697 feat: add functionality to force two-fa
  src/entryPoints/AuthModule/TwoFaAuth/TotpSetup.res
  src/entryPoints/AuthModule/TwoFaAuth/TwoFaLanding.res
  src/entryPoints/AuthModule/TwoFaAuth/TwoFaTypes.res
  src/entryPoints/AuthModule/TwoFaAuth/TwoFaUtils.res
Labels: feature

#1700 feat: change password feature
  src/entryPoints/AuthModule/Common/CommonAuthForm.res
  src/entryPoints/AuthModule/Common/CommonAuthTypes.res
  src/entryPoints/AuthModule/Common/CommonAuthUtils.res
  src/entryPoints/AuthModule/Common/CommonInputFields.res
  src/entryPoints/AuthModule/TwoFaAuth/TwoFaUtils.res
  src/screens/Settings/HSwitchProfile/HSwitchProfileSettings.res
  src/utils/Modal.res
Labels: S-waiting-on-review, C-feature

#1684 chore: update mixpanel details
  src/screens/APIUtils/APIUtils.res
  src/screens/GenerateReports/DownloadReportModal.res
  src/screens/MixpanelHook.res
  src/utils/HyperSwitchUtils.res
Labels: chore

#1716 fix: compare date range component minor fixes
  src/components/DateRangeCompareFields.res
  src/container/NewAnalyticsContainer.res
  src/screens/NewAnalytics/NewAnalyticsUtils.res
Labels: bug, analytics

#1711 fix: sankey flow chart count fix
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycleUtils.res
Labels: bug, analytics

#1710 fix: handle logout
  src/entryPoints/AuthModule/Common/CommonInviteScreen.res
  src/entryPoints/AuthModule/PreLoginModule/ListInvitationScreen.res
  src/entryPoints/AuthModule/TwoFaAuth/TotpSetup.res
  src/entryPoints/AuthModule/TwoFaAuth/TwoFaLanding.res
  src/screens/Settings/HSwitchProfile/HSwitchProfileSettings.res
Labels: S-waiting-on-review

#1701 fix: show role name for custom roles
  src/screens/UserManagement/UserRevamp/NewUserInvitationForm.res
  src/screens/UserManagement/UserRevamp/UserInfo.res
Labels: S-waiting-on-review, C-ui

#1722 fix: sankey ui fixes
  src/screens/NewAnalytics/Graphs/SankyGraph/SankeyGraphTypes.res
  src/screens/NewAnalytics/Graphs/SankyGraph/SankeyGraphUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycle.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycleUtils.res
Labels: bug, analytics

#1725 fix: payment processed USD string fix
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
Labels: bug, analytics

#1708 fix: bug fixes for two-fa restriction
  src/components/PopUpContainer.res
  src/entryPoints/AuthModule/TwoFaAuth/TotpSetup.res
  src/entryPoints/AuthModule/TwoFaAuth/TwoFaLanding.res
  src/hooks/AuthHooks.res
  src/screens/Settings/HSwitchProfile/TwoFaSettings/RegenerateRC.res
  src/screens/Settings/HSwitchProfile/TwoFaSettings/ResetTotp.res
Labels: bug

#1719 feat: profile id search
  src/components/SelectBox.res
Labels: C-feature

#1729 ci: git checkout token for open source contribution
  .githooks/commit-msg
  .github/workflows/ci.yml
  .github/workflows/cypress-test.yml
  .github/workflows/eslint-check.yml
  .github/workflows/pr-title-spell-check.yml
  .github/workflows/release-stable-version.yml
Labels: S-waiting-on-review

#1669 feat: update org name
  src/screens/APIUtils/APIUtils.res
  src/screens/APIUtils/APIUtilsTypes.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/OMPSwitch/OrgSwitch.res
Labels: S-waiting-on-review, core

#1732 fix: analytics minor bugs
  src/components/DateRangeCompareFields.res
  src/components/DateRangeField.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycleUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRate.res
Labels: bug, analytics

#1736 chore: sankey single value fix
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycleUtils.res
Labels: S-waiting-on-review, bug, analytics

#1717 Fix: Filter routing connector list
  src/screens/PayoutRouting/PayoutRoutingConfigure.res
  src/screens/Routing/DefaultRouting.res
  src/screens/Routing/RoutingConfigure.res
  src/screens/Routing/VolumeSplitRouting.res
  src/screens/RoutingRevamp/AdvancedRouting.res
Labels: S-waiting-on-review, core

#1687 chore: remove duplicate api calls
  src/entryPoints/HyperSwitchApp.res
  src/screens/OMPSwitch/ProfileSwitch.res
Labels: S-waiting-on-review, core

#1748 fix: list profile api
  src/screens/OMPSwitch/ProfileSwitch.res
Labels: S-waiting-on-review, bug, core

#1749 fix: login cancel link fix
  src/entryPoints/AuthModule/AuthModuleHooks.res
Labels: bug

#1753 chore: removing api call not required on sdk page
  src/screens/SDKPayment/WebSDK.res
Labels: S-waiting-on-review, core

#1745 fix: payment prosecces count fix
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
Labels: S-waiting-on-review, bug, analytics

#1759 feat: dispute count analytics for new analytics overview section
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSection.res
Labels: S-waiting-on-review, analytics

#1756 fix: totp error toast
  src/components/SelectBox.res
  src/entryPoints/AuthModule/Common/CommonAuthTypes.res
  src/entryPoints/AuthModule/Common/CommonAuthUtils.res
  src/entryPoints/AuthModule/TwoFaAuth/TotpSetup.res
  src/screens/Settings/HSwitchProfile/TwoFaSettings/ResetTotp.res
Labels: C-ui

#1761 fix: filter sessionized metrics
  src/screens/Analytics/AnalyticsUtils.res
  src/screens/Analytics/DisputeAnalytics/DisputeAnalytics.res
  src/screens/Analytics/PaymentsAnalytics/PaymentAnalytics.res
  src/screens/Analytics/RefundsAnalytics/RefundsAnalytics.res
Labels: S-waiting-on-review, analytics

#1746 feat: customer ID filter
  src/components/Filter.res
  src/screens/Disputes/DisputesUtils.res
  src/screens/HSwitchRemoteFilter.res
  src/screens/Order/OrderUIUtils.res
  src/screens/Order/Orders.res
  src/screens/Payouts/PayoutsUtils.res
  src/screens/Refunds/RefundUtils.res
Labels: S-waiting-on-review, C-feature

#1763 feat(assets): Add welcome email assets
  .gitignore
  public/hyperswitch/assets/welcome-email/communityArrow.png
  public/hyperswitch/assets/welcome-email/docs.png
  public/hyperswitch/assets/welcome-email/docsArrow.png
  public/hyperswitch/assets/welcome-email/github-logo1.png
  public/hyperswitch/assets/welcome-email/linkedin.png
  public/hyperswitch/assets/welcome-email/logo.png
  public/hyperswitch/assets/welcome-email/logotext.png
  public/hyperswitch/assets/welcome-email/repoArrow.png
  public/hyperswitch/assets/welcome-email/slack-dark.png
  public/hyperswitch/assets/welcome-email/slack.png
  public/hyperswitch/assets/welcome-email/star.png
  public/hyperswitch/assets/welcome-email/twitter.png
  public/hyperswitch/index.html
  public/hyperswitch/wasm/package.json
Labels: S-waiting-on-review, feature

#1765 fix: default routing connector list extraction changes
  src/screens/Routing/DefaultRouting.res
Labels: S-waiting-on-review, bug

#1769 fix: Customer ID remove key
  src/screens/Disputes/DisputesUtils.res
  src/screens/HSwitchRemoteFilter.res
  src/screens/Order/OrderUIUtils.res
  src/screens/Payouts/PayoutsUtils.res
  src/screens/Refunds/RefundUtils.res
Labels: C-bug

#1781 chore: reverting routing filtering connector list changes
  src/screens/PayoutRouting/PayoutRoutingConfigure.res
  src/screens/Routing/DefaultRouting.res
  src/screens/Routing/RoutingConfigure.res
Labels: S-waiting-on-review, core

#1777 feat: fiuu connector added note part
  src/screens/Connectors/ConnectorPreview.res
Labels: S-waiting-on-review, chore

#1734 feat: global search categories suggestions
  src/screens/Analytics/GlobalSearch/GlobalSearchBar.res
  src/screens/Analytics/GlobalSearch/GlobalSearchBarHelper.res
  src/screens/Analytics/GlobalSearch/GlobalSearchBarUtils.res
  src/screens/Analytics/GlobalSearch/GlobalSearchTypes.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/Disputes/DisputeTable.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/PaymentAttempt/PaymentAttemptTable.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/PaymentIntent/PaymentIntentTable.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/Refunds/RefundsTable.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/ResultsTableUtils.res
  src/screens/Analytics/GlobalSearchResults/SearchResultsPage.res
  src/screens/Analytics/GlobalSearchResults/SearchResultsPageUtils.res
Labels: S-waiting-on-review, analytics

#1768 chore: design feedback changes
  src/components/form/BoolInput.res
  src/container/NewAnalyticsContainer.res
  src/screens/Analytics/PaymentsAnalytics/PaymentAnalytics.res
  src/screens/NewAnalytics/NewAnalyticsHelper.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRate.res
Labels: S-waiting-on-review, analytics

#1791 chore: analytic amount metrics
  src/container/NewAnalyticsContainer.res
Labels: bug, analytics

#1689 feat: frontend invite limit
  src/screens/UserManagement/UserRevamp/UserUtils.res
Labels: S-in-progress

#1773 fix: analytics table data display changes and distribution cols order change
  src/screens/NewAnalytics/PaymentAnalytics/FailedPaymentsDistribution/FailedPaymentsDistribution.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
  src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistribution.res
Labels: bug, analytics

#1776 fix: error on sdk page when no payment connector connected
  src/screens/SDKPayment/SDKPage.res
Labels: S-waiting-on-review, bug, core

#1770 chore: url path after OMP switch
  src/screens/OMPSwitch/MerchantSwitch.res
  src/screens/OMPSwitch/OrgSwitch.res
  src/screens/OMPSwitch/ProfileSwitch.res
  src/utils/GlobalVars.res
Labels: S-waiting-on-review, core

#1793 chore: enable we domain for fiuu apple pay
  src/screens/Connectors/ConnectorMetaData/ApplePay/ApplePayIntegration.res
Labels: S-waiting-on-review, core

#1797 fix: global search enter listener
  src/screens/Analytics/GlobalSearch/GlobalSearchBar.res
  src/screens/Analytics/GlobalSearch/GlobalSearchBarHelper.res
Labels: S-waiting-on-review, analytics

#1803 fix: changed global search date range fix
  src/screens/Analytics/GlobalSearch/GlobalSearchBarUtils.res
Labels: S-waiting-on-review, analytics

#1810 feat(authn): Enable cookies
  config/config.toml
  src/hooks/AuthHooks.res
Labels: S-waiting-on-review, C-feature

#1747 chore: fix admin permission to create new omp
  src/screens/Hooks/OMPCreateAccessHook.res
  src/screens/OMPSwitch/MerchantSwitch.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/OMPSwitch/ProfileSwitch.res
Labels: S-waiting-on-review, core

#1819 fix: Move columns in payment operations
  src/screens/Order/OrderEntity.res
Labels: C-ui

#1816 fix: global search filters access check
  src/screens/Analytics/GlobalSearch/GlobalSearchBar.res
Labels: S-waiting-on-review, analytics

#1811 fix: Horizontal Scrollbar to Tables
  src/components/Table.res
Labels: S-waiting-on-review, C-bug

#1804 chore: added ref for user-info to get updated data
  src/entryPoints/AuthModule/UserInfo/UserInfoProvider.res
  src/entryPoints/AuthModule/UserInfo/UserInfoTypes.res
  src/entryPoints/AuthModule/UserInfo/UserInfoUtils.res
  src/screens/Hooks/OMPSwitchHooks.res
Labels: chore, user-management

#1820 fix: sanky flow chart change and tooltip ui advancements
  src/screens/NewAnalytics/Graphs/SankyGraph/SankeyGraphTypes.res
  src/screens/NewAnalytics/Graphs/SankyGraph/SankeyGraphUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycle.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycleTypes.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycleUtils.res
Labels: S-waiting-on-review, bug, analytics

#1815 chore: minor modification for enhancement and bugfix
  src/screens/SDKPayment/SDKPage.res
Labels: S-waiting-on-review, core

#1813 fix: sidebar-active-selection-resolution
  src/screens/Sidebar/Sidebar.res
Labels: S-waiting-on-review, C-bug

#1785 chore: redesign omp dropdowns
  public/hyperswitch/icons/solid.svg
  src/components/Navbar.res
  src/entryPoints/HyperSwitchApp.res
  src/screens/OMPSwitch/MerchantSwitch.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/OMPSwitch/OrgSwitch.res
  src/screens/OMPSwitch/ProfileSwitch.res
  src/screens/Order/HSwitchOrderUtils.res
  src/screens/Order/Metadata.res
  src/screens/Order/OrderEntity.res
  src/screens/Sidebar/Sidebar.res
  src/screens/Sidebar/SidebarSwitch.res
  tailwind.config.js
Labels: S-waiting-on-review, core

#1796 feat: Payment Operations Amount Filter
  public/hyperswitch/icons/solid.svg
  src/components/Filter.res
  src/components/FilterSelectBox.res
  src/components/RemoteFiltersUtils.res
  src/components/form/FormRenderer.res
  src/context/FilterContext.res
  src/entryPoints/AuthModule/Common/CommonInputFields.res
  src/screens/Order/OrderTypes.res
  src/screens/Order/OrderUIUtils.res
  src/screens/Order/Orders.res
  src/screens/Order/OrdersHelper.res
  src/utils/LogicUtils.res
  tailwind.config.js
Labels: C-feature

#1826 chore: omp remove copy icon
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/OMPSwitch/OrgSwitch.res
Labels: S-waiting-on-review, core

#1824 fix: date range compare component end time fix 00:00 to 59.59
  src/utils/DateRangeUtils.res
Labels: S-waiting-on-review, bug, analytics
