Repository juspay/hyperswitch-control-center, pull requests merged in 2024-01, with the labels that each got.

#131 fix: wasm to support minimum_amount and maximum amount
  public/hyperswitch/wasm/euclid_bg.wasm
  public/hyperswitch/wasm/package.json
  src/screens/HyperSwitch/Connectors/ConnectorTableUtils.res
  src/screens/HyperSwitch/Connectors/ConnectorTypes.res
  src/screens/HyperSwitch/Connectors/ConnectorUIUtils/PaymentMethod.res
  src/screens/HyperSwitch/Connectors/ConnectorUtils.res
  src/screens/HyperSwitch/Connectors/Wallets/Wallet.res
  src/screens/HyperSwitch/SelfServe/HSwitchProdOnboarding/SetupConnectorCredentials.res
  src/screens/HyperSwitch/SetupAccount/HSwitchSetupAccountUtils.res
Labels: S-waiting-on-review

#153 fix: Scrollbar revert
  tailwindHyperSwitch.config.js
Labels: S-waiting-on-review

#152 fix: business profile addition modal bugfix
  src/screens/HyperSwitch/Settings/BusinessMapping/BusinessProfile.res
Labels: S-waiting-on-review

#154 fix: Unnecessary API List count of connectors stop
  src/screens/HyperSwitch/Home/HomeUtils.res
  src/screens/HyperSwitch/Order/Orders.res
Labels: S-waiting-on-review

#158 feat: added mixpanel events
  .env
  README.md
  src/entryPoints/hyperswitch/SidebarValues.res
  src/libraries/Window.res
  src/screens/HyperSwitch/Analytics/GenerateReport.res
  src/screens/HyperSwitch/Developer/APIKeys/KeyManagement.res
  src/screens/HyperSwitch/Home/HomeUtils.res
  src/screens/HyperSwitch/Home/HomeV2.res
  src/screens/HyperSwitch/MixpanelHook.res
  src/screens/HyperSwitch/Order/OrderUIUtils.res
  src/screens/HyperSwitch/Routing/ActiveRouting.res
  src/screens/HyperSwitch/ThreeDSFlow/HSwitchThreeDS.res
  src/screens/HyperSwitch/UserManagement/UserRoleEntry.res
  src/screens/login/HSwitchLoginFlow/HyperSwitchAuth.res
  src/utils/HSwitchGlobalVars.res
Labels: S-waiting-on-review

#79 feat: Multi filters support
  src/components/DynamicChart.res
  src/components/DynamicFilter.res
  src/components/DynamicSingleStat.res
  src/components/DynamicTabs.res
  src/components/FilterUtils.res
  src/components/RemoteFilter.res
  src/context/AnalyticsUrlUpdaterContext.res
  src/context/ChartContext.res
  src/context/FilterContext.res
  src/context/SingleStatContext.res
  src/entities/analytics/AnalyticsUtils.res
  src/entities/analytics/SaveViewEntity.res
  src/entryPoints/hyperswitch/HyperSwitchApp.res
  src/hooks/AnalyticsHooks.res
  src/screens/HyperSwitch/Analytics/Analytics.res
  src/screens/HyperSwitch/Analytics/SystemMetrics/SystemMetricsAnalytics.res
  src/screens/HyperSwitch/HSwitchRemoteFilter.res
  src/screens/HyperSwitch/Order/Orders.res
  src/screens/HyperSwitch/Refunds/Refund.res
  src/screens/analyticsScreens/DateTimeWrapper.res
  src/utils/UrlUtils.res
Labels: S-waiting-on-review

#128 feat: Prod enum changes
  config/FeatureFlag.json
  src/entryPoints/hyperswitch/FeatureFlagUtils.res
  src/entryPoints/hyperswitch/HyperSwitchApp.res
  src/entryPoints/hyperswitch/SidebarValues.res
  src/screens/HyperSwitch/SelfServe/HSwitchProdOnboarding/ProdOnboardingLanding.res
  src/screens/HyperSwitch/Settings/HSwitchProfileSettings.res
Labels: S-blocked

#161 fix: Enabled braintree in prod
  src/screens/HyperSwitch/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review

#162 fix: disputes api change
  src/screens/HyperSwitch/APIUtils/APIUtils.res
Labels: S-waiting-on-review

#164 fix: Connector list fix for search live
  src/entryPoints/hyperswitch/SidebarValues.res
Labels: S-waiting-on-review

#163 fix: email issue in mixpanel capture
  src/screens/login/HSwitchLoginFlow/HyperSwitchAuth.res
Labels: S-waiting-on-review

#148 fix: cashtocode update flow
  public/hyperswitch/wasm/euclid_bg.wasm
  src/screens/HyperSwitch/Connectors/ConnectorAccountDetails.res
  src/screens/HyperSwitch/Connectors/ConnectorAccountDetailsHelper.res
  src/screens/HyperSwitch/Connectors/ConnectorTypes.res
  src/screens/HyperSwitch/Connectors/ConnectorUtils.res
  src/screens/HyperSwitch/Home/CommonConnectorFlow/SetupConnector.res
  src/screens/HyperSwitch/SelfServe/HSwitchProdOnboarding/SetupConnectorCredentials.res
Labels: S-waiting-on-review

#167 docs: added security policy, code of conduct and contributing md files
  docs/CODE_OF_CONDUCT.md
  docs/CONTRIBUTING.md
  docs/SECURITY.md
Labels: S-waiting-on-review

#168 docs: added license file and contributing guidelines
  LICENSE
  README.md
  docs/CONTRIBUTING.md
Labels: S-waiting-on-review

#171 chore: mixpanel country added
  README.md
  config/FeatureFlag.json
  src/entryPoints/hyperswitch/FeatureFlagUtils.res
  src/screens/HyperSwitch/MixpanelHook.res
Labels: S-waiting-on-review

#174 chore: Array changes
  src/components/CustomCharts/HighchartHorizontalBarChart.res
  src/components/CustomExpandableTable.res
  src/components/DynamicSingleStat.res
  src/components/FilterUtils.res
  src/components/LoadedTable.res
  src/components/ReactWindowTable.res
  src/components/SelectBox.res
  src/components/Table.res
  src/components/form/FormRenderer.res
  src/components/form/MultipleTextInput.res
  src/components/form/NumericTextInput.res
  src/context/ChartContext.res
  src/context/FilterContext.res
  src/entryPoints/hyperswitch/HyperSwitchApp.res
  src/hooks/OutsideClick.res
  src/hooks/QueryHook.res
  src/libraries/LocalStorage.res
  src/screens/HyperSwitch/Connectors/ConnectorAccountDetailsHelper.res
  src/screens/HyperSwitch/Connectors/ConnectorHome.res
  src/screens/HyperSwitch/Connectors/ConnectorUtils.res
  src/screens/HyperSwitch/Helpers/HelperComponents.res
  src/screens/HyperSwitch/Home/HomeV2.res
  src/screens/HyperSwitch/Order/ShowOrder.res
  src/screens/HyperSwitch/RoutingRevamp/AdvancedRoutingUIUtils.res
  src/screens/HyperSwitch/Surcharge/Surcharge.res
  src/screens/HyperSwitch/Surcharge/SurchargeUtils.res
  src/screens/componentsDemo/CardTable.res
  src/utils/LogicUtils.res
Labels: S-waiting-on-review

#176 fix: Switch merchant enabled for Live Env
  config/FeatureFlag.json
  src/entryPoints/hyperswitch/HyperSwitchApp.res
  src/screens/HyperSwitch/SelfServe/HSwitchProdOnboarding/HSwitchAgreementScreen.res
  src/screens/HyperSwitch/SelfServe/HSwitchProdOnboarding/ProdOnboardingLanding.res
  src/screens/HyperSwitch/SwitchMerchant/SwitchMerchant.res
Labels: S-waiting-on-review

#166 chore: Add eslint hook
  .eslintrc.json
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/workflows/eslint-check.yml
  docs/CODE_OF_CONDUCT.md
  docs/SECURITY.md
  package.json
  src/components/AnalyticsComponent/NestedDropdownWithCalendar.res
  src/components/Button.res
  src/components/CustomCharts/HighchartTimeSeriesChart.res
  src/components/DateRangePicker.res
  src/components/InputFields.res
  src/components/InputFields.resi
  src/components/LoadedTable.res
  src/components/LoadedTable.resi
  src/components/MultipleFileUpload.res
  src/components/NestedDropdown.res
  src/components/NewDateRangePicker.res
  src/components/ReactWindowTable.res
  src/components/TableUtils.res
  src/components/TableUtils.resi
  src/components/form/FileUpload.res
  src/components/form/TextInput.res
  src/entities/analytics/AnalyticsUtils.res
  src/hooks/AnalyticsHooks.res
  src/libraries/Recoil.res
  src/libraries/SankeyHighcharts.res
  src/screens/HyperSwitch/Analytics/Analytics.res
  src/screens/HyperSwitch/Analytics/SystemMetrics/SystemMetricsAnalytics.res
  src/screens/HyperSwitch/Connectors/ConnectorPreview.res
  src/screens/HyperSwitch/HSwitchRemoteFilter.res
  src/screens/HyperSwitch/Order/OrderHooks.res
  src/screens/HyperSwitch/Order/ShowOrder.res
  src/screens/HyperSwitch/PostLoginScreen/PostLoginScreen.res
  src/screens/HyperSwitch/PostLoginScreen/PostLoginUtils.res
  src/screens/HyperSwitch/Refunds/RefundHook.res
  src/screens/HyperSwitch/Refunds/ShowRefund.res
  src/screens/HyperSwitch/SelfServe/HSwitchSandboxOnboarding/UserOnboardingUIUtils.res
  src/screens/HyperSwitch/UserManagement/InviteUsers.res
Labels: S-in-progress

#184 fix: add merchant fix
  src/screens/HyperSwitch/SwitchMerchant/SwitchMerchant.res
Labels: S-waiting-on-review

#172 feat: added new filters for payments
  src/screens/HyperSwitch/HSwitchRemoteFilter.res
  src/screens/HyperSwitch/Order/OrderEntity.res
  src/screens/HyperSwitch/Order/OrderUIUtils.res
Labels: S-waiting-on-review

#192 fix: connector integration status and disabled ui change
  src/screens/HyperSwitch/Connectors/ConnectorPreview.res
  src/screens/HyperSwitch/Connectors/ConnectorTableUtils.res
Labels: S-waiting-on-review

#194 chore: analytics files Js.Dict -> Dict migration
  src/components/CustomCharts/HighchartTimeSeriesChart.res
  src/components/CustomCharts/LineChartUtils.res
  src/components/DynamicChart.res
  src/components/DynamicSingleStat.res
  src/components/DynamicTable.res
  src/components/HSwitchSingleStatWidget.res
  src/components/RemoteFiltersUtils.res
  src/components/SelectBox.res
  src/components/SelectBox.resi
  src/components/SingleStats/SingleStatEntity.res
  src/context/FilterContext.res
  src/context/SingleStatContext.res
  src/entities/analytics/AnalyticsUtils.res
  src/hooks/AnalyticsHooks.res
  src/hooks/QueryHook.res
  src/libraries/Highcharts.res
  src/screens/HyperSwitch/Analytics/Analytics.res
  src/screens/HyperSwitch/Analytics/PaymentsAnalytics/PaymentAnalyticsEntity.res
  src/screens/HyperSwitch/Analytics/SystemMetrics/SystemMetricsAnalytics.res
  src/utils/TimeZoneConversion.res
Labels: S-waiting-on-review

#198 feat: Customers module
  src/entryPoints/hyperswitch/HyperSwitchApp.res
  src/entryPoints/hyperswitch/SidebarValues.res
  src/screens/HyperSwitch/APIUtils/APIUtils.res
  src/screens/HyperSwitch/APIUtils/APIUtilsTypes.res
  src/screens/HyperSwitch/Customers/Customers.res
  src/screens/HyperSwitch/Customers/CustomersEntity.res
  src/screens/HyperSwitch/Customers/CustomersType.res
  src/screens/HyperSwitch/Customers/ShowCustomers.res
Labels: S-waiting-on-review

#205 fix: eslint issue
  .github/workflows/eslint-check.yml
  src/components/form/TextInput.res
Labels: S-waiting-on-review, C-bug

#160 fix: filters enhance
  src/components/DateRangePicker.res
  src/screens/HyperSwitch/HSwitchRemoteFilter.res
Labels: S-waiting-on-review

#213 feat: Modal added for Switch merchant switch.
  src/screens/HyperSwitch/SwitchMerchant/SwitchMerchant.res
Labels: S-waiting-on-review

#146 feat: duplicate and edit configuration in volume based routing
  src/components/priority-logics/AddPLGateway.res
  src/screens/HyperSwitch/Routing/AdvancedRouting/RoutingPreviewer.res
  src/screens/HyperSwitch/Routing/RoutingConfigure.res
  src/screens/HyperSwitch/Routing/RoutingUtils.res
  src/screens/HyperSwitch/Routing/VolumeSplitRouting.res
  src/screens/HyperSwitch/RoutingRevamp/AddRuleGateway.res
  src/screens/HyperSwitch/RoutingRevamp/BasicDetailsForm.res
Labels: S-waiting-on-review

#218 feat: Customers Module feature flag
  README.md
  config/FeatureFlag.json
  src/entryPoints/hyperswitch/FeatureFlagUtils.res
  src/entryPoints/hyperswitch/HyperSwitchApp.res
  src/entryPoints/hyperswitch/SidebarValues.res
Labels: Closed

#216 feat: Connector Label added in Show Payments
  src/screens/HyperSwitch/Order/OrderEntity.res
  src/screens/HyperSwitch/Order/OrderTypes.res
  src/screens/HyperSwitch/Order/ShowOrder.res
Labels: S-waiting-on-review

#110 fix: Moved HyperLoader script
  public/hyperswitch/index.html
  src/genericUtils/DOMUtils.res
  src/libraries/Window.res
  src/screens/HyperSwitch/SDKPayment/SDKPage.res
  src/screens/HyperSwitch/SDKPayment/WebSDK.res
Labels: S-waiting-on-review

#226 fix: make self-serve sidebar responsive
  src/screens/HyperSwitch/Utils/HSSelfServeSidebar.res
Labels: S-waiting-on-review

#222 feat: mixpanel added for quick start flow
  src/screens/HyperSwitch/Home/CommonConnectorFlow/ConfigureConnector.res
  src/screens/HyperSwitch/Home/CommonConnectorFlow/QuickStartConnectorFlow.res
  src/screens/HyperSwitch/Home/CommonConnectorFlow/SetupConnector.res
  src/screens/HyperSwitch/Home/QuickStart/GoLive.res
  src/screens/HyperSwitch/Home/QuickStart/IntegrateYourApp/IntegrateYourAppLanding.res
  src/screens/HyperSwitch/Home/QuickStart/IntegrateYourApp/MigrateFromStripe.res
Labels: S-waiting-on-review

#212 feat: change data type response for switch merchant
  src/screens/HyperSwitch/SwitchMerchant/SwitchMerchant.res
Labels: S-waiting-on-review

#233 fix: show billing and shipping address
  src/screens/HyperSwitch/Order/OrderEntity.res
  src/screens/HyperSwitch/Order/ShowOrder.res
  src/utils/LogicUtils.res
Labels: Closed

#236 fix: profile changes in Routing
  src/screens/HyperSwitch/Routing/PriorityRouting.res
  src/screens/HyperSwitch/Routing/VolumeSplitRouting.res
  src/screens/HyperSwitch/RoutingRevamp/AdvancedRouting.res
  src/screens/HyperSwitch/RoutingRevamp/AdvancedRoutingUtils.res
  src/screens/HyperSwitch/RoutingRevamp/BasicDetailsForm.res
Labels: S-waiting-on-review

#238 fix: surcharge value type
  src/screens/HyperSwitch/Order/OrderEntity.res
  src/screens/HyperSwitch/Order/OrderTypes.res
  src/screens/HyperSwitch/Order/ShowOrder.res
  src/screens/HyperSwitch/RoutingRevamp/AdvancedRouting.res
  src/screens/HyperSwitch/RoutingRevamp/AdvancedRoutingUtils.res
  src/screens/HyperSwitch/RoutingRevamp/Previewers/RulePreviewer.res
  src/screens/HyperSwitch/Surcharge/Surcharge.res
  src/screens/HyperSwitch/Surcharge/SurchargeUtils.res
Labels: S-waiting-on-review

#242 fix: customer module flag removal
  README.md
  config/FeatureFlag.json
  src/entryPoints/hyperswitch/FeatureFlagUtils.res
  src/entryPoints/hyperswitch/HyperSwitchApp.res
  src/entryPoints/hyperswitch/SidebarValues.res
Labels: S-waiting-on-review

#246 feat: zero payment added
  src/screens/HyperSwitch/SDKPayment/SDKPaymentTypes.res
  src/screens/HyperSwitch/SDKPayment/SDKPaymentUtils.res
Labels: S-waiting-on-review

#249 fix: currency change
  src/screens/HyperSwitch/SDKPayment/SDKPaymentUtils.res
Labels: S-waiting-on-review

#256 feat: Cybersource enabled in Prod
  src/screens/HyperSwitch/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review

#259 fix: make tax_on_surcharge optional and add description
  src/screens/HyperSwitch/Surcharge/Surcharge.res
  src/screens/HyperSwitch/Surcharge/SurchargeUtils.res
Labels: S-waiting-on-review

#237 feat: add new user
  src/screens/HyperSwitch/SwitchMerchant/SwitchMerchant.res
  src/screens/HyperSwitch/UserManagement/InviteUsers.res
  src/utils/LoaderModal.res
  src/utils/PromiseUtils.res
Labels: S-waiting-on-review

#267 chore: Added Access Type & Remove the Read & ReadWrite Type
  src/components/EntityScaffold.res
  src/components/UnauthorizedPage.res
  src/components/form/BoolInput.res
  src/context/FormAuthContext.res
  src/entryPoints/hyperswitch/HyperSwitchApp.res
  src/entryPoints/hyperswitch/SidebarValues.res
  src/screens/HyperSwitch/UserManagement/PermissionUtils.res
  src/screens/login/AuthTypes.res
Labels: S-waiting-on-review

#270 fix: floating point value fix for test payment
  src/screens/HyperSwitch/SDKPayment/SDKPage.res
  src/screens/HyperSwitch/SDKPayment/SDKPaymentTypes.res
  src/screens/HyperSwitch/SDKPayment/SDKPaymentUtils.res
  src/screens/HyperSwitch/SDKPayment/WebSDK.res
Labels: S-waiting-on-review

#254 refactor: routing types and utils
  src/components/priority-logics/PriorityLogicUtils.res
  src/screens/HyperSwitch/Routing/AdvancedRouting/RoutingPreviewer.res
  src/screens/HyperSwitch/Routing/HistoryEntity.res
  src/screens/HyperSwitch/Routing/PriorityRouting.res
  src/screens/HyperSwitch/Routing/RoutingTypes.res
  src/screens/HyperSwitch/Routing/RoutingUtils.res
  src/screens/HyperSwitch/Routing/VolumeSplitRouting.res
  src/screens/HyperSwitch/RoutingRevamp/AdvancedRouting.res
  src/screens/HyperSwitch/RoutingRevamp/AdvancedRoutingUIUtils.res
  src/screens/HyperSwitch/RoutingRevamp/AdvancedRoutingUtils.res
  src/screens/HyperSwitch/SelfServe/HSwitchSandboxOnboarding/UserOnboardingUIUtils.res
  src/screens/HyperSwitch/Surcharge/Surcharge.res
  src/screens/HyperSwitch/ThreeDSFlow/HSwitchThreeDS.res
Labels: S-waiting-on-review

#273 chore: refactor invite users
  src/screens/HyperSwitch/UserManagement/InviteUsers.res
Labels: S-waiting-on-review

#207 feat: update pr label on merge to closed
  .github/workflows/pr-label.yml
Labels: S-waiting-on-review

#271 fix: make basic details form to accept form input without Save button
  src/screens/HyperSwitch/Routing/RoutingUtils.res
  src/screens/HyperSwitch/Routing/VolumeSplitRouting.res
  src/screens/HyperSwitch/RoutingRevamp/AdvancedRouting.res
  src/screens/HyperSwitch/RoutingRevamp/BasicDetailsForm.res
  src/screens/HyperSwitch/Surcharge/Surcharge.res
  src/screens/HyperSwitch/ThreeDSFlow/HSwitchThreeDS.res
  src/screens/login/HSwitchLoginFlow/HyperSwitchAuthUtils.res
Labels: S-waiting-on-review

#265 feat: permission based sidebar navigation
  config/FeatureFlag.json
  src/components/EntityScaffold.res
  src/entryPoints/hyperswitch/FeatureFlagUtils.res
  src/entryPoints/hyperswitch/HyperSwitchApp.res
  src/entryPoints/hyperswitch/HyperswitchAtom.res
  src/entryPoints/hyperswitch/SidebarValues.res
  src/screens/HyperSwitch/APIUtils/APIUtils.res
  src/screens/HyperSwitch/APIUtils/APIUtilsTypes.res
  src/screens/HyperSwitch/Routing/RoutingUtils.res
  src/screens/HyperSwitch/UserManagement/PermissionUtils.res
  src/utils/AccessControl.res
Labels: S-in-progress

#277 feat: ACLButton Added
  src/components/ACLButton.res
  src/components/ACLButton.resi
  src/components/Button.res
  src/components/Button.resi
Labels: S-waiting-on-review

#283 fix: Use apifetcher function update
  src/components/HSwitchFeedBackModal.res
  src/entryPoints/hyperswitch/HyperSwitchEntry.res
  src/entryPoints/hyperswitch/WooCommerce/WooCommerceUIUtils.res
  src/screens/HyperSwitch/APIUtils/APIUtils.res
  src/screens/HyperSwitch/Analytics/Analytics.res
  src/screens/HyperSwitch/Analytics/DownloadReportModal.res
  src/screens/HyperSwitch/Analytics/HomePageOverview/HomePageOverviewComponent.res
  src/screens/HyperSwitch/Analytics/RefundsAnalytics/RefundsAnalytics.res
  src/screens/HyperSwitch/Analytics/SystemMetrics/SystemMetricsAnalytics.res
  src/screens/HyperSwitch/Connectors/ConnectorAccountDetails.res
  src/screens/HyperSwitch/Connectors/ConnectorPaymentMethod.res
  src/screens/HyperSwitch/Connectors/ConnectorPreview.res
  src/screens/HyperSwitch/Connectors/Wallets/ApplePayWalletIntegration.res
  src/screens/HyperSwitch/Developer/APIKeys/KeyManagement.res
  src/screens/HyperSwitch/Developer/PaymentSettings/PaymentSettings.res
  src/screens/HyperSwitch/FraudAndRisk/FRMIntegrationFields.res
  src/screens/HyperSwitch/FraudAndRisk/FRMSummary.res
  src/screens/HyperSwitch/HSwitchRemoteFilter.res
  src/screens/HyperSwitch/Home/CommonConnectorFlow/ConfigureConnector.res
  src/screens/HyperSwitch/Home/CommonConnectorFlow/QuickStartConnectorFlow.res
  src/screens/HyperSwitch/Home/CommonConnectorFlow/SetupConnector.res
  src/screens/HyperSwitch/Home/DelayedVerificationBanner.res
  src/screens/HyperSwitch/Home/ProdIntent/ProdVerifyModal.res
  src/screens/HyperSwitch/Home/QuickStart/GoLive.res
  src/screens/HyperSwitch/Home/QuickStart/IntegrateYourApp/IntegrationDocsPage.res
  src/screens/HyperSwitch/Hooks/EnumVariantHook.res
  src/screens/HyperSwitch/Order/OrderRefundForm.res
  src/screens/HyperSwitch/Order/OrderUIUtils.res
  src/screens/HyperSwitch/Order/ShowOrder.res
  src/screens/HyperSwitch/PaymentLogs/PaymentLogs.res
  src/screens/HyperSwitch/PostLoginScreen/PostLoginScreen.res
  src/screens/HyperSwitch/Recon/Recon.res
  src/screens/HyperSwitch/Refunds/RefundUtils.res
  src/screens/HyperSwitch/Routing/ActiveRouting.res
  src/screens/HyperSwitch/Routing/DefaultRouting.res
  src/screens/HyperSwitch/Routing/PriorityRouting.res
  src/screens/HyperSwitch/Routing/VolumeSplitRouting.res
  src/screens/HyperSwitch/RoutingRevamp/AdvancedRouting.res
  src/screens/HyperSwitch/SDKPayment/TestPayment.res
  src/screens/HyperSwitch/SelfServe/HSwitchProdOnboarding/HSwitchAgreementScreen.res
  src/screens/HyperSwitch/SelfServe/HSwitchProdOnboarding/LiveEndpointsSetup.res
  src/screens/HyperSwitch/SelfServe/HSwitchProdOnboarding/ProdOnboardingLanding.res
  src/screens/HyperSwitch/SelfServe/HSwitchProdOnboarding/SetupConnectorCredentials.res
  src/screens/HyperSwitch/SelfServe/HSwitchSandboxOnboarding/IntegrationDocs.res
  src/screens/HyperSwitch/SelfServe/HSwitchSandboxOnboarding/UserOnboarding.res
  src/screens/HyperSwitch/SelfServe/HSwitchSandboxOnboarding/UserOnboardingUIUtils.res
  src/screens/HyperSwitch/Settings/BusinessDetails.res
  src/screens/HyperSwitch/Settings/BusinessMapping/BusinessProfile.res
  src/screens/HyperSwitch/Settings/HSwitchProfileSettings.res
  src/screens/HyperSwitch/Settings/HSwitchSettings.res
  src/screens/HyperSwitch/SetupAccount/HSwitchSetupAccount.res
  src/screens/HyperSwitch/StripePlusPaypal/StripePlusPaypalUIUtils.res
  src/screens/HyperSwitch/Surcharge/Surcharge.res
  src/screens/HyperSwitch/SwitchMerchant/SwitchMerchant.res
  src/screens/HyperSwitch/ThreeDSFlow/HSwitchThreeDS.res
  src/screens/HyperSwitch/UserManagement/InviteUsers.res
  src/screens/HyperSwitch/UserManagement/ShowUserData.res
  src/screens/login/HSwitchLoginFlow/HyperSwitchAuth.res
  src/screens/login/HSwitchLoginFlow/HyperSwitchEmailVerifyScreen.res
Labels: S-waiting-on-review

#257 fix: changes for supporting form data type in api
  src/hooks/AuthHooks.res
  src/screens/HyperSwitch/APIUtils/APIUtils.res
  src/screens/HyperSwitch/Order/OrderUIUtils.res
  src/screens/HyperSwitch/Refunds/RefundUtils.res
Labels: S-waiting-on-review

#284 fix: Access Control Issue
  src/entryPoints/hyperswitch/HyperSwitchApp.res
  src/utils/AccessControl.res
Labels: S-waiting-on-review

#282 chore: utils refactor
  src/hooks/ListHooks.res
  src/screens/HyperSwitch/Analytics/HomePageOverview/HomePageOverviewComponent.res
  src/screens/HyperSwitch/Connectors/ConnectorAccountDetails.res
  src/screens/HyperSwitch/Connectors/ConnectorList.res
  src/screens/HyperSwitch/Connectors/ConnectorPaymentMethod.res
  src/screens/HyperSwitch/Connectors/ConnectorTableUtils.res
  src/screens/HyperSwitch/Connectors/ConnectorTypes.res
  src/screens/HyperSwitch/Connectors/ConnectorUIUtils/PaymentMethod.res
  src/screens/HyperSwitch/Connectors/ConnectorUtils.res
  src/screens/HyperSwitch/Home/CommonConnectorFlow/SetupConnector.res
  src/screens/HyperSwitch/Home/QuickStart/QuickStartUIUtils.res
  src/screens/HyperSwitch/Home/QuickStart/QuickStartUtils.res
  src/screens/HyperSwitch/Routing/PriorityRouting.res
  src/screens/HyperSwitch/SelfServe/HSwitchProdOnboarding/SetupConnectorCredentials.res
  src/screens/HyperSwitch/SetupAccount/HSwitchSetupAccountUtils.res
  src/screens/HyperSwitch/Utils/HSwitchUtils.res
  src/screens/HyperSwitch/Utils/UtilsTypes.res
  src/screens/login/HSwitchLoginFlow/HyperSwitchAuth.res
Labels: S-waiting-on-review

#302 fix: content type fix
  src/hooks/AuthHooks.res
Labels: S-waiting-on-review

#272 feat: added webhooks events
  public/hyperswitch/icons/solid.svg
  src/screens/HyperSwitch/APIUtils/APIUtils.res
  src/screens/HyperSwitch/APIUtils/APIUtilsTypes.res
  src/screens/HyperSwitch/PaymentLogs/PaymentLogs.res
  src/screens/HyperSwitch/PaymentLogs/PaymentLogsTypes.res
  src/screens/HyperSwitch/PaymentLogs/PaymentLogsUtils.res
  src/utils/LogicUtils.res
  tailwindHyperSwitch.config.js
Labels: S-waiting-on-review

#300 feat: syntax highlighter
  package.json
  src/libraries/ReactSyntaxHighlighter.res
  src/screens/HyperSwitch/PaymentLogs/PaymentLogs.res
Labels: S-waiting-on-review

#298 chore: remove redundant code
  src/components/AuthWrapperUtils.res
  src/components/DynamicTableUtils.res
  src/components/RemoteFilter.res
  src/components/SelectBox.res
  src/components/SelectBox.resi
  src/components/form/FormValuesSpy.res
  src/context/ThemeProvider.res
  src/entities/analytics/EulerAnalyticsLogUtils.res
  src/genericUtils/DOMUtils.res
  src/hooks/AuthHooks.res
  src/libraries/Clipboard.res
  src/libraries/Window.res
  src/screens/HyperSwitch/Analytics/Analytics.res
  src/screens/HyperSwitch/Analytics/HSAnalyticsUtils.res
  src/screens/HyperSwitch/SDKPayment/WebSDK.res
  src/screens/HyperSwitch/Utils/HSSelfServeSidebar.res
Labels: S-waiting-on-review

#303 fix: close connector drop down bydefault
  src/screens/HyperSwitch/Connectors/ConnectorPreview.res
Labels: S-waiting-on-review

#297 chore: change tag creation
  .github/git-cliff-changelog.toml
  .github/workflows/pr-label.yml
  .github/workflows/release-new-nightly-version.yml
  .github/workflows/release-stable-version.yml
Labels: Closed

#305 fix: audit log fix
  src/screens/HyperSwitch/PaymentLogs/PaymentLogs.res
Labels: S-waiting-on-review

#214 feat: accept dispute
  config/FeatureFlag.json
  public/hyperswitch/icons/solid.svg
  src/entryPoints/hyperswitch/FeatureFlagUtils.res
  src/screens/HyperSwitch/APIUtils/APIUtils.res
  src/screens/HyperSwitch/APIUtils/APIUtilsTypes.res
  src/screens/HyperSwitch/Disputes/DisputeTypes.res
  src/screens/HyperSwitch/Disputes/Disputes.res
  src/screens/HyperSwitch/Disputes/DisputesEntity.res
  src/screens/HyperSwitch/Disputes/DisputesUtils.res
  src/screens/HyperSwitch/Disputes/ShowDisputes.res
  src/screens/HyperSwitch/Order/ShowOrder.res
Labels: S-waiting-on-review

#309 fix: enabling nmi in prod
  src/screens/HyperSwitch/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review

#299 refactor: proper identification of reactHyperJs from hyperswitch
  src/libraries/HyperSwitch/HyperSwitch.res
  src/libraries/HyperSwitch/ReactHyperJs.res
  src/libraries/Window.res
  src/screens/HyperSwitch/Home/HomeUtils.res
  src/screens/HyperSwitch/SDKPayment/TestPayment.res
  src/screens/HyperSwitch/SDKPayment/WebSDK.res
Labels: S-waiting-on-review

#308 feat: made the customize columns to appear in Portal for same line
  src/components/Button.res
  src/components/DateRangePicker.res
  src/components/DynamicTable.res
  src/components/LoadedTable.res
  src/components/LoadedTableWithCustomColumns.res
  src/components/RemoteFilter.res
  src/screens/HyperSwitch/Analytics/GenerateReport.res
  src/screens/HyperSwitch/HSwitchRemoteFilter.res
  src/screens/HyperSwitch/Order/OrderUIUtils.res
  src/screens/HyperSwitch/Order/Orders.res
  src/screens/HyperSwitch/Refunds/Refund.res
Labels: S-waiting-on-review

#285 feat: paypal changes
  public/hyperswitch/icons/solid.svg
  src/entryPoints/hyperswitch/HyperswitchAtom.res
  src/screens/HyperSwitch/Connectors/ConnectPayPalFlow/ConnectPayPal.res
  src/screens/HyperSwitch/Connectors/ConnectPayPalFlow/MenuOptionForPayPal.res
  src/screens/HyperSwitch/Connectors/ConnectPayPalFlow/PayPalFlowTypes.res
  src/screens/HyperSwitch/Connectors/ConnectPayPalFlow/PayPalFlowUtils.res
  src/screens/HyperSwitch/Connectors/ConnectorAccountDetails.res
  src/screens/HyperSwitch/Connectors/ConnectorAccountDetailsHelper.res
  src/screens/HyperSwitch/Connectors/ConnectorHome.res
  src/screens/HyperSwitch/Connectors/ConnectorPreview.res
  src/screens/HyperSwitch/Connectors/ConnectorTypes.res
  src/screens/HyperSwitch/Connectors/ConnectorUIUtils/PaymentMethod.res
  src/screens/HyperSwitch/Connectors/ConnectorUtils.res
  src/screens/HyperSwitch/FraudAndRisk/FRMConfigure.res
  src/screens/HyperSwitch/FraudAndRisk/FRMInfo.res
  src/screens/HyperSwitch/SelfServe/HSwitchProdOnboarding/ProdOnboardingLanding.res
Labels: S-waiting-on-review

#316 chore: feature flag addition for paypal automatic flow
  config/FeatureFlag.json
  src/entryPoints/hyperswitch/FeatureFlagUtils.res
  src/screens/HyperSwitch/Connectors/ConnectPayPalFlow/ConnectPayPal.res
  src/screens/HyperSwitch/Connectors/ConnectorAccountDetails.res
  src/screens/HyperSwitch/Connectors/ConnectorHome.res
  src/screens/HyperSwitch/Connectors/ConnectorPreview.res
Labels: S-waiting-on-review
