Repository juspay/hyperswitch-control-center, pull requests merged in 2024-10, with the labels that each got.

#1517 fix: table text-wrap removed
  src/components/TableUtils.res
Labels: S-waiting-on-review, core

#1518 feat: new analytics filter
  src/container/NewAnalyticsContainer.res
  src/screens/NewAnalytics/NewAnalyticsContainerUtils.res
Labels: S-waiting-on-review, analytics

#1526 fix: error due to unautorised url
  src/components/UnauthorizedPage.res
Labels: S-waiting-on-review, core

#1521 feat: api integration new analytics
  src/container/NewAnalyticsContainer.res
  src/libraries/FramerMotion.res
  src/screens/APIUtils/APIUtils.res
  src/screens/APIUtils/APIUtilsTypes.res
  src/screens/NewAnalytics/Graphs/LineGraph/LineGraphTypes.res
  src/screens/NewAnalytics/Graphs/LineGraph/LineGraphUtils.res
  src/screens/NewAnalytics/NewAnalyticsContainerUtils.res
  src/screens/NewAnalytics/NewAnalyticsHelper.res
  src/screens/NewAnalytics/NewAnalyticsTypes.res
  src/screens/NewAnalytics/NewAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalytics.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsEntity.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedTypes.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRate.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRateTypes.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRateUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistribution.res
  src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistributionTypes.res
  src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistributionUtils.res
Labels: S-waiting-on-review, analytics

#1531 chore: modify new analytics utils
  src/screens/NewAnalytics/NewAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalytics.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRate.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRateUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistribution.res
  src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistributionUtils.res
Labels: analytics

#1524 chore: sanky mapper function
  src/screens/APIUtils/APIUtils.res
  src/screens/APIUtils/APIUtilsTypes.res
  src/screens/NewAnalytics/Graphs/SankyGraph/SankeyGraph.res
  src/screens/NewAnalytics/Graphs/SankyGraph/SankeyGraphTypes.res
  src/screens/NewAnalytics/Graphs/SankyGraph/SankeyGraphUtils.res
  src/screens/NewAnalytics/NewAnalyticsTypes.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsEntity.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycle.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycleTypes.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycleUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRate.res
  src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistribution.res
Labels: S-waiting-on-review, analytics

#1493 chore: remove agreement screen and prod onboarding
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/Provider/GlobalProvider.res
  src/entryPoints/Provider/ProviderTypes.res
  src/screens/APIUtils/APIUtils.res
  src/screens/APIUtils/APIUtilsTypes.res
  src/screens/HSwitchUtils.res
  src/screens/Home/CommonConnectorFlow/ConfigureConnector.res
  src/screens/Home/CommonConnectorFlow/QuickStartConnectorFlow.res
  src/screens/Home/CommonConnectorFlow/SetupConnector.res
  src/screens/Home/HomeUtils.res
  src/screens/Home/HomeV2.res
  src/screens/Home/QuickStart/ConfigureControlCenter.res
  src/screens/Home/QuickStart/GoLive.res
  src/screens/Home/QuickStart/IntegrateYourApp/CustomIntegrationPage.res
  src/screens/Home/QuickStart/IntegrateYourApp/IntegrateFromScratch.res
  src/screens/Home/QuickStart/IntegrateYourApp/IntegrateYourAppLanding.res
  src/screens/Home/QuickStart/IntegrateYourApp/IntegrateYourAppUtils.res
  src/screens/Home/QuickStart/IntegrateYourApp/IntegrationDocsPage.res
  src/screens/Home/QuickStart/IntegrateYourApp/MigrateFromStripe.res
  src/screens/Home/QuickStart/QuickStartTypes.res
  src/screens/Home/QuickStart/QuickStartUIUtils.res
  src/screens/Home/QuickStart/QuickStartUtils.res
  src/screens/Hooks/EnumVariantHook.res
  src/screens/SDKPayment/TestPayment.res
  src/screens/SelfServe/HSwitchProdOnboarding/ChooseConnector.res
  src/screens/SelfServe/HSwitchProdOnboarding/HSwitchAgreementScreen.res
  src/screens/SelfServe/HSwitchProdOnboarding/LiveEndpointsSetup.res
  src/screens/SelfServe/HSwitchProdOnboarding/ProdOnboardingLanding.res
  src/screens/SelfServe/HSwitchProdOnboarding/ProdOnboardingTypes.res
  src/screens/SelfServe/HSwitchProdOnboarding/ProdOnboardingUIUtils.res
  src/screens/SelfServe/HSwitchProdOnboarding/ProdOnboardingUtils.res
  src/screens/SelfServe/HSwitchProdOnboarding/SetupConnectorCredentials.res
  src/screens/StripePlusPaypal/StripePlusPaypal.res
  src/screens/StripePlusPaypal/StripePlusPaypalUIUtils.res
  src/screens/StripePlusPaypal/StripePlusPaypalUtils.res
  src/screens/SwitchMerchant/SwitchMerchant.res
  src/screens/WooCommerce/WooCommerce.res
  src/screens/WooCommerce/WooCommerceUIUtils.res
  src/screens/WooCommerce/WooCommerceUtils.res
Labels: S-waiting-on-review, core

#1542 feat: compare function
  src/hooks/AuthHooks.res
  src/screens/NewAnalytics/Graphs/LineGraph/LineGraphUtils.res
  src/screens/NewAnalytics/NewAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycle.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRate.res
Labels: S-waiting-on-review, analytics

#1497 test: creation of dummy connector using cypress
  cypress/e2e/connector/connector.cy.js
  src/entryPoints/AuthModule/Common/CommonAuth.res
  src/entryPoints/AuthModule/TwoFaAuth/TwoFaAuth.res
Labels: hacktoberfest

#1550 refactor: code changes
  src/components/CustomizeNotificationsModal.res
  src/components/DynamicTabs.res
  src/components/TableUtils.res
  src/entryPoints/AuthModule/Common/CommonInviteScreen.res
  src/screens/Connectors/ConnectorUIUtils/PaymentMethod.res
  src/screens/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review

#127 fix: Prod x feature deployment
  config/config.toml
  src/components/AdvancedSearchComponent.res
  src/components/AdvancedSearchModal.res
  src/components/DynamicChart.res
  src/components/DynamicSingleStat.res
  src/components/DynamicTable.res
  src/components/custom-icons/LottieFiles.res
  src/context/ChartContext.res
  src/context/SingleStatContext.res
  src/entryPoints/AuthModule/UserInfo/UserInfoProvider.res
  src/entryPoints/FeatureFlagUtils.res
  src/hooks/AuthHooks.res
  src/screens/APIUtils/APIUtils.res
  src/screens/Connectors/ConnectorMetaData/ApplePay/ApplePaySimplifiedFlow.res
  src/screens/Hooks/OMPSwitchHooks.res
  src/screens/MixpanelHook.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycleUtils.res
  src/screens/SDKPayment/WebSDK.res
  src/screens/Settings/ComplianceCertificates/Compliance.res
  src/server/health.mjs
Labels: S-waiting-on-review

#1552 feat: payments overview section
  cypress/e2e/connector/connector.cy.js
  public/hyperswitch/assets/smart-retry.svg
  src/entryPoints/AuthModule/Common/CommonAuth.res
  src/entryPoints/AuthModule/TwoFaAuth/TwoFaAuth.res
  src/screens/NewAnalytics/NewAnalyticsHelper.res
  src/screens/NewAnalytics/NewAnalyticsTypes.res
  src/screens/NewAnalytics/NewAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalytics.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsEntity.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycle.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSection.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionTypes.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionUtils.res
Labels: S-waiting-on-author, analytics

#1565 fix: api not getting called due to user permission data not updated
  src/entryPoints/HyperSwitchApp.res
Labels: S-waiting-on-review, core

#1551 feat: add auto retries in payment settings
  src/screens/Developer/APIKeys/DeveloperUtils.res
  src/screens/Developer/PaymentSettings/PaymentSettings.res
  src/screens/Developer/PaymentSettings/PaymentSettingsListEntity.res
  src/screens/Settings/BusinessMapping/BusinessMappingEntity.res
  src/screens/Settings/HSwitchSettingTypes.res
  src/screens/Settings/MerchantAccountUtils.res
  src/utils/LogicUtils.res
  src/utils/Mappers/BusinessProfileMapper.res
Labels: S-waiting-on-review, core

#1560 fix: Selected item displays on top of list
  src/components/SelectBox.res
Labels: C-ui

#1571 feat: tooltip fix and enhancement
  src/screens/NewAnalytics/Graphs/LineGraph/LineGraphTypes.res
  src/screens/NewAnalytics/Graphs/LineGraph/LineGraphUtils.res
  src/screens/NewAnalytics/NewAnalyticsHelper.res
  src/screens/NewAnalytics/NewAnalyticsTypes.res
  src/screens/NewAnalytics/NewAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycleUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSection.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRate.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRateUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistribution.res
  src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistributionUtils.res
Labels: S-waiting-on-review, analytics

#1538 fix: UI connector preview
  src/screens/Connectors/ConnectPayPalFlow/MenuOptionForPayPal.res
  src/screens/Connectors/ConnectorHome.res
  src/screens/Connectors/ConnectorPreview.res
  src/screens/Connectors/ConnectorPreviewHelper.res
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUpdateAuthCreds.res
  src/screens/Connectors/ConnectorUtils.res
  src/screens/PMAuthenticationProcessor/PMAuthenticationHome.res
  src/screens/TaxProcessor/TaxProcessorHome.res
  src/screens/ThreeDsProcessors/ThreeDsProcessorHome.res
  src/utils/Mappers/ConnectorListMapper.res
Labels: core, C-ui

#1575 fix: Update status of connector ( Disable / Enable )
  src/screens/Connectors/ConnectorPreview.res
Labels: S-waiting-on-review, core

#1574 feat: graphs legends display
  src/container/AnalyticsContainer.res
  src/entryPoints/HyperSwitchApp.res
  src/hooks/AuthHooks.res
  src/screens/NewAnalytics/NewAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRateUtils.res
Labels: analytics

#1569 feat: Addition of new connector "NEXIXPAY"
  public/hyperswitch/Gateway/NEXIXPAY.svg
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUtils.res
Labels: S-in-progress

#1556 chore: file movement for two fa attempts inside dashboard
  src/screens/Settings/HSwitchProfile/ModifyTwoFaSettings.res
  src/screens/Settings/HSwitchProfile/TwoFaSettings/ModifyTwoFaSettings.res
  src/screens/Settings/HSwitchProfile/TwoFaSettings/RegenerateRC.res
  src/screens/Settings/HSwitchProfile/TwoFaSettings/ResetTotp.res
  src/screens/Settings/HSwitchProfile/TwoFaSettings/TwoFaHelper.res
Labels: chore

#1543 feat: Org changes for invite
  src/screens/UserManagement/UserRevamp/UserInfo.res
  src/screens/UserManagement/UserRevamp/UserManagementHelper.res
  src/screens/UserManagement/UserRevamp/UserUtils.res
Labels: S-waiting-on-review, core

#828 fix: added command to run the project in windows env
  package.json
Labels: S-waiting-on-review

#1586 fix: url name issue in create custom role page
  src/screens/APIUtils/APIUtils.res
Labels: bug

#1588 fix: unauthorised page issue
  src/components/SelectBox.res
  src/entryPoints/HyperSwitchApp.res
  src/screens/Helpers/PageLoaderWrapper.res
Labels: S-blocked, bug

#1597 feat: fiuu google pay gateway name
  src/screens/Connectors/ConnectorMetaData/GooglePay/GooglePayUtils.res
Labels: S-waiting-on-review, C-feature

#1579 chore: sankey response structure
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycleUtils.res
Labels: S-waiting-on-review, S-blocked, analytics

#1600 chore: overview section spacing fix and payments metrics changes
  src/screens/NewAnalytics/NewAnalyticsTypes.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsEntity.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSection.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
Labels: S-waiting-on-review, analytics

#1563 feat: dispute views
  src/screens/APIUtils/APIUtils.res
  src/screens/APIUtils/APIUtilsTypes.res
  src/screens/Disputes/Disputes.res
  src/screens/TransactionViews/TransactionView.res
  src/screens/TransactionViews/TransactionViewUtils.res
Labels: S-waiting-on-review, core

#1564 fix: profile name validations
  src/screens/Connectors/ConnectorUtils.res
  src/screens/OMPSwitch/MerchantSwitch.res
  src/screens/OMPSwitch/ProfileSwitch.res
Labels: S-waiting-on-review, core

#1605 fix: connected list on top in 3DS connectors , tax processors and PM authentication processors
  src/screens/PMAuthenticationProcessor/PMAuthenticationConnectorList.res
  src/screens/TaxProcessor/TaxProcessorList.res
  src/screens/ThreeDsProcessors/ThreeDsConnectorList.res
Labels: C-ui

#1584 feat: Added search func (profile) and id in OMP dropdowns (scroll and sort fixed)
  public/hyperswitch/assets/copyid.svg
  src/Recoils/HyperswitchAtom.res
  src/components/SelectBox.res
  src/components/SelectBox.resi
  src/screens/Hooks/ClearRecoilValueHook.res
  src/screens/OMPSwitch/MerchantSwitch.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/OMPSwitch/OMPSwitchUtils.res
  src/screens/OMPSwitch/OrgSwitch.res
  src/screens/OMPSwitch/ProfileSwitch.res
Labels: S-waiting-on-review, C-feature

#1613 fix: disable edit for profile level user (Business section)
  src/screens/Hooks/OMPSwitchHooks.res
  src/screens/Settings/BusinessDetails.res
Labels: S-waiting-on-review, bug

#1562 chore: Enhance transaction views
  src/screens/APIUtils/APIUtils.res
  src/screens/TransactionViews/TransactionView.res
  src/screens/TransactionViews/TransactionViewTypes.res
  src/screens/TransactionViews/TransactionViewUtils.res
Labels: S-waiting-on-review, core

#1633 chore: profile name validations on edit profile
  src/screens/Settings/BusinessMapping/BusinessMappingEntity.res
Labels: S-waiting-on-review, core

#1592 chore: create separate webpack
  package.json
  webpack.custom.js
Labels: S-waiting-on-review, chore

#1447 feat: card-network in payment filters
  src/screens/Order/OrderUIUtils.res
Labels: S-waiting-on-review, feature

#1636 fix: new analytics metric name fixes
  src/screens/APIUtils/APIUtils.res
  src/screens/APIUtils/APIUtilsTypes.res
  src/screens/NewAnalytics/NewAnalyticsTypes.res
  src/screens/NewAnalytics/NewAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/FailedPaymentsDistribution/FailedPaymentsDistribution.res
  src/screens/NewAnalytics/PaymentAnalytics/FailedPaymentsDistribution/FailedPaymentsDistributionTypes.res
  src/screens/NewAnalytics/PaymentAnalytics/FailedPaymentsDistribution/FailedPaymentsDistributionUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsEntity.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSection.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionHelper.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionTypes.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedTypes.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRate.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRateTypes.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRateUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistribution.res
  src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistributionTypes.res
  src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistributionUtils.res
Labels: S-waiting-on-review, analytics

#1632 fix: make auto retry value field mandatory
  src/screens/Developer/APIKeys/DeveloperUtils.res
  src/screens/Developer/PaymentSettings/PaymentSettings.res
  src/screens/Settings/MerchantAccountUtils.res
Labels: S-waiting-on-review, core

#1634 fix: single status view setting to all
  src/screens/TransactionViews/TransactionView.res
Labels: S-waiting-on-review, core

#1555 test: creation of test payment using sdk cypress
  config/config.toml
  cypress.config.js
  cypress/e2e/connector/connector.cy.js
Labels: hacktoberfest

#1639 fix: auto retry bug
  src/screens/Settings/MerchantAccountUtils.res
Labels: S-waiting-on-review, core

#1626 fix: merchant account credentials not shown in profile view
  src/container/MerchantAccountContainer.res
Labels: S-waiting-on-review, C-bug

#1643 chore: Add merchant specific config
  config/config.toml
  cypress/e2e/auth/auth.cy.js
  cypress/start_hyperswitch.sh
  src/Recoils/HyperswitchAtom.res
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/HyperSwitchEntry.res
  src/entryPoints/SidebarValues.res
  src/hooks/AuthHooks.res
  src/screens/Hooks/MerchantSpecificConfigHook.res
  src/server/Server.res
  src/server/config.mjs
  webpack.dev.js
Labels: S-waiting-on-review, core

#1655 fix: changes to enable card-network
  src/screens/Order/OrderUIUtils.res
Labels: bug

#1642 feat: Smart retry analytics
  src/screens/NewAnalytics/NewAnalyticsContainerUtils.res
  src/screens/NewAnalytics/NewAnalyticsHelper.res
  src/screens/NewAnalytics/NewAnalyticsTypes.res
  src/screens/NewAnalytics/PaymentAnalytics/FailedPaymentsDistribution/FailedPaymentsDistribution.res
  src/screens/NewAnalytics/PaymentAnalytics/FailedPaymentsDistribution/FailedPaymentsDistributionUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalytics.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsEntity.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycle.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycleUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSection.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRate.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRateUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistribution.res
  src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistributionUtils.res
Labels: S-waiting-on-review, analytics

#1665 fix: analytics sessionizer bugs
  src/screens/Analytics/GlobalSearch/GlobalSearchBarUtils.res
  src/screens/Analytics/GlobalSearch/GlobalSearchTypes.res
  src/screens/Analytics/GlobalSearchResults/SearchResultsPage.res
  src/screens/Home/HomeUtils.res
Labels: S-waiting-on-review, bug

#1658 test: verification of time range filters in payment operations page using cypress
  cypress/e2e/connector/connector.cy.js
  src/components/Calendar.res
  src/components/DateRangeField.res
Labels: S-waiting-on-author, hacktoberfest

#1667 test: Verify Columns in Payment operations page
  cypress/e2e/Payment/00001-PaymentOperationsColumns.cy.js
  cypress/support/commands.js
Labels: hacktoberfest
