Repository juspay/hyperswitch-control-center, pull requests merged in 2024-08, with the labels that each got.

#1104 fix: added datatrans connector icon
  public/hyperswitch/Gateway/DATATRANS.svg
Labels: S-waiting-on-review, core

#1106 fix: signin password check removed
  src/entryPoints/AuthModule/BasicAuth/BasicAuth.res
  src/entryPoints/AuthModule/TwoFaAuth/TwoFaAuth.res
Labels: S-waiting-on-review, user-management

#1116 chore: extra param for row level customization with select box
  src/components/FilterSelectBox.res
  src/components/SelectBox.res
  src/components/SelectBox.resi
Labels: S-waiting-on-review, chore

#1096 chore: plaid connector addition
  public/hyperswitch/Gateway/PLAID.svg
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review

#1133 fix: frictionless success metric fix
  src/screens/Analytics/AuthenticationAnalytics/AuthenticationAnalyticsEntity.res
Labels: S-waiting-on-review

#1118 chore: changes for tabs & table customization
  src/components/LoadedTable.res
  src/components/LoadedTable.resi
  src/components/Table.res
  src/components/Table.resi
  src/components/Tabs.res
  src/components/Tabs.resi
Labels: S-waiting-on-review, chore

#1102 chore: performance monitor
  config/config.toml
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/SidebarValues.res
  src/screens/APIUtils/APIUtils.res
  src/screens/APIUtils/APIUtilsTypes.res
  src/screens/Analytics/AnalyticsTypes.res
  src/screens/Analytics/PaymentsAnalytics/PaymentAnalytics.res
  src/screens/Analytics/PerformanceMonitor/BarChartPerformance/BarChartPerformance.res
  src/screens/Analytics/PerformanceMonitor/BarChartPerformance/BarChartPerformanceUtils.res
  src/screens/Analytics/PerformanceMonitor/PerformanceMonitor.res
  src/screens/Analytics/PerformanceMonitor/PerformanceMonitorEntity.res
  src/screens/Analytics/PerformanceMonitor/PerformanceMonitorTypes.res
  src/screens/Analytics/PerformanceMonitor/PerformanceUtils.res
  src/screens/Analytics/PerformanceMonitor/PieChartPerformance/PieChartPerformance.res
  src/screens/Analytics/PerformanceMonitor/PieChartPerformance/PieChartPerformanceUtils.res
Labels: S-waiting-on-review, analytics

#1136 fix: commented apex charts and pinned mixpanel version
  package.json
  src/components/HSwitchSingleStatWidget.res
Labels: S-waiting-on-review

#1140 chore: added merchant connector id
  src/screens/Connectors/ConnectorTableUtils.res
Labels: S-waiting-on-review

#1143 fix: frm api payload update
  src/screens/FraudAndRisk/FRMInfo.res
Labels: S-waiting-on-review

#1135 refactor: using joinWith instead of joinWithUnsafe
  src/components/AdvancedSearchModal.res
  src/components/CustomCharts/LineChartUtils.res
  src/components/DateRangeField.res
  src/components/DateRangePicker.res
  src/components/DynamicChart.res
  src/components/DynamicSingleStat.res
  src/components/DynamicTable.res
  src/components/DynamicTabs.res
  src/components/Filter.res
  src/components/FilterSelectBox.res
  src/components/FilterUtils.res
  src/components/LoadedTable.res
  src/components/RemoteFiltersUtils.res
  src/components/SelectBox.res
  src/components/TimeInput.res
  src/components/form/FormRenderer.res
  src/components/form/NumericTextInput.res
  src/context/ChartContext.res
  src/context/SingleStatContext.res
  src/context/UserPrefContext.res
  src/entryPoints/AuthModule/Common/CommonAuthUtils.res
  src/hooks/DateRefreshHooks.res
  src/screens/Analytics/Analytics.res
  src/screens/Analytics/SystemMetrics/SystemMetricsAnalytics.res
  src/screens/Connectors/ConnectPayPalFlow/ConnectPayPal.res
  src/screens/Connectors/ConnectorPreview.res
  src/screens/Connectors/ConnectorTableUtils.res
  src/screens/Home/CommonConnectorFlow/SetupConnector.res
  src/screens/PayoutRouting/PayoutRoutingStack.res
  src/screens/Recon/ReconModule.res
  src/screens/Routing/RoutingStack.res
  src/screens/RoutingRevamp/AdvancedRoutingUIUtils.res
  src/screens/SelfServe/HSwitchProdOnboarding/ProdOnboardingLanding.res
  src/screens/UserManagement/RolesEntity.res
  src/screens/WooCommerce/WooCommerceUIUtils.res
  src/utils/HyperSwitchUtils.res
  src/utils/LogicUtils.res
  src/utils/UrlUtils.res
Labels: S-waiting-on-review

#1126 feat: integrating pm authenticator processor in connector flow
  src/screens/Connectors/ConnectorMetaData/ApplePay/ApplePayIntegration.res
  src/screens/Connectors/ConnectorMetaData/BankDebit/BankDebit.res
  src/screens/Connectors/ConnectorMetaData/BankDebit/BankDebitTypes.res
  src/screens/Connectors/ConnectorMetaData/BankDebit/BankDebitUtils.res
  src/screens/Connectors/ConnectorPaymentMethod.res
  src/screens/Connectors/ConnectorUIUtils/PaymentMethod.res
  src/screens/Connectors/PaymentMethodAdditionalDetails/AdditionalDetailsSidebar.res
  src/screens/Connectors/PaymentMethodAdditionalDetails/AdditionalDetailsSidebarHelper.res
  src/screens/Connectors/Wallets/Wallet.res
  src/screens/Home/CommonConnectorFlow/SetupConnector.res
  src/screens/StripePlusPaypal/StripePlusPaypalUIUtils.res
  src/screens/WooCommerce/WooCommerceUIUtils.res
Labels: S-waiting-on-review, core

#1151 chore: update wasm
  public/hyperswitch/wasm/euclid.d.ts
  public/hyperswitch/wasm/euclid.js
  public/hyperswitch/wasm/euclid_bg.wasm
  public/hyperswitch/wasm/euclid_bg.wasm.d.ts
Labels: S-waiting-on-review

#1149 feat: added table performance
  src/components/CustomCharts/HighchartTimeSeriesChart.res
  src/components/CustomCharts/LineChartUtils.res
  src/components/Table.res
  src/screens/Analytics/PerformanceMonitor/BarChartPerformance/BarChartPerformance.res
  src/screens/Analytics/PerformanceMonitor/BarChartPerformance/BarChartPerformanceUtils.res
  src/screens/Analytics/PerformanceMonitor/PerformanceMonitor.res
  src/screens/Analytics/PerformanceMonitor/PerformanceMonitorEntity.res
  src/screens/Analytics/PerformanceMonitor/PerformanceMonitorTypes.res
  src/screens/Analytics/PerformanceMonitor/PerformanceUtils.res
  src/screens/Analytics/PerformanceMonitor/PieChartPerformance/PieChartPerformance.res
  src/screens/Analytics/PerformanceMonitor/PieChartPerformance/PieChartPerformanceUtils.res
  src/screens/Analytics/PerformanceMonitor/TablePerformance/TablePerformance.res
  src/screens/Analytics/PerformanceMonitor/TablePerformance/TablePerformanceUtils.res
Labels: S-waiting-on-review, analytics

#1157 chore: added mca id in 3ds and pm auth table
  src/screens/PMAuthenticationProcessor/PMAuthenticationTableEntity.res
  src/screens/ThreeDsProcessors/ThreeDsTableEntity.res
Labels: S-waiting-on-review

#1153 fix: bug fix
  src/screens/Connectors/ConnectorMetaData/BankDebit/BankDebit.res
  src/screens/PMAuthenticationProcessor/PMAuthenticationHome.res
Labels: S-waiting-on-review, bug

#1152 fix: Feature flag sidebar
  src/screens/Connectors/ConnectorUIUtils/PaymentMethod.res
Labels: S-waiting-on-review, bug

#1155 feat: added sr rate graphs
  src/screens/Analytics/PerformanceMonitor/BarChartPerformance/BarChartPerformanceUtils.res
  src/screens/Analytics/PerformanceMonitor/GaugeChart/CustomGraphs/GaugeFailureRate.res
  src/screens/Analytics/PerformanceMonitor/GaugeChart/CustomGraphs/GaugeFailureRateUtils.res
  src/screens/Analytics/PerformanceMonitor/GaugeChart/GaugeChartPerformance.res
  src/screens/Analytics/PerformanceMonitor/GaugeChart/GaugeChartPerformanceUtils.res
  src/screens/Analytics/PerformanceMonitor/PerformanceMonitor.res
  src/screens/Analytics/PerformanceMonitor/PerformanceMonitorEntity.res
  src/screens/Analytics/PerformanceMonitor/PerformanceMonitorTypes.res
  src/screens/Analytics/PerformanceMonitor/PerformanceUtils.res
  src/screens/Analytics/PerformanceMonitor/PieChartPerformance/PieChartPerformanceUtils.res
Labels: S-waiting-on-review, analytics

#1141 refactor: removed unused packages
  package-lock.json
  package.json
  src/components/SketchPicker.res
  src/libraries/CsvToJson.res
  src/libraries/HtmlToImage.res
  src/libraries/IntroJsReact.res
  src/libraries/NProgress.css
  src/libraries/NProgress.res
  src/libraries/ReactVirtualizedAutoSizer.res
Labels: S-waiting-on-review, chore

#1161 chore: refactor gauge chart entity
  src/screens/Analytics/PerformanceMonitor/BarChartPerformance/BarChartPerformance.res
  src/screens/Analytics/PerformanceMonitor/BarChartPerformance/BarChartPerformanceUtils.res
  src/screens/Analytics/PerformanceMonitor/GaugeChart/CustomGraphs/GaugeFailureRate.res
  src/screens/Analytics/PerformanceMonitor/GaugeChart/CustomGraphs/GaugeFailureRateUtils.res
  src/screens/Analytics/PerformanceMonitor/GaugeChart/GaugeChartPerformance.res
  src/screens/Analytics/PerformanceMonitor/GaugeChart/GaugeChartPerformanceUtils.res
  src/screens/Analytics/PerformanceMonitor/PerformanceMonitor.res
  src/screens/Analytics/PerformanceMonitor/PerformanceMonitorEntity.res
  src/screens/Analytics/PerformanceMonitor/PerformanceMonitorTypes.res
  src/screens/Analytics/PerformanceMonitor/PerformanceUtils.res
  src/screens/Analytics/PerformanceMonitor/PieChartPerformance/PieChartPerformance.res
  src/screens/Analytics/PerformanceMonitor/PieChartPerformance/PieChartPerformanceUtils.res
  src/screens/Analytics/PerformanceMonitor/TablePerformance/TablePerformance.res
Labels: S-waiting-on-review, chore, analytics

#1165 chore: refund type removed from refunds api
  src/screens/Order/OrderRefundForm.res
Labels: S-waiting-on-review, chore

#1170 fix: failure rate formula fix
  src/screens/Analytics/PerformanceMonitor/GaugeChart/CustomGraphs/GaugeFailureRateUtils.res
Labels: S-waiting-on-review, bug, analytics

#782 chore: frm api changes
  src/screens/Connectors/ConnectorTypes.res
  src/screens/FraudAndRisk/FRMPaymentMethods.res
  src/screens/FraudAndRisk/FRMSummary.res
  src/screens/FraudAndRisk/FRMTypes.res
  src/screens/FraudAndRisk/FRMUtils.res
  src/utils/Mappers/ConnectorListMapper.res
Labels: S-waiting-on-review, core

#1171 chore: updated wasm
  public/hyperswitch/wasm/euclid.js
  public/hyperswitch/wasm/euclid_bg.wasm
Labels: S-waiting-on-review

#1065 chore: updating the user profile in mixpanel after user login
  src/entryPoints/AuthModule/BasicAuth/BasicAuth.res
  src/entryPoints/AuthModule/Common/CommonAuthUtils.res
  src/entryPoints/AuthModule/TwoFaAuth/TwoFaAuth.res
  src/entryPoints/HyperSwitchEntry.res
  src/screens/MixpanelHook.res
Labels: S-waiting-on-review

#1167 chore: connector api dependency on orders removed
  src/screens/Order/OrderEntity.res
  src/screens/Order/OrderTypes.res
  src/screens/Order/Orders.res
  src/screens/Order/ShowOrder.res
Labels: S-waiting-on-review

#1169 chore: user revamp independent files
  config/config.toml
  public/hyperswitch/icons/solid.svg
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/SidebarValues.res
  src/screens/UserManagement/UserManagementTypes.res
Labels: S-waiting-on-review, chore

#1183 fix: totp extra settings not visible in profile page
  src/entryPoints/AuthModule/UserInfo/UserInfoUtils.res
Labels: S-waiting-on-review, bug

#1178 feat: performance monitor exclude filter value
  src/screens/Analytics/PerformanceMonitor/BarChartPerformance/BarChartPerformance.res
  src/screens/Analytics/PerformanceMonitor/GaugeChart/CustomGraphs/GaugeFailureRate.res
  src/screens/Analytics/PerformanceMonitor/GaugeChart/GaugeChartPerformance.res
  src/screens/Analytics/PerformanceMonitor/PerformanceMonitor.res
  src/screens/Analytics/PerformanceMonitor/PerformanceMonitorEntity.res
  src/screens/Analytics/PerformanceMonitor/PerformanceMonitorTypes.res
  src/screens/Analytics/PerformanceMonitor/PerformanceUtils.res
  src/screens/Analytics/PerformanceMonitor/PieChartPerformance/PieChartPerformance.res
  src/screens/Analytics/PerformanceMonitor/TablePerformance/TablePerformance.res
Labels: S-waiting-on-review, analytics, feature

#1110 chore: make email with password login
  src/entryPoints/AuthModule/BasicAuth/BasicAuthScreen.res
  src/entryPoints/AuthModule/Common/CommonAuthHooks.res
  src/entryPoints/AuthModule/TwoFaAuth/TwoFaAuthScreen.res
Labels: S-waiting-on-review, core

#1190 fix: performance monitor bugs
  src/components/Paginator.res
  src/screens/Analytics/PerformanceMonitor/GaugeChart/CustomGraphs/GaugeFailureRateUtils.res
  src/screens/Analytics/PerformanceMonitor/GaugeChart/GaugeChartPerformanceUtils.res
Labels: S-waiting-on-review, bug, analytics

#1195 fix: loading page height before login screen
  src/entryPoints/AuthModule/AuthWrapper.res
  src/entryPoints/AuthModule/SSOAuth/SSODecisionScreen.res
Labels: S-waiting-on-review

#1113 chore: List users UI changes
  .github/PULL_REQUEST_TEMPLATE.md
  public/hyperswitch/icons/solid.svg
  public/hyperswitch/wasm/package.json
  src/entryPoints/HyperSwitchApp.res
  src/screens/APIUtils/APIUtils.res
  src/screens/UserManagement/CommonUtils/UserManagementTypes.res
  src/screens/UserManagement/CommonUtils/UserManagementUtils.res
  src/screens/UserManagement/OldUserManagement/CreateCustomRole.res
  src/screens/UserManagement/OldUserManagement/InviteUsers.res
  src/screens/UserManagement/OldUserManagement/PermissionUtils.res
  src/screens/UserManagement/OldUserManagement/RoleListTableView.res
  src/screens/UserManagement/OldUserManagement/RolesEntity.res
  src/screens/UserManagement/OldUserManagement/ShowUserData.res
  src/screens/UserManagement/OldUserManagement/UserRoleEntity.res
  src/screens/UserManagement/OldUserManagement/UserRoleEntry.res
  src/screens/UserManagement/UserRevamp/ListRoles.res
  src/screens/UserManagement/UserRevamp/ListUserTableEntity.res
  src/screens/UserManagement/UserRevamp/ListUsers.res
  src/screens/UserManagement/UserRevamp/UserManagementLanding.res
Labels: S-waiting-on-review, user-management

#1175 chore: plaid minor enhancements
  src/screens/Connectors/ConnectorMetaData/BankDebit/BankDebit.res
  src/screens/Connectors/ConnectorMetaData/BankDebit/BankDebitUtils.res
  src/screens/Connectors/PaymentMethodAdditionalDetails/AdditionalDetailsSidebar.res
Labels: S-waiting-on-review

#1082 fix: redirect on new tab fix
  src/components/CustomCharts/HighchartTimeSeriesChart.res
  src/components/LoadedTable.res
  src/components/ReactWindowTable.res
  src/components/router/Link.res
  src/screens/Analytics/Analytics.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/PaymentAttempt/PaymentAttemptEntity.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/PaymentIntent/PaymentIntentEntity.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/Refunds/RefundsTableEntity.res
  src/screens/Analytics/Logs/LogUtils/AuditLogUI.res
  src/screens/Analytics/PaymentsAnalytics/PaymentAnalytics.res
  src/screens/Analytics/PaymentsAnalytics/SmartRetryAnalytics.res
  src/screens/Analytics/SystemMetrics/SystemMetricsAnalytics.res
  src/screens/Customers/CustomersEntity.res
  src/screens/Disputes/DisputesEntity.res
  src/screens/HSwitchRemoteFilter.res
  src/screens/Order/HSwitchOrderUtils.res
  src/screens/Order/OrderEntity.res
  src/screens/Order/OrderUIUtils.res
  src/screens/Payouts/PayoutsEntity.res
  src/screens/Payouts/PayoutsUtils.res
  src/screens/Refunds/RefundEntity.res
  src/screens/Refunds/RefundUtils.res
  src/screens/Sidebar/Sidebar.res
  src/utils/BreadCrumbNavigation.res
  src/utils/UrlUtils.res
Labels: S-waiting-on-review, bug, core

#1193 chore: pmt billing address name fields
  src/screens/Order/OrderEntity.res
  src/screens/Order/OrderTypes.res
  src/screens/Order/ShowOrder.res
Labels: S-waiting-on-review, core

#1207 chore: graphs color code update
  src/entryPoints/SidebarValues.res
  src/screens/Analytics/PerformanceMonitor/BarChartPerformance/BarChartPerformanceUtils.res
  src/screens/Analytics/PerformanceMonitor/PieChartPerformance/PieChartPerformanceUtils.res
Labels: S-waiting-on-review, analytics

#1176 chore: refactor initial pageload
  src/components/NotFoundPage.res
  src/components/UnauthorizedPage.res
  src/container/BusinessProfileContainer.res
  src/container/ConnectorContainer.res
  src/container/MerchantAccountContainer.res
  src/entryPoints/HyperSwitchApp.res
  src/screens/Connectors/ConnectorList.res
  src/screens/Connectors/ConnectorPaymentMethod.res
  src/screens/Home/Home.res
Labels: S-waiting-on-review, chore, core

#1213 chore: rearrange connector folders
  src/screens/Connectors/Common/CommonConnectorHelper.res
  src/screens/Connectors/Common/CommonConnectorTypes.res
  src/screens/Connectors/Common/CommonConnectorUtils.res
  src/screens/Connectors/ConnectorMetaData/ApplePay/ApplePayIntegrationHelper.res
  src/screens/Connectors/ConnectorMetaData/ApplePay/ApplePayManualFlow.res
  src/screens/Connectors/ConnectorMetaData/ApplePay/ApplePaySimplifiedFlow.res
  src/screens/Connectors/ConnectorMetaData/ApplePay/ApplePayZen.res
  src/screens/Connectors/ConnectorMetaData/ConnectorMetaData.res
  src/screens/Connectors/ConnectorMetaData/ConnectorMetaDataUtils.res
  src/screens/Connectors/ConnectorMetaData/GooglePay/GooglePayIntegration.res
  src/screens/Connectors/ConnectorMetaData/GooglePay/GooglePayUtils.res
  src/screens/Connectors/ConnectorUtils.res
Labels: chore, core

#1202 feat: paybox wellsfargo connector added
  public/hyperswitch/Gateway/PAYBOX.svg
  public/hyperswitch/Gateway/WELLSFARGO.svg
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review, core

#1220 feat: pagination support for payouts table
  src/screens/Payouts/PayoutsList.res
  src/screens/Payouts/PayoutsUtils.res
Labels: S-waiting-on-review, core

#1211 feat: Netcetera to prod
  src/screens/Connectors/ConnectorUtils.res
  src/screens/ThreeDsProcessors/ThreeDsConnectorList.res
Labels: Closed

#1224 chore: user info provider changes
  src/entryPoints/AuthModule/Common/CommonAuthHooks.res
  src/entryPoints/AuthModule/UserInfo/UserInfoProvider.res
  src/entryPoints/AuthModule/UserInfo/UserInfoTypes.res
  src/entryPoints/AuthModule/UserInfo/UserInfoUtils.res
  src/screens/Home/Home.res
  src/screens/Home/HomeV2.res
  src/screens/Settings/HSwitchProfile/HSwitchProfileSettings.res
  src/screens/SwitchMerchant/SwitchMerchant.res
Labels: S-waiting-on-review, chore

#1222 chore: auth hooks change
  src/hooks/AuthHooks.res
Labels: S-waiting-on-review, chore

#1228 fix: smart retries tooltip bug fix
  src/components/HSwitchSingleStatTableWidget.res
  src/screens/Analytics/PaymentsAnalytics/SmartRetryAnalytics.res
Labels: S-waiting-on-review, analytics

#1234 fix: disputes table col ordering
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/Disputes/DisputeTableEntity.res
Labels: S-waiting-on-review, core

#1230 fix: payouts pagination order fix
  src/screens/Payouts/PayoutsList.res
Labels: S-waiting-on-review, core

#1236 fix: hyperlinks fix at login page
  src/entryPoints/AuthModule/Common/CommonAuthForm.res
Labels: S-waiting-on-review, core

#1246 fix: pagination rows per page selector fix
  src/components/Paginator.res
Labels: S-waiting-on-review, core

#1235 chore: home payments ops copy changes
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/PaymentAttempt/PaymentAttemptEntity.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/PaymentIntent/PaymentIntentEntity.res
  src/screens/Order/OrderEntity.res
  src/screens/Order/OrderUIUtils.res
Labels: S-waiting-on-review, core

#1249 feat: Core changes omp list
  public/hyperswitch/icons/solid.svg
  src/components/SelectBox.res
  src/components/SelectBox.resi
  src/screens/APIUtils/APIUtils.res
  src/screens/APIUtils/APIUtilsTypes.res
  src/screens/Sidebar/Sidebar.res
  tailwind.config.js
Labels: S-waiting-on-review

#1221 feat: switch component for OMP
  src/entryPoints/HyperSwitchApp.res
  src/screens/OMPSwitch/MerchantSwitch.res
  src/screens/OMPSwitch/OMPSwitchTypes.res
  src/screens/OMPSwitch/OMPSwitchUtils.res
  src/screens/OMPSwitch/OrgSwitch.res
  src/screens/OMPSwitch/ProfileSwitch.res
  src/screens/Settings/BusinessMapping/BusinessProfile.res
  src/screens/Sidebar/Sidebar.res
  src/screens/Sidebar/SidebarSwitch.res
Labels: S-waiting-on-review

#1232 chore: list users with api changes
  src/screens/APIUtils/APIUtils.res
  src/screens/APIUtils/APIUtilsTypes.res
  src/screens/UserManagement/UserRevamp/ListUserTableEntity.res
  src/screens/UserManagement/UserRevamp/ListUsers.res
Labels: chore, user-management

#1253 chore: Org, merch ,profile list atom
  src/Recoils/HyperswitchAtom.res
  src/screens/OMPSwitch/MerchantSwitch.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/OMPSwitch/OMPSwitchTypes.res
  src/screens/OMPSwitch/OMPSwitchUtils.res
  src/screens/OMPSwitch/OrgSwitch.res
  src/screens/OMPSwitch/ProfileSwitch.res
Labels: S-waiting-on-review, chore
