Repository juspay/hyperswitch-control-center, pull requests merged in 2024-04, with the labels that each got.

#540 chore: Js.Array2 core changes for sorted function
  src/components/CustomCharts/HighchartTimeSeriesChart.res
  src/components/CustomCharts/LineChartUtils.res
  src/components/CustomizeTableColumns.res
  src/components/HSwitchSingleStatWidget.res
  src/components/LoadedTable.res
  src/components/ReactWindowTable.res
  src/components/SelectBox.res
  src/screens/Analytics/Logs/LogUtils/LogUtils.res
  src/screens/Analytics/PaymentsAnalytics/PaymentAnalyticsEntity.res
  src/screens/Analytics/RefundsAnalytics/RefundsAnalyticsEntity.res
  src/screens/Analytics/SystemMetrics/SystemMetricsAnalyticsUtils.res
  src/screens/Analytics/UserAnalytics/UserJourneyAnalyticsEntity.res
  src/screens/Connectors/ConnectorTableUtils.res
  src/screens/Routing/RoutingStack.res
  src/screens/ThreeDsProcessors/ThreeDsTableEntity.res
  src/screens/componentsDemo/DragDrop.res
  src/screens/componentsDemo/DragDropComponent.res
  src/screens/componentsDemo/DragNDropDemo.res
  src/screens/componentsDemo/DragNDropDemo.resi
  src/utils/LogicUtils.res
Labels: S-waiting-on-review

#542 fix: audit log scroll fix
  src/screens/Analytics/Logs/LogUtils/AuditLogUI.res
Labels: S-waiting-on-review

#550 chore: global search feature flag
  config/FeatureFlag.json
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/screens/Analytics/GlobalSearch/GlobalSearchBar.res
  src/screens/Analytics/GlobalSearchResults/SearchResultsPage.res
Labels: S-waiting-on-review

#493 chore: sorting processor list
  src/screens/Connectors/ConnectorUtils.res
  src/screens/Processors/ProcessorCards.res
Labels: S-waiting-on-review

#552 chore: payout wasm changes
  public/hyperswitch/module.js
  public/hyperswitch/wasm/euclid_bg.wasm
  src/libraries/Window.res
Labels: S-waiting-on-review

#553 fix: days to respond in show disputes issue
  src/screens/Disputes/ShowDisputes.res
Labels: S-waiting-on-review

#557 chore: added feature flag for disputes
  config/FeatureFlag.json
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/SidebarValues.res
Labels: S-waiting-on-review

#495 feat: accept country and currency while configuring a connector
  public/hyperswitch/icons/solid.svg
  src/components/RemoteFilter.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/SidebarValues.res
  src/screens/APIUtils/APIUtils.res
  src/screens/APIUtils/APIUtilsTypes.res
  src/screens/ConfigurePMTs/PaymentMethodConfig.res
  src/screens/ConfigurePMTs/PaymentMethodConfigTypes.res
  src/screens/ConfigurePMTs/PaymentMethodConfigUtils.res
  src/screens/ConfigurePMTs/PaymentMethodEntity.res
  src/screens/ConfigurePMTs/paymentMethodList.res
  src/screens/Connectors/ConnectorPreview.res
  src/screens/Connectors/ConnectorUtils.res
  src/screens/Sidebar/Sidebar.res
  src/utils/Mappers/ConnectorListMapper.res
  tailwind.config.js
Labels: S-waiting-on-review

#561 fix: Billwerk connector addition
  public/hyperswitch/wasm/euclid.d.ts
  public/hyperswitch/wasm/euclid.js
  public/hyperswitch/wasm/euclid_bg.wasm
  public/hyperswitch/wasm/euclid_bg.wasm.d.ts
  public/hyperswitch/wasm/package.json
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review, S-blocked

#562 fix: billwerk icon addition
  public/hyperswitch/Gateway/BILLWERK.svg
Labels: S-waiting-on-review

#563 fix: billwerk-icon change
  public/hyperswitch/Gateway/BILLWERK.svg
  src/components/SelectBox.res
  src/screens/ConfigurePMTs/PaymentMethodConfigUtils.res
Labels: S-waiting-on-review

#564 fix: configure pmts page issue fix
  config/FeatureFlag.json
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/SidebarValues.res
  src/screens/ConfigurePMTs/PaymentMethodConfig.res
  tailwind.config.js
Labels: S-waiting-on-review

#569 fix: return url and webhook url regex change
  src/screens/Connectors/ConnectorPreview.res
  src/screens/Developer/PaymentSettings/PaymentSettings.res
  src/screens/Settings/BusinessDetails.res
  src/screens/Settings/MerchantAccountUtils.res
Labels: S-waiting-on-review

#567 chore: checkbox input type added
  src/components/InputFields.res
  src/components/InputFields.resi
Labels: S-waiting-on-review

#572 fix: webhook url and return url regex change
  src/screens/Settings/MerchantAccountUtils.res
Labels: S-waiting-on-review

#582 chore: audit log ui fixes
  src/screens/Analytics/Logs/LogUtils/ApiDetailsComponent.res
  src/screens/Analytics/Logs/LogUtils/AuditLogUI.res
  src/screens/Analytics/Logs/LogUtils/LogUtils.res
Labels: S-waiting-on-review

#578 feat: zsl processor addition
  public/hyperswitch/Gateway/ZSL.svg
  public/hyperswitch/index.html
  public/hyperswitch/module.js
  public/hyperswitch/wasm/euclid.js
  public/hyperswitch/wasm/euclid_bg.wasm
  public/hyperswitch/wasm/package.json
  src/config/UIConfig.res
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review

#527 chore: dummy processor flow
  cypress/e2e/processors/processores-paypal_test.cy.js
  public/hyperswitch/Gateway/FAUXPAY.svg
  public/hyperswitch/Gateway/PAYPAL_TEST.svg
  public/hyperswitch/Gateway/PRETENDPAY.svg
  public/hyperswitch/Gateway/STRIPE_TEST.svg
  public/hyperswitch/assets/CopyToClipboard.svg
  public/hyperswitch/icons/solid.svg
  src/components/DatePicker.res
  src/components/HSwitchFeedBackModal.res
  src/components/HSwitchFeedBackModalUtils.res
  src/components/LoadedTable.res
  src/components/MultiLineTextInput.res
  src/components/ReactWindowTable.res
  src/components/Table.resi
  src/components/TableUtils.res
  src/components/TableUtils.resi
  src/components/form/FormRenderer.res
  src/components/form/TextInput.res
  src/config/UIConfig.res
  src/screens/Connectors/ConnectorList.res
  src/screens/Connectors/ConnectorTableUtils.res
  src/screens/Connectors/ConnectorUtils.res
  src/screens/Disputes/DisputesEntity.res
  src/screens/FraudAndRisk/FRMSelect.res
  src/screens/Home/HomeV2.res
  src/screens/Order/OrderEntity.res
  src/screens/Processors/DummyProcessorModal.res
  src/screens/Processors/ProcessorCards.res
  src/screens/Refunds/RefundEntity.res
  src/screens/ThreeDsProcessors/ThreeDsConnectorList.res
  src/screens/Utils/PageUtils.res
  src/utils/LogicUtils.res
  src/utils/Modal.res
  src/utils/ModalUtils.res
  tailwind.config.js
Labels: S-waiting-on-review

#584 fix: Ui button css changes
  src/components/Button.res
  src/config/UIConfig.res
Labels: S-waiting-on-review

#583 feat: signout api call
  src/screens/APIUtils/APIUtils.res
Labels: S-waiting-on-review

#591 fix: added dummy connector image
  public/hyperswitch/assets/DummyConnectorImage.svg
Labels: S-waiting-on-review

#566 chore: profile page changes
  src/components/LoadedTable.res
  src/components/Table.res
  src/screens/Settings/HSwitchProfile/HSwitchProfileSettings.res
  src/screens/Settings/HSwitchProfile/HSwitchProfileSettingsEntity.res
  src/screens/SwitchMerchant/SwitchMerchant.res
  src/screens/SwitchMerchant/SwitchMerchantUtils.res
  src/utils/LogicUtils.res
Labels: S-waiting-on-review

#600 fix: agreement version change
  src/utils/HSwitchGlobalVars.res
Labels: S-waiting-on-review

#602 chore: update connector metadata for nmi and 3ds
  public/hyperswitch/wasm/euclid.js
  public/hyperswitch/wasm/euclid_bg.wasm
  public/hyperswitch/wasm/package.json
  src/components/InputFields.res
  src/components/InputFields.resi
  src/components/form/BoolInput.res
  src/screens/Connectors/ConnectorAccountDetailsHelper.res
  src/screens/Connectors/ConnectorUtils.res
  src/screens/ThreeDsProcessors/ThreeDsProcessorHome.res
Labels: S-waiting-on-review

#603 fix: base url show payments fix
  src/screens/Order/OrderEntity.res
Labels: S-waiting-on-review

#606 feat: Authorize.net in prod
  src/screens/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review

#605 feat: added netcetera threeds authenticator
  public/hyperswitch/wasm/euclid_bg.wasm
  src/entryPoints/WooCommerce/WooCommerceUIUtils.res
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUtils.res
  src/screens/Home/CommonConnectorFlow/SetupConnector.res
  src/screens/Home/QuickStart/QuickStartUtils.res
Labels: S-blocked

#607 fix: netcetera icon added
  public/hyperswitch/Gateway/NETCETERA.svg
  public/hyperswitch/wasm/package.json
  src/screens/Connectors/ConnectorAccountDetailsHelper.res
  src/screens/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review

#608 fix: empty box in connector fix
  src/screens/Connectors/ConnectorAccountDetailsHelper.res
Labels: Closed

#601 fix: global search ux
  src/components/CustomExpandableTable.res
  src/components/DynamicChart.res
  src/components/HSwitchFeedBackModal.res
  src/components/HeadlessUISelectBox.res
  src/components/MakeRuleFieldComponent.res
  src/components/Paginator.res
  src/components/PopUpConfirm.res
  src/components/SingleStats/SingleStatEntity.res
  src/components/TableLocalFilters.res
  src/components/TableUtils.res
  src/entities/analytics/EulerAnalyticsLogUtils.res
  src/screens/Analytics/GlobalSearch/GlobalSearchBarUtils.res
  src/screens/Analytics/GlobalSearchResults/Tables/PaymentAttempt/PaymentAttemptEntity.res
  src/screens/Analytics/GlobalSearchResults/Tables/Refunds/RefundsTableEntity.res
  src/screens/Order/HSwitchOrderUtils.res
  src/screens/PayoutRouting/PayoutRoutingStack.res
Labels: C-bug

#593 feat: onboarding survey changes
  src/entryPoints/HyperSwitchApp.res
  src/screens/APIUtils/APIUtils.res
  src/screens/APIUtils/APIUtilsTypes.res
  src/screens/Connectors/ConnectorAccountDetailsHelper.res
  src/screens/Home/QuickStart/QuickStartTypes.res
  src/screens/Home/QuickStart/QuickStartUtils.res
  src/screens/Others/CompanyNameModal.res
  src/screens/Others/OnboardingSurveyModalUtils.res
  src/screens/Others/SbxOnboardingSurvey.res
Labels: S-waiting-on-review

#609 fix: onboarding survey api call fix
  src/entryPoints/HyperSwitchApp.res
Labels: S-waiting-on-review
