Repository juspay/hyperswitch-control-center, pull requests merged in 2024-07, with the labels that each got.

#881 refactor: handle logout hook changes
  src/context/AuthInfoProvider.res
  src/entryPoints/AcceptInvite.res
  src/entryPoints/AuthModule/AuthWrapper.res
  src/entryPoints/AuthModule/BasicAuth/BasicAuthWrapper.res
  src/entryPoints/AuthModule/BasicAuth/BasicDecisionScreen.res
  src/entryPoints/AuthModule/BasicAuth/BasicEmailVerifyScreen.res
  src/entryPoints/AuthModule/BasicAuth/BasicInviteFromEmail.res
  src/entryPoints/AuthModule/Common/CommonInviteScreen.res
  src/entryPoints/AuthModule/PreLoginModule/AcceptInviteScreen.res
  src/entryPoints/AuthModule/PreLoginModule/AuthSelect.res
  src/entryPoints/AuthModule/PreLoginModule/DecisionScreen.res
  src/entryPoints/AuthModule/PreLoginModule/MerchantSelectScreen.res
  src/entryPoints/AuthModule/PreLoginModule/ResetPassword.res
  src/entryPoints/AuthModule/PreLoginModule/VerifyUserFromEmail.res
  src/entryPoints/AuthModule/SSOAuth/SSODecisionScreen.res
  src/entryPoints/AuthModule/TwoFaAuth/TotpSetup.res
  src/entryPoints/AuthModule/UserInfoScreen.res
  src/libraries/CookieStorage.res
  src/screens/APIUtils/APIUtils.res
  src/screens/Home/HomeUtils.res
  src/screens/PostLoginScreen/PostLoginScreen.res
  src/screens/Sidebar/Sidebar.res
  src/screens/Utils/DefaultLandingPage.res
Labels: S-waiting-on-review

#885 chore: singout api call falling using spt
  src/context/AuthInfoProvider.res
  src/entryPoints/AuthModule/AuthWrapper.res
  src/entryPoints/AuthModule/BasicAuth/BasicDecisionScreen.res
  src/entryPoints/AuthModule/BasicAuth/BasicEmailVerifyScreen.res
  src/entryPoints/AuthModule/BasicAuth/BasicInviteFromEmail.res
  src/entryPoints/AuthModule/Common/CommonInviteScreen.res
  src/entryPoints/AuthModule/PreLoginModule/AcceptInviteScreen.res
  src/entryPoints/AuthModule/PreLoginModule/AuthSelect.res
  src/entryPoints/AuthModule/PreLoginModule/DecisionScreen.res
  src/entryPoints/AuthModule/PreLoginModule/MerchantSelectScreen.res
  src/entryPoints/AuthModule/PreLoginModule/ResetPassword.res
  src/entryPoints/AuthModule/PreLoginModule/VerifyUserFromEmail.res
  src/entryPoints/AuthModule/SSOAuth/SSODecisionScreen.res
  src/entryPoints/AuthModule/TwoFaAuth/TotpSetup.res
  src/entryPoints/AuthModule/UserInfoScreen.res
Labels: S-waiting-on-review

#883 chore: payment logs ui changes
  src/components/DynamicTabs.res
  src/screens/Analytics/Logs/LogUtils/AuditLogUI.res
Labels: S-waiting-on-review

#872 feat: realtime user analytics
  config/config.toml
  public/hyperswitch/icons/solid.svg
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/screens/APIUtils/APIUtils.res
  src/screens/APIUtils/APIUtilsTypes.res
  src/screens/Analytics/ActiveUserCounter.res
Labels: S-waiting-on-author, C-feature

#896 chore: more date filter options
  src/components/DateRangeField.res
  src/components/tooltip/ToolTip.res
  src/screens/Analytics/HSAnalyticsUtils.res
  src/screens/Order/OrderUIUtils.res
  src/screens/Payouts/PayoutsUtils.res
  src/screens/Refunds/RefundUtils.res
Labels: S-waiting-on-review

#895 chore: orders card network column change and orders and refunds more …
  src/components/LoadedTable.res
  src/screens/APIUtils/APIUtils.res
  src/screens/Order/OrderEntity.res
  src/screens/Order/Orders.res
  src/screens/Refunds/Refund.res
Labels: S-waiting-on-review

#917 fix: routing stack bug fix
  src/screens/Routing/RoutingStack.res
Labels: S-waiting-on-review, bug

#919 fix: accept invite flow breaking for non-auth users
  src/entryPoints/AuthModule/AuthUtils.res
  src/entryPoints/AuthModule/AuthWrapper.res
  src/entryPoints/AuthModule/PreLoginModule/AuthSelect.res
  src/entryPoints/AuthModule/SSOAuth/SSOTypes.res
  src/entryPoints/AuthModule/SSOAuth/SSOUtils.res
Labels: S-waiting-on-review, bug

#925 fix: analytics warnings
  src/components/DynamicChart.res
  src/components/DynamicTabs.res
  src/screens/Analytics/Analytics.res
Labels: chore-analytcis

#863 chore: analytics filters separation
  src/components/CustomCharts/HighchartTimeSeriesChart.res
  src/components/CustomCharts/LineChartUtils.res
  src/components/DynamicChart.res
  src/components/DynamicSingleStat.res
  src/components/DynamicTabs.res
  src/components/HSwitchSingleStatTableWidget.res
  src/components/HSwitchSingleStatWidget.res
  src/components/tooltip/ToolTip.res
  src/components/tooltip/ToolTip.resi
  src/entryPoints/HyperSwitchApp.res
  src/libraries/ApexCharts.res
  src/screens/Analytics/Analytics.res
  src/screens/Analytics/AnalyticsNew.res
  src/screens/Analytics/AnalyticsTypes.res
  src/screens/Analytics/AuthenticationAnalytics/AuthenticationAnalyticsEntity.res
  src/screens/Analytics/DisputeAnalytics/DisputeAnalyticsEntity.res
  src/screens/Analytics/HomePageOverview/HomePageOverviewComponent.res
  src/screens/Analytics/HomePageOverview/PaymentsOverview/PaymentOverview.res
  src/screens/Analytics/HomePageOverview/PaymentsOverview/PaymentOverviewUtils.res
  src/screens/Analytics/PaymentsAnalytics/PaymentAnalytics.res
  src/screens/Analytics/PaymentsAnalytics/PaymentAnalyticsEntity.res
  src/screens/Analytics/RefundsAnalytics/RefundsAnalyticsEntity.res
  src/screens/Analytics/SystemMetrics/SystemMetricsAnalytics.res
  src/screens/Analytics/SystemMetrics/SystemMetricsAnalyticsUtils.res
  src/screens/Analytics/UserJourneyAnalytics/UserJourneyAnalyticsEntity.res
Labels: S-waiting-on-review

#924 feat: analytics more granularity to the graphs
  src/components/CustomCharts/LineChartUtils.res
  src/components/DynamicChart.res
  src/components/DynamicSingleStat.res
Labels: S-waiting-on-review, analytics

#934 fix: return url validation
  src/screens/Developer/PaymentSettings/PaymentSettings.res
  src/screens/Settings/HSwitchSettingTypes.res
  src/screens/Settings/MerchantAccountUtils.res
Labels: bug

#936 chore: api utils refactoring
  src/screens/APIUtils/APIUtils.res
  src/screens/APIUtils/APIUtilsTypes.res
Labels: S-waiting-on-review

#933 feat: mixpanel page view
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HyperSwitchEntry.res
  src/screens/MixpanelHook.res
Labels: S-waiting-on-review, C-feature

#951 chore: added razorpay in payment connectors
  public/hyperswitch/Gateway/RAZORPAY.svg
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review

#957 chore: url refactoring
  src/entryPoints/AuthModule/TwoFaAuth/TotpSetup.res
  src/entryPoints/HyperSwitchApp.res
  src/screens/APIUtils/APIUtils.res
  src/screens/APIUtils/APIUtilsTypes.res
  src/screens/Connectors/ConnectPayPalFlow/ConnectPayPal.res
  src/screens/Connectors/ConnectPayPalFlow/PayPalFlowUtils.res
  src/screens/Connectors/ConnectorHome.res
  src/screens/Connectors/Wallets/ApplePayWalletIntegration.res
  src/screens/FraudAndRisk/FRMConfigure.res
  src/screens/Home/ProdIntent/ProdIntentForm.res
  src/screens/Home/QuickStart/GoLive.res
  src/screens/Hooks/EnumVariantHook.res
  src/screens/PayoutRouting/PayoutRoutingStack.res
  src/screens/Routing/DefaultRouting.res
  src/screens/Routing/RoutingStack.res
  src/screens/RoutingRevamp/AdvancedRouting.res
  src/screens/SelfServe/HSwitchProdOnboarding/ProdOnboardingLanding.res
  src/screens/SelfServe/HSwitchProdOnboarding/ProdOnboardingUtils.res
  src/screens/UserManagement/CreateCustomRole.res
  src/screens/UserManagement/InviteUsers.res
  src/screens/UserManagement/ShowUserData.res
  src/screens/UserManagement/UserRoleEntry.res
Labels: S-waiting-on-review

#959 fix: heading for new table column merchant ref id
  src/screens/Order/OrderEntity.res
Labels: S-waiting-on-review

#961 feat: added feature flag for the granularity
  config/config.toml
  src/components/DynamicChart.res
  src/entryPoints/FeatureFlagUtils.res
  src/screens/Analytics/UserJourneyAnalytics/UserJourneyAnalytics.res
  src/screens/Analytics/UserJourneyAnalytics/UserJourneyAnalyticsEntity.res
Labels: S-waiting-on-review, analytics, feature

#926 feat: recon module changes
  config/config.toml
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/HyperSwitchEntry.res
  src/entryPoints/SidebarValues.res
  src/entryPoints/configs/HyperSwitchConfigTypes.res
  src/libraries/Window.res
  src/screens/Recon/ReconModule.res
  src/utils/IframeUtils.res
  tailwind.config.js
Labels: S-waiting-on-review

#971 fix: Recon not showing fixes
  src/entryPoints/SidebarValues.res
Labels: S-waiting-on-review

#970 chore: orders and refunds more table items
  src/components/Paginator.res
  src/screens/APIUtils/APIUtils.res
  src/screens/Order/Orders.res
  src/screens/Refunds/Refund.res
Labels: S-waiting-on-review, C-feature

#964 feat: global search customer email search support
  src/screens/Analytics/GlobalSearch/GlobalSearchBar.res
Labels: S-waiting-on-review, analytics, feature

#973 chore: new connector added bambora apac
  public/hyperswitch/Gateway/BAMBORAAPAC.svg
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUtils.res
Labels: Closed

#963 chore: common filter for payment analytics page
  src/components/DynamicSingleStat.res
  src/components/Filter.res
  src/components/HSwitchSingleStatTableWidget.res
  src/entryPoints/HyperSwitchApp.res
  src/screens/Analytics/AnalyticsNew.res
  src/screens/Analytics/PaymentsAnalytics/PaymentAnalytics.res
  src/screens/Analytics/PaymentsAnalytics/PaymentAnalyticsEntity.res
  src/screens/Analytics/PaymentsAnalytics/SmartRetryAnalytics.res
Labels: S-waiting-on-review, analytics

#975 fix: user analytics granularity fix
  src/components/DynamicChart.res
  src/screens/Analytics/UserJourneyAnalytics/UserJourneyAnalyticsEntity.res
Labels: S-waiting-on-review, analytics

#976 chore: removed console logs for testing
  src/entryPoints/SidebarValues.res
Labels: S-waiting-on-review

#982 fix: dynamic charts and filter ui fix
  src/components/DynamicSingleStat.res
  src/components/Filter.res
  src/components/HSwitchSingleStatWidget.res
  src/screens/Analytics/HomePageOverview/PaymentsOverview/PaymentOverview.res
  src/screens/Analytics/PaymentsAnalytics/PaymentAnalytics.res
  src/screens/Analytics/PaymentsAnalytics/SmartRetryAnalytics.res
  src/screens/Home/HomeUtils.res
Labels: S-waiting-on-review, analytics

#854 chore: refactor connector metadata
  package.json
  public/.DS_Store
  public/hyperswitch/wasm/euclid.js
  public/hyperswitch/wasm/euclid_bg.wasm
  src/screens/Connectors/ConnectPayPalFlow/ConnectPayPal.res
  src/screens/Connectors/ConnectorAccountDetailsHelper.res
  src/screens/Connectors/ConnectorMetaData/ApplePay/ApplePayIntegration.res
  src/screens/Connectors/ConnectorMetaData/ApplePay/ApplePayIntegrationHelper.res
  src/screens/Connectors/ConnectorMetaData/ApplePay/ApplePayIntegrationTypes.res
  src/screens/Connectors/ConnectorMetaData/ApplePay/ApplePayIntegrationUtils.res
  src/screens/Connectors/ConnectorMetaData/ApplePay/ApplePayManualFlow.res
  src/screens/Connectors/ConnectorMetaData/ApplePay/ApplePaySimplifiedFlow.res
  src/screens/Connectors/ConnectorMetaData/ApplePay/ApplePayZen.res
  src/screens/Connectors/ConnectorMetaData/Common/CommonMetaDataHelper.res
  src/screens/Connectors/ConnectorMetaData/Common/CommonMetaDataTypes.res
  src/screens/Connectors/ConnectorMetaData/Common/CommonMetaDataUtils.res
  src/screens/Connectors/ConnectorMetaData/ConnectorMetaData.res
  src/screens/Connectors/ConnectorMetaData/ConnectorMetaDataUtils.res
  src/screens/Connectors/ConnectorMetaData/GooglePay/GooglePayIntegration.res
  src/screens/Connectors/ConnectorMetaData/GooglePay/GooglePayIntegrationTypes.res
  src/screens/Connectors/ConnectorMetaData/GooglePay/GooglePayUtils.res
  src/screens/Connectors/ConnectorPaymentMethod.res
  src/screens/Connectors/ConnectorUIUtils/PaymentMethod.res
  src/screens/Connectors/ConnectorUtils.res
  src/screens/Connectors/Wallets/ApplePayWalletIntegration.res
  src/screens/Connectors/Wallets/ApplePayWalletIntegrationTypes.res
  src/screens/Connectors/Wallets/ApplePayWalletIntegrationUtils.res
  src/screens/Connectors/Wallets/Wallet.res
  src/screens/Home/CommonConnectorFlow/SetupConnector.res
  src/screens/StripePlusPaypal/StripePlusPaypalUIUtils.res
  src/screens/WooCommerce/WooCommerceUIUtils.res
  src/utils/LogicUtils.res
Labels: S-waiting-on-review, chore

#980 fix: generate reports access change
  src/screens/GenerateReports/GenerateReport.res
  src/screens/UserManagement/PermissionUtils.res
Labels: S-waiting-on-review

#931 feat: load time metric - user journey analytics
  src/screens/Analytics/AnalyticsTypes.res
  src/screens/Analytics/UserJourneyAnalytics/UserJourneyAnalyticsEntity.res
  src/utils/LogicUtils.res
Labels: S-waiting-on-review, analytics

#988 fix: audit trail empty log details on load
  src/screens/Analytics/Logs/LogUtils/AuditLogUI.res
Labels: S-waiting-on-review

#946 chore: mixpanel changes
  src/components/router/Link.res
  src/screens/Analytics/GlobalSearch/GlobalSearchBar.res
  src/screens/FraudAndRisk/FRMIntegrationFields.res
  src/screens/FraudAndRisk/FRMPaymentMethods.res
  src/screens/FraudAndRisk/FRMSelect.res
  src/screens/FraudAndRisk/FRMSummary.res
  src/screens/GenerateReports/DownloadReportModal.res
  src/screens/MixpanelHook.res
  src/screens/Recon/Recon.res
  src/screens/Settings/BusinessMapping/BusinessProfile.res
  src/screens/Sidebar/Sidebar.res
  src/screens/Surcharge/Surcharge.res
Labels: S-waiting-on-review

#997 chore: inform users about currency denomination in rule based routing
  src/screens/RoutingRevamp/AdvancedRouting.res
  src/screens/ThreeDSFlow/HSwitchThreeDS.res
Labels: S-waiting-on-review

#979 chore: removed open source tile from Home
  src/screens/Home/HomeUtils.res
  src/screens/Home/HomeV2.res
Labels: S-waiting-on-review

#991 fix: removed agreement screen
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/Provider/ProviderTypes.res
Labels: S-waiting-on-review

#1001 feat: add support for outgoing webhook custom http headers
  src/screens/Developer/PaymentSettings/PaymentSettings.res
  src/screens/Developer/PaymentSettings/PaymentSettingsListEntity.res
  src/screens/Settings/BusinessDetails.res
  src/screens/Settings/BusinessMapping/BusinessMappingEntity.res
  src/screens/Settings/HSwitchSettingTypes.res
  src/screens/Settings/MerchantAccountUtils.res
  src/utils/Mappers/BusinessProfileMapper.res
Labels: S-waiting-on-review, feature

#1002 fix: added attempts count column in payment list table
  src/screens/Order/OrderEntity.res
  src/screens/Order/OrderTypes.res
Labels: S-waiting-on-review

#998 fix: active payments counter changes
  src/entryPoints/HyperSwitchApp.res
  src/screens/Analytics/ActiveUserCounter/ActivePaymentsCounter.res
  src/screens/Analytics/ActiveUserCounter/ActiveUserCounter.res
Labels: S-waiting-on-review, C-feature, analytics

#1020 fix: payout routing rule list
  src/screens/PayoutRouting/PayoutRoutingStack.res
Labels: S-waiting-on-review

#1013 feat: add mifinity to prod
  src/screens/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review

#1018 fix: global search email fix
  src/screens/Analytics/GlobalSearch/GlobalSearchBar.res
  src/screens/Analytics/GlobalSearch/GlobalSearchBarUtils.res
  src/screens/Analytics/GlobalSearchResults/SearchResultsPage.res
Labels: S-waiting-on-review, analytics

#999 chore: replaced deprecated function in webpack
  webpack.dev.js
Labels: S-waiting-on-review

#1005 feat: customer more details
  src/screens/Customers/ShowCustomers.res
Labels: S-waiting-on-review, feature

#1028 fix: Add icon fix for safari
  src/screens/Developer/PaymentSettings/PaymentSettings.res
Labels: S-waiting-on-review

#1030 fix: global search empty table fix
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/Disputes/DisputeTable.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/Disputes/DisputeTableEntity.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/PaymentAttempt/PaymentAttemptEntity.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/PaymentAttempt/PaymentAttemptTable.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/PaymentIntent/PaymentIntentEntity.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/PaymentIntent/PaymentIntentTable.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/Refunds/RefundsTable.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/Refunds/RefundsTableEntity.res
Labels: S-waiting-on-review, bug, analytics

#1036 fix: custom webhook headers
  src/screens/Developer/PaymentSettings/PaymentSettings.res
  src/screens/Settings/MerchantAccountUtils.res
  src/utils/LogicUtils.res
Labels: S-in-progress, bug

#1034 fix: moved delete all sample data from account settings
  src/components/ACLDiv.res
  src/components/ACLDiv.resi
  src/screens/Order/OrderUIUtils.res
  src/screens/Order/Orders.res
Labels: S-waiting-on-review

#1042 feat: itaubank connector addition
  public/hyperswitch/Gateway/ITAUBANK.svg
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review

#1040 fix: global search minor bugs
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/ResultsTableUtils.res
  src/screens/Disputes/ShowDisputes.res
  src/screens/Order/ShowOrder.res
  src/screens/Refunds/ShowRefund.res
Labels: S-waiting-on-review, bug, analytics

#1045 chore: itaubank icon update
  public/hyperswitch/Gateway/ITAUBANK.svg
Labels: S-waiting-on-review

#1059 fix: Sign up button not working for sbx
  src/entryPoints/AuthModule/BasicAuth/BasicAuth.res
  src/entryPoints/AuthModule/TwoFaAuth/TwoFaAuth.res
Labels: S-waiting-on-review

#1057 chore: removing recon_v2 feature flag
  config/config.toml
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/SidebarValues.res
Labels: S-waiting-on-review

#1048 chore: core api changes for regex
  src/components/FilterSelectBox.res
  src/components/SelectBox.res
  src/components/SelectBox.resi
  src/components/Table.resi
  src/components/TableUtils.res
  src/components/TableUtils.resi
  src/components/form/PasswordStrengthInputAsChips.res
  src/entryPoints/AuthModule/Common/CommonAuthUtils.res
  src/entryPoints/AuthModule/TwoFaAuth/OtpInput.res
  src/screens/Connectors/ConnectorUtils.res
  src/screens/Developer/APIKeys/DeveloperUtils.res
  src/screens/HSwitchUtils.res
  src/screens/Home/ProdIntent/ProdVerifyModalUtils.res
  src/screens/Order/OrderUIUtils.res
  src/screens/Routing/RoutingUtils.res
  src/screens/Settings/BusinessMapping/BusinessMappingUtils.res
  src/screens/Settings/MerchantAccountUtils.res
  src/utils/LogicUtils.res
Labels: S-waiting-on-review

#1026 fix: redirect url from payout connector enable/disable
  src/screens/Connectors/ConnectorPreview.res
Labels: S-waiting-on-review

#1053 fix: global search back button fix
  src/screens/Analytics/GlobalSearch/GlobalSearchBar.res
Labels: bug, analytics

#1027 feat: PCI certificate addition under compliance section
  config/config.toml
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/HyperSwitchEntry.res
  src/entryPoints/SidebarValues.res
  src/entryPoints/configs/HyperSwitchConfigTypes.res
  src/screens/SelfServe/HSwitchProdOnboarding/HSwitchAgreementScreen.res
  src/screens/Settings/ComplianceCertificates/Compliance.res
Labels: S-waiting-on-review, feature

#1063 fix: SimplifiedHelper optional
  src/screens/Connectors/ConnectorMetaData/ApplePay/ApplePayIntegrationHelper.res
  src/screens/Connectors/ConnectorMetaData/ApplePay/ApplePaySimplifiedFlow.res
Labels: S-waiting-on-review

#1071 fix: order customer email fix
  src/screens/Order/OrderEntity.res
  src/screens/Order/OrderRefundForm.res
  src/screens/Order/OrderTypes.res
Labels: S-waiting-on-review, bug

#1047 chore: Apple pay extra step addition
  src/screens/Connectors/ConnectorMetaData/ApplePay/ApplePayIntegrationHelper.res
  src/screens/Connectors/ConnectorMetaData/ApplePay/ApplePaySimplifiedFlow.res
  src/screens/Connectors/ConnectorUIUtils/PaymentMethod.res
  src/screens/Settings/ComplianceCertificates/Compliance.res
Labels: S-waiting-on-review

#1075 chore: added frm_metadata in payments api sdk
  src/screens/SDKPayment/SDKPaymentTypes.res
  src/screens/SDKPayment/SDKPaymentUtils.res
Labels: S-waiting-on-review

#1081 fix: rename single stat titles and tooltip texts
  src/screens/Analytics/UserJourneyAnalytics/UserJourneyAnalyticsEntity.res
Labels: analytics

#1089 fix: remove name from address fields
  src/screens/Order/OrderEntity.res
Labels: bug

#1088 chore: improve lighthouse performance
  public/hyperswitch/index.html
  src/components/HyperSwitchLogo.res
  src/components/MultipleFileUpload.res
  src/components/NoDataFound.res
  src/components/custom-icons/GatewayIcon.res
  src/entryPoints/AuthModule/Common/CommonAuth.res
  src/entryPoints/AuthModule/Common/CommonAuthError.res
  src/entryPoints/AuthModule/Common/CommonInviteScreen.res
  src/entryPoints/AuthModule/TwoFaAuth/TotpRecoveryCodes.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/HyperSwitchEntry.res
  src/screens/Analytics/GlobalSearch/GlobalSearchBar.res
  src/screens/Connectors/ConnectPayPalFlow/ConnectPayPal.res
  src/screens/Connectors/ConnectorList.res
  src/screens/Connectors/ConnectorPreview.res
  src/screens/Connectors/ConnectorUIUtils/IntegrationHelp.res
  src/screens/Developer/PaymentSettings/PaymentSettings.res
  src/screens/FraudAndRisk/FRMSelect.res
  src/screens/Helpers/CardUtils.res
  src/screens/Helpers/DefaultLandingPage.res
  src/screens/Helpers/HelperComponents.res
  src/screens/Home/HomeUtils.res
  src/screens/Home/HomeV2.res
  src/screens/Home/QuickStart/QuickStartUIUtils.res
  src/screens/Order/ShowOrder.res
  src/screens/PostLoginScreen/PostLoginScreen.res
  src/screens/Processors/ProcessorCards.res
  src/screens/SDKPayment/SDKPage.res
  src/screens/SDKPayment/TestCredentials.res
  src/screens/SelfServe/HSwitchProdOnboarding/HSwitchAgreementScreen.res
  src/screens/SelfServe/HSwitchSandboxOnboarding/UserOnboardingUIUtils.res
  src/screens/Settings/HSwitchProfile/ModifyTwoFaSettings.res
  src/screens/WooCommerce/WooCommerce.res
Labels: performance

#1091 feat: datatrans new connector addition
  public/hyperswitch/wasm/euclid.js
  public/hyperswitch/wasm/euclid_bg.wasm
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review, core
