Repository juspay/hyperswitch-control-center, pull requests merged in 2024-09, with the labels that each got.

#1226 chore: switch org merch profile logic
  src/entryPoints/AuthModule/UserInfo/UserInfoProvider.res
  src/screens/APIUtils/APIUtils.res
  src/screens/APIUtils/APIUtilsTypes.res
  src/screens/Hooks/OMPSwitchHooks.res
Labels: chore, user-management, user-management-revamp

#1261 chore: integrate core profile level apis
  src/components/SelectBox.resi
  src/entryPoints/AuthModule/UserInfo/UserInfoTypes.res
  src/entryPoints/AuthModule/UserInfo/UserInfoUtils.res
  src/screens/APIUtils/APIUtils.res
  src/screens/APIUtils/APIUtilsTypes.res
  src/screens/Order/Orders.res
  src/screens/Refunds/Refund.res
Labels: feature, core, user-management-revamp

#1269 chore: removed duplicated file and updated imports
  src/screens/Hooks/SwitchHooks.res
  src/screens/OMPSwitch/MerchantSwitch.res
  src/screens/OMPSwitch/OrgSwitch.res
  src/screens/OMPSwitch/ProfileSwitch.res
Labels: S-waiting-on-review

#1255 chore: remove basic auth
  .github/workflows/release-stable-version.yml
  config/config.toml
  src/context/AuthInfoProvider.res
  src/context/TokenContextProvider.res
  src/context/UserPrefContext.res
  src/entryPoints/AcceptInvite.res
  src/entryPoints/AuthModule/AuthModuleHooks.res
  src/entryPoints/AuthModule/AuthProviderTypes.res
  src/entryPoints/AuthModule/BasicAuth/BasicAuth.res
  src/entryPoints/AuthModule/BasicAuth/BasicAuthEntry.res
  src/entryPoints/AuthModule/BasicAuth/BasicAuthScreen.res
  src/entryPoints/AuthModule/BasicAuth/BasicAuthTypes.res
  src/entryPoints/AuthModule/BasicAuth/BasicAuthUtils.res
  src/entryPoints/AuthModule/BasicAuth/BasicAuthWrapper.res
  src/entryPoints/AuthModule/BasicAuth/BasicDecisionScreen.res
  src/entryPoints/AuthModule/BasicAuth/BasicEmailVerifyScreen.res
  src/entryPoints/AuthModule/BasicAuth/BasicInviteFromEmail.res
  src/entryPoints/AuthModule/Common/CommonAuthHooks.res
  src/entryPoints/AuthModule/PreLoginModule/AcceptInviteScreen.res
  src/entryPoints/AuthModule/PreLoginModule/MerchantSelectScreen.res
  src/entryPoints/AuthModule/PreLoginModule/ResetPassword.res
  src/entryPoints/AuthModule/PreLoginModule/VerifyUserFromEmail.res
  src/entryPoints/AuthModule/TwoFaAuth/TwoFaAuth.res
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/HyperSwitchEntry.res
  src/hooks/AuthHooks.res
  src/screens/APIUtils/APIUtils.res
  src/screens/APIUtils/APIUtilsTypes.res
  src/screens/Home/Home.res
  src/screens/Home/HomeV2.res
  src/screens/Settings/BusinessMapping/BusinessProfile.res
  src/screens/Settings/HSwitchProfile/HSwitchProfileSettings.res
  src/screens/Sidebar/Sidebar.res
  src/screens/SwitchMerchant/SwitchMerchant.res
  src/screens/UserManagement/OldUserManagement/InviteUsers.res
Labels: S-waiting-on-review, user-management-revamp

#1217 feat: square connector added
  public/hyperswitch/Gateway/SQUARE.svg
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review, core

#1258 chore: list roles table api changes
  src/screens/APIUtils/APIUtils.res
  src/screens/UserManagement/UserRevamp/ListRoles.res
  src/screens/UserManagement/UserRevamp/ListRolesTableEntity.res
Labels: S-waiting-on-review, user-management, user-management-revamp

#1271 fix: recon issue fixed
  src/container/MerchantAccountContainer.res
  src/entryPoints/HyperSwitchApp.res
Labels: S-waiting-on-review, bug

#1248 fix: routing gateway same name fix
  src/components/priority-logics/AddPLGateway.res
  src/screens/RoutingRevamp/Previewers/RulePreviewer.res
Labels: S-waiting-on-review, core

#1227 feat: profile settings changes
  src/screens/Developer/PaymentSettings/PaymentSettings.res
  src/screens/Developer/PaymentSettings/PaymentSettingsListEntity.res
  src/screens/Settings/BusinessMapping/BusinessMappingEntity.res
  src/screens/Settings/HSwitchSettingTypes.res
  src/screens/Settings/MerchantAccountUtils.res
  src/utils/Mappers/BusinessProfileMapper.res
Labels: S-waiting-on-review, core

#1275 chore: new user invitation independent files
  src/Recoils/HyperswitchAtom.res
  src/entryPoints/AuthModule/UserInfo/UserInfoUtils.res
  src/screens/APIUtils/APIUtils.res
  src/screens/APIUtils/APIUtilsTypes.res
  src/screens/Hooks/OMPSwitchHooks.res
  src/screens/UserManagement/CommonUtils/UserManagementTypes.res
  src/screens/UserManagement/CommonUtils/UserManagementUtils.res
  src/screens/UserManagement/OldUserManagement/ShowUserData.res
  src/screens/UserManagement/OldUserManagement/UserRoleEntry.res
  src/screens/UserManagement/UserRevamp/ListRoles.res
  src/screens/UserManagement/UserRevamp/UserManagementHelper.res
  src/screens/UserManagement/UserRevamp/UserUtils.res
Labels: S-waiting-on-review, chore

#1277 feat: payment views core
  src/components/LoadedTable.res
  src/components/LoadedTableWithCustomColumns.res
  src/components/Table.res
  src/components/Table.resi
  src/screens/APIUtils/APIUtils.res
  src/screens/APIUtils/APIUtilsTypes.res
  src/screens/Order/Orders.res
Labels: S-waiting-on-review, core

#1265 chore: call switch api in core modules
  .gitignore
  public/.DS_Store
  src/components/EntityScaffold.res
  src/container/BusinessProfileContainer.res
  src/container/ConnectorContainer.res
  src/entryPoints/HyperSwitchApp.res
  src/screens/Disputes/DisputeTypes.res
  src/screens/Disputes/DisputesEntity.res
  src/screens/Disputes/ShowDisputes.res
  src/screens/Hooks/OMPSwitchHooks.res
  src/screens/Order/OrderEntity.res
  src/screens/Order/ShowOrder.res
  src/screens/Payouts/PayoutsEntity.res
  src/screens/Payouts/ShowPayout.res
  src/screens/Refunds/RefundEntity.res
  src/screens/Refunds/ShowRefund.res
Labels: core, user-management-revamp

#1283 chore: update user info context with extra parameter
  .github/workflows/release-new-nightly-version.yml
  src/components/Table.resi
  src/entryPoints/AuthModule/UserInfo/UserInfoTypes.res
  src/entryPoints/AuthModule/UserInfo/UserInfoUtils.res
Labels: user-management, core, user-management-revamp

#1287 chore: update user info hook
  src/screens/Hooks/OMPSwitchHooks.res
Labels: user-management, user-management-revamp

#1285 chore: profile level api integration
  src/screens/APIUtils/APIUtils.res
Labels: S-waiting-on-review, chore

#1293 fix: entity scaffold url path
  src/components/EntityScaffold.res
  src/screens/Disputes/ShowDisputes.res
  src/screens/Order/ShowOrder.res
  src/screens/Payouts/ShowPayout.res
  src/screens/Refunds/ShowRefund.res
Labels: user-management-revamp

#1289 feat: added Fiserv IPG connector
  public/hyperswitch/Gateway/FISERVEMEA.svg
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review, core

#1199 chore: New user invitation page
  src/container/UserManagementContainer.res
  src/entryPoints/HyperSwitchApp.res
  src/screens/APIUtils/APIUtils.res
  src/screens/APIUtils/APIUtilsTypes.res
  src/screens/UserManagement/CommonUtils/UserManagementTypes.res
  src/screens/UserManagement/UserRevamp/DropdownWithLoading.res
  src/screens/UserManagement/UserRevamp/InviteMember.res
  src/screens/UserManagement/UserRevamp/NewUserInvitationForm.res
  src/screens/UserManagement/UserRevamp/UserManagementHelper.res
  src/screens/UserManagement/UserRevamp/UserUtils.res
Labels: S-waiting-on-review, user-management

#1290 chore: add profile level views in payment page
  src/container/TransactionContainer.res
  src/entryPoints/AuthModule/UserInfo/UserInfoProvider.res
  src/entryPoints/AuthModule/UserInfo/UserInfoTypes.res
  src/entryPoints/AuthModule/UserInfo/UserInfoUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/screens/APIUtils/APIUtils.res
  src/screens/APIUtils/APIUtilsTypes.res
  src/screens/Disputes/Disputes.res
  src/screens/HSwitchRemoteFilter.res
  src/screens/Hooks/OMPSwitchHooks.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/OMPSwitch/OMPSwitchTypes.res
  src/screens/Order/OrderUIUtils.res
  src/screens/Order/Orders.res
  src/screens/Payouts/PayoutsList.res
  src/screens/Refunds/Refund.res
  src/screens/SwitchMerchant/SwitchMerchantListHook.res
Labels: user-management, user-management-revamp

#1304 chore: disable customers for profile level users
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/SidebarValues.res
  src/screens/APIUtils/APIUtils.res
Labels: S-waiting-on-review, user-management, user-management-revamp

#1300 feat: enabled wellsfargo connector
  src/screens/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review, core

#1302 chore: analytics org merchant profile level api
  src/screens/APIUtils/APIUtils.res
  src/screens/APIUtils/APIUtilsTypes.res
  src/screens/Analytics/AuthenticationAnalytics/AuthenticationAnalytics.res
  src/screens/Analytics/AuthenticationAnalytics/AuthenticationAnalyticsEntity.res
  src/screens/Analytics/DisputeAnalytics/DisputeAnalytics.res
  src/screens/Analytics/DisputeAnalytics/DisputeAnalyticsEntity.res
  src/screens/Analytics/HomePageOverview/HomePageOverviewComponent.res
  src/screens/Analytics/HomePageOverview/PaymentsOverview/PaymentOverview.res
  src/screens/Analytics/HomePageOverview/PaymentsOverview/PaymentOverviewUtils.res
  src/screens/Analytics/Logs/DisputeLogs/DisputeLogs.res
  src/screens/Analytics/Logs/PaymentLogs/PaymentLogs.res
  src/screens/Analytics/Logs/RefundLogs/RefundLogs.res
  src/screens/Analytics/PaymentsAnalytics/PaymentAnalytics.res
  src/screens/Analytics/PaymentsAnalytics/PaymentAnalyticsEntity.res
  src/screens/Analytics/PaymentsAnalytics/SmartRetryAnalytics.res
  src/screens/Analytics/RefundsAnalytics/RefundsAnalytics.res
  src/screens/Analytics/RefundsAnalytics/RefundsAnalyticsEntity.res
  src/screens/Analytics/SystemMetrics/SystemMetricsAnalytics.res
  src/screens/Analytics/SystemMetrics/SystemMetricsAnalyticsUtils.res
  src/screens/Analytics/UserJourneyAnalytics/UserJourneyAnalytics.res
  src/screens/Analytics/UserJourneyAnalytics/UserJourneyAnalyticsEntity.res
Labels: chore, analytics, user-management-revamp

#1308 feat: fiuu connector added
  public/hyperswitch/Gateway/FIUU.svg
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review, core

#1208 chore: show user details page
  public/hyperswitch/icons/solid.svg
  src/container/UserManagementContainer.res
  src/screens/APIUtils/APIUtils.res
  src/screens/APIUtils/APIUtilsTypes.res
  src/screens/UserManagement/CommonUtils/UserManagementTypes.res
  src/screens/UserManagement/UserRevamp/ListUserTableEntity.res
  src/screens/UserManagement/UserRevamp/ManageUserModal.res
  src/screens/UserManagement/UserRevamp/NewUserInvitationForm.res
  src/screens/UserManagement/UserRevamp/UserInfo.res
  src/screens/UserManagement/UserRevamp/UserManagementHelper.res
  src/screens/UserManagement/UserRevamp/UserUtils.res
Labels: S-waiting-on-review, user-management, user-management-revamp

#1303 chore: org merchant profile level views analytics
  src/container/AnalyticsContainser.res
  src/entryPoints/AuthModule/UserInfo/UserInfoProvider.res
  src/entryPoints/AuthModule/UserInfo/UserInfoTypes.res
  src/entryPoints/AuthModule/UserInfo/UserInfoUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/screens/Analytics/Analytics.res
  src/screens/Analytics/PaymentsAnalytics/PaymentAnalytics.res
  src/screens/Analytics/PerformanceMonitor/PerformanceMonitor.res
  src/screens/Analytics/RefundsAnalytics/RefundsAnalytics.res
  src/screens/Disputes/Disputes.res
  src/screens/Hooks/OMPSwitchHooks.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/OMPSwitch/OMPSwitchUtils.res
  src/screens/Order/Orders.res
  src/screens/Payouts/PayoutsList.res
  src/screens/Refunds/Refund.res
Labels: S-blocked, chore, analytics, user-management-revamp

#1307 chore: Pending invites screen changes
  src/entryPoints/AuthModule/PreLoginModule/DecisionScreen.res
  src/entryPoints/AuthModule/PreLoginModule/ListInvitationScreen.res
  src/entryPoints/AuthModule/PreLoginModule/PreLoginTypes.res
  src/entryPoints/AuthModule/PreLoginModule/PreLoginUtils.res
  src/screens/APIUtils/APIUtils.res
  src/screens/APIUtils/APIUtilsTypes.res
Labels: S-waiting-on-review, user-management, user-management-revamp

#1311 fix: bug fixes user restructuring
  src/components/SelectBox.res
  src/components/SelectBox.resi
  src/entryPoints/AuthModule/UserInfo/UserInfoUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/screens/APIUtils/APIUtils.res
  src/screens/OMPSwitch/MerchantSwitch.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/OMPSwitch/OMPSwitchUtils.res
  src/screens/OMPSwitch/OrgSwitch.res
  src/screens/OMPSwitch/ProfileSwitch.res
  src/screens/Sidebar/Sidebar.res
  src/screens/Sidebar/SidebarSwitch.res
Labels: S-waiting-on-review

#1299 fix: dialog on org , merchant and profile switch & bug-fixes
  src/container/UserManagementContainer.res
  src/entryPoints/HyperSwitchApp.res
  src/screens/APIUtils/APIUtils.res
  src/screens/OMPSwitch/MerchantSwitch.res
  src/screens/OMPSwitch/OrgSwitch.res
  src/screens/OMPSwitch/ProfileSwitch.res
  src/screens/UserManagement/UserRevamp/DropdownWithLoading.res
Labels: S-waiting-on-review

#1317 fix: user-revamp fixes
  src/container/MerchantAccountContainer.res
  src/container/UserManagementContainer.res
  src/entryPoints/AuthModule/UserInfo/UserInfoUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/SidebarValues.res
  src/screens/Analytics/Analytics.res
  src/screens/Disputes/Disputes.res
  src/screens/Hooks/ClearRecoilValueHook.res
  src/screens/Hooks/OMPSwitchHooks.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/OMPSwitch/OMPSwitchUtils.res
  src/screens/SDKPayment/SDKPage.res
  src/screens/UserManagement/OldUserManagement/CreateCustomRole.res
  src/screens/UserManagement/UserRevamp/InviteMember.res
  src/screens/UserManagement/UserRevamp/ListRoles.res
  src/screens/UserManagement/UserRevamp/ListUserTableEntity.res
  src/screens/UserManagement/UserRevamp/ListUsers.res
  src/screens/UserManagement/UserRevamp/ManageUserModal.res
  src/screens/UserManagement/UserRevamp/UserInfo.res
  src/screens/UserManagement/UserRevamp/UserManagementHelper.res
Labels: S-waiting-on-review, user-management-revamp

#1318 fix: fixed all profiles issue in teams
  src/screens/UserManagement/UserRevamp/DropdownWithLoading.res
  src/screens/UserManagement/UserRevamp/InviteMember.res
Labels: S-waiting-on-review

#1324 fix: merchant id from user-info
  src/screens/Analytics/GlobalSearch/GlobalSearchBar.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/ResultsTableUtils.res
  src/screens/Analytics/GlobalSearchResults/SearchResultsPage.res
  src/screens/Connectors/ConnectorMetaData/ApplePay/ApplePaySimplifiedFlow.res
Labels: S-waiting-on-review

#1313 feat: mixpanel 5xx error
  src/screens/APIUtils/APIUtils.res
Labels: S-waiting-on-review, core

#1330 chore: pending invitations in home page
  src/entryPoints/PendingInvitationsHome.res
  src/screens/APIUtils/APIUtils.res
  src/screens/APIUtils/APIUtilsTypes.res
  src/screens/Home/Home.res
  src/screens/Home/HomeV2.res
  src/screens/MixpanelHook.res
  src/screens/UserManagement/UserRevamp/InviteMember.res
  src/screens/UserManagement/UserRevamp/NewUserInvitationForm.res
Labels: S-waiting-on-review, user-management, user-management-revamp

#1198 feat: table remote sorting feature
  src/components/CustomCharts/HighchartTimeSeriesChart.res
  src/components/CustomExpandableTable.res
  src/components/DynamicTable.res
  src/components/HSwitchSingleStatTableWidget.res
  src/components/LoadedTable.res
  src/components/LoadedTable.resi
  src/components/LoadedTableWithCustomColumns.res
  src/components/ReactWindowTable.res
  src/components/Table.res
  src/components/TableUtils.res
  src/screens/Analytics/DisputeAnalytics/DisputeAnalyticsEntity.res
  src/screens/Analytics/ErrorReasons.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/Disputes/DisputeTableEntity.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/PaymentAttempt/PaymentAttemptEntity.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/PaymentIntent/PaymentIntentEntity.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/Refunds/RefundsTableEntity.res
  src/screens/Analytics/PaymentsAnalytics/PaymentAnalyticsEntity.res
  src/screens/Analytics/PerformanceMonitor/PerformanceMonitorEntity.res
  src/screens/Analytics/RefundsAnalytics/RefundsAnalyticsEntity.res
  src/screens/ConfigurePMTs/PaymentMethodEntity.res
  src/screens/Connectors/ConnectorTableUtils.res
  src/screens/Customers/CustomersEntity.res
  src/screens/Developer/APIKeys/DeveloperUtils.res
  src/screens/Developer/PaymentSettings/PaymentSettingsListEntity.res
  src/screens/Disputes/DisputesEntity.res
  src/screens/HSwitchRemoteFilter.res
  src/screens/Order/OrderEntity.res
  src/screens/Order/OrderRefundForm.res
  src/screens/Order/OrderTypes.res
  src/screens/Order/Orders.res
  src/screens/PMAuthenticationProcessor/PMAuthenticationTableEntity.res
  src/screens/PayoutRouting/PayoutHistoryTableEntity.res
  src/screens/Payouts/PayoutsEntity.res
  src/screens/Refunds/RefundEntity.res
  src/screens/Routing/HistoryEntity.res
  src/screens/Settings/BusinessMapping/BusinessMappingEntity.res
  src/screens/ThreeDsProcessors/ThreeDsTableEntity.res
  src/screens/UserManagement/OldUserManagement/RolesEntity.res
  src/screens/UserManagement/OldUserManagement/UserRoleEntity.res
  src/screens/UserManagement/UserRevamp/ListRolesTableEntity.res
  src/screens/UserManagement/UserRevamp/ListUserTableEntity.res
Labels: S-waiting-on-review, feature, core

#1338 feat: new analytics tabs
  src/components/Tabs.res
  src/container/NewAnalyticsContainer.res
  src/entryPoints/HyperSwitchApp.res
  src/screens/NewAnalytics/NewAnalyticsTypes.res
  src/screens/NewAnalytics/NewAnalyticsUtils.res
Labels: S-waiting-on-review, analytics

#1350 fix: ui bugs homepage
  src/screens/OMPSwitch/MerchantSwitch.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/OMPSwitch/ProfileSwitch.res
  src/screens/Sidebar/SidebarSwitch.res
Labels: S-waiting-on-review

#1355 fix: user management revamp bugs
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/SidebarValues.res
  src/screens/OMPSwitch/ProfileSwitch.res
  src/screens/UserManagement/UserRevamp/ListRoles.res
Labels: S-waiting-on-review, user-management

#1365 fix: volume based routing fix
  src/components/priority-logics/AddPLGateway.res
Labels: bug

#1366 fix: global search fixes
  src/screens/Analytics/GlobalSearch/GlobalSearchBarUtils.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/Disputes/DisputeTableEntity.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/PaymentAttempt/PaymentAttemptEntity.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/PaymentIntent/PaymentIntentEntity.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/Refunds/RefundsTableEntity.res
Labels: S-waiting-on-review, user-management

#1349 chore: line graph utils
  src/screens/NewAnalytics/Graphs/LineGraph/LineGraph.res
  src/screens/NewAnalytics/Graphs/LineGraph/LineGraphTypes.res
  src/screens/NewAnalytics/Graphs/LineGraph/LineGraphUtils.res
  src/screens/NewAnalytics/Graphs/SankyGraph/SankeyGraph.res
  src/screens/NewAnalytics/OverViewAnalytics/OverViewAnalytics.res
  src/screens/NewAnalytics/OverViewAnalytics/OverViewAnalyticsEntity.res
  src/screens/NewAnalytics/OverViewAnalytics/OverViewAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalytics.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsEntity.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsUtils.res
Labels: S-waiting-on-review, analytics

#1378 feat: core file changes for tax processor addition
  config/config.toml
  public/hyperswitch/module.js
  src/entryPoints/FeatureFlagUtils.res
  src/libraries/Window.res
Labels: S-waiting-on-review

#1389 chore: moved user management files from old modules
  src/screens/UserManagement/UserRevamp/CreateCustomRole.res
  src/screens/UserManagement/UserRevamp/PermissionUtils.res
Labels: S-waiting-on-review, chore

#1391 chore: update wasm for tax processor
  public/hyperswitch/wasm/euclid.d.ts
  public/hyperswitch/wasm/euclid.js
  public/hyperswitch/wasm/euclid_bg.wasm
  public/hyperswitch/wasm/euclid_bg.wasm.d.ts
Labels: S-waiting-on-review

#1203 feat: payment operation revamp
  src/components/DateRangeField.res
  src/components/Filter.res
  src/screens/APIUtils/APIUtils.res
  src/screens/Order/OrderUIUtils.res
  src/screens/Order/Orders.res
  src/screens/TransactionViews/TransactionView.res
  src/screens/TransactionViews/TransactionViewTypes.res
  src/screens/TransactionViews/TransactionViewUtils.res
Labels: S-waiting-on-review, core

#1373 feat: novalnet connector addition
  public/hyperswitch/Gateway/NOVALNET.svg
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review, core

#1377 chore: analytics entity refactor
  src/screens/NewAnalytics/NewAnalyticsHelper.res
  src/screens/NewAnalytics/NewAnalyticsTypes.res
  src/screens/NewAnalytics/OverViewAnalytics/OverViewAnalytics.res
  src/screens/NewAnalytics/OverViewAnalytics/OverViewAnalyticsEntity.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalytics.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsEntity.res
Labels: S-waiting-on-review, analytics

#1379 feat: tax processor addition and taxjar addition
  src/container/ConnectorContainer.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/SidebarValues.res
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUtils.res
  src/screens/Routing/RoutingTypes.res
  src/screens/Routing/RoutingUtils.res
  src/screens/TaxProcessor/TaxProcessorHome.res
  src/screens/TaxProcessor/TaxProcessorList.res
  src/screens/TaxProcessor/TaxProcessorTableEntity.res
  src/screens/TaxProcessor/TaxProcessorTypes.res
Labels: S-waiting-on-review, core

#1381 feat: table view switch to the graph component
  src/screens/NewAnalytics/Graphs/LineGraph/LineGraph.res
  src/screens/NewAnalytics/NewAnalyticsHelper.res
  src/screens/NewAnalytics/NewAnalyticsTypes.res
  src/screens/NewAnalytics/OverViewAnalytics/OverViewAnalytics.res
  src/screens/NewAnalytics/OverViewAnalytics/OverViewAnalyticsEntity.res
  src/screens/NewAnalytics/OverViewAnalytics/OverViewAnalyticsTypes.res
  src/screens/NewAnalytics/OverViewAnalytics/OverViewAnalyticsUtils.res
  src/screens/NewAnalytics/OverViewAnalytics/PaymentsProcessed/PaymentsProcessed.res
  src/screens/NewAnalytics/OverViewAnalytics/PaymentsProcessed/PaymentsProcessedEntity.res
  src/screens/NewAnalytics/OverViewAnalytics/PaymentsProcessed/PaymentsProcessedTypes.res
  src/screens/NewAnalytics/OverViewAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalytics.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsEntity.res
Labels: S-waiting-on-review, analytics

#1405 chore: tax processor
  src/container/ConnectorContainer.res
  src/screens/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review, bug

#1400 feat: handle masked api keys
  src/screens/Connectors/ConnectorHome.res
  src/screens/Connectors/ConnectorPreview.res
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUpdateAuthCreds.res
  src/screens/Connectors/ConnectorUtils.res
  src/screens/FraudAndRisk/FRMConfigure.res
  src/screens/FraudAndRisk/FRMSummary.res
  src/screens/Home/CommonConnectorFlow/QuickStartConnectorFlow.res
  src/screens/PMAuthenticationProcessor/PMAuthenticationHome.res
  src/screens/StripePlusPaypal/StripePlusPaypal.res
  src/screens/TaxProcessor/TaxProcessorHome.res
  src/screens/ThreeDsProcessors/ThreeDsProcessorHome.res
  src/screens/WooCommerce/WooCommerce.res
  src/utils/Mappers/ConnectorListMapper.res
Labels: S-waiting-on-review, core

#1396 fix: bug fixes ui
  src/entryPoints/AuthModule/TwoFaAuth/OtpInput.res
  src/entryPoints/AuthModule/TwoFaAuth/TotpSetup.res
Labels: S-waiting-on-review, bug

#1394 feat: Remove user-management revamp feature flag
  config/config.toml
  src/container/UserManagementContainer.res
  src/entryPoints/AuthModule/PreLoginModule/DecisionScreen.res
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/SidebarValues.res
  src/screens/APIUtils/APIUtils.res
  src/screens/Analytics/Analytics.res
  src/screens/Analytics/PaymentsAnalytics/PaymentAnalytics.res
  src/screens/Analytics/PerformanceMonitor/PerformanceMonitor.res
  src/screens/Disputes/Disputes.res
  src/screens/Home/Home.res
  src/screens/Home/HomeV2.res
  src/screens/Order/Orders.res
  src/screens/Payouts/PayoutsList.res
  src/screens/Refunds/Refund.res
  src/screens/Settings/BusinessMapping/BusinessProfile.res
  src/screens/Sidebar/Sidebar.res
  src/screens/UserManagement/CommonUtils/UserManagementUtils.res
  src/screens/UserManagement/OldUserManagement/InviteUsers.res
  src/screens/UserManagement/OldUserManagement/RoleListTableView.res
  src/screens/UserManagement/OldUserManagement/RolesEntity.res
  src/screens/UserManagement/OldUserManagement/ShowUserData.res
  src/screens/UserManagement/OldUserManagement/UserRoleEntity.res
  src/screens/UserManagement/OldUserManagement/UserRoleEntry.res
  src/screens/UserManagement/UserRevamp/InviteMember.res
  src/screens/UserManagement/UserRevamp/ListRoles.res
  src/screens/UserManagement/UserRevamp/ListUserTableEntity.res
  src/screens/UserManagement/UserRevamp/ListUsers.res
  src/screens/UserManagement/UserRevamp/ManageUserModal.res
  src/screens/UserManagement/UserRevamp/UserInfo.res
Labels: S-waiting-on-review, feature

#1409 chore: home page changes for profile level users
  src/screens/Home/HomeUtils.res
Labels: S-waiting-on-review, chore

#1416 chore: merchant name validation added
  src/screens/OMPSwitch/MerchantSwitch.res
Labels: S-waiting-on-review, chore

#1408 feat: new connector deutsche bank
  public/hyperswitch/Gateway/DEUTSCHEBANK.svg
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review, core

#1429 chore: update wasm for deutsche
  public/hyperswitch/wasm/euclid_bg.wasm
Labels: S-waiting-on-review

#1427 chore: post login questions page related files removal
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/Provider/ProviderTypes.res
  src/screens/Home/DelayedVerificationBanner.res
  src/screens/PostLoginScreen/PostLoginScreen.res
  src/screens/PostLoginScreen/PostLoginUtils.res
Labels: S-waiting-on-review, chore

#1420 test: cypress update
  .github/workflows/cypress-test.yml
  README.md
  cypress/e2e/auth/auth.cy.js
  cypress/e2e/processors/processores-paypal_test.cy.js
  cypress/e2e/quick-start/prod-quick-start.cy.js
  cypress/e2e/quick-start/sbx-quick-start.cy.js
  cypress/start_hyperswitch.sh
  cypress/support/commands.js
  package.json
  src/entryPoints/AuthModule/TwoFaAuth/TotpSetup.res
Labels: cypress

#1438 chore: UI change update creds
  src/screens/Connectors/ConnectorPreview.res
  src/screens/Connectors/ConnectorUpdateAuthCreds.res
Labels: chore

#1432 fix: user management name changes
  src/screens/UserManagement/UserRevamp/ListRolesTableEntity.res
  src/screens/UserManagement/UserRevamp/UserInfo.res
Labels: S-waiting-on-review, bug

#1434 chore: update profile dropdown
  src/screens/OMPSwitch/ProfileSwitch.res
Labels: S-waiting-on-review, core

#1440 feat: new tabs ui
  src/entryPoints/SidebarValues.res
  src/screens/NewAnalytics/NewAnalyticsContainerUtils.res
  src/screens/NewAnalytics/NewAnalyticsHelper.res
  src/screens/NewAnalytics/NewAnalyticsTypes.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycleTypes.res
Labels: analytics, core

#1439 chore: payments success rate graph
  src/screens/NewAnalytics/Graphs/LineGraph/LineGraph.res
  src/screens/NewAnalytics/Graphs/LineGraph/LineGraphTypes.res
  src/screens/NewAnalytics/NewAnalyticsHelper.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalytics.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsEntity.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedTypes.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRate.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRateTypes.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRateUtils.res
Labels: S-waiting-on-review, analytics

#1452 fix: omp views changes in analytics & ops
  src/screens/Analytics/Analytics.res
  src/screens/Analytics/AuthenticationAnalytics/AuthenticationAnalytics.res
  src/screens/Analytics/DisputeAnalytics/DisputeAnalytics.res
  src/screens/Analytics/HSAnalyticsUtils.res
  src/screens/Analytics/PaymentsAnalytics/PaymentAnalytics.res
  src/screens/Analytics/RefundsAnalytics/RefundsAnalytics.res
  src/screens/Analytics/SystemMetrics/SystemMetricsAnalytics.res
  src/screens/Analytics/UserJourneyAnalytics/UserJourneyAnalytics.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/OMPSwitch/OMPSwitchUtils.res
Labels: S-waiting-on-review

#1457 feat: bar graph entity
  src/screens/Connectors/ConnectorPreview.res
  src/screens/Connectors/ConnectorUpdateAuthCreds.res
  src/screens/NewAnalytics/Graphs/BarGraph/BarGraph.res
  src/screens/NewAnalytics/Graphs/BarGraph/BarGraphTypes.res
  src/screens/NewAnalytics/Graphs/BarGraph/BarGraphUtils.res
Labels: S-waiting-on-review, analytics

#1453 fix: list users views in users page
  src/screens/APIUtils/APIUtils.res
  src/screens/Hooks/OMPSwitchHooks.res
  src/screens/OMPSwitch/OMPSwitchTypes.res
  src/screens/UserManagement/UserRevamp/ListRoles.res
  src/screens/UserManagement/UserRevamp/ListUsers.res
  src/screens/UserManagement/UserRevamp/UserManagementHelper.res
  src/screens/UserManagement/UserRevamp/UserManagementLanding.res
  src/screens/UserManagement/UserRevamp/UserManagementTypes.res
  src/screens/UserManagement/UserRevamp/UserManagementUtils.res
Labels: S-waiting-on-review, user-management

#1460 chore: empty points generator function for graphs
  src/screens/NewAnalytics/NewAnalyticsUtils.res
Labels: S-waiting-on-review, analytics

#1472 chore: transaction view feature flag
  config/config.toml
  src/entryPoints/FeatureFlagUtils.res
  src/screens/Order/Orders.res
Labels: S-waiting-on-review, core

#1469 fix: table customise column bugfix
  src/components/Table.res
  src/components/TableUtils.res
Labels: S-waiting-on-review, bug

#1459 chore: Payments distribution graph
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalytics.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsEntity.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsDistribution/PaymentsDistribution.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsDistribution/PaymentsDistributionTypes.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsDistribution/PaymentsDistributionUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRateUtils.res
Labels: S-waiting-on-review, analytics

#1458 chore: github template added
  .github/ISSUE_TEMPLATE/connector_addition.yml
Labels: S-waiting-on-review

#1478 chore: removed compiler warning and threeds comp change
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/PaymentAttempt/PaymentAttemptEntity.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/PaymentIntent/PaymentIntentEntity.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/Refunds/RefundsTableEntity.res
  src/screens/Disputes/DisputesEntity.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsEntity.res
  src/screens/Order/OrderEntity.res
  src/screens/Payouts/PayoutsEntity.res
  src/screens/Refunds/RefundEntity.res
  src/screens/ThreeDsProcessors/ThreeDsProcessorHome.res
Labels: S-waiting-on-review, bug

#1477 chore: modified table customise columns, warning remove
  public/hyperswitch/icons/solid.svg
  src/components/Filter.res
  src/components/LoadedTable.res
  src/components/LoadedTableWithCustomColumns.res
  src/components/Table.res
  src/components/Table.resi
  src/screens/HSwitchRemoteFilter.res
  src/screens/Refunds/Refund.res
Labels: S-waiting-on-review, core

#1467 chore: internal entity removal
  src/entryPoints/AuthModule/UserInfo/UserInfoTypes.res
  src/entryPoints/AuthModule/UserInfo/UserInfoUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/SidebarValues.res
  src/screens/APIUtils/APIUtils.res
  src/screens/Sidebar/Sidebar.res
  src/screens/UserManagement/UserRevamp/NewUserInvitationForm.res
  src/screens/UserManagement/UserRevamp/UserManagementHelper.res
  src/screens/UserManagement/UserRevamp/UserManagementTypes.res
  src/screens/UserManagement/UserRevamp/UserManagementUtils.res
  src/utils/HyperSwitchUtils.res
Labels: S-waiting-on-review, chore, user-management

#1445 feat: custom tool-tip analytics
  src/screens/NewAnalytics/Graphs/LineGraph/LineGraphTypes.res
  src/screens/NewAnalytics/Graphs/LineGraph/LineGraphUtils.res
Labels: S-waiting-on-review, analytics

#1485 feat: metric selector and tabs for new analytics module
  src/screens/NewAnalytics/Graphs/BarGraph/BarGraph.res
  src/screens/NewAnalytics/Graphs/LineGraph/LineGraph.res
  src/screens/NewAnalytics/Graphs/SankyGraph/SankeyGraph.res
  src/screens/NewAnalytics/NewAnalyticsHelper.res
  src/screens/NewAnalytics/NewAnalyticsTypes.res
  src/screens/NewAnalytics/NewAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalytics.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsDistribution/PaymentsDistribution.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsDistribution/PaymentsDistributionTypes.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsDistribution/PaymentsDistributionUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycleUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRate.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRateTypes.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRateUtils.res
Labels: S-waiting-on-review, analytics

#1315 feat: refund view changes
  src/screens/APIUtils/APIUtils.res
  src/screens/APIUtils/APIUtilsTypes.res
  src/screens/Refunds/Refund.res
  src/screens/TransactionViews/TransactionView.res
  src/screens/TransactionViews/TransactionViewTypes.res
  src/screens/TransactionViews/TransactionViewUtils.res
Labels: S-waiting-on-review, core

#1486 chore: omp views ui changes
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/UserManagement/UserRevamp/UserManagementHelper.res
  src/screens/UserManagement/UserRevamp/UserManagementLanding.res
Labels: S-waiting-on-review, chore

#1507 chore: fix testing bug - displaying Processor in table
  src/screens/PMAuthenticationProcessor/PMAuthenticationTableEntity.res
  src/screens/TaxProcessor/TaxProcessorTableEntity.res
  src/screens/ThreeDsProcessors/ThreeDsTableEntity.res
Labels: S-waiting-on-review, bug

#1506 fix: check for disabled pm auth connector
  src/screens/Connectors/ConnectorUIUtils/PaymentMethod.res
Labels: S-waiting-on-review, bug

#1500 fix: removed unused api from app
  src/entryPoints/AcceptInviteHome.res
  src/entryPoints/AuthModule/PreLoginModule/MerchantSelectScreen.res
  src/entryPoints/HyperSwitchApp.res
  src/screens/APIUtils/APIUtils.res
  src/screens/APIUtils/APIUtilsTypes.res
  src/screens/SbxOnboardingSurvey/SbxOnboardingSurvey.res
  src/screens/Settings/HSwitchProfile/HSwitchProfileSettings.res
  src/screens/SwitchMerchant/SwitchMerchant.res
  src/screens/SwitchMerchant/SwitchMerchantListHook.res
Labels: S-waiting-on-review, core

#1498 fix: transaction views
  src/components/FilterSelectBox.res
  src/entryPoints/HyperSwitchEntry.res
  src/screens/TransactionViews/TransactionView.res
  src/screens/TransactionViews/TransactionViewUtils.res
Labels: S-waiting-on-review, core

#1496 chore: changes in connector addition template
  .github/ISSUE_TEMPLATE/connector_addition.yml
Labels: S-waiting-on-review

#1519 chore: updated file names and variables names for successful payment …
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalytics.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsEntity.res
  src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistribution.res
  src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistributionTypes.res
  src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistributionUtils.res
Labels: S-waiting-on-review
