Repository juspay/hyperswitch-control-center, pull requests merged in 2024-12, with the labels that each got.

#1832 fix: global search fixes
  src/screens/Analytics/GlobalSearch/GlobalSearchBar.res
  src/screens/Analytics/GlobalSearch/GlobalSearchBarHelper.res
  src/screens/Analytics/GlobalSearch/GlobalSearchBarUtils.res
  src/screens/Analytics/GlobalSearchResults/SearchResultsPage.res
Labels: S-waiting-on-review, bug, analytics

#1838 fix: refunds amount overview fix
  src/screens/Analytics/RefundsAnalytics/RefundsAnalyticsEntity.res
Labels: S-waiting-on-review, bug, analytics

#1840 fix: global search on key press fix
  src/screens/Analytics/GlobalSearch/GlobalSearchBar.res
Labels: S-waiting-on-review, bug, analytics

#1843 chore: hiding org merchant dropdown for internal user
  src/entryPoints/HyperSwitchApp.res
  src/screens/Sidebar/Sidebar.res
Labels: S-waiting-on-review, core

#1847 chore: global search filters list update
  src/screens/Analytics/GlobalSearch/GlobalSearchBar.res
  src/screens/Analytics/GlobalSearch/GlobalSearchBarHelper.res
  src/screens/Analytics/GlobalSearch/GlobalSearchBarUtils.res
  src/screens/Analytics/GlobalSearch/GlobalSearchTypes.res
Labels: S-waiting-on-review, analytics

#1590 chore: refactoring ops utils file
  src/screens/Disputes/Disputes.res
  src/screens/Disputes/DisputesUtils.res
  src/screens/HSwitchRemoteFilter.res
  src/screens/OMPSwitch/OrgSwitch.res
  src/screens/Order/OrderUIUtils.res
  src/screens/Order/Orders.res
  src/screens/Refunds/Refund.res
  src/screens/Refunds/RefundUtils.res
Labels: S-waiting-on-review, core

#1851 fix: global search filters feature flag
  config/config.toml
  src/entryPoints/FeatureFlagUtils.res
  src/screens/Analytics/GlobalSearch/GlobalSearchBar.res
  src/screens/Analytics/GlobalSearch/GlobalSearchBarUtils.res
Labels: S-waiting-on-review, analytics

#1830 fix: horizontal scroll in views
  src/components/FilterSelectBox.res
  src/components/LoadedTable.res
  src/components/LoadedTable.resi
  src/components/LoadedTableWithCustomColumns.res
  src/components/Table.res
  src/components/Table.resi
  src/screens/Customers/Customers.res
  src/screens/Disputes/Disputes.res
  src/screens/Order/Orders.res
  src/screens/Payouts/PayoutsList.res
  src/screens/Refunds/Refund.res
Labels: C-ui

#1853 chore: new analytics minor changes
  src/screens/NewAnalytics/Graphs/BarGraph/BarGraphTypes.res
  src/screens/NewAnalytics/NewAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/FailedPaymentsDistribution/FailedPaymentsDistribution.res
  src/screens/NewAnalytics/PaymentAnalytics/FailedPaymentsDistribution/FailedPaymentsDistributionUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycle.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycleUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRate.res
  src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistribution.res
  src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistributionUtils.res
Labels: S-waiting-on-review, analytics

#1787 refactor: recon - update recon resources for rendering sidebar values based on permissions
  src/container/MerchantAccountContainer.res
  src/entryPoints/SidebarValues.res
  src/screens/UserManagement/UserRevamp/UserManagementTypes.res
  src/utils/Mappers/GroupACLMapper.res
Labels: core

#1856 chore: new analytics code refactor
  src/screens/NewAnalytics/NewAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/FailedPaymentsDistribution/FailedPaymentsDistributionUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRateUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistributionUtils.res
Labels: S-waiting-on-review, analytics

#1870 chore: percentage calculation changes
  public/hyperswitch/icons/arrow.svg
  src/screens/NewAnalytics/NewAnalyticsHelper.res
  src/screens/NewAnalytics/NewAnalyticsUtils.res
Labels: S-waiting-on-review, analytics

#1876 chore: Organize transaction modules
  src/screens/Transaction/Disputes/DisputeTypes.res
  src/screens/Transaction/Disputes/Disputes.res
  src/screens/Transaction/Disputes/DisputesEntity.res
  src/screens/Transaction/Disputes/DisputesUtils.res
  src/screens/Transaction/Disputes/ShowDisputes.res
  src/screens/Transaction/Disputes/UploadEvidenceForDisputes.res
  src/screens/Transaction/Order/HSwitchOrderUtils.res
  src/screens/Transaction/Order/OrderEntity.res
  src/screens/Transaction/Order/OrderRefundForm.res
  src/screens/Transaction/Order/OrderTypes.res
  src/screens/Transaction/Order/OrderUIUtils.res
  src/screens/Transaction/Order/Orders.res
  src/screens/Transaction/Order/OrdersHelper.res
  src/screens/Transaction/Order/ShowOrder.res
  src/screens/Transaction/Refunds/Refund.res
  src/screens/Transaction/Refunds/RefundEntity.res
  src/screens/Transaction/Refunds/RefundUtils.res
  src/screens/Transaction/Refunds/ShowRefund.res
Labels: S-waiting-on-review

#1873 fix: update list on accept invite
  src/container/MerchantAccountContainer.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/PendingInvitationsHome.res
  src/screens/Home/Home.res
Labels: user-management

#1515 chore: updated api endpoints /removed v2 urls
  src/screens/APIUtils/APIUtils.res
  src/screens/APIUtils/APIUtilsTypes.res
  src/screens/UserManagement/UserRevamp/ListRoles.res
  src/screens/UserManagement/UserRevamp/ListUsers.res
  src/screens/UserManagement/UserRevamp/NewUserInvitationForm.res
Labels: S-waiting-on-review, core

#1807 feat: Merchant Reference ID filter PaymentOps
  src/components/Filter.res
  src/screens/Transaction/Order/OrderUIUtils.res
Labels: S-waiting-on-review, C-feature

#1855 fix: Truncate cols of connector transaction ID in Payment ops
  src/screens/Transaction/Order/OrderEntity.res
Labels: C-ui

#1869 fix: Amount Filter Validations and Changes
  src/components/Filter.res
  src/components/RemoteFiltersUtils.res
  src/context/FilterContext.res
  src/screens/Transaction/CommonFilters/AmountFilter/AmountFilter.res
  src/screens/Transaction/CommonFilters/AmountFilter/AmountFilterTypes.res
  src/screens/Transaction/CommonFilters/AmountFilter/AmountFilterUtils.res
  src/screens/Transaction/Order/HSwitchOrderUtils.res
  src/screens/Transaction/Order/OrderTypes.res
  src/screens/Transaction/Order/OrderUIUtils.res
  src/screens/Transaction/Order/Orders.res
  src/screens/Transaction/Order/OrdersHelper.res
  src/utils/LogicUtils.res
Labels: S-waiting-on-review, C-feature

#1865 chore: smart retry tab code
  config/config.toml
  src/container/NewAnalyticsContainer.res
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/screens/NewAnalytics/NewAnalyticsContainerUtils.res
  src/screens/NewAnalytics/NewAnalyticsTypes.res
Labels: S-waiting-on-review, analytics

#1872 feat: smart retry amount analytics
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
  src/screens/NewAnalytics/SmartRetryAnalytics/NewSmartRetryAnalyticsEntity.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessed.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessedTypes.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessedUtils.res
Labels: S-waiting-on-review, analytics

#1880 chore: new analytics bar file refactor
  src/container/NewAnalyticsContainer.res
  src/screens/NewAnalytics/NewAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/FailedPaymentsDistribution/FailedPaymentsDistribution.res
  src/screens/NewAnalytics/PaymentAnalytics/FailedPaymentsDistribution/FailedPaymentsDistributionUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRate.res
  src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistribution.res
  src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistributionUtils.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessed.res
Labels: S-waiting-on-review, analytics

#1886 feat: new analytics smart retry failure distribution
  src/screens/NewAnalytics/SmartRetryAnalytics/FailureSmartRetryDistribution/FailureSmartRetryDistribution.res
  src/screens/NewAnalytics/SmartRetryAnalytics/FailureSmartRetryDistribution/FailureSmartRetryDistributionTypes.res
  src/screens/NewAnalytics/SmartRetryAnalytics/FailureSmartRetryDistribution/FailureSmartRetryDistributionUtils.res
  src/screens/NewAnalytics/SmartRetryAnalytics/NewSmartRetryAnalyticsEntity.res
Labels: S-waiting-on-review, analytics

#1890 feat: smart retry analytics modules
  src/container/NewAnalyticsContainer.res
  src/screens/NewAnalytics/SmartRetryAnalytics/NewSmartRetryAnalytics.res
Labels: S-waiting-on-review, analytics

#1884 feat: Refunds amount filter and UI enhancements
  src/screens/HSwitchRemoteFilter.res
  src/screens/Payouts/PayoutsList.res
  src/screens/Transaction/CommonFilters/AmountFilter/AmountFilterUtils.res
  src/screens/Transaction/Disputes/Disputes.res
  src/screens/Transaction/Order/OrderUIUtils.res
  src/screens/Transaction/Order/Orders.res
  src/screens/Transaction/Refunds/Refund.res
  src/screens/Transaction/Refunds/RefundUtils.res
  src/utils/LogicUtils.res
Labels: S-waiting-on-review, C-feature

#1892 feat: paymants failure reasons
  src/entryPoints/SidebarValues.res
  src/screens/NewAnalytics/NewAnalyticsTypes.res
  src/screens/NewAnalytics/PaymentAnalytics/FailureReasonsPayments/FailureReasonsPayments.res
  src/screens/NewAnalytics/PaymentAnalytics/FailureReasonsPayments/FailureReasonsPaymentsTypes.res
  src/screens/NewAnalytics/PaymentAnalytics/FailureReasonsPayments/FailureReasonsPaymentsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalytics.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsEntity.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessed.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessedUtils.res
Labels: S-waiting-on-review, analytics

#1897 fix: analytics minor changes
  src/components/Calendar.res
  src/screens/NewAnalytics/NewAnalyticsHelper.res
  src/screens/NewAnalytics/NewAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/FailureReasonsPayments/FailureReasonsPaymentsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionHelper.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRate.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessed.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessedUtils.res
Labels: S-waiting-on-review, analytics

#1900 fix: Amount Filter bug
  src/screens/Connectors/ConnectorWalletDetails/Paze/PazeIntegration.res
  src/screens/Transaction/CommonFilters/AmountFilter/AmountFilter.res
  src/screens/Transaction/CommonFilters/AmountFilter/AmountFilterUtils.res
Labels: C-bug

#1908 feat: update custom webhook headers
  src/screens/Developer/PaymentSettings/PaymentSettings.res
Labels: S-waiting-on-review

#1910 fix: custom http headers
  src/screens/Developer/PaymentSettings/PaymentSettings.res
  src/server/config.mjs
Labels: bug

#1901 feat: new pill input type
  src/components/form/PillInput.res
Labels: C-feature

#1902 chore: new analytics text font and color changes
  src/screens/NewAnalytics/Graphs/BarGraph/BarGraphTypes.res
  src/screens/NewAnalytics/Graphs/BarGraph/BarGraphUtils.res
  src/screens/NewAnalytics/Graphs/LineGraph/LineGraphTypes.res
  src/screens/NewAnalytics/Graphs/LineGraph/LineGraphUtils.res
  src/screens/NewAnalytics/Graphs/SankyGraph/SankeyGraphUtils.res
  src/screens/NewAnalytics/NewAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/FailedPaymentsDistribution/FailedPaymentsDistributionUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycleUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistributionUtils.res
Labels: S-waiting-on-review, analytics

#1889 feat: new analytics refunds tab
  config/config.toml
  src/container/NewAnalyticsContainer.res
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/screens/NewAnalytics/NewAnalyticsContainerUtils.res
  src/screens/NewAnalytics/NewAnalyticsTypes.res
Labels: S-waiting-on-review, analytics

#1913 chore: refunds analytics v2 file refactor
  src/screens/NewAnalytics/NewAnalyticsHelper.res
  src/screens/NewAnalytics/NewAnalyticsTypes.res
  src/screens/NewAnalytics/NewAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/FailedPaymentsDistribution/FailedPaymentsDistribution.res
  src/screens/NewAnalytics/PaymentAnalytics/FailureReasonsPayments/FailureReasonsPayments.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSection.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionHelper.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionTypes.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRateUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistribution.res
  src/screens/NewAnalytics/SmartRetryAnalytics/FailureSmartRetryDistribution/FailureSmartRetryDistribution.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessedUtils.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SuccessfulSmartRetryDistribution/SuccessfulSmartRetryDistribution.res
Labels: S-waiting-on-review, analytics

#1916 fix: separate section custom headers
  src/screens/Developer/PaymentSettings/PaymentSettings.res
  src/screens/Settings/MerchantAccountUtils.res
Labels: bug

#1917 feat: refunds success rate
  src/container/NewAnalyticsContainer.res
  src/screens/NewAnalytics/NewAnalyticsTypes.res
  src/screens/NewAnalytics/NewRefundsAnalytics/NewRefundsAnalytics.res
  src/screens/NewAnalytics/NewRefundsAnalytics/NewRefundsAnalyticsEntity.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsSuccessRate/RefundsSuccessRate.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsSuccessRate/RefundsSuccessRateTypes.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsSuccessRate/RefundsSuccessRateUtils.res
Labels: S-waiting-on-review, analytics

#1914 fix: handle recon-iframe logout in dashboard
  src/container/MerchantAccountContainer.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/SidebarValues.res
  src/screens/Recon/ReconModule.res
  src/screens/Recon/ReconTypes.res
  src/screens/Recon/ReconUtils.res
Labels: bug

#1920 fix: removing unused feature flags
  README.md
  config/config.toml
  cypress/e2e/auth/auth.cy.js
  src/entryPoints/AuthModule/TwoFaAuth/TwoFaElements.res
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/SidebarValues.res
  src/screens/Transaction/Disputes/Disputes.res
  src/screens/Transaction/Order/Orders.res
  src/screens/Transaction/Refunds/Refund.res
Labels: S-waiting-on-review, chore

#1911 feat: Additional recipients in generate report
  src/components/form/PillInput.res
  src/screens/GenerateReports/DownloadReportModal.res
  src/screens/Transaction/Order/Orders.res
Labels: C-feature

#1915 feat: refunds amount count module
  src/screens/NewAnalytics/NewRefundsAnalytics/NewRefundsAnalytics.res
  src/screens/NewAnalytics/NewRefundsAnalytics/NewRefundsAnalyticsEntity.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsProcessed/RefundsProcessed.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsProcessed/RefundsProcessedTypes.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsProcessed/RefundsProcessedUtils.res
Labels: S-waiting-on-review, analytics

#1946 chore: package update
  Dockerfile
  README.md
  package-lock.json
  package.json
  src/libraries/ReactDiffViewer.res
  src/libraries/ReactDiffViewerBase.res
  src/screens/SelfServe/HSwitchSandboxOnboarding/UserOnboardingUIUtils.res
  webpack.common.js
  webpack.custom.js
Labels: S-waiting-on-review, chore

#1942 fix: Search box issues in "Connectors" pages
  src/screens/Connectors/ConnectorList.res
  src/screens/FraudAndRisk/FRMSelect.res
  src/screens/PMAuthenticationProcessor/PMAuthenticationConnectorList.res
  src/screens/TaxProcessor/TaxProcessorList.res
  src/screens/ThreeDsProcessors/ThreeDsConnectorList.res
Labels: S-waiting-on-review, bug

#1932 feat: refunds overview section
  src/screens/NewAnalytics/NewRefundsAnalytics/NewRefundsAnalytics.res
  src/screens/NewAnalytics/NewRefundsAnalytics/NewRefundsAnalyticsEntity.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsOverviewSection/RefundsOverviewSection.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsOverviewSection/RefundsOverviewSectionTypes.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsOverviewSection/RefundsOverviewSectionUtils.res
Labels: S-waiting-on-review, analytics

#1935 feat: refunds success distribution
  src/screens/NewAnalytics/NewRefundsAnalytics/NewRefundsAnalytics.res
  src/screens/NewAnalytics/NewRefundsAnalytics/NewRefundsAnalyticsEntity.res
  src/screens/NewAnalytics/NewRefundsAnalytics/SuccessfulRefundsDistribution/SuccessfulRefundsDistribution.res
  src/screens/NewAnalytics/NewRefundsAnalytics/SuccessfulRefundsDistribution/SuccessfulRefundsDistributionTypes.res
  src/screens/NewAnalytics/NewRefundsAnalytics/SuccessfulRefundsDistribution/SuccessfulRefundsDistributionUtils.res
Labels: S-waiting-on-review, analytics

#1937 feat: refunds failure distribution
  src/screens/NewAnalytics/NewRefundsAnalytics/FailedRefundsDistribution/FailedRefundsDistribution.res
  src/screens/NewAnalytics/NewRefundsAnalytics/FailedRefundsDistribution/FailedRefundsDistributionTypes.res
  src/screens/NewAnalytics/NewRefundsAnalytics/FailedRefundsDistribution/FailedRefundsDistributionUtils.res
  src/screens/NewAnalytics/NewRefundsAnalytics/NewRefundsAnalytics.res
  src/screens/NewAnalytics/NewRefundsAnalytics/NewRefundsAnalyticsEntity.res
Labels: S-waiting-on-review, analytics

#1938 feat: refunds failure reasons
  src/screens/NewAnalytics/NewRefundsAnalytics/FailureReasonsRefunds/FailureReasonsRefunds.res
  src/screens/NewAnalytics/NewRefundsAnalytics/FailureReasonsRefunds/FailureReasonsRefundsTypes.res
  src/screens/NewAnalytics/NewRefundsAnalytics/FailureReasonsRefunds/FailureReasonsRefundsUtils.res
  src/screens/NewAnalytics/NewRefundsAnalytics/NewRefundsAnalytics.res
  src/screens/NewAnalytics/NewRefundsAnalytics/NewRefundsAnalyticsEntity.res
Labels: S-waiting-on-review, analytics

#1919 refactor: invite user input
  src/components/form/PillInput.res
  src/screens/UserManagement/UserRevamp/UserManagementHelper.res
  src/screens/UserManagement/UserRevamp/UserManagementUtils.res
Labels: S-waiting-on-review

#1950 feat: Addition of new connector - Elavon
  public/hyperswitch/Gateway/ELAVON.svg
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review, C-feature

#1927 feat: add click to pay in payment settings
  config/config.toml
  cypress/e2e/auth/auth.cy.js
  src/container/BusinessProfileContainer.res
  src/container/ConnectorContainer.res
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/screens/Developer/PaymentSettings/PaymentSettings.res
  src/screens/Developer/PaymentSettings/PaymentSettingsListEntity.res
  src/screens/Settings/BusinessMapping/BusinessMappingEntity.res
  src/screens/Settings/HSwitchSettingTypes.res
  src/screens/Settings/MerchantAccountUtils.res
  src/utils/LogicUtils.res
  src/utils/Mappers/BusinessProfileMapper.res
Labels: S-waiting-on-review, C-feature

#1956 chore: add fiuu to prod
  src/screens/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review, core

#1894 chore: omp views redesign changes
  public/hyperswitch/icons/solid.svg
  src/components/DynamicFilter.res
  src/components/Filter.res
  src/components/SelectBox.res
  src/components/SelectBox.resi
  src/screens/APIUtils/APIUtils.res
  src/screens/Analytics/Analytics.res
  src/screens/Analytics/PaymentsAnalytics/PaymentAnalytics.res
  src/screens/Analytics/PerformanceMonitor/PerformanceMonitor.res
  src/screens/ConfigurePMTs/PaymentMethodEntity.res
  src/screens/Connectors/PMAuthenticationProcessor/PMAuthenticationTableEntity.res
  src/screens/Connectors/PaymentProcessor/ConnectorTableUtils.res
  src/screens/Connectors/TaxProcessor/TaxProcessorTableEntity.res
  src/screens/Connectors/ThreeDsProcessors/ThreeDsTableEntity.res
  src/screens/Helpers/HelperComponents.res
  src/screens/Home/Home.res
  src/screens/Hooks/BusinessProfileHook.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/PayoutRouting/PayoutHistoryTableEntity.res
  src/screens/Payouts/PayoutsList.res
  src/screens/Routing/ActiveRouting.res
  src/screens/Routing/HistoryEntity.res
  src/screens/RoutingRevamp/BasicDetailsForm.res
  src/screens/Transaction/Disputes/Disputes.res
  src/screens/Transaction/Order/HSwitchOrderUtils.res
  src/screens/Transaction/Order/OrderEntity.res
  src/screens/Transaction/Order/Orders.res
  src/screens/Transaction/Refunds/Refund.res
  src/screens/UserManagement/UserRevamp/ListRoles.res
  src/screens/UserManagement/UserRevamp/ListUsers.res
  src/screens/UserManagement/UserRevamp/UserManagementHelper.res
  src/screens/UserManagement/UserRevamp/UserManagementLanding.res
  src/screens/UserManagement/UserRevamp/UserManagementTypes.res
Labels: S-waiting-on-review, core

#1898 chore: Omp views new analytics
  src/container/NewAnalyticsContainer.res
Labels: S-waiting-on-review, core

#1925 chore: show switch org input box for tenant admin
  src/screens/OMPSwitch/OrgSwitch.res
Labels: S-waiting-on-review, core

#1949 fix: Move disabled connectors at bottom
  src/screens/Connectors/ConnectorUtils.res
  src/screens/Connectors/FraudAndRisk/FRMSelect.res
  src/screens/Connectors/PMAuthenticationProcessor/PMAuthenticationConnectorList.res
  src/screens/Connectors/PaymentProcessor/ConnectorList.res
  src/screens/Connectors/PayoutProcessor/PayoutProcessorList.res
  src/screens/Connectors/TaxProcessor/TaxProcessorList.res
  src/screens/Connectors/ThreeDsProcessors/ThreeDsConnectorList.res
Labels: S-waiting-on-review, C-ui

#1966 chore: setup recon product
  config/config.toml
  src/APIUtils/APIUtils.res
  src/APIUtils/APIUtilsTypes.res
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HSReconApp.res
  src/entryPoints/HSReconSidebarValues.res
  src/entryPoints/HyperSwitchApp.res
  src/reconContainer/ReconAnalyticsContainer.res
  src/reconContainer/ReconHomeContainer.res
  src/reconContainer/ReconOnBoardingContainer.res
  src/reconScreens/ReconAnalytics/ReconAnalytics.res
  src/reconScreens/ReconHome/ReconHome.res
  src/reconScreens/ReconOnboarding/RecoOnbdConfiguration.res
  src/reconScreens/ReconOnboarding/ReconOnbdLanding.res
  src/reconScreens/ReconOnboarding/ReconOnboarding.res
  src/screens/Sidebar/Sidebar.res
Labels: chore

#1958 feat: New Theme Structure and Custom Style Integration
  config/config.toml
  public/hyperswitch/module.js
  src/UIConifg/UIConfig.res
  src/components/Button.res
  src/context/ThemeProvider.res
  src/entryPoints/AuthModule/AuthWrapper.res
  src/entryPoints/AuthModule/PreLoginModule/AuthSelect.res
  src/entryPoints/AuthModule/PreLoginModule/ResetPassword.res
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/HyperSwitchEntry.res
  src/entryPoints/configs/HyperSwitchConfigTypes.res
  src/entryPoints/configs/HyperSwitchDefaultConfig.res
  src/libraries/Window.res
  src/screens/Sidebar/Sidebar.res
  tailwind.config.js
Labels: C-feature

#1972 chore: setup recon configuration
  src/reconScreens/ReconConfiguration/ConnectOrderData/ConnectOrderData.res
  src/reconScreens/ReconConfiguration/ConnectProcessorData/ConnectProcessorData.res
  src/reconScreens/ReconConfiguration/ConnectSettlementData/ConnectSettlementData.res
  src/reconScreens/ReconConfiguration/ScheduleReconReports/ScheduleReconReports.res
  src/screens/Connectors/FraudAndRisk/FRMSelect.res
  src/screens/Connectors/PMAuthenticationProcessor/PMAuthenticationConnectorList.res
  src/screens/Connectors/PaymentProcessor/ConnectorList.res
  src/screens/Connectors/PayoutProcessor/PayoutProcessorList.res
  src/screens/Connectors/TaxProcessor/TaxProcessorList.res
  src/screens/Connectors/ThreeDsProcessors/ThreeDsConnectorList.res
Labels: S-waiting-on-review, chore

#1970 feat: Recon Landing Page
  public/hyperswitch/assets/reconLanding.svg
  src/reconScreens/ReconOnboarding/ReconOnbdLanding.res
  tailwind.config.js
Labels: S-waiting-on-review, C-feature

#1974 feat: added 3ds connector for click to pay - mastercard
  public/hyperswitch/Gateway/CTP_MASTERCARD.svg
  public/hyperswitch/wasm/euclid_bg.wasm
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review

#1977 feat: global search filters ux enhancements
  src/screens/Analytics/GlobalSearch/GlobalSearchBar.res
  src/screens/Analytics/GlobalSearch/GlobalSearchBarHelper.res
  src/screens/Analytics/GlobalSearch/GlobalSearchBarUtils.res
Labels: S-waiting-on-review, analytics

#1984 chore: Connector search results fix in routing
  src/components/SelectBox.res
Labels: S-waiting-on-review, C-bug

#1983 refactor: Refunds popup design
  src/screens/Transaction/Order/OrderRefundForm.res
  src/screens/Transaction/Order/ShowOrder.res
Labels: S-waiting-on-review, C-ui

#1988 fix: background color default config fix
  src/context/ThemeProvider.res
Labels: C-ui

#1976 feat: enable google pay for airwallex
  src/screens/Connectors/PaymentProcessor/ConnectorUIUtils/PaymentMethod.res
Labels: C-feature
