Repository juspay/hyperswitch-control-center, pull requests merged in 2025-05, with the labels that each got.

#2886 fix: browser navigation issues
  src/IntelligentRouting/IntelligentRoutingScreens/IntelligentRoutingHome.res
  src/Orchestration/OrchestrationApp.res
  src/Recon/ReconContainer/ReconReportsContainer.res
  src/Recon/ReconScreens/ReconOnboarding/ReconOnboardingHelper.res
  src/components/DefaultOnboardingPage.res
  src/components/UnauthorizedPage.res
  src/entryPoints/AuthModule/AuthModuleHooks.res
  src/entryPoints/AuthModule/AuthUtils.res
  src/entryPoints/AuthModule/AuthWrapper.res
  src/entryPoints/AuthModule/Common/CommonAuthForm.res
  src/entryPoints/AuthModule/Common/CommonAuthHooks.res
  src/entryPoints/AuthModule/ProductSelection/ProductSelectionProvider.res
  src/entryPoints/AuthModule/TwoFaAuth/TwoFaAuth.res
  src/entryPoints/AuthModule/TwoFaAuth/TwoFaAuthScreen.res
  src/entryPoints/AuthModule/TwoFaAuth/TwoFaElements.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/ProductUtils.res
  src/entryPoints/ProductsSidebarValues.res
Labels: S-waiting-on-review, C-bug

#2920 fix: added validation for the api keys
  src/screens/Developer/APIKeys/DeveloperUtils.res
  src/screens/Developer/APIKeys/KeyManagement.res
Labels: S-waiting-on-review, C-bug

#2918 fix: changed old analytics graph font style to InterDisplay
  src/components/CustomCharts/HighchartTimeSeriesChart.res
  src/components/CustomCharts/LineChartUtils.res
  src/screens/Analytics/PerformanceMonitor/BarChartPerformance/BarChartPerformanceUtils.res
  src/screens/Analytics/PerformanceMonitor/GaugeChart/CustomGraphs/GaugeFailureRateUtils.res
  src/screens/Analytics/PerformanceMonitor/GaugeChart/GaugeChartPerformanceUtils.res
  src/screens/Analytics/PerformanceMonitor/PieChartPerformance/PieChartPerformanceUtils.res
Labels: S-waiting-on-review, S-analytics

#2936 test: payment operations date checking with 2 digits
  cypress/e2e/3-operations/paymentOperations.cy.js
Labels: S-waiting-on-review, S-cypress

#2915 chore: updated pr label workflow
  .github/workflows/pr-label.yml
Labels: S-waiting-on-review, C-enhancement

#2925 fix: recovery Processor Reference ID empty value validation check
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/RecoveryOnboardingBilling.res
Labels: S-Recovery

#2926 fix: old analytics tab value bug fix
  src/screens/Analytics/Analytics.res
  src/screens/Analytics/AnalyticsNew.res
Labels: S-analytics

#2919 fix: override 3ds rule popup changes when deleted all 3ds rules
  src/screens/ThreeDSFlow/HSwitchThreeDS.res
Labels: S-waiting-on-review, C-bug

#2905 feat: added wasm for intelligent routing
  public/hyperswitch/index.html
  public/hyperswitch/module.js
  public/hyperswitch/pkg/.gitignore
  public/hyperswitch/pkg/package.json
  public/hyperswitch/pkg/procesmo.d.ts
  public/hyperswitch/pkg/procesmo.js
  public/hyperswitch/pkg/procesmo_bg.wasm
  public/hyperswitch/pkg/procesmo_bg.wasm.d.ts
  src/IntelligentRouting/IntelligentRoutingScreens/IntelligentRoutingConfiguration.res
  src/libraries/Window.res
Labels: S-waiting-on-review, S-modularity

#2955 feat: include UPI collect SVG asset in TestProcessor
  public/hyperswitch/assets/TestProcessor/UPI_COLLECT.svg
Labels: C-feature, C-enhancement

#2895 feat: SDK page revamp with updated configuration support
  package-lock.json
  package.json
  public/hyperswitch/icons/solid.svg
  src/APIUtils/APIUtils.res
  src/APIUtils/APIUtilsTypes.res
  src/Orchestration/OrchestrationApp.res
  src/components/ColorPickerInput.res
  src/components/InputFields.res
  src/components/InputFields.resi
  src/components/SketchPicker.res
  src/components/form/FormRenderer.res
  src/container/ConnectorContainer.res
  src/container/MerchantAccountContainer.res
  src/libraries/ReactHyperJs.res
  src/screens/Helpers/PageUtils.res
  src/screens/Home/HomeUtils.res
  src/screens/SDKPayment/FormSection/CheckoutDetails.res
  src/screens/SDKPayment/FormSection/EditCheckoutDetails.res
  src/screens/SDKPayment/FormSection/ThemeCustomization.res
  src/screens/SDKPayment/FormSection/ToggleFormSection.res
  src/screens/SDKPayment/PreviewSection/CheckoutForm.res
  src/screens/SDKPayment/PreviewSection/SDKPage.res
  src/screens/SDKPayment/PreviewSection/SDKPayment.res
  src/screens/SDKPayment/PreviewSection/WebSDK.res
  src/screens/SDKPayment/SDKHelper/SDKPaymentHelper.res
  src/screens/SDKPayment/SDKHelper/TestCredentials.res
  src/screens/SDKPayment/SDKPage.res
  src/screens/SDKPayment/SDKPaymentTypes.res
  src/screens/SDKPayment/SDKPaymentUtils.res
  src/screens/SDKPayment/SDKProvider/SDKProvider.res
  src/screens/SDKPayment/SDKUtils/SDKPaymentUtils.res
  src/screens/SDKPayment/TestCredentials.res
  src/screens/SDKPayment/TestPayment.res
  src/screens/SDKPayment/WebSDK.res
  src/screens/SelfServe/HSwitchProdOnboarding/CheckoutHelper.res
  src/screens/Transaction/Order/ShowOrder.res
  src/utils/Country.res
  src/utils/CountryUtils.res
  src/utils/DOMUtils.res
  webpack.dev.js
Labels: S-waiting-on-review

#2966 chore: api call for payments - theme customization & bg-color added
  src/components/ColorPickerInput.res
  src/screens/SDKPayment/FormSection/CheckoutDetails.res
  src/screens/SDKPayment/FormSection/ThemeCustomization.res
  src/screens/SDKPayment/PreviewSection/SDKPayment.res
  tailwind.config.js
Labels: S-waiting-on-review

#2961 feat: add clarity tracking
  config/config.toml
  src/entryPoints/HyperSwitchEntry.res
  src/entryPoints/configs/HyperSwitchConfigTypes.res
  src/utils/DOMUtils.res
Labels: C-feature

#2967 chore: style issues for scrolling sdk
  src/screens/SDKPayment/PreviewSection/SDKPayment.res
  src/screens/SDKPayment/PreviewSection/WebSDK.res
  src/screens/SDKPayment/SDKHelper/TestCredentials.res
Labels: S-waiting-on-review

#2963 fix: insights side bar highlight fix
  src/Orchestration/OrchestrationApp.res
  src/entryPoints/SidebarValues.res
  src/screens/NewAnalytics/NewAnalyticsContainerUtils.res
  src/screens/NewAnalytics/NewAnalyticsTypes.res
Labels: S-waiting-on-review, S-analytics

#2848 feat: hubspot changes
  src/screens/Home/ProdIntent/ProdIntentHelper.res
  src/screens/Home/ProdIntent/ProdVerifyModal.res
  src/screens/Home/ProdIntent/ProdVerifyModalUtils.res
  src/utils/HubspotUtils.res
Labels: S-blocked

#2912 chore: sample data analytics
  src/components/InputFields.res
  src/components/InputFields.resi
  src/container/NewAnalyticsContainer.res
  src/context/FilterContext.res
  src/screens/NewAnalytics/NewAnalyticsContainerUtils.res
  src/screens/NewAnalytics/NewAnalyticsFilters/NewAnalyticsFilters.res
  src/screens/NewAnalytics/NewAnalyticsHelper.res
  src/screens/NewAnalytics/NewAnalyticsUtils.res
  src/screens/NewAnalytics/NewRefundsAnalytics/FailedRefundsDistribution/FailedRefundsDistribution.res
  src/screens/NewAnalytics/NewRefundsAnalytics/FailureReasonsRefunds/FailureReasonsRefunds.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsOverviewSection/RefundsOverviewSection.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsProcessed/RefundsProcessed.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsReasons/RefundsReasons.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsSuccessRate/RefundsSuccessRate.res
  src/screens/NewAnalytics/NewRefundsAnalytics/SuccessfulRefundsDistribution/SuccessfulRefundsDistribution.res
  src/screens/NewAnalytics/PaymentAnalytics/FailedPaymentsDistribution/FailedPaymentsDistribution.res
  src/screens/NewAnalytics/PaymentAnalytics/FailureReasonsPayments/FailureReasonsPayments.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycle.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSection.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRate.res
  src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistribution.res
  src/screens/NewAnalytics/SmartRetryAnalytics/FailureSmartRetryDistribution/FailureSmartRetryDistribution.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessed.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SuccessfulSmartRetryDistribution/SuccessfulSmartRetryDistribution.res
  src/utils/LogicUtils.res
  webpack.dev.js
Labels: S-waiting-on-review, S-analytics

#2982 fix: soft color correction
  tailwind.config.js
Labels: S-waiting-on-review

#2984 chore: banner text design for sample analytics
  src/screens/NewAnalytics/NewAnalyticsHelper.res
Labels: S-waiting-on-review, C-ui

#2986 chore: fix typo in config
  config/config.toml
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HyperSwitchApp.res
Labels: C-chore

#2969 fix: fixed arrows in custom range calenders
  src/components/CalendarList.res
Labels: S-waiting-on-review, C-ui

#2994 chore: Sample data analytics feature flag and mixpanel addition
  config/config.toml
  src/entryPoints/FeatureFlagUtils.res
  src/screens/NewAnalytics/InsightsHelper.res
Labels: S-waiting-on-review, S-analytics

#2988 chore: revert "browser navigation" handle redirect from sso
  src/entryPoints/AuthModule/AuthWrapper.res
  src/entryPoints/AuthModule/TwoFaAuth/TwoFaAuthScreen.res
  src/screens/Connectors/PMAuthenticationProcessor/PMAuthenticationTableEntity.res
  src/screens/Connectors/PaymentProcessor/ConnectorTableUtils.res
  src/screens/Connectors/PayoutProcessor/PayoutProcessorTableEntity.res
  src/screens/Connectors/TaxProcessor/TaxProcessorTableEntity.res
  src/screens/Connectors/ThreeDsProcessors/ThreeDsTableEntity.res
Labels: C-bug

#3012 fix: Analytics sample fixes
  src/components/InputFields.res
  src/components/InputFields.resi
  src/components/SelectBox.res
  src/container/InsightsAnalyticsContainer.res
  src/screens/NewAnalytics/InsightsAnalyticsFilters/InsightsAnalyticsFilters.res
  src/screens/NewAnalytics/InsightsContainerUtils.res
  src/screens/NewAnalytics/InsightsUtils.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
Labels: C-bug, S-analytics

#3007 fix: webhook ui enhancement
  src/screens/Developer/Webhooks/WebhooksDetails.res
Labels: S-waiting-on-review

#3016 chore: redsys connector live
  src/screens/Connectors/ConnectorUtils.res
Labels: C-feature, Closed

#3017 chore: webhook minor updates 1
  src/screens/Developer/Webhooks/Webhooks.res
  src/screens/Developer/Webhooks/WebhooksDetails.res
  src/screens/Developer/Webhooks/WebhooksUtils.res
Labels: S-waiting-on-review

#3020 fix: prevent Web SDK script from loading multiple times
  src/screens/SDKPayment/PreviewSection/WebSDK.res
Labels: S-waiting-on-review, C-bug

#3026 test: fix failing tests
  cypress/e2e/4-connectors/connector.cy.js
  cypress/support/pages/workflow/paymentRouting/PaymentRouting.js
Labels: C-Testing

#3013 refactor: move typography folder under UI config
  src/UIConifg/Typography/Typography.res
  src/UIConifg/Typography/TypographyTypes.res
  src/UIConifg/Typography/TypographyUtils.res
Labels: S-waiting-on-review, C-enhancement

#3027 fix: payout processor unknown name in edit pmt
  src/screens/Connectors/PayoutProcessor/PayoutProcessorPaymentMethod.res
Labels: S-waiting-on-review, C-bug

#2998 chore: refactor hooks folder
  src/hooks/MixpanelHook.res
  src/screens/Analytics/GlobalSearch/GlobalSearchBar.res
  src/screens/Analytics/GlobalSearchResults/SearchResultsPage.res
  src/screens/HSwitchUtils.res
  src/screens/Home/HomeUtils.res
  src/screens/OrchestrationHooks/AnalyticsLogUtilsHook.res
  src/screens/OrchestrationHooks/BusinessProfileHook.res
  src/screens/OrchestrationHooks/ClearRecoilValueHook.res
  src/screens/OrchestrationHooks/ConnectorListHook.res
  src/screens/OrchestrationHooks/GroupACLHooks.res
  src/screens/OrchestrationHooks/MerchantDetailsHook.res
  src/screens/OrchestrationHooks/MerchantSpecificConfigHook.res
  src/screens/OrchestrationHooks/OMPCreateAccessHook.res
  src/screens/OrchestrationHooks/OMPSwitchHooks.res
  src/screens/OrchestrationHooks/TotpHooks.res
  src/screens/Recon/Recon.res
  src/screens/SelfServe/HSwitchSandboxOnboarding/UserOnboardingUIUtils.res
Labels: C-chore

#3025 feat: debit routing configuration addition
  public/hyperswitch/icons/solid.svg
  src/screens/Developer/PaymentSettings/PaymentSettings.res
  src/screens/OrchestrationHooks/BusinessProfileHook.res
  src/screens/Routing/ActiveRouting.res
  src/screens/Routing/AdvancedRouting/AdvancedRoutingUtils.res
  src/screens/Routing/DebitRouting/DebitRouting.res
  src/screens/Routing/DebitRouting/DebitRoutingActiveCard.res
  src/screens/Routing/DebitRouting/DebitRoutingConfigureModal.res
  src/screens/Routing/DebitRouting/DebitRoutingDeactivateModal.res
  src/screens/Routing/History.res
  src/screens/Routing/RoutingStack.res
  src/screens/Routing/RoutingUtils.res
  src/utils/Modal.res
  src/utils/ModalUtils.res
  tailwind.config.js
Labels: S-waiting-on-review, C-feature

#2974 chore: get prod access UI revamp
  src/IntelligentRouting/IntelligentRoutingScreens/IntelligentRoutingAnalytics.res
  src/IntelligentRouting/IntelligentRoutingScreens/IntelligentRoutingConfiguration.res
  src/IntelligentRouting/IntelligentRoutingScreens/IntelligentRoutingHelper.res
  src/Recon/ReconHelper.res
  src/Recon/ReconScreens/ReconOnboarding/ReconOnboardingHelper.res
  src/Recon/ReconScreens/ReconReports/ReconReports.res
  src/RevenueRecovery/RevenueRecoveryContainer/RecoveryConnectorContainer.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryOnboarding/RevenueRecoveryOnboardingUtils.res
  src/components/Navbar.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/HyperswitchAppHelper.res
  src/entryPoints/SidebarValues.res
  src/screens/Home/ProdIntent/GetProductionAccess.res
  src/screens/Home/ProdIntent/ProdIntentForm.res
  src/screens/Home/ProdIntent/ProdVerifyModal.res
  tailwind.config.js
Labels: S-waiting-on-review, C-enhancement

#3040 fix: Standardise disabled state for sample analytics and show daterange filter field as dropdown
  public/hyperswitch/icons/solid.svg
  src/components/Button.res
  src/components/DateRangeCompareFields.res
  src/components/DateRangeField.res
  src/components/Filter.res
  src/components/InputFields.res
  src/components/InputFields.resi
  src/components/SelectBox.res
  src/screens/NewAnalytics/InsightsContainerUtils.res
  src/screens/NewAnalytics/InsightsHelper.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/utils/DateRangeUtils.res
Labels: S-waiting-on-review, C-ui

#3058 fix: sdk issue description
  src/screens/SDKPayment/PreviewSection/CheckoutForm.res
Labels: S-waiting-on-review

#2927 feat: Upload flow changes
  config/config.toml
  public/hyperswitch/icons/solid.svg
  src/APIUtils/APIUtils.res
  src/IntelligentRouting/IntelligentRoutingScreens/IntelligentRoutingAnalytics.res
  src/IntelligentRouting/IntelligentRoutingScreens/IntelligentRoutingConfiguration.res
  src/IntelligentRouting/IntelligentRoutingScreens/IntelligentRoutingConfiguration/AnalyzeData.res
  src/IntelligentRouting/IntelligentRoutingScreens/IntelligentRoutingConfiguration/IntelligentRoutingConfiguration.res
  src/IntelligentRouting/IntelligentRoutingScreens/IntelligentRoutingConfiguration/ReviewDataSummary.res
  src/IntelligentRouting/IntelligentRoutingScreens/IntelligentRoutingTypes.res
  src/IntelligentRouting/IntelligentRoutingScreens/IntelligentRoutingUtils.res
  src/components/Button.res
  src/entryPoints/HyperSwitchEntry.res
  src/entryPoints/configs/HyperSwitchConfigTypes.res
  webpack.dev.js
Labels: S-waiting-on-review, S-modularity

#2959 chore: update latest routing wasm
  public/hyperswitch/pkg/.gitignore
  public/hyperswitch/pkg/procesmo_bg.wasm
Labels: S-waiting-on-review, S-modularity

#3065 chore: removed frontend email case conversion
  src/entryPoints/AuthModule/TwoFaAuth/TwoFaAuth.res
Labels: S-waiting-on-review, C-enhancement

#3068 feat: recovery auth rate summary graph, api utils and onboarding changes
  src/APIUtils/APIUtils.res
  src/APIUtils/APIUtilsTypes.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RecoveryProcessorsPaymentProcessors/RecoveryOnboardingPayments.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingProcessorsReviewDetails.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryOnboarding/RevenueRecoveryData.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryOnboarding/RevenueRecoveryOnboarding.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryOnboarding/RevenueRecoveryOnboardingTypes.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryOnboarding/RevenueRecoveryOnboardingUtils.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryAnalytics/AuthRateSummary/AuthRateSummary.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryAnalytics/AuthRateSummary/AuthRateSummaryTypes.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryAnalytics/AuthRateSummary/AuthRateSummaryUtils.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryAnalytics/RevenueRecoveryAnalytics.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryAnalytics/RevenueRecoveryAnalyticsEntity.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryAnalytics/RevenueRecoveryAnalyticsUtils.res
  src/components/Graphs/BarGraph/BarGraphTypes.res
  src/entryPoints/ProductUtils.res
  tailwind.config.js
Labels: S-waiting-on-review, S-Recovery

#3077 feat: auth rate up lift graph
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryAnalytics/RetryStrategies/RetryStrategiesAnalytics.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryAnalytics/RetryStrategies/RetryStrategiesAnalyticsTypes.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryAnalytics/RetryStrategies/RetryStrategiesAnalyticsUtils.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryAnalytics/RevenueRecoveryAnalytics.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryAnalytics/RevenueRecoveryAnalyticsEntity.res
Labels: S-waiting-on-review, S-Recovery
