Repository juspay/hyperswitch-control-center, pull requests merged in 2025-07, with the labels that each got.

#3229 feat: Orchestrator v2 connected connectors table
  src/OrchestrationV2/OrchestrationV2Screens/Connectors/PaymentConnectors.res
  src/OrchestrationV2/OrchestrationV2Screens/Connectors/PaymentProcessorEntity.res
Labels: S-waiting-on-review, S-orchestration-v2

#3239 fix: improvement and bug fixes
  src/screens/Developer/PaymentSettings/AcquirerConfigSettings/AcquirerConfigEntity.res
  src/screens/Developer/PaymentSettings/AcquirerConfigSettings/AcquirerConfigSettings.res
  src/screens/Developer/PaymentSettings/AcquirerConfigSettings/AcquirerConfigUtils.res
Labels: S-waiting-on-review

#3249 chore: display prefilled merchant name in create merchant modal
  src/entryPoints/AuthModule/ProductSelection/ProductSelectionProvider.res
  src/screens/OMPSwitch/MerchantSwitch.res
Labels: S-waiting-on-review, C-chore

#3252 fix: prod access form not visible
  src/screens/Home/ProdIntent/GetProductionAccess.res
Labels: S-waiting-on-review, C-bug

#3250 test: Add cypress tests
  .github/workflows/cypress-test.yml
  cypress/e2e/1-auth/auth.cy.js
  cypress/e2e/3-operations/paymentOperations.cy.js
  cypress/support/commands.js
  cypress/support/e2e.js
  package-lock.json
  package.json
Labels: C-Testing

#3266 feat: recon engine transactions page
  src/Recoils/TableAtoms.res
  src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/ReconEngineTransactions.res
  src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/ReconEngineTransactionsHelper.res
  src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/ReconEngineTransactionsTypes.res
  src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/ReconEngineTransactionsUtils.res
  src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/SampleData/SampleTransactions.res
  src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/TransactionsTableEntity.res
Labels: C-feature

#3275 feat: recon engine transaction audit trail
  src/ReconEngine/ReconEngineApp/ReconEngineApp.res
  src/ReconEngine/ReconEngineContainer/ReconEngineTransactionContainer.res
  src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/AuditTrailStepIndicator/AuditTrailStepIndicator.res
  src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/AuditTrailStepIndicator/AuditTrailStepIndicatorTypes.res
  src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/AuditTrailStepIndicator/AuditTrailStepIndicatorUtils.res
  src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/EntriesTableEntity.res
  src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/ReconEngineTransactions.res
  src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/ReconEngineTransactionsDetail.res
  src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/ReconEngineTransactionsHelper.res
  src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/ReconEngineTransactionsTypes.res
  src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/ReconEngineTransactionsUtils.res
  src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/SampleData/SampleTransactions.res
  src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/TransactionsTableEntity.res
  tailwind.config.js
Labels: S-waiting-on-review, C-feature, S-Recon

#3283 feat: Recon v1 rules Library
  src/ReconEngine/ReconEngineApp/ReconEngineApp.res
  src/ReconEngine/ReconEngineContainer/ReconEngineRulesContainer.res
  src/ReconEngine/ReconEngineScreens/ReconEngineRules/ReconEngineRule.res
  src/ReconEngine/ReconEngineScreens/ReconEngineRules/ReconEngineRules.res
  src/ReconEngine/ReconEngineScreens/ReconEngineRules/ReconEngineRulesEntity.res
  src/ReconEngine/ReconEngineScreens/ReconEngineRules/ReconEngineRulesTypes.res
  src/ReconEngine/ReconEngineScreens/ReconEngineRules/ReconEngineRulesUtils.res
  src/ReconEngine/ReconEngineScreens/ReconEngineRules/SampleDataReconRules/SampleData.res
Labels: C-feature

#3289 fix: audit logs order and log details mismatch fix
  src/screens/Analytics/Logs/LogUtils/AuditLogUI.res
Labels: S-waiting-on-review, C-chore

#3285 feat: Recon v1 Exceptions module
  src/ReconEngine/ReconEngineApp/ReconEngineApp.res
  src/ReconEngine/ReconEngineContainer/ReconEngineExceptionContainer.res
  src/ReconEngine/ReconEngineScreens/ReconEngineExceptions/ReconEngineExceptionStaging/ReconEngineExceptionStaging.res
  src/ReconEngine/ReconEngineScreens/ReconEngineExceptions/ReconEngineExceptionStaging/SampleData/SampleDataExceptionStaging.res
  src/ReconEngine/ReconEngineScreens/ReconEngineExceptions/ReconEngineExceptionTransaction/ReconEngineExceptionsDetails.res
  src/ReconEngine/ReconEngineScreens/ReconEngineExceptions/ReconEngineExceptionTransaction/ReconExceptionTransaction.res
  src/ReconEngine/ReconEngineScreens/ReconEngineExceptions/ReconEngineExceptionTransaction/SampleData/SampleDataExceptionTransaction.res
  src/ReconEngine/ReconEngineScreens/ReconEngineExceptions/ReconEngineExceptions.res
  src/ReconEngine/ReconEngineScreens/ReconEngineOverview/ReconEngineAccount/ReconEngineAccountTable/ReconEngineAccountEntity.res
  src/ReconEngine/ReconEngineScreens/ReconEngineQueue/ReconEngineQueueUploadModalBox/ReconEngineFileUploadModal.res
Labels: C-feature, S-Recon

#3282 refactor: remove unused code
  src/screens/Connectors/PMAuthenticationProcessor/PMAuthenticationTableEntity.res
  src/screens/Connectors/PaymentProcessor/ConnectorTableUtils.res
  src/screens/Connectors/PayoutProcessor/PayoutProcessorTableEntity.res
  src/screens/Connectors/TaxProcessor/TaxProcessorTableEntity.res
  src/screens/Connectors/ThreeDsProcessors/ThreeDsTableEntity.res
Labels: S-waiting-on-review, C-enhancement

#3300 fix: sidebar hidden fix
  src/OrchestrationV2/OrchestrationV2Screens/Connectors/DummyProcessorModalV2.res
  src/OrchestrationV2/OrchestrationV2Screens/Connectors/PaymentConnectors.res
  src/OrchestrationV2/OrchestrationV2Screens/Connectors/PaymentProcessorCards.res
  src/screens/Processors/ProcessorCards.res
Labels: S-waiting-on-review, C-bug

#3303 feat: recon engine overview page
  src/Recoils/TableAtoms.res
  src/ReconEngine/ReconEngineApp/ReconEngineApp.res
  src/ReconEngine/ReconEngineContainer/ReconEngineOverviewContainer.res
  src/ReconEngine/ReconEngineScreens/ReconEngineExceptions/ReconEngineExceptionEntity.res
  src/ReconEngine/ReconEngineScreens/ReconEngineExceptions/ReconEngineExceptionStaging/ReconEngineExceptionStaging.res
  src/ReconEngine/ReconEngineScreens/ReconEngineExceptions/ReconEngineExceptionStaging/ReconEngineExceptionStagingUtils.res
  src/ReconEngine/ReconEngineScreens/ReconEngineExceptions/ReconEngineExceptionTransaction/ReconEngineExceptionsDetails.res
  src/ReconEngine/ReconEngineScreens/ReconEngineExceptions/ReconEngineExceptionTransaction/ReconExceptionTransaction.res
  src/ReconEngine/ReconEngineScreens/ReconEngineExceptions/ReconEngineExceptionTransaction/SampleData/SampleDataExceptionTransaction.res
  src/ReconEngine/ReconEngineScreens/ReconEngineExceptions/ReconEngineExceptionTypes.res
  src/ReconEngine/ReconEngineScreens/ReconEngineExceptions/ReconEngineExceptions.res
  src/ReconEngine/ReconEngineScreens/ReconEngineOverview/ReconEngineAccount/ReconEngineAccount.res
  src/ReconEngine/ReconEngineScreens/ReconEngineOverview/ReconEngineOverview.res
  src/ReconEngine/ReconEngineScreens/ReconEngineOverview/ReconEngineOverviewDetails/ReconEngineOverviewDetails.res
  src/ReconEngine/ReconEngineScreens/ReconEngineOverview/ReconEngineOverviewDetails/ReconEngineOverviewDetailsComponents/ReconEngineOverviewCardDetails.res
  src/ReconEngine/ReconEngineScreens/ReconEngineOverview/ReconEngineOverviewDetails/ReconEngineOverviewDetailsComponents/ReconEngineOverviewLineGraph.res
  src/ReconEngine/ReconEngineScreens/ReconEngineOverview/ReconEngineOverviewDetails/ReconEngineOverviewDetailsComponents/ReconEngineOverviewStackedBarGraph.res
  src/ReconEngine/ReconEngineScreens/ReconEngineOverview/ReconEngineOverviewDetails/ReconEngineOverviewDetailsComponents/ReconEngineOverviewTransactions.res
  src/ReconEngine/ReconEngineScreens/ReconEngineOverview/ReconEngineOverviewHelper.res
  src/ReconEngine/ReconEngineScreens/ReconEngineOverview/ReconEngineOverviewTypes.res
  src/ReconEngine/ReconEngineScreens/ReconEngineOverview/ReconEngineOverviewUtils.res
  src/ReconEngine/ReconEngineScreens/ReconEngineOverview/SampleData/SampleOverviewData.res
  src/ReconEngine/ReconEngineScreens/ReconEngineQueue/ReconEngineQueue.res
  src/ReconEngine/ReconEngineScreens/ReconEngineQueue/ReconEngineQueueSample/ReconEngineQueueSample.res
  src/ReconEngine/ReconEngineScreens/ReconEngineRules/ReconEngineRule.res
  src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/ReconEngineTransactions.res
  src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/ReconEngineTransactionsDetail.res
  src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/ReconEngineTransactionsHook.res
  src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/ReconEngineTransactionsTypes.res
  src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/ReconEngineTransactionsUtils.res
  src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/TransactionsTableEntity.res
Labels: S-Recon

#3329 chore: common entity for connector list loaded table
  src/Interface/ConnectorInterface/ConnectorInterfaceTableEntity.res
  src/OrchestrationV2/OrchestrationV2Screens/Connectors/PaymentConnectors.res
  src/Vault/VaultScreens/VaultConnectors/VaultConnectorEntity.res
  src/Vault/VaultScreens/VaultConnectors/VaultProcessorList.res
  src/Vault/VaultScreens/VaultCustomersAndTokens/VaultCustomersAndTokens.res
  src/Vault/VaultScreens/VaultCustomersAndTokens/VaultCustomersEntity.res
  src/components/priority-logics/AddPLGateway.res
  src/screens/Connectors/FraudAndRisk/FRMTableUtils.res
  src/screens/Connectors/PaymentProcessor/ConnectorList.res
  src/screens/Connectors/PaymentProcessor/ConnectorPreview.res
  src/screens/Routing/AdvancedRouting/AddRuleGateway.res
  src/screens/Routing/AdvancedRouting/AdvancedRouting.res
  src/screens/Routing/AdvancedRouting/RulePreviewer.res
  src/screens/Routing/DefaultRouting/DefaultRouting.res
  src/screens/Routing/VolumeSplitRouting/VolumeSplitRoutingPreviewer.res
Labels: S-waiting-on-review, S-orchestration-v2

#3169 feat: right drawer for product exploration
  .github/workflows/cypress-test.yml
  README.md
  config/config.toml
  docs/CONTRIBUTING.md
  memory-bank/activeContext.md
  memory-bank/productContext.md
  memory-bank/progress.md
  memory-bank/projectbrief.md
  memory-bank/systemPatterns.md
  memory-bank/techContext.md
  memory-bank/thematic/PageCreationWithTableAndChart/chartImplementation.md
  memory-bank/thematic/PageCreationWithTableAndChart/index.md
  memory-bank/thematic/TableComponentPage/creatingNewTablePage.md
  memory-bank/thematic/api/apiUtils.md
  memory-bank/thematic/api/apiVersioning.md
  memory-bank/thematic/graphs/lineAndColumnGraph.md
  memory-bank/thematic/graphs/pieGraph.md
  memory-bank/thematic/intelligent-routing/routingOverview.md
  memory-bank/thematic/rescript/apiCallStructure.md
  memory-bank/thematic/rescript/index.md
  memory-bank/thematic/rescript/syntax/commonStdLib.md
  memory-bank/thematic/rescript/syntax/functionsAndBindings.md
  memory-bank/thematic/rescript/syntax/jsInterop.md
  memory-bank/thematic/rescript/syntax/jsxPatterns.md
  memory-bank/thematic/rescript/syntax/modules.md
  memory-bank/thematic/rescript/syntax/patternMatching.md
  memory-bank/thematic/rescript/syntax/reactHooksDependencies.md
  memory-bank/thematic/rescript/syntax/typesAndDataStructures.md
  package-lock.json
  public/common/NewThemeOnboarding.css
  public/common/Onboarding.css
  public/hyperswitch/assets/workflows/3ds_auth_graphic.png
  public/hyperswitch/assets/workflows/routing_graphic.png
  public/hyperswitch/assets/workflows/smart_retries_graphic.png
  public/hyperswitch/icons/solid.svg
  public/hyperswitch/index.html
  public/hyperswitch/public/gifs/smartRetry/step1.mp4
  public/hyperswitch/public/gifs/smartRetry/step2.mp4
  public/hyperswitch/public/gifs/smartRetry/step3.mp4
  public/hyperswitch/public/gifs/smartRetry/step4.mp4
  src/OrchestrationV2/OrchestrationV2Screens/Connectors/PaymentProcessorCards.res
  src/UIConifg/Typography/TypographyTypes.res
  src/UIConifg/Typography/TypographyUtils.res
  src/components/Accordion.res
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/Provider/GlobalProvider.res
  src/entryPoints/Provider/ProviderTypes.res
  src/screens/ExploreWorkflows/ExploreWorkflowsSection.res
  src/screens/ExploreWorkflows/ExploreWorkflowsTypes.res
  src/screens/ExploreWorkflows/ExploreWorkflowsUtils.res
  src/screens/ExploreWorkflows/WorkflowSideDrawer.res
  src/screens/ExploreWorkflows/WorkflowSideDrawerHelper.res
  src/screens/Home/Home.res
  src/screens/Processors/ProcessorCards.res
  src/server/config.mjs
  tailwind.config.js
  webpack.common.js
Labels: S-blocked

#3258 chore: payment interface types for v1 and v2
  src/Interface/PaymentInterface/PaymentInterfaceTypes/PaymentInterfaceTypes.res
  src/Interface/PaymentInterface/PaymentInterfaceTypes/PaymentInterfaceTypesV1.res
  src/Interface/PaymentInterface/PaymentInterfaceTypes/PaymentInterfaceTypesV2.res
  src/Interface/PaymentInterface/PaymentInterfaceUtils/PaymentInterfaceUtils.res
  src/Interface/PaymentInterface/PaymentInterfaceUtils/PaymentInterfaceUtilsV1.res
  src/Interface/PaymentInterface/PaymentInterfaceUtils/PaymentInterfaceUtilsV2.res
  src/Interface/PaymentInterface/PaymentsInterface.res
  src/utils/LogicUtils.res
Labels: S-waiting-on-review, S-orchestration-v2

#3332 fix: recon V1 suggested ui changes
  src/ReconEngine/ReconEngineScreens/ReconEngineExceptions/ReconEngineExceptionEntity.res
  src/ReconEngine/ReconEngineScreens/ReconEngineOverview/ReconEngineOverviewUtils.res
  src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/EntriesTableEntity.res
  src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/ReconEngineTransactionsUtils.res
  src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/TransactionsTableEntity.res
  src/ReconEngine/ReconEngineUtils.res
Labels: C-ui, S-Recon

#3330 feat: recon engine connections screen
  src/ReconEngine/ReconEngineApp/ReconEngineApp.res
  src/ReconEngine/ReconEngineApp/ReconEngineSidebarValues.res
  src/ReconEngine/ReconEngineContainer/ReconEngineConnectionContainer.res
  src/ReconEngine/ReconEngineScreens/ReconEngineConnection/ReconEngineConnection.res
  src/ReconEngine/ReconEngineScreens/ReconEngineConnection/ReconEngineConnectionDisplay.res
  src/ReconEngine/ReconEngineScreens/ReconEngineConnection/ReconEngineConnectionType.res
  src/ReconEngine/ReconEngineScreens/ReconEngineRules/ReconEngineRuleDetails.res
  src/utils/LogicUtils.res
Labels: S-in-progress

#3325 refactor: remove orgchart feature flag
  config/config.toml
  src/entryPoints/FeatureFlagUtils.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
Labels: C-enhancement

#3324 feat: chat bot ui changes
  src/hooks/AuthHooks.res
  src/screens/ChatBot/ChatBot.res
  src/screens/ChatBot/ChatBotTypes.res
Labels: S-waiting-on-review, C-feature, C-enhancement

#3358 feat: add filters in routing analytics
  src/screens/Analytics/RoutingAnalytics/RoutingAnalytics.res
  src/screens/Analytics/RoutingAnalytics/RoutingAnalyticsDistribution/RoutingAnalyticsDistribution.res
  src/screens/Analytics/RoutingAnalytics/RoutingAnalyticsDistribution/RoutingAnalyticsDistributionComponents/RoutingAnalyticsDistributionConnectorVolume.res
  src/screens/Analytics/RoutingAnalytics/RoutingAnalyticsDistribution/RoutingAnalyticsDistributionComponents/RoutingAnalyticsDistributionRoutingApproach.res
  src/screens/Analytics/RoutingAnalytics/RoutingAnalyticsHelper.res
  src/screens/Analytics/RoutingAnalytics/RoutingAnalyticsTypes.res
  src/screens/Analytics/RoutingAnalytics/RoutingAnalyticsUtils.res
Labels: S-waiting-on-review, C-feature

#3361 feat: Routing Analytics Trends Distribution Graph
  src/screens/Analytics/RoutingAnalytics/RoutingAnalytics.res
  src/screens/Analytics/RoutingAnalytics/RoutingAnalyticsTrends/RoutingAnalyticsTrends.res
  src/screens/Analytics/RoutingAnalytics/RoutingAnalyticsTrends/RoutingAnalyticsTrendsEntity.res
  src/screens/Analytics/RoutingAnalytics/RoutingAnalyticsTrends/RoutingAnalyticsTrendsTypes.res
  src/screens/Analytics/RoutingAnalytics/RoutingAnalyticsTrends/RoutingAnalyticsTrendsUtils.res
Labels: S-analytics

#3374 refactor: Chatbot button changes
  public/hyperswitch/icons/solid.svg
  src/entryPoints/HyperSwitchApp.res
Labels: C-enhancement

#3345 chore: removed merchantCountryCode field
  src/screens/Developer/PaymentSettings/AcquirerConfigSettings/AcquirerConfigEntity.res
  src/screens/Developer/PaymentSettings/AcquirerConfigSettings/AcquirerConfigSettings.res
  src/screens/Developer/PaymentSettings/AcquirerConfigSettings/AcquirerConfigTypes.res
  src/screens/Developer/PaymentSettings/AcquirerConfigSettings/AcquirerConfigUtils.res
Labels: S-waiting-on-review
