Repository juspay/hyperswitch-control-center, pull requests merged in 2025-01, with the labels that each got.

#1964 chore: invite users enhancement
  src/screens/UserManagement/UserRevamp/UserManagementHelper.res
  src/screens/UserManagement/UserRevamp/UserManagementUtils.res
Labels: S-waiting-on-review, core

#1962 feat: new analytics filter component
  src/screens/NewAnalytics/NewAnalyticsFilters/NewAnalyticsFilters.res
  src/screens/NewAnalytics/NewAnalyticsFilters/NewAnalyticsFiltersHelper.res
  src/screens/NewAnalytics/NewAnalyticsFilters/NewAnalyticsFiltersUtils.res
  src/screens/NewAnalytics/NewAnalyticsHelper.res
  src/screens/NewAnalytics/NewAnalyticsTypes.res
  src/screens/NewAnalytics/NewAnalyticsUtils.res
Labels: S-waiting-on-review, analytics

#2000 fix: Get production access component visibility in sandbox
  src/entryPoints/SidebarValues.res
Labels: S-waiting-on-review, chore

#1990 chore: banner revamp
  public/hyperswitch/icons/solid.svg
  src/entryPoints/AuthModule/TwoFaAuth/TotpRecoveryCodes.res
  src/screens/Connectors/PaymentProcessor/ConnectorAccountDetailsHelper.res
  src/screens/Connectors/PaymentProcessor/ConnectorHome.res
  src/screens/Connectors/PaymentProcessor/ConnectorPaymentMethod.res
  src/screens/Connectors/PayoutProcessor/PayoutProcessorHome.res
  src/screens/Connectors/PayoutProcessor/PayoutProcessorPaymentMethod.res
  src/screens/HSwitchUtils.res
  src/screens/HSwitchUtilsTypes.res
  src/screens/Home/HomeUtils.res
  src/screens/SelfServe/HSwitchSandboxOnboarding/UserOnboardingUIUtils.res
  src/screens/Settings/BusinessMapping/BusinessProfile.res
  src/screens/Settings/HSwitchProfile/TwoFaSettings/RegenerateRC.res
  tailwind.config.js
Labels: S-waiting-on-review, core

#1979 chore: support multitenancy domain
  src/entryPoints/AuthModule/AuthUtils.res
  src/entryPoints/AuthModule/TwoFaAuth/TwoFaAuth.res
  src/entryPoints/HyperSwitchEntry.res
  src/screens/Hooks/MerchantSpecificConfigHook.res
  src/screens/OMPSwitch/OrgSwitch.res
  src/screens/UserManagement/UserRevamp/UserManagementUtils.res
  src/server/Server.res
Labels: S-waiting-on-review, core

#1996 refactor: payment settings redesign
  src/screens/Developer/PaymentSettings/PaymentSettings.res
  tailwind.config.js
Labels: C-ui

#2008 chore: added required tenant user checks
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/SidebarValues.res
  src/screens/OMPSwitch/OMPSwitchUtils.res
  src/screens/UserManagement/UserRevamp/InviteMember.res
Labels: S-waiting-on-review, core

#1991 fix: Api creds redesign
  src/screens/Connectors/PaymentProcessor/ConnectorPreview.res
  src/screens/Connectors/PaymentProcessor/ConnectorPreviewHelper.res
  src/screens/Connectors/PaymentProcessor/ConnectorUpdateAuthCreds.res
  tailwind.config.js
Labels: S-waiting-on-review, C-feature

#1994 fix: Made responsive
  src/screens/Helpers/CardUtils.res
  src/screens/Home/HomeUtils.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/UserManagement/UserRevamp/ListRoles.res
  src/screens/UserManagement/UserRevamp/ListUsers.res
  src/screens/UserManagement/UserRevamp/ManageUserModal.res
  src/screens/UserManagement/UserRevamp/NewUserInvitationForm.res
  src/screens/UserManagement/UserRevamp/UserInfo.res
  src/screens/UserManagement/UserRevamp/UserManagementHelper.res
Labels: S-waiting-on-review, C-feature, C-ui

#1998 chore: event logs ui enhancements
  public/hyperswitch/icons/solid.svg
  src/screens/Analytics/Logs/LogUtils/ApiDetailsComponent.res
  src/screens/Analytics/Logs/LogUtils/AuditLogUI.res
Labels: C-ui

#2011 feat: new analytics filter utils changes
  src/screens/NewAnalytics/NewAnalyticsFilters/NewAnalyticsFiltersHelper.res
  src/screens/NewAnalytics/NewAnalyticsFilters/NewAnalyticsFiltersUtils.res
  src/screens/NewAnalytics/NewAnalyticsHelper.res
  src/screens/NewAnalytics/NewAnalyticsTypes.res
  src/screens/NewAnalytics/NewAnalyticsUtils.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsOverviewSection/RefundsOverviewSection.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSection.res
Labels: S-waiting-on-review, analytics

#2025 chore: Dropdown ellipses text
  src/components/SelectBox.res
  src/screens/UserManagement/UserRevamp/UserManagementHelper.res
Labels: S-waiting-on-review, C-bug

#2013 fix: Dropdown buttons
  src/components/ACLDiv.res
  src/components/ACLDiv.resi
  src/screens/OMPSwitch/OMPSwitchHelper.res
Labels: S-waiting-on-review, C-bug

#2016 chore: Moved Connector and Business Profile API call to SDK Page
  src/container/MerchantAccountContainer.res
  src/screens/Home/HomeUtils.res
  src/screens/SDKPayment/SDKPage.res
Labels: S-waiting-on-review, chore

#2001 feat: Extenddatebutton
  src/components/NoDataFound.res
  src/screens/Payouts/PayoutsList.res
  src/screens/Payouts/PayoutsUtils.res
  src/screens/Transaction/Disputes/Disputes.res
  src/screens/Transaction/Order/Orders.res
  src/screens/Transaction/Refunds/Refund.res
  src/screens/Transaction/Refunds/RefundUtils.res
Labels: C-feature

#2026 chore: dropdown options for profile
  src/screens/OMPSwitch/OMPSwitchUtils.res
Labels: S-waiting-on-review, core

#2031 chore: minor file refactor and table data ordering
  src/screens/NewAnalytics/NewRefundsAnalytics/FailedRefundsDistribution/FailedRefundsDistribution.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsOverviewSection/RefundsOverviewSection.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsProcessed/RefundsProcessed.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsSuccessRate/RefundsSuccessRate.res
  src/screens/NewAnalytics/PaymentAnalytics/FailedPaymentsDistribution/FailedPaymentsDistribution.res
  src/screens/NewAnalytics/PaymentAnalytics/FailedPaymentsDistribution/FailedPaymentsDistributionUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRate.res
  src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistribution.res
  src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistributionUtils.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessed.res
Labels: S-waiting-on-review, analytics

#2028 feat: global search mixpanel events
  src/screens/Analytics/GlobalSearch/GlobalSearchBar.res
Labels: S-waiting-on-review, analytics

#2019 feat: new analytics filter payments
  src/screens/NewAnalytics/PaymentAnalytics/FailedPaymentsDistribution/FailedPaymentsDistribution.res
  src/screens/NewAnalytics/PaymentAnalytics/FailureReasonsPayments/FailureReasonsPayments.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalytics.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSection.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionTypes.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedTypes.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRate.res
  src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistribution.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessed.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessedTypes.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessedUtils.res
Labels: S-waiting-on-review, analytics

#2034 chore: global search free text handling
  src/screens/Analytics/GlobalSearch/GlobalSearchBar.res
  src/screens/Analytics/GlobalSearch/GlobalSearchBarHelper.res
Labels: S-waiting-on-review, analytics

#2037 feat: new analytics currency filter smart retry
  src/screens/NewAnalytics/SmartRetryAnalytics/FailureSmartRetryDistribution/FailureSmartRetryDistribution.res
  src/screens/NewAnalytics/SmartRetryAnalytics/NewSmartRetryAnalytics.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessed.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessedUtils.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SuccessfulSmartRetryDistribution/SuccessfulSmartRetryDistribution.res
Labels: S-waiting-on-review, analytics

#2040 chore: show merchant switch toast
  src/screens/Hooks/OMPSwitchHooks.res
Labels: S-waiting-on-review, core

#2041 chore: show info banner for download api key
  src/entryPoints/AuthModule/TwoFaAuth/TotpRecoveryCodes.res
  src/screens/Connectors/PaymentProcessor/ConnectorAccountDetailsHelper.res
  src/screens/Connectors/PaymentProcessor/ConnectorHome.res
  src/screens/Connectors/PaymentProcessor/ConnectorPaymentMethod.res
  src/screens/Connectors/PayoutProcessor/PayoutProcessorHome.res
  src/screens/Connectors/PayoutProcessor/PayoutProcessorPaymentMethod.res
  src/screens/Developer/APIKeys/DeveloperUtils.res
  src/screens/HSwitchUtils.res
  src/screens/Home/HomeUtils.res
  src/screens/SelfServe/HSwitchSandboxOnboarding/UserOnboardingUIUtils.res
  src/screens/Settings/BusinessMapping/BusinessProfile.res
  src/screens/Settings/HSwitchProfile/TwoFaSettings/RegenerateRC.res
Labels: S-waiting-on-review, core

#1982 chore: Themes API Frontend Support
  public/hyperswitch/module.js
  src/UIConifg/UIConfig.res
  src/components/Button.res
  src/components/Calendar.res
  src/components/FilterSelectBox.res
  src/components/InfraCalendar.res
  src/components/MultiLineTextInput.res
  src/components/NewCalendar.res
  src/components/NewCalendarTimeInput.res
  src/components/NewThemeUtils.res
  src/components/PopUpConfirm.res
  src/components/RangeSlider.res
  src/components/SearchInput.res
  src/components/SelectBox.res
  src/components/TableUtils.res
  src/context/ThemeProvider.res
  src/entryPoints/AuthModule/TwoFaAuth/OtpInput.res
  src/entryPoints/AuthModule/UserInfo/UserInfoTypes.res
  src/entryPoints/AuthModule/UserInfo/UserInfoUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/HyperSwitchEntry.res
  src/entryPoints/configs/HyperSwitchDefaultConfig.res
  src/screens/Analytics/HomePageOverview/HomePageOverviewComponent.res
  src/screens/Connectors/PaymentProcessor/ConnectPayPalFlow/ConnectPayPal.res
  src/screens/Connectors/PaymentProcessor/ConnectorPreview.res
  src/screens/Helpers/PageLoaderWrapper.res
  src/screens/NewAnalytics/NewAnalyticsHelper.res
  src/screens/OMPSwitch/MerchantSwitch.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/OMPSwitch/OrgSwitch.res
  src/screens/OMPSwitch/ProfileSwitch.res
  src/screens/Payouts/PayoutsEntity.res
  src/screens/Routing/AdvancedRouting/RoutingPreviewer.res
  src/screens/Routing/DefaultRouting.res
  src/screens/Routing/PriorityRouting.res
  src/screens/SelfServe/HSwitchSandboxOnboarding/UserOnboardingUIUtils.res
  src/screens/Sidebar/Sidebar.res
  src/screens/Sidebar/SidebarSwitch.res
  src/screens/Transaction/CommonFilters/AmountFilter/AmountFilter.res
  src/screens/Transaction/Disputes/DisputesEntity.res
  src/screens/Transaction/Order/OrderEntity.res
  src/screens/Transaction/Refunds/RefundEntity.res
  src/screens/TransactionViews/TransactionView.res
Labels: S-waiting-on-review, C-feature

#2048 fix: font color primary
  src/context/ThemeProvider.res
Labels: C-ui

#2046 chore: limit unusually large width of dropdown
  src/screens/OMPSwitch/MerchantSwitch.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/OMPSwitch/ProfileSwitch.res
Labels: S-waiting-on-review, core

#2022 feat: banner for maintenance
  config/config.toml
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/screens/OMPSwitch/OrgSwitch.res
Labels: S-waiting-on-review, C-ui

#2053 chore: org dropdown for tenant admin
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/OMPSwitch/OrgSwitch.res
Labels: S-waiting-on-review, core

#2058 fix: disable deselecting item
  src/screens/OMPSwitch/OMPSwitchHelper.res
Labels: S-waiting-on-review, core

#2054 fix: global search id search fix
  src/components/EntityScaffold.res
  src/container/TransactionContainer.res
  src/entryPoints/AuthModule/UserInfo/UserInfoProvider.res
  src/entryPoints/AuthModule/UserInfo/UserInfoTypes.res
  src/entryPoints/AuthModule/UserInfo/UserInfoUtils.res
  src/screens/Analytics/GlobalSearch/GlobalSearchBarUtils.res
  src/screens/Analytics/GlobalSearch/GlobalSearchTypes.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/Disputes/DisputeTableEntity.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/PaymentAttempt/PaymentAttemptEntity.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/PaymentIntent/PaymentIntentEntity.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/Refunds/RefundsTableEntity.res
  src/screens/Hooks/OMPSwitchHooks.res
  src/screens/OMPSwitch/MerchantSwitch.res
  src/screens/OMPSwitch/OrgSwitch.res
  src/screens/OMPSwitch/ProfileSwitch.res
  src/screens/OMPSwitch/SwitchMerchantForInternal.res
  src/screens/Payouts/ShowPayout.res
  src/screens/Transaction/Disputes/Disputes.res
  src/screens/Transaction/Disputes/DisputesEntity.res
  src/screens/Transaction/Disputes/ShowDisputes.res
  src/screens/Transaction/Order/OrderEntity.res
  src/screens/Transaction/Order/OrderRefundForm.res
  src/screens/Transaction/Order/Orders.res
  src/screens/Transaction/Order/ShowOrder.res
  src/screens/Transaction/Refunds/Refund.res
  src/screens/Transaction/Refunds/RefundEntity.res
  src/screens/Transaction/Refunds/ShowRefund.res
Labels: bug

#2050 chore: conditional enforcement of cookies
  config/config.toml
  src/APIUtils/APIUtils.res
  src/components/AdvancedSearchComponent.res
  src/components/AdvancedSearchModal.res
  src/components/DynamicChart.res
  src/components/DynamicSingleStat.res
  src/components/DynamicTable.res
  src/components/custom-icons/LottieFiles.res
  src/context/ChartContext.res
  src/context/SingleStatContext.res
  src/context/ThemeProvider.res
  src/entryPoints/AuthModule/UserInfo/UserInfoProvider.res
  src/entryPoints/FeatureFlagUtils.res
  src/hooks/AuthHooks.res
  src/screens/Connectors/PaymentProcessor/ConnectorMetaData/ApplePay/ApplePaySimplifiedFlow.res
  src/screens/Hooks/OMPSwitchHooks.res
  src/screens/MixpanelHook.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/SDKPayment/WebSDK.res
  src/screens/Settings/ComplianceCertificates/Compliance.res
  webpack.dev.js
Labels: S-waiting-on-review, core

#2056 feat: new analytics filter refunds
  src/container/NewAnalyticsContainer.res
  src/screens/NewAnalytics/NewAnalyticsUtils.res
  src/screens/NewAnalytics/NewRefundsAnalytics/FailedRefundsDistribution/FailedRefundsDistribution.res
  src/screens/NewAnalytics/NewRefundsAnalytics/FailureReasonsRefunds/FailureReasonsRefunds.res
  src/screens/NewAnalytics/NewRefundsAnalytics/NewRefundsAnalytics.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsOverviewSection/RefundsOverviewSection.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsOverviewSection/RefundsOverviewSectionTypes.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsOverviewSection/RefundsOverviewSectionUtils.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsProcessed/RefundsProcessed.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsProcessed/RefundsProcessedTypes.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsProcessed/RefundsProcessedUtils.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsReasons/RefundsReasons.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsSuccessRate/RefundsSuccessRate.res
  src/screens/NewAnalytics/NewRefundsAnalytics/SuccessfulRefundsDistribution/SuccessfulRefundsDistribution.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessed.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessedUtils.res
Labels: S-waiting-on-review, analytics

#2064 fix: Fixed extend date button functionality
  src/components/NoDataFound.res
  src/screens/Payouts/PayoutsList.res
  src/screens/Transaction/Disputes/Disputes.res
  src/screens/Transaction/Order/Orders.res
  src/screens/Transaction/Refunds/Refund.res
Labels: C-bug

#2067 fix: currency filter value fixes
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionHelper.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessed.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessedUtils.res
Labels: S-waiting-on-review, analytics

#2065 chore: filter authentication processor
  src/screens/Developer/PaymentSettings/PaymentSettings.res
Labels: S-waiting-on-review

#2069 refactor: connector_type type added
  src/screens/ConfigurePMTs/PaymentMethodConfigUtils.res
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUtils.res
  src/screens/Connectors/PMAuthenticationProcessor/PMAuthenticationConnectorList.res
  src/screens/Connectors/PMAuthenticationProcessor/PMAuthenticationHome.res
  src/screens/Connectors/PaymentProcessor/ConnectorHome.res
  src/screens/Connectors/PaymentProcessor/ConnectorList.res
  src/screens/Connectors/PaymentProcessor/ConnectorPaymentMethod.res
  src/screens/Connectors/PaymentProcessor/ConnectorPreview.res
  src/screens/Connectors/PaymentProcessor/ConnectorUpdateAuthCreds.res
  src/screens/Connectors/PayoutProcessor/PayoutProcessorHome.res
  src/screens/Connectors/PayoutProcessor/PayoutProcessorList.res
  src/screens/Connectors/TaxProcessor/TaxProcessorHome.res
  src/screens/Connectors/TaxProcessor/TaxProcessorList.res
  src/screens/Connectors/ThreeDsProcessors/ThreeDsConnectorList.res
  src/screens/Connectors/ThreeDsProcessors/ThreeDsProcessorHome.res
  src/screens/Developer/PaymentSettings/PaymentSettings.res
  src/screens/Routing/RoutingUtils.res
  src/utils/Mappers/ConnectorListMapper.res
Labels: S-waiting-on-review

#2071 feat: customer table pagination
  src/APIUtils/APIUtils.res
  src/screens/Customers/Customers.res
Labels: S-waiting-on-review, core

#2063 feat: sidebar changes for modularity
  public/hyperswitch/icons/solid.svg
  public/hyperswitch/module.js
  src/UIConifg/UIConfig.res
  src/context/ThemeProvider.res
  src/entryPoints/configs/HyperSwitchConfigTypes.res
  src/entryPoints/configs/HyperSwitchDefaultConfig.res
  src/screens/Helpers/PageLoaderWrapper.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/OMPSwitch/OrgSwitch.res
  src/screens/Sidebar/Sidebar.res
  tailwind.config.js
Labels: S-waiting-on-review, chore

#2079 refactor: Moved Graphs folder to components
  src/components/Graphs/BarGraph/BarGraph.res
  src/components/Graphs/BarGraph/BarGraphTypes.res
  src/components/Graphs/BarGraph/BarGraphUtils.res
  src/components/Graphs/LineGraph/LineGraph.res
  src/components/Graphs/LineGraph/LineGraphTypes.res
  src/components/Graphs/LineGraph/LineGraphUtils.res
  src/components/Graphs/SankyGraph/SankeyGraph.res
  src/components/Graphs/SankyGraph/SankeyGraphTypes.res
  src/components/Graphs/SankyGraph/SankeyGraphUtils.res
Labels: S-waiting-on-review, chore

#2081 chore: Change Bar graph component
  src/components/Graphs/BarGraph/BarGraph.res
  src/components/Graphs/BarGraph/BarGraphUtils.res
  src/screens/NewAnalytics/NewRefundsAnalytics/FailedRefundsDistribution/FailedRefundsDistribution.res
  src/screens/NewAnalytics/NewRefundsAnalytics/SuccessfulRefundsDistribution/SuccessfulRefundsDistribution.res
  src/screens/NewAnalytics/PaymentAnalytics/FailedPaymentsDistribution/FailedPaymentsDistribution.res
  src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistribution.res
  src/screens/NewAnalytics/SmartRetryAnalytics/FailureSmartRetryDistribution/FailureSmartRetryDistribution.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SuccessfulSmartRetryDistribution/SuccessfulSmartRetryDistribution.res
Labels: S-waiting-on-review, chore

#2084 feat: new analytics filters feature flag
  config/config.toml
  src/entryPoints/FeatureFlagUtils.res
  src/screens/NewAnalytics/NewRefundsAnalytics/NewRefundsAnalytics.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalytics.res
  src/screens/NewAnalytics/SmartRetryAnalytics/NewSmartRetryAnalytics.res
Labels: S-waiting-on-review, analytics

#2061 feat: added responsiveness to api keys page
  src/components/CardTable.res
  src/components/LoadedTable.res
  src/screens/Developer/APIKeys/KeyManagement.res
  src/screens/Developer/APIKeys/PublishableAndHashKeySection.res
  src/screens/Helpers/HelperComponents.res
Labels: C-ui

#2089 refactor: changed linegraph and sankeygraph options
  src/components/Graphs/BarGraph/BarGraph.res
  src/components/Graphs/LineGraph/LineGraph.res
  src/components/Graphs/SankyGraph/SankeyGraph.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsProcessed/RefundsProcessed.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsSuccessRate/RefundsSuccessRate.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsLifeCycle/PaymentsLifeCycle.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRate.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessed.res
Labels: S-waiting-on-review, chore

#1931 chore: Remove unused feature flags and codeblocks
  README.md
  config/config.toml
  cypress/e2e/auth/auth.cy.js
  src/components/LoadedTable.res
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/SidebarValues.res
  src/screens/Analytics/ActiveUserCounter/ActivePaymentsCounter.res
  src/screens/Analytics/AuthenticationAnalytics/AuthenticationAnalytics.res
  src/screens/Analytics/AuthenticationAnalytics/AuthenticationAnalyticsEntity.res
  src/screens/Analytics/HomePageOverview/HomePageOverviewComponent.res
  src/screens/Analytics/SystemMetrics/SystemMetricsAnalytics.res
  src/screens/Analytics/SystemMetrics/SystemMetricsAnalyticsUtils.res
  src/screens/Analytics/UserJourneyAnalytics/UserJourneyAnalytics.res
  src/screens/Analytics/UserJourneyAnalytics/UserJourneyAnalyticsEntity.res
  src/screens/Developer/APIKeys/KeyManagement.res
Labels: S-waiting-on-review, chore

#2017 feat: granularity new analytics changes
  src/components/Graphs/LineGraph/LineGraphUtils.res
  src/screens/NewAnalytics/NewAnalyticsHelper.res
  src/screens/NewAnalytics/NewAnalyticsTypes.res
  src/screens/NewAnalytics/NewAnalyticsUtils.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsProcessed/RefundsProcessed.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsSuccessRate/RefundsSuccessRate.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRate.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessed.res
Labels: S-waiting-on-review, analytics

#2098 refactor: Value formatter moved to LogicUtils
  src/components/Graphs/SankyGraph/SankeyGraphUtils.res
  src/screens/NewAnalytics/NewAnalyticsFilters/NewAnalyticsFiltersUtils.res
  src/screens/NewAnalytics/NewAnalyticsHelper.res
  src/screens/NewAnalytics/NewAnalyticsTypes.res
  src/screens/NewAnalytics/NewAnalyticsUtils.res
  src/screens/NewAnalytics/NewRefundsAnalytics/FailureReasonsRefunds/FailureReasonsRefundsUtils.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsOverviewSection/RefundsOverviewSectionUtils.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsProcessed/RefundsProcessed.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsProcessed/RefundsProcessedUtils.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsReasons/RefundsReasonsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/FailedPaymentsDistribution/FailedPaymentsDistributionUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/FailureReasonsPayments/FailureReasonsPaymentsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsOverviewSection/NewPaymentsOverviewSectionUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistributionUtils.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessed.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessedUtils.res
  src/utils/LogicUtils.res
  src/utils/LogicUtilsTypes.res
Labels: S-waiting-on-review, chore

#2101 chore: enabled paybox connector on prod
  src/screens/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review, core

#2102 fix: sdk go to payment button redirection fix
  src/screens/SDKPayment/SDKPage.res
Labels: S-waiting-on-review, core

#2010 fix: Add email support
  cypress.config.js
  cypress/e2e/Payment/00001-PaymentOperationsColumns.cy.js
  cypress/e2e/auth/auth.cy.js
  cypress/e2e/connector/connector.cy.js
  cypress/start_hyperswitch.sh
  cypress/support/commands.js
  package.json
  src/screens/SDKPayment/TestPayment.res
  src/screens/SDKPayment/WebSDK.res
Labels: C-bug, cypress

#2099 fix: Merchant View Only Access to APIKeys
  src/entryPoints/HyperSwitchApp.res
  src/screens/Developer/APIKeys/KeyManagement.res
Labels: S-waiting-on-review, bug

#2113 fix: Refactoring append themes css logic
  public/hyperswitch/module.js
Labels: C-bug

#2117 fix: Removed System Metrics
  src/APIUtils/APIUtils.res
  src/APIUtils/APIUtilsTypes.res
  src/entryPoints/SidebarValues.res
  src/screens/Analytics/Analytics.res
  src/screens/Analytics/AnalyticsTypes.res
Labels: bug

#2112 feat: Addition of new connectors-Xendit and Jp morgan
  public/hyperswitch/Gateway/JPMORGAN.svg
  public/hyperswitch/Gateway/XENDIT.svg
  public/hyperswitch/wasm/euclid.d.ts
  public/hyperswitch/wasm/euclid.js
  public/hyperswitch/wasm/euclid_bg.wasm
  public/hyperswitch/wasm/euclid_bg.wasm.d.ts
  public/hyperswitch/wasm/package.json
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUtils.res
Labels: C-feature

#2120 chore: customer list limit increased from 10 to 50
  src/screens/Customers/Customers.res
Labels: S-waiting-on-review, core

#2124 fix: connector list not updating properly everytime
  src/screens/Connectors/FraudAndRisk/FRMIntegrationFields.res
  src/screens/Connectors/PMAuthenticationProcessor/PMAuthenticationHome.res
  src/screens/Connectors/PaymentProcessor/ConnectorPaymentMethod.res
  src/screens/Connectors/PayoutProcessor/PayoutProcessorPaymentMethod.res
  src/screens/Connectors/ThreeDsProcessors/ThreeDsProcessorHome.res
Labels: S-waiting-on-review

#2130 fix: theme logo
  src/context/ThemeProvider.res
  src/entryPoints/HyperSwitchEntry.res
Labels: bug

#2122 chore: granularity time formatting to user time zone
  src/components/Graphs/LineGraph/LineGraphUtils.res
  src/screens/HSwitchRemoteFilter.res
  src/screens/NewAnalytics/NewAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRate.res
Labels: S-waiting-on-review, analytics

#2129 fix: sorted userlist by email
  src/screens/UserManagement/UserRevamp/ListUsers.res
Labels: bug

#2132 chore: insights single point enhancement
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsProcessed/RefundsProcessedUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessedUtils.res
Labels: S-waiting-on-review, analytics

#2127 fix: Surcharge delete button
  src/screens/Helpers/CardUtils.res
  src/screens/Surcharge/Surcharge.res
Labels: bug

#2126 fix: sdk checkout overlapping divs
  src/screens/SelfServe/HSwitchProdOnboarding/CheckoutHelper.res
Labels: C-ui

#2141 feat: recovery product feature flag and folder structure
  config/config.toml
  src/RevenueRecoveryScreens/RevenueRecoveryBillingProcessors/RevenueRecoveryBillingProcessors.res
  src/RevenueRecoveryScreens/RevenueRecoveryHome/RevenueRecoveryHome.res
  src/RevenueRecoveryScreens/RevenueRecoveryPaymentProcessors/RevenueRecoveryPaymentProcessors.res
  src/RevenueRecoveryScreens/RevenueRecoveryPayments/RevenueRecoveryPayments.res
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HSReconApp.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/ProductsSidebarValues.res
  src/entryPoints/ReconApp/ReconApp.res
  src/entryPoints/ReconApp/ReconSidebarValues.res
  src/entryPoints/RevenueRecoveryApp/RevenueRecoveryApp.res
  src/entryPoints/RevenueRecoveryApp/RevenueRecoverySidebarValues.res
  src/screens/PendingInvitationsHome.res
Labels: S-waiting-on-review, Recovery

#2128 chore: added profile name validation
  src/screens/Settings/BusinessMapping/BusinessMappingEntity.res
Labels: S-waiting-on-review, core

#2148 fix: Surcharge and 3DS Delete permission
  src/screens/Surcharge/Surcharge.res
  src/screens/ThreeDSFlow/HSwitchThreeDS.res
Labels: bug

#2143 fix: Refactor modal warning icon in Smart and volume based routing
  public/hyperswitch/icons/solid.svg
  src/screens/Routing/CustomModal.res
  src/screens/Routing/VolumeSplitRouting.res
  src/screens/RoutingRevamp/AdvancedRouting.res
Labels: S-waiting-on-review, C-bug

#2156 fix: analytics filters init set function modification
  src/container/NewAnalyticsContainer.res
  src/screens/HSwitchRemoteFilter.res
Labels: S-waiting-on-review, analytics

#2158 chore: add analytics authentication
  config/config.toml
  src/APIUtils/APIUtils.res
  src/APIUtils/APIUtilsTypes.res
  src/container/AnalyticsContainer.res
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/SidebarValues.res
  src/screens/Analytics/Analytics.res
  src/screens/Analytics/AnalyticsTypes.res
  src/screens/Analytics/AuthenticationAnalytics/AuthenticationAnalytics.res
  src/screens/Analytics/AuthenticationAnalytics/AuthenticationAnalyticsEntity.res
Labels: analytics

#2087 feat: Org Sidebar
  config/config.toml
  public/hyperswitch/icons/solid.svg
  src/UIConifg/UIConfig.res
  src/components/InlineEditInput.res
  src/components/InlineEditInput.resi
  src/context/ThemeProvider.res
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/screens/Helpers/HelperComponents.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/Sidebar/OrgSidebar.res
  src/screens/Sidebar/Sidebar.res
  src/screens/Sidebar/SidebarSwitch.res
  tailwind.config.js
Labels: C-feature

#2149 feat: global font change to InterDisplay
  public/hyperswitch/assets/fonts/InterDisplay-Black.woff2
  public/hyperswitch/assets/fonts/InterDisplay-BlackItalic.woff2
  public/hyperswitch/assets/fonts/InterDisplay-Bold.woff2
  public/hyperswitch/assets/fonts/InterDisplay-BoldItalic.woff2
  public/hyperswitch/assets/fonts/InterDisplay-ExtraBold.woff2
  public/hyperswitch/assets/fonts/InterDisplay-ExtraBoldItalic.woff2
  public/hyperswitch/assets/fonts/InterDisplay-ExtraLight.woff2
  public/hyperswitch/assets/fonts/InterDisplay-ExtraLightItalic.woff2
  public/hyperswitch/assets/fonts/InterDisplay-Italic.woff2
  public/hyperswitch/assets/fonts/InterDisplay-Light.woff2
  public/hyperswitch/assets/fonts/InterDisplay-LightItalic.woff2
  public/hyperswitch/assets/fonts/InterDisplay-Medium.woff2
  public/hyperswitch/assets/fonts/InterDisplay-MediumItalic.woff2
  public/hyperswitch/assets/fonts/InterDisplay-Regular.woff2
  public/hyperswitch/assets/fonts/InterDisplay-SemiBold.woff2
  public/hyperswitch/assets/fonts/InterDisplay-SemiBoldItalic.woff2
  public/hyperswitch/assets/fonts/InterDisplay-Thin.woff2
  public/hyperswitch/assets/fonts/InterDisplay-ThinItalic.woff2
  public/hyperswitch/index.html
  tailwind.config.js
  webpack.common.js
Labels: feature

#2106 feat: granularity options for smart retry tab analytics
  src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessed.res
Labels: S-waiting-on-review, analytics

#2107 feat: granularity options for refunds tab analytics
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsProcessed/RefundsProcessed.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsSuccessRate/RefundsSuccessRate.res
Labels: S-waiting-on-review, analytics

#2145 chore: redacted customers details page view
  src/screens/Customers/ShowCustomers.res
Labels: S-waiting-on-review, core

#2151 feat: klarna-checkout added for klarna updated wasm
  public/hyperswitch/wasm/euclid_bg.wasm
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUtils.res
  src/screens/Connectors/PaymentProcessor/ConnectorUIUtils/PaymentMethod.res
Labels: S-waiting-on-review, core

#2147 feat: New UI button
  .github/workflows/cypress-test.yml
  src/UIConifg/UIConfig.res
  src/components/Button.res
  src/components/ButtonGroupIp.res
  src/components/CustomizeNotificationsModal.res
  src/components/DateRangeCompareFields.res
  src/components/DateRangeField.res
  src/components/DateRangeHelper.res
  src/components/DateRangePicker.res
  src/components/DynamicTable.res
  src/components/DynamicTabs.res
  src/components/Filter.res
  src/components/FilterSelectBox.res
  src/components/InputFields.res
  src/components/InputFields.resi
  src/components/LoadedTableWithCustomColumns.res
  src/components/NotFoundPage.res
  src/components/Pagination.res
  src/components/Paginator.res
  src/components/PopUpConfirm.res
  src/components/UnauthorizedPage.res
  src/context/ThemeProvider.res
  src/reconScreens/ReconConfiguration/ReconConfigurationHelper.res
  src/reconScreens/ReconOnboarding/ReconOnbdLanding.res
  src/screens/Connectors/PaymentProcessor/ConnectorMetaData/ApplePay/ApplePaySimplifiedFlow.res
  src/screens/Developer/APIKeys/KeyManagement.res
  src/screens/Developer/PaymentSettings/PaymentSettings.res
  src/screens/GenerateReports/GenerateReport.res
  src/screens/Home/HomeUtils.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/PayoutRouting/PayoutRoutingStack.res
  src/screens/PendingInvitationsHome.res
  src/screens/Processors/ProcessorCards.res
  src/screens/Routing/ActiveRouting.res
  src/screens/Routing/VolumeSplitRouting.res
  src/screens/RoutingRevamp/AdvancedRouting.res
  src/screens/RoutingRevamp/AdvancedRoutingUIUtils.res
  src/screens/SDKPayment/TestPayment.res
  src/screens/SDKPayment/WebSDK.res
  src/screens/SelfServe/HSwitchSandboxOnboarding/IntegrationDocs.res
  src/screens/SelfServe/HSwitchSandboxOnboarding/UserOnboardingUIUtils.res
  src/screens/Settings/BusinessDetails.res
  src/screens/Settings/HSwitchProfile/HSwitchProfileSettings.res
  src/screens/Transaction/Disputes/UploadEvidenceForDisputes.res
  src/screens/Transaction/Order/OrderUIUtils.res
  src/screens/Transaction/Order/ShowOrder.res
  src/screens/Transaction/Refunds/ShowRefund.res
  src/screens/UserManagement/UserRevamp/ListUsers.res
  src/screens/UserManagement/UserRevamp/ManageUserModal.res
  tailwind.config.js
Labels: S-waiting-on-review, C-ui

#2166 chore: text comp ui update
  src/screens/Helpers/HelperComponents.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
Labels: S-waiting-on-review, core

#2170 feat: Product sidebar changes
  public/hyperswitch/icons/solid.svg
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/ProductTypes.res
  src/entryPoints/ProductUtils.res
  src/entryPoints/ProductsSidebarValues.res
  src/entryPoints/Provider/GlobalProvider.res
  src/entryPoints/Provider/ProviderTypes.res
  src/entryPoints/SidebarValues.res
  src/screens/Analytics/GlobalSearch/GlobalSearchBar.res
  src/screens/Analytics/GlobalSearchResults/SearchResultsPage.res
  src/screens/Sidebar/Sidebar.res
Labels: feature

#2172 fix: Filter Select Box changes
  src/components/FilterSelectBox.res
Labels: S-waiting-on-review, C-bug

#2153 chore: Dashboard White Theme Changes ( Including OMP )
  config/config.toml
  public/hyperswitch/icons/solid.svg
  src/UIConifg/UIConfig.res
  src/components/InlineEditInput.res
  src/components/SelectBox.res
  src/components/SelectBox.resi
  src/context/ThemeProvider.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/configs/HyperSwitchConfigTypes.res
  src/entryPoints/configs/HyperSwitchDefaultConfig.res
  src/libraries/Clipboard.res
  src/screens/Helpers/HelperComponents.res
  src/screens/Hooks/OMPSwitchHooks.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsProcessed/RefundsProcessed.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsSuccessRate/RefundsSuccessRate.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessed.res
  src/screens/OMPSwitch/MerchantSwitch.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/OMPSwitch/OMPSwitchTypes.res
  src/screens/OMPSwitch/OrgSwitch.res
  src/screens/OMPSwitch/ProfileSwitch.res
  src/screens/Sidebar/OrgSidebar.res
  src/screens/Sidebar/Sidebar.res
  src/screens/Sidebar/SidebarSwitch.res
  tailwind.config.js
Labels: C-feature

#2174 chore: config colors changes
  config/config.toml
Labels: C-bug

#2176 fix: Dashboard redesign ui issues
  public/hyperswitch/icons/solid.svg
  src/components/DatePicker.res
  src/components/LoadedTable.res
  src/components/PopUpConfirm.res
  src/entryPoints/AuthModule/TwoFaAuth/TotpRecoveryCodes.res
  src/entryPoints/SidebarValues.res
  src/screens/Connectors/PaymentProcessor/ConnectorMetaData/ApplePay/ApplePayIntegrationHelper.res
  src/screens/Connectors/PaymentProcessor/ConnectorPreview.res
  src/screens/Developer/APIKeys/PublishableAndHashKeySection.res
  src/screens/Developer/PaymentSettings/PaymentSettings.res
  src/screens/Helpers/HelperComponents.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/OMPSwitch/OrgSwitch.res
  src/screens/Routing/ActiveRouting.res
  src/screens/Routing/CustomModal.res
  src/screens/RoutingRevamp/AdvancedRouting.res
  src/screens/SelfServe/HSwitchSandboxOnboarding/UserOnboardingUIUtils.res
  src/screens/Settings/HSwitchProfile/TwoFaSettings/RegenerateRC.res
  src/screens/Sidebar/OrgSidebar.res
  src/screens/Transaction/Order/HSwitchOrderUtils.res
  tailwind.config.js
Labels: C-ui

#2177 feat: vaulting setup
  config/config.toml
  public/hyperswitch/icons/solid.svg
  src/Vault/VaultScreens/VaultConfiguration.res
  src/Vault/VaultScreens/VaultCustomersAndTokens.res
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/ProductTypes.res
  src/entryPoints/ProductUtils.res
  src/entryPoints/ProductsSidebarValues.res
  src/entryPoints/SidebarValues.res
  src/entryPoints/VaultApp/VaultApp.res
  src/entryPoints/VaultApp/VaultSidebarValues.res
  src/screens/Sidebar/Sidebar.res
Labels: feature

#2180 fix: org name update
  src/components/InlineEditInput.res
Labels: C-bug

#2182 chore: vaulting landing page
  public/hyperswitch/assets/VaultOnboarding.svg
  public/hyperswitch/assets/VaultSdkImage.svg
  public/hyperswitch/assets/VaultServerImage.svg
  src/Vault/VaultScreens/VaultConfiguration.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/ReconApp/ReconSidebarValues.res
  src/entryPoints/RevenueRecoveryApp/RevenueRecoverySidebarValues.res
  src/entryPoints/SidebarValues.res
  src/entryPoints/VaultApp/VaultSidebarValues.res
  src/screens/Sidebar/Sidebar.res
  tailwind.config.js
Labels: chore

#2184 fix: org indexes logic fix
  src/entryPoints/SidebarValues.res
  src/screens/Sidebar/OrgSidebar.res
Labels: C-ui
