Repository juspay/hyperswitch-control-center, pull requests merged in 2025-06, with the labels that each got.

#3087 chore: missing line 1 & line 2 added
  src/screens/SDKPayment/FormSection/ToggleFormSection.res
  src/screens/SDKPayment/SDKHelper/SDKPaymentHelper.res
  src/screens/SDKPayment/SDKPaymentTypes.res
  src/screens/SDKPayment/SDKUtils/SDKPaymentUtils.res
Labels: S-waiting-on-review

#3075 feat: recovery invoices api data and removed hard coded data
  src/APIUtils/APIUtils.res
  src/APIUtils/APIUtilsTypes.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryOnboarding/RevenueRecoveryData.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryInvoices/RevenueRecoveryEntity.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryInvoices/RevenueRecoveryInvoices.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryInvoices/ShowRevenueRecovery.res
  src/hooks/AuthHooks.res
Labels: S-waiting-on-review, S-Recovery

#3064 fix: Updates for debit routing
  src/screens/Routing/ActiveRouting.res
  src/screens/Routing/DebitRouting/DebitRoutingConfigureModal.res
  src/screens/Routing/DebitRouting/DebitRoutingDeactivateModal.res
Labels: S-waiting-on-review, C-bug

#3094 fix: Debit routing configure modal
  src/screens/Routing/DebitRouting/DebitRoutingConfigureModal.res
Labels: C-ui

#3096 chore: displaying proper error message in case file is invalid in upl…
  src/IntelligentRouting/IntelligentRoutingScreens/IntelligentRoutingConfiguration/AnalyzeData.res
Labels: Closed

#3093 test: fix failing routing tests
  cypress/e2e/6-workflow/PaymentRouting.cy.js
  cypress/support/pages/workflow/paymentRouting/PaymentRouting.js
Labels: C-Testing

#3114 fix: debit routing duplication with multiple rules configuration
  src/screens/Routing/ActiveRouting.res
  src/screens/Routing/DebitRouting/DebitRoutingConfigureModal.res
Labels: C-bug

#3071 fix: overflow orgs case
  public/hyperswitch/icons/solid.svg
  src/entryPoints/HyperSwitchApp.res
  src/screens/Sidebar/OrgSidebar.res
Labels: S-waiting-on-review, C-bug

#3086 chore: removed recovery hard coded dummy keys
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryOnboarding/RevenueRecoveryData.res
  src/utils/LogicUtils.res
Labels: S-waiting-on-review, S-Recovery

#3120 feat: routing audit logs
  src/APIUtils/APIUtils.res
  src/APIUtils/APIUtilsTypes.res
  src/screens/Analytics/Logs/LogUtils/ApiDetailsComponent.res
  src/screens/Analytics/Logs/LogUtils/AuditLogUI.res
  src/screens/Analytics/Logs/LogUtils/LogTypes.res
  src/screens/Analytics/Logs/LogUtils/LogUtils.res
  src/screens/Analytics/Logs/PaymentLogs/PaymentLogs.res
Labels: S-waiting-on-review, C-chore

#3090 feat: new connector worldpay vantiv
  public/hyperswitch/Gateway/WORLDPAYVANTIV.svg
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review, C-feature

#3127 fix: swap tabs in payout routing
  src/screens/PayoutRouting/PayoutRoutingStack.res
Labels: C-bug

#3101 fix: horizontal scroll fix
  src/screens/ConfigurePMTs/paymentMethodList.res
  src/screens/Connectors/FraudAndRisk/FRMSelect.res
  src/screens/Connectors/PMAuthenticationProcessor/PMAuthenticationConnectorList.res
  src/screens/Connectors/PaymentProcessor/ConnectorList.res
  src/screens/Connectors/PayoutProcessor/PayoutProcessorList.res
  src/screens/Connectors/TaxProcessor/TaxProcessorList.res
  src/screens/Connectors/ThreeDsProcessors/ThreeDsConnectorList.res
  src/screens/Developer/APIKeys/KeyManagement.res
  src/screens/Developer/Webhooks/Webhooks.res
Labels: S-waiting-on-review, C-ui

#3131 fix: Custom daterange selector overlap with sidebar
  src/components/DateRangeCompareFields.res
  src/components/DateRangeField.res
  src/components/DateRangeHelper.res
  tailwind.config.js
Labels: S-waiting-on-review, C-ui

#3136 chore: recovery removed analytics feature flag
  config/config.toml
  src/RevenueRecovery/RevenueRecoveryApp/RevenueRecoverySidebarValues.res
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/ProductsSidebarValues.res
  src/entryPoints/SidebarValues.res
Labels: S-waiting-on-review, S-Recovery

#3124 chore: recovery analytics ui changes
  public/hyperswitch/icons/smart-retry.svg
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryAnalytics/RetriesComparision/RetriesComparisionAnalytics.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryAnalytics/RetriesComparision/RetriesComparisionAnalyticsUtils.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryAnalytics/RetryStrategies/RetryStrategiesAnalytics.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryAnalytics/RetryStrategies/RetryStrategiesAnalyticsUtils.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryAnalytics/RevenueRecoveryAnalytics.res
  src/components/Graphs/LineScatterGraph/LineScatterGraphTypes.res
  src/components/Graphs/LineScatterGraph/LineScatterGraphUtils.res
Labels: S-waiting-on-review, S-Recovery

#3134 test: add support for sso tests
  .github/workflows/cypress-test.yml
  cypress.config.js
  cypress/e2e/1-auth/auth.cy.js
  cypress/support/commands.js
  cypress/support/e2e.js
  cypress/support/pages/auth/SignInPage.js
  cypress/support/pages/homepage/HomePage.js
  package.json
Labels: C-Testing

#3156 fix: correct 3DS sankey data calculation and ui
  src/screens/NewAnalytics/NewAuthenticationAnalytics/NewAuthenticationAnalytics.res
  src/screens/NewAnalytics/NewAuthenticationAnalytics/NewAuthenticationAnalyticsHelper.res
  src/screens/NewAnalytics/NewAuthenticationAnalytics/SCAExemptionAnalytics/SCAExemptionAnalyticsUtils.res
Labels: S-waiting-on-review, S-analytics

#3103 fix: Validation of not allowing same merchant name in same organisation
  src/screens/OMPSwitch/MerchantSwitch.res
Labels: C-enhancement

#3155 fix: screen sizes calender filter positioning
  src/components/DateRangeField.res
  src/components/Filter.res
  tailwind.config.js
Labels: C-bug

#3165 fix: Debit routing present in Payout routing
  src/screens/Routing/ActiveRouting.res
  src/screens/Routing/RoutingUtils.res
Labels: S-waiting-on-review, C-bug

#3001 chore: OMP Hierarchy
  config/config.toml
  public/hyperswitch/icons/solid.svg
  src/Orchestration/OrchestrationApp.res
  src/components/EmptyPage.res
  src/components/UnauthorizedPage.res
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/Settings/OrganisationChart/OrganisationChart.res
  src/screens/Settings/OrganisationChart/OrganisationChartArrowUtils.res
  src/screens/Settings/OrganisationChart/OrganisationChartArrows.res
Labels: C-feature

#3181 chore: recovery graphs minor ui tweaks
  public/hyperswitch/icons/static-retry.svg
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryAnalytics/RetriesComparision/RetriesComparisionAnalytics.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryAnalytics/RetriesComparision/RetriesComparisionAnalyticsUtils.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryAnalytics/SmartRetryStrategy/SmartRetryStrategyAnalytics.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryAnalytics/SmartRetryStrategy/SmartRetryStrategyAnalyticsTypes.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryAnalytics/SmartRetryStrategy/SmartRetryStrategyAnalyticsUtils.res
  src/components/Graphs/LineScatterGraph/LineScatterGraphTypes.res
  src/components/Graphs/LineScatterGraph/LineScatterGraphUtils.res
  src/screens/NewAnalytics/InsightsTypes.res
Labels: S-waiting-on-review, S-Recovery

#3190 feat: 3ds-exemption-rules
  config/config.toml
  public/hyperswitch/module.js
  src/APIUtils/APIUtils.res
  src/APIUtils/APIUtilsTypes.res
  src/Orchestration/OrchestrationApp.res
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/SidebarValues.res
  src/libraries/Window.res
  src/screens/Routing/AdvancedRouting/AdvancedRouting.res
  src/screens/Routing/AdvancedRouting/AdvancedRoutingUIUtils.res
  src/screens/Routing/AdvancedRouting/AdvancedRoutingUtils.res
  src/screens/Routing/AdvancedRouting/RulePreviewer.res
  src/screens/Routing/RoutingTypes.res
  src/screens/Routing/RoutingUtils.res
  src/screens/ThreeDsExemptionFlow/HSwitchThreeDsExemption.res
  src/screens/ThreeDsExemptionFlow/ThreeDsExemptionUtils.res
Labels: S-waiting-on-review, C-feature

#3185 fix: acquirer config bug fixes
  src/APIUtils/APIUtils.res
  src/screens/Developer/PaymentSettings/AcquirerConfigSettings/AcquirerConfigEntity.res
  src/screens/Developer/PaymentSettings/AcquirerConfigSettings/AcquirerConfigSettings.res
  src/screens/Developer/PaymentSettings/AcquirerConfigSettings/AcquirerConfigTypes.res
  src/screens/Developer/PaymentSettings/AcquirerConfigSettings/AcquirerConfigUtils.res
Labels: S-waiting-on-review, C-feature

#3197 fix: theme colors for sidebar ompchart and border fix
  src/Recon/ReconScreens/ReconConfiguration/ConnectProcessors/ConnectProcessorsHelper.res
  src/Recon/ReconScreens/ReconOnboarding/ReconOnboardingHelper.res
  src/Recon/ReconScreens/ReconReports/ReconReportsHelper.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
Labels: C-ui

#3200 chore: recovery demo items changes
  public/hyperswitch/Gateway/STRIPEBILLING.svg
  src/APIUtils/APIUtils.res
  src/APIUtils/APIUtilsTypes.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RecoveryProcessorsPaymentProcessors/RecoveryOnboardingPayments.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingConnectorAuthKeys.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingConnectorsSummary.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingProcessorsUtils.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryOnboarding/RevenueRecoveryOnboardingUtils.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryAnalytics/AuthRateSummary/AuthRateSummary.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryAnalytics/SmartRetryStrategy/SmartRetryStrategyAnalytics.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryInvoices/RevenueRecoveryEntity.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryInvoices/RevenueRecoveryInvoices.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryInvoices/ShowRevenueRecovery.res
  src/hooks/AuthHooks.res
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review, S-Recovery
