Repository juspay/hyperswitch-control-center, pull requests merged in 2025-02, with the labels that each got.

#2189 test: fix failing cypress test cases
  cypress/e2e/1-auth/auth.cy.js
  cypress/e2e/3-operations/paymentOperationsColumns.cy.js
  cypress/e2e/4-connectors/connector.cy.js
  cypress/support/commands.js
  cypress/support/helper.js
Labels: C-Testing

#2181 chore: Navbar Redesign and OMP Movement
  config/config.toml
  public/hyperswitch/icons/solid.svg
  src/components/InlineEditInput.res
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/SidebarValues.res
  src/screens/Analytics/GlobalSearch/GlobalSearchBarHelper.res
  src/screens/OMPSwitch/MerchantSwitch.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/OMPSwitch/OrgSwitch.res
  src/screens/OMPSwitch/ProfileSwitch.res
  src/screens/Sidebar/OrgSidebar.res
  src/screens/Sidebar/Sidebar.res
  src/screens/Sidebar/SidebarSwitch.res
  tailwind.config.js
Labels: S-waiting-on-review, chore

#2187 chore: Modularity Default Home page
  config/config.toml
  public/hyperswitch/assets/DefaultHomeReconCard.svg
  public/hyperswitch/assets/DefaultHomeRecoveryCard.svg
  public/hyperswitch/assets/DefaultHomeTeam.svg
  public/hyperswitch/assets/DefaultHomeVaultCard.svg
  public/hyperswitch/icons/solid.svg
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/SidebarValues.res
  src/screens/DefaultHome/DefaultHome.res
  src/screens/DefaultHome/DefaultHomeTypes.res
  src/screens/DefaultHome/DefaultHomeUtils.res
  tailwind.config.js
Labels: chore

#2192 fix: User is logged when org and merchant switch occurs in product landing page
  src/utils/GlobalVars.res
Labels: bug

#2199 chore: Connector summary page
  src/fragments/ConnectorFragments/ConnectorAuthKeys/ConnectorAuthKeyUtils.res
  src/fragments/ConnectorFragments/ConnectorAuthKeys/ConnectorAuthKeys.res
  src/fragments/ConnectorFragments/ConnectorAuthKeys/ConnectorAuthKeysHelper.res
  src/fragments/ConnectorFragments/ConnectorPaymentMethodv2/ConnectorPaymentMethodV2.res
  src/fragments/ConnectorFragments/ConnectorPaymentMethodv2/ConnectorPaymentMethodV2Utils.res
  src/fragments/FragmentUtils.res
  src/screens/ConnectorV2/ConnectorSummary.res
  src/screens/ConnectorV2/PaymentProcessorSummary.res
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/PaymentProcessor/ConnectorHome.res
Labels: chore

#2203 chore: Vault connector integration
  src/Vault/VaultScreens/VaultConfiguration.res
  src/Vault/VaultScreens/VaultHome.res
  src/Vault/VaultScreens/VaultOnboarding.res
  src/entryPoints/ProductsSidebarValues.res
  src/entryPoints/VaultApp/VaultApp.res
  src/entryPoints/VaultApp/VaultSidebarValues.res
  src/fragments/ConnectorFragments/ConnectorAuthKeys/ConnectorAuthKeys.res
  src/fragments/ConnectorFragments/ConnectorAuthKeys/ConnectorAuthKeysHelper.res
  src/screens/ConnectorV2/ConnectorSummary.res
  src/screens/HSwitchUtils.res
Labels: chore

#2195 feat: Added Onboarding Vertical Step Indicator
  public/hyperswitch/icons/solid.svg
  src/RevenueRecoveryScreens/RevenueRecoveryHome/RevenueRecoveryHome.res
  src/RevenueRecoveryScreens/RevenueRecoveryHome/RevenueRecoveryHomeTypes.res
  src/RevenueRecoveryScreens/RevenueRecoveryHome/RevenueRecoveryHomeUtils.res
  src/Vault/VaultScreens/VaultConfiguration.res
  src/Vault/VaultScreens/VaultOnboarding.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/Provider/GlobalProvider.res
  src/entryPoints/Provider/ProviderTypes.res
  src/entryPoints/VaultApp/VaultApp.res
  src/fragments/VerticalStepIndicator/VerticalStepIndicator.res
  src/fragments/VerticalStepIndicator/VerticalStepIndicatorTypes.res
  src/fragments/VerticalStepIndicator/VerticalStepIndicatorUtils.res
  tailwind.config.js
Labels: S-waiting-on-review, C-feature

#2194 fix: Search text being sent in payload even when search field is cleared
  src/screens/Transaction/Order/Orders.res
Labels: S-waiting-on-review, C-bug

#2204 fix: Button issues fix in payment settings and auth select
  src/entryPoints/AuthModule/PreLoginModule/AuthSelect.res
  src/screens/Developer/PaymentSettings/PaymentSettings.res
  src/screens/Routing/ActiveRouting.res
Labels: S-waiting-on-review, bug

#2209 chore: payment method UI changes wrt to new design
  public/hyperswitch/icons/solid.svg
  src/fragments/ConnectorFragments/ConnectorPaymentMethodv2/ConnectorPaymentMethodV2.res
  src/fragments/ConnectorFragments/ConnectorPaymentMethodv2/ConnectorPaymentMethodV2Utils.res
  src/screens/ConnectorV2/PaymentProcessorSummary.res
  tailwind.config.js
Labels: chore

#2208 chore: table ui refactor
  public/hyperswitch/icons/solid.svg
  src/UIConifg/UIConfig.res
  src/components/Button.res
  src/components/LoadedTable.res
  src/components/Pagination.res
  src/components/Paginator.res
  src/components/Table.res
  src/components/Table.resi
  src/libraries/Clipboard.res
  src/screens/Helpers/HelperComponents.res
  src/screens/Settings/BusinessMapping/BusinessProfile.res
  src/screens/Transaction/Order/HSwitchOrderUtils.res
  src/screens/Transaction/Order/OrderEntity.res
  src/screens/UserManagement/UserRevamp/ListUsers.res
  tailwind.config.js
Labels: S-waiting-on-review, C-ui

#2220 fix: default homepage fixes
  src/screens/DefaultHome/DefaultHomeUtils.res
  src/screens/Home/HomeUtils.res
Labels: C-ui

#2225 chore: sidebar enhancement
  config/config.toml
  public/hyperswitch/icons/solid.svg
  src/context/ThemeProvider.res
  src/entryPoints/SidebarValues.res
  src/screens/Sidebar/Sidebar.res
  src/screens/Sidebar/SidebarTypes.res
  src/utils/LogicUtils.res
Labels: C-ui

#2233 feat: Added Pie charts
  src/components/Graphs/PieGraph/PieGraph.res
  src/components/Graphs/PieGraph/PieGraphTypes.res
  src/components/Graphs/PieGraph/PieGraphUtils.res
Labels: S-waiting-on-review, chore-analytcis, feature

#2223 feat: allow surcharge rule editing
  public/hyperswitch/icons/solid.svg
  src/screens/RoutingRevamp/AdvancedRoutingTypes.res
  src/screens/RoutingRevamp/AdvancedRoutingUIUtils.res
  src/screens/RoutingRevamp/AdvancedRoutingUtils.res
  src/screens/Surcharge/Surcharge.res
  src/screens/Surcharge/SurchargeUtils.res
Labels: S-waiting-on-review, core

#2237 fix: update privacy policy hyperlink on login page
  src/entryPoints/AuthModule/Common/CommonAuth.res
Labels: S-waiting-on-review, core

#2231 feat: global search amount filter
  src/screens/Analytics/GlobalSearch/GlobalSearchBarHelper.res
  src/screens/Analytics/GlobalSearch/GlobalSearchBarUtils.res
  src/screens/Analytics/GlobalSearch/GlobalSearchTypes.res
Labels: S-waiting-on-review, analytics

#2242 fix: payout details page display
  src/screens/Payouts/PayoutsEntity.res
  src/screens/Payouts/PayoutsList.res
  src/screens/Payouts/ShowPayout.res
Labels: S-waiting-on-review, C-bug

#2228 chore: granularity options for smart retry and refunds tab and minor bug fixes
  src/screens/NewAnalytics/NewAnalyticsUtils.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsProcessed/RefundsProcessed.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsSuccessRate/RefundsSuccessRate.res
  src/screens/NewAnalytics/PaymentAnalytics/NewPaymentAnalyticsUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRate.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessed.res
Labels: S-waiting-on-review, analytics

#2217 feat: Added vault connector flow pages
  public/hyperswitch/icons/solid.svg
  src/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryOnboarding/RevenueRecoveryOnboarding.res
  src/Vault/VaultScreens/VaultConfiguration.res
  src/Vault/VaultScreens/VaultConnectors/VaultConfiguration.res
  src/Vault/VaultScreens/VaultConnectors/VaultConnectorEntity.res
  src/Vault/VaultScreens/VaultConnectors/VaultProceesorReview.res
  src/Vault/VaultScreens/VaultConnectors/VaultProcessorCards.res
  src/Vault/VaultScreens/VaultConnectors/VaultProcessorList.res
  src/Vault/VaultScreens/VaultCustomersAndTokens/VaultCustomersAndTokens.res
  src/Vault/VaultScreens/VaultHome.res
  src/Vault/VaultScreens/VaultHomeTypes.res
  src/Vault/VaultScreens/VaultHomeUtils.res
  src/Vault/VaultScreens/VaultOnboarding.res
  src/components/Button.res
  src/components/LoadedTable.res
  src/components/Tabs.res
  src/entryPoints/VaultApp/VaultApp.res
  src/fragments/ConnectorFragments/ConnectorAuthKeys/ConnectorAuthKeyUtils.res
  src/fragments/ConnectorFragments/ConnectorAuthKeys/ConnectorAuthKeys.res
  src/fragments/ConnectorFragments/ConnectorAuthKeys/ConnectorAuthKeysHelper.res
  src/fragments/ConnectorFragments/ConnectorFragmentUtils.res
  src/fragments/ConnectorFragments/ConnectorHelperV2.res
  src/fragments/ConnectorFragments/ConnectorLabel/ConnectorLabelV2.res
  src/fragments/ConnectorFragments/ConnectorMetadataV2/ConnectorMetadataV2.res
  src/fragments/ConnectorFragments/ConnectorWebhookDetails/ConnectorWebhookDetails.res
  src/fragments/ConnectorFragments/ConnectorWebhookDetails/ConnectorWebhookPreview.res
  src/fragments/VerticalStepIndicator/VerticalStepIndicator.res
  src/screens/ConnectorV2/ConnectorSummary.res
  src/screens/ConnectorV2/PaymentProcessorSummary.res
  tailwind.config.js
Labels: S-waiting-on-review

#2245 feat: Addition of new connectors-Inespay
  public/hyperswitch/Gateway/INESPAY.svg
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review

#2246 chore: wasm update for Inespay
  public/hyperswitch/wasm/euclid_bg.wasm
Labels: S-waiting-on-review

#2250 chore: vault-fixes and enhancements
  public/hyperswitch/icons/solid.svg
  src/Vault/VaultScreens/VaultOnboarding.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/VaultApp/VaultSidebarValues.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/Sidebar/Sidebar.res
  src/utils/Modal.res
  tailwind.config.js
Labels: S-in-progress

#2256 fix: Added focus-visible on button and used hsl to generate colors
  src/UIConifg/UIConfig.res
  src/components/Button.res
  src/context/ThemeProvider.res
  src/entryPoints/AuthModule/TwoFaAuth/TwoFaAuth.res
  src/entryPoints/configs/HyperSwitchDefaultConfig.res
  src/screens/Settings/HSwitchProfile/HSwitchProfileSettings.res
  src/screens/Transaction/Order/OrderUIUtils.res
  src/screens/Transaction/Order/ShowOrder.res
  src/screens/Transaction/Refunds/ShowRefund.res
  src/screens/UserManagement/UserRevamp/ListRoles.res
  tailwind.config.js
Labels: S-waiting-on-review, C-feature, C-bug

#2264 chore: commenting unavailable api
  src/Vault/VaultScreens/VaultCustomersAndTokens/VaultCustomerSummary.res
  src/Vault/VaultScreens/VaultCustomersAndTokens/VaultPaymentMethodDetailsSidebar.res
Labels: S-waiting-on-review, core

#2268 chore: Sidebar collapse in products
  src/Vault/VaultScreens/VaultOnboarding.res
  src/entryPoints/HyperSwitchApp.res
  src/screens/Sidebar/Sidebar.res
  src/utils/Modal.res
Labels: S-waiting-on-review, C-ui

#2266 fix: global search amount filter special characters fix
  src/screens/Analytics/GlobalSearch/GlobalSearchBarUtils.res
Labels: S-waiting-on-review, analytics

#2273 fix: Fixed ui design bugs
  src/Vault/VaultScreens/VaultConnectors/VaultProcessorList.res
  src/components/Filter.res
  src/screens/Connectors/PaymentProcessor/Common/CommonConnectorHelper.res
  src/screens/Home/HomeUtils.res
  src/screens/Transaction/CommonFilters/AmountFilter/AmountFilter.res
  src/screens/Transaction/Order/ShowOrder.res
Labels: C-ui

#2248 feat: billing connector addition
  public/hyperswitch/Gateway/CHARGEBEE.svg
  src/RevenueRecoveryScreens/RecoveryProcessors/BillingProcessors/BillingProcessorsUtils.res
  src/Vault/VaultScreens/VaultConnectors/VaultProceesorReview.res
  src/screens/ConnectorV2/PaymentProcessorSummary.res
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUtils.res
  src/screens/Connectors/PaymentProcessor/ConnectorPreview.res
  src/screens/Connectors/PaymentProcessor/ConnectorUpdateAuthCreds.res
Labels: Recovery

#2281 fix: User role selection width adjustment in manage user modal
  src/entryPoints/EntryPointUtils.res
  src/screens/UserManagement/UserRevamp/ManageUserModal.res
Labels: S-waiting-on-review, C-bug

#2279 chore: novalnet live
  src/screens/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review, C-feature

#2287 fix: table ui fixes
  src/entryPoints/HyperSwitchApp.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/Disputes/DisputeTableEntity.res
  src/screens/Transaction/Order/HSwitchOrderUtils.res
Labels: C-ui

#2272 chore: enable cancel edit pmt
  public/hyperswitch/icons/solid.svg
  src/RevenueRecoveryScreens/RevenueRecoveryOverview/RevenueRecoveryEntity.res
  src/Vault/VaultScreens/VaultConnectors/VaultProceesorReview.res
  src/Vault/VaultScreens/VaultOnboarding.res
  src/entryPoints/VaultApp/VaultApp.res
  src/fragments/ConnectorFragments/ConnectorAuthKeys/ConnectorAuthKeys.res
  src/fragments/ConnectorFragments/ConnectorFragmentUtils.res
  src/fragments/ConnectorFragments/ConnectorHelperV2.res
  src/fragments/ConnectorFragments/ConnectorLabel/ConnectorLabelV2.res
  src/fragments/ConnectorFragments/ConnectorMetadataV2/ConnectorMetadataV2.res
  src/fragments/ConnectorFragments/ConnectorPaymentMethodv2/ConnectorPaymentMethodV3.res
  src/fragments/ConnectorFragments/ConnectorPaymentMethodv2/ConnectorPaymentMethodV3Utils.res
  src/fragments/ConnectorFragments/ConnectorPaymentMethodv2/Sections/Card.res
  src/fragments/ConnectorFragments/ConnectorPaymentMethodv2/Sections/OtherPaymentMethod.res
  src/fragments/ConnectorFragments/ConnectorPaymentMethodv2/Sections/SectionHelper.res
  src/fragments/ConnectorFragments/ConnectorWebhookDetails/ConnectorWebhookDetails.res
  src/screens/ConnectorV2/ConnectorSummary.res
  src/screens/ConnectorV2/PaymentProcessorSummary.res
  src/screens/Connectors/PaymentProcessor/ConnectorHome.res
Labels: S-waiting-on-review

#2290 feat: added new connector coingate
  public/hyperswitch/Gateway/COINGATE.svg
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review, C-feature

#2291 feat: wasm update for coingate
  public/hyperswitch/wasm/euclid_bg.wasm
Labels: S-waiting-on-review, C-feature

#2292 chore: add pmt in vault onboarding
  src/Vault/VaultScreens/VaultHomeUtils.res
  src/Vault/VaultScreens/VaultOnboarding.res
Labels: S-waiting-on-review

#2294 fix: Overflowing merchant profile names in dropdowns
  src/screens/OMPSwitch/OMPSwitchHelper.res
Labels: S-waiting-on-review, C-ui

#2297 chore: Addition of card discovery filter in payment ops
  src/screens/Transaction/Order/OrderUIUtils.res
Labels: S-waiting-on-review, C-feature

#2288 feat: recovery payment connector
  src/RevenueRecoveryScreens/RecoveryProcessors/RecoveryConnectorEntity.res
  src/RevenueRecoveryScreens/RecoveryProcessors/RecoveryConnectorHome.res
  src/RevenueRecoveryScreens/RecoveryProcessors/RecoveryConnectorList.res
  src/RevenueRecoveryScreens/RecoveryProcessors/RecoveryConnectorTypes.res
  src/RevenueRecoveryScreens/RecoveryProcessors/RecoveryConnectorUtils.res
  src/RevenueRecoveryScreens/RecoveryProcessors/RecoveryProceesorReview.res
  src/RevenueRecoveryScreens/RecoveryProcessors/RecoveryProcessorCards.res
  src/container/RecoveryConnectorContainer.res
  src/entryPoints/RevenueRecoveryApp/RevenueRecoveryApp.res
Labels: S-waiting-on-review, Recovery

#2310 test: fix failing connector test
  cypress/e2e/4-connectors/connector.cy.js
Labels: C-Testing

#2321 chore: Merchant search in dropdown
  src/components/SearchInput.res
  src/components/SelectBox.res
  src/screens/OMPSwitch/MerchantSwitch.res
Labels: S-waiting-on-review, C-feature

#2324 fix: recon icon display
  public/hyperswitch/icons/solid.svg
Labels: S-waiting-on-review, C-ui

#2314 chore: recovery new folder structure
  src/RevenueRecovery/RevenueRecoveryApp/RevenueRecoveryApp.res
  src/RevenueRecovery/RevenueRecoveryApp/RevenueRecoverySidebarValues.res
  src/RevenueRecovery/RevenueRecoveryContainer/RecoveryConnectorContainer.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RecoveryConnectorEntity.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RecoveryConnectorHome.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RecoveryConnectorList.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RecoveryConnectorTypes.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RecoveryConnectorUtils.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RecoveryProceesorReview.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RecoveryProcessorCards.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingProcessorsUtils.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/RevenueRecoveryBillingProcessors.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryOnboarding/RevenueRecoveryOnboarding.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryOnboarding/RevenueRecoveryOnboardingTypes.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryOnboarding/RevenueRecoveryOnboardingUtils.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryOnboarding/RevenueRecoveryOnboardingLanding.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryOverview/RecoveryOverviewHelper.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryOverview/RevenueRecoveryEntity.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryOverview/RevenueRecoveryOrderTypes.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryOverview/RevenueRecoveryOrderUtils.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryOverview/RevenueRecoveryOverview.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryOverview/RevenueRecoveryTypes.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryOverview/ShowRevenueRecovery.res
Labels: Recovery

#2334 fix: Responsive merchant and profile dropdowns
  src/components/Navbar.res
  src/entryPoints/HyperSwitchApp.res
  src/screens/Helpers/CardUtils.res
  src/screens/OMPSwitch/MerchantSwitch.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/OMPSwitch/ProfileSwitch.res
Labels: S-waiting-on-review, C-bug

#2337 fix: maintaining org sidebar list order
  src/screens/Sidebar/OrgSidebar.res
  src/screens/UserManagement/UserRevamp/ListUsers.res
Labels: S-waiting-on-review, C-feature

#2341 feat: Alt payment methods
  config/config.toml
  public/hyperswitch/AlternatePaymentMethods/AlternatePaymentMethodsOnboarding.svg
  public/hyperswitch/icons/solid.svg
  src/AlternatePaymentMethods/AlternatePaymentMethodsHome.res
  src/AlternatePaymentMethods/AlternatePaymentMethodsOnboarding.res
  src/entryPoints/AlternatePaymentMethods/AlternatePaymentMethodsApp.res
  src/entryPoints/AlternatePaymentMethods/AlternatePaymentMethodsSidebarValues.res
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/ProductTypes.res
  src/entryPoints/ProductUtils.res
  src/entryPoints/ProductsSidebarValues.res
  src/entryPoints/SidebarValues.res
Labels: S-waiting-on-review, core
