Repository juspay/hyperswitch-control-center, pull requests merged in 2025-08, with the labels that each got.

#3367 feat: Payment interface modifications for v1 and v2
  src/Interface/PaymentInterface/PaymentInterfaceTypes/PaymentInterfaceTypes.res
  src/Interface/PaymentInterface/PaymentInterfaceTypes/PaymentInterfaceTypesV2.res
  src/Interface/PaymentInterface/PaymentInterfaceUtils/PaymentInterfaceUtils.res
  src/Interface/PaymentInterface/PaymentInterfaceUtils/PaymentInterfaceUtilsV1.res
  src/Interface/PaymentInterface/PaymentInterfaceUtils/PaymentInterfaceUtilsV2.res
  src/Interface/PaymentInterface/PaymentListInterface.res
  src/Interface/PaymentInterface/PaymentsInterface.res
  src/screens/Transaction/Order/HSwitchOrderUtils.res
  src/screens/Transaction/Order/OrderEntity.res
  src/screens/Transaction/Order/OrderRefundForm.res
  src/screens/Transaction/Order/OrderTypes.res
  src/screens/Transaction/Order/OrderUIUtils.res
  src/screens/Transaction/Order/Orders.res
  src/screens/Transaction/Order/OrdersHook.res
  src/screens/Transaction/Order/ShowOrder.res
  src/screens/Transaction/Refunds/ShowRefund.res
Labels: S-waiting-on-review, S-orchestration-v2

#3395 feat: recovery prod changes
  public/hyperswitch/Gateway/CUSTOMBILLING.svg
  src/APIUtils/APIUtils.res
  src/APIUtils/APIUtilsTypes.res
  src/Recon/ReconScreens/ReconConfiguration/Final/Final.res
  src/RevenueRecovery/RevenueRecoveryApp/RevenueRecoverySidebarValues.res
  src/RevenueRecovery/RevenueRecoveryContainer/RecoveryConnectorContainerUtils.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RecoveryProcessorsPaymentProcessors/RecoveryConnectorUtils.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RecoveryProcessorsPaymentProcessors/RecoveryOnboardingPayments.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingConnectorAuthKeys.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingConnectorsSummary.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingProcessorsConfigureRetry.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingProcessorsConnectProcessor.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingProcessorsReviewDetails.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingProcessorsSetUp.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingProcessorsUtils.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/RecoveryOnboardingBilling.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryOnboarding/RevenueRecoveryData.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryOnboarding/RevenueRecoveryOnboarding.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryOnboarding/RevenueRecoveryOnboardingLanding.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryOnboarding/RevenueRecoveryOnboardingTypes.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryOnboarding/RevenueRecoveryOnboardingUtils.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryAnalytics/AuthRateSummary/AuthRateSummary.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryAnalytics/RetriesComparision/RetriesComparisionAnalytics.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryAnalytics/RetryStrategies/RetryStrategiesAnalytics.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryAnalytics/SmartRetryStrategy/SmartRetryStrategyAnalytics.res
  src/components/UnauthorizedPage.res
  src/entryPoints/AuthModule/ProductSelection/ProductSelectionProvider.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/ProductUtils.res
  src/entryPoints/SidebarValues.res
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUtils.res
  src/screens/DefaultHome/DefaultHomeUtils.res
  src/screens/Developer/APIKeys/KeyManagement.res
  src/screens/NewAnalytics/InsightsHelper.res
Labels: S-waiting-on-review, S-Recovery

#3415 chore: api keys support for v2 and for vault
  public/hyperswitch/icons/solid.svg
  src/APIUtils/APIUtils.res
  src/Orchestration/OrchestrationApp.res
  src/Vault/VaultApp/VaultApp.res
  src/Vault/VaultApp/VaultSidebarValues.res
  src/components/BottomModal.res
  src/screens/Developer/APIKeys/DeveloperUtils.res
  src/screens/Developer/APIKeys/KeyManagement.res
  src/screens/Developer/APIKeys/KeyManagementHelper.res
  src/screens/Developer/APIKeys/PublishableAndHashKeySection.res
Labels: S-waiting-on-review, S-orchestration-v2

#3439 feat: add new connector `CheckBook`
  public/hyperswitch/Gateway/CHECKBOOK.svg
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review, C-feature

#3440 chore: rename data assistant to pulse ai and add mixpanel events
  public/hyperswitch/icons/solid.svg
  src/entryPoints/HyperSwitchApp.res
  src/screens/ChatBot/ChatBot.res
Labels: S-waiting-on-review, C-enhancement

#3442 feat: enable refund reason field for `adyen` connector
  src/screens/ChatBot/ChatBot.res
  src/screens/Transaction/Order/HSwitchOrderUtils.res
  src/screens/Transaction/Order/OrderRefundForm.res
Labels: S-waiting-on-review, C-feature, C-enhancement

#3462 feat: add rule wise stacked bar graphs in summary
  src/ReconEngine/ReconEngineScreens/ReconEngineOverview/ReconEngineOverview.res
  src/ReconEngine/ReconEngineScreens/ReconEngineOverview/ReconEngineOverviewDetails/ReconEngineOverviewDetails.res
  src/ReconEngine/ReconEngineScreens/ReconEngineOverview/ReconEngineOverviewSummary/ReconEngineOverviewSummary.res
  src/ReconEngine/ReconEngineScreens/ReconEngineOverview/ReconEngineOverviewSummary/ReconEngineOverviewSummaryComponents/ReconEngineOverviewSummaryStackedBarGraphs.res
  src/ReconEngine/ReconEngineScreens/ReconEngineOverview/ReconEngineOverviewSummary/ReconEngineOverviewSummaryUtils.res
  src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/EntriesTableEntity.res
  src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/ReconEngineTransactionsHelper.res
  src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/ReconEngineTransactionsTypes.res
  src/ReconEngine/ReconEngineScreens/ReconEngineTransactions/TransactionsTableEntity.res
  src/components/Tabs.res
Labels: S-waiting-on-review, C-feature, S-Recon

#3469 chore: remove sync for terminal payment intent status
  src/screens/Transaction/Order/HSwitchOrderUtils.res
  src/screens/Transaction/Order/ShowOrder.res
Labels: S-waiting-on-review, C-chore

#3483 feat: add new connector `Affirm`
  public/hyperswitch/Gateway/AFFIRM.svg
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review, C-feature

#3490 fix: sample analytics group by bugfix
  src/screens/NewAnalytics/Insights/PaymentAnalytics/FailedPaymentsDistribution/FailedPaymentsDistribution.res
  src/screens/NewAnalytics/Insights/PaymentAnalytics/InsightsPaymentAnalyticsUtils.res
  src/screens/NewAnalytics/Insights/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistribution.res
  src/screens/NewAnalytics/Insights/SmartRetryAnalytics/FailureSmartRetryDistribution/FailureSmartRetryDistribution.res
  src/screens/NewAnalytics/Insights/SmartRetryAnalytics/SuccessfulSmartRetryDistribution/SuccessfulSmartRetryDistribution.res
Labels: S-analytics
