Repository juspay/hyperswitch-control-center, pull requests merged in 2025-04, with the labels that each got.

#2721 chore: updating graph
  cypress/support/pages/homepage/HomePage.js
  public/common/lottie-files/spinner.json
  src/IntelligentRoutingScreens/IntelligentRoutingAnalytics.res
  src/IntelligentRoutingScreens/IntelligentRoutingConfiguration.res
  src/IntelligentRoutingScreens/IntelligentRoutingHelper.res
  src/components/Graphs/LineAndColumn/LineAndColumnGraphTypes.res
  src/components/Graphs/LineAndColumn/LineAndColumnGraphUtils.res
Labels: Closed

#2732 fix: connector metadata
  public/hyperswitch/wasm/euclid_bg.wasm
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUtils.res
  src/screens/Connectors/PaymentProcessor/ConnectorMetaData/ApplePay/ApplePayManualFlow.res
  src/screens/Connectors/PaymentProcessor/ConnectorPaymentMethod.res
  src/screens/Connectors/PayoutProcessor/PayoutProcessorPaymentMethod.res
  src/screens/SetupAccount/HSwitchSetupAccountUtils.res
Labels: C-bug

#2720 feat: debit routing toggle
  config/config.toml
  src/entryPoints/FeatureFlagUtils.res
  src/screens/Developer/PaymentSettings/PaymentSettings.res
  src/screens/Developer/PaymentSettings/PaymentSettingsListEntity.res
  src/screens/Settings/BusinessMapping/BusinessMappingEntity.res
  src/screens/Settings/HSwitchSettingTypes.res
  src/screens/Settings/MerchantAccountUtils.res
  src/utils/Mappers/BusinessProfileMapper.res
Labels: S-waiting-on-review, C-feature

#2726 chore: removed default allowed auth methods in google pay
  src/screens/Connectors/PaymentProcessor/ConnectorMetaData/GooglePay/GooglePayIntegration.res
  src/screens/Connectors/PaymentProcessor/ConnectorMetaData/GooglePay/GooglePayUtils.res
Labels: S-waiting-on-review, C-enhancement

#2758 chore: restructuring intelligent routing files
  src/IntelligentRouting/IntelligentRoutingApp/IntelligentRoutingApp.res
  src/IntelligentRouting/IntelligentRoutingApp/IntelligentRoutingSidebarValues.res
  src/IntelligentRouting/IntelligentRoutingScreens/IntelligentRoutingAnalytics.res
  src/IntelligentRouting/IntelligentRoutingScreens/IntelligentRoutingConfiguration.res
  src/IntelligentRouting/IntelligentRoutingScreens/IntelligentRoutingHelper.res
  src/IntelligentRouting/IntelligentRoutingScreens/IntelligentRoutingHome.res
  src/IntelligentRouting/IntelligentRoutingScreens/IntelligentRoutingReviewFieldsEntity.res
  src/IntelligentRouting/IntelligentRoutingScreens/IntelligentRoutingStatsResponse.res
  src/IntelligentRouting/IntelligentRoutingScreens/IntelligentRoutingTransactionsEntity.res
  src/IntelligentRouting/IntelligentRoutingScreens/IntelligentRoutingTypes.res
  src/IntelligentRouting/IntelligentRoutingScreens/IntelligentRoutingUtils.res
  src/components/InputFields.resi
  src/screens/Analytics/HSAnalyticsUtils.res
Labels: S-waiting-on-review, S-modularity

#2778 Revert "refactor: hyperswitch app refactor"
  src/Orchestrator/OrchestratorApp.res
  src/entryPoints/HyperSwitchApp.res
Labels: S-conventions-not-followed

#2771 fix: Toast notification redesign
  public/hyperswitch/icons/solid.svg
  src/components/ToastContainer.res
  tailwind.config.js
Labels: S-waiting-on-review, C-ui, S-adhoc

#2770 chore: number type input for connector metadata
  src/screens/Connectors/PaymentProcessor/Common/CommonConnectorHelper.res
  src/screens/Connectors/PaymentProcessor/Common/CommonConnectorTypes.res
  src/screens/Connectors/PaymentProcessor/Common/CommonConnectorUtils.res
  src/screens/Connectors/PaymentProcessor/ConnectorMetaData/ConnectorMetaDataUtils.res
Labels: C-chore, S-adhoc

#2776 fix: disabled the recon onboarding input fields
  src/Recon/ReconScreens/ReconConfiguration/ConnectProcessors/ConnectProcessorsHelper.res
  src/Recon/ReconScreens/ReconConfiguration/ConnectProcessors/ConnectProcessorsUtils.res
Labels: S-waiting-on-review, C-bug, S-Recon, C-enhancement

#2780 fix: hypersense product name change to cost observability
  src/Hypersense/HypersenseScreens/HypersenseConfiguration.res
  src/Hypersense/HypersenseScreens/HypersenseHome.res
  src/entryPoints/AuthModule/ProductSelection/ProductSelectionProvider.res
  src/entryPoints/ProductUtils.res
Labels: S-adhoc

#2783 Chore: Remove apm from product types
  src/entryPoints/ProductTypes.res
  src/entryPoints/ProductUtils.res
  src/entryPoints/SidebarValues.res
  src/screens/PayoutRouting/PayoutHistoryTableEntity.res
  src/screens/Routing/HistoryEntity.res
Labels: S-conventions-not-followed, S-waiting-on-review

#2773 test: Add workflow tests
  config/config.toml
  cypress/e2e/6-workflow/PaymentRouting.cy.js
  cypress/support/commands.js
  cypress/support/pages/homepage/HomePage.js
  cypress/support/pages/workflow/paymentRouting/VolumeBasedConfiguration.js
Labels: C-Testing

#2786 chore: made charts responsive
  src/IntelligentRouting/IntelligentRoutingScreens/IntelligentRoutingAnalytics.res
  src/IntelligentRouting/IntelligentRoutingScreens/IntelligentRoutingHelper.res
  src/components/Graphs/LineAndColumn/LineAndColumnGraphTypes.res
  src/components/Graphs/LineAndColumn/LineAndColumnGraphUtils.res
  src/components/Graphs/LineGraph/LineGraphTypes.res
  src/components/Graphs/LineGraph/LineGraphUtils.res
  src/components/Graphs/PieGraph/PieGraphUtils.res
  src/context/MatchMedia.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsProcessed/RefundsProcessedUtils.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsSuccessRate/RefundsSuccessRateUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRateUtils.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessedUtils.res
  tailwind.config.js
Labels: S-waiting-on-review

#2801 chore: show global search bar only for orchestrator
  src/entryPoints/HyperSwitchApp.res
Labels: S-waiting-on-review, C-chore

#2795 fix: threeds app url validation
  src/screens/Settings/HSwitchSettingTypes.res
  src/screens/Settings/MerchantAccountUtils.res
Labels: S-waiting-on-review, C-bug

#2798 chore: recovery product name change
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingConnectorsSummary.res
  src/entryPoints/ProductUtils.res
  src/screens/DefaultHome/DefaultHomeUtils.res
Labels: S-waiting-on-review, S-Recovery

#2652 feat: google pay decryption flow for cybersource
  config/config.toml
  public/hyperswitch/icons/solid.svg
  public/hyperswitch/wasm/euclid_bg.wasm
  src/entryPoints/FeatureFlagUtils.res
  src/screens/Connectors/PaymentProcessor/ConnectorMetaData/ApplePay/ApplePayIntegration.res
  src/screens/Connectors/PaymentProcessor/ConnectorMetaData/GooglePay/GPayFlow/GPayDirectFlow.res
  src/screens/Connectors/PaymentProcessor/ConnectorMetaData/GooglePay/GPayFlow/GPayFlow.res
  src/screens/Connectors/PaymentProcessor/ConnectorMetaData/GooglePay/GPayFlow/GPayFlowHelper.res
  src/screens/Connectors/PaymentProcessor/ConnectorMetaData/GooglePay/GPayFlow/GPayFlowTypes.res
  src/screens/Connectors/PaymentProcessor/ConnectorMetaData/GooglePay/GPayFlow/GPayFlowUtils.res
  src/screens/Connectors/PaymentProcessor/ConnectorMetaData/GooglePay/GPayFlow/GPayPaymentGatewayFlow.res
  src/screens/Connectors/PaymentProcessor/ConnectorMetaData/GooglePay/GooglePayFlow.res
  src/screens/Connectors/PaymentProcessor/ConnectorMetaData/GooglePay/GooglePayIntegration.res
  src/screens/Connectors/PaymentProcessor/ConnectorMetaData/GooglePay/GooglePayUtils.res
  src/screens/Connectors/PaymentProcessor/ConnectorMetaData/GooglePay/GooglePayZen.res
  src/screens/Connectors/PaymentProcessor/PaymentMethodAdditionalDetails/AdditionalDetailsSidebarHelper.res
  src/utils/LogicUtils.res
Labels: S-waiting-on-review, C-feature

#2731 feat: Field addition for create refund for coingate connector
  src/screens/Transaction/Order/HSwitchOrderUtils.res
  src/screens/Transaction/Order/OrderRefundForm.res
Labels: S-waiting-on-review, C-feature

#2805 fix: show payment details issue on new tab open
  src/screens/Sidebar/OrgSidebar.res
Labels: C-bug

#2794 fix: pci security issues in docker and cypress
  .github/workflows/cypress-test.yml
  Dockerfile
  cypress.config.js
  cypress/e2e/4-connectors/connector.cy.js
  public/common/iframe.html
  public/common/shadow.html
  src/server/config.mjs
Labels: S-waiting-on-review, C-enhancement

#2811 chore: added titles to the table instead of empty string
  src/IntelligentRouting/IntelligentRoutingScreens/IntelligentRoutingAnalytics.res
  src/Vault/VaultContainer/VaultContainer.res
  src/Vault/VaultScreens/VaultCustomersAndTokens/VaultCustomerSummary.res
  src/Vault/VaultScreens/VaultCustomersAndTokens/VaultCustomersAndTokens.res
  src/Vault/VaultScreens/VaultCustomersAndTokens/VaultPaymentMethodDetailsSidebar.res
  src/components/HSwitchSingleStatTableWidget.res
  src/screens/Analytics/ErrorReasons.res
  src/screens/Analytics/PerformanceMonitor/TablePerformance/TablePerformance.res
  src/screens/ConfigurePMTs/paymentMethodList.res
  src/screens/Connectors/PaymentProcessor/ConnectorAccountDetailsHelper.res
  src/screens/Connectors/PaymentProcessor/ConnectorMetaData/GooglePay/GPayFlow/GPayFlow.res
  src/screens/Connectors/PaymentProcessor/ConnectorMetaData/GooglePay/GPayFlow/GPayFlowUtils.res
  src/screens/Connectors/PaymentProcessor/ConnectorMetaData/GooglePay/GooglePayIntegration.res
  src/screens/Customers/Customers.res
  src/screens/Developer/APIKeys/KeyManagement.res
  src/screens/Developer/PaymentSettings/PaymentSettingsList.res
  src/screens/NewAnalytics/NewRefundsAnalytics/FailedRefundsDistribution/FailedRefundsDistribution.res
  src/screens/NewAnalytics/NewRefundsAnalytics/FailureReasonsRefunds/FailureReasonsRefunds.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsProcessed/RefundsProcessed.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsReasons/RefundsReasons.res
  src/screens/NewAnalytics/NewRefundsAnalytics/SuccessfulRefundsDistribution/SuccessfulRefundsDistribution.res
  src/screens/NewAnalytics/PaymentAnalytics/FailedPaymentsDistribution/FailedPaymentsDistribution.res
  src/screens/NewAnalytics/PaymentAnalytics/FailureReasonsPayments/FailureReasonsPayments.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessed.res
  src/screens/NewAnalytics/PaymentAnalytics/SuccessfulPaymentsDistribution/SuccessfulPaymentsDistribution.res
  src/screens/NewAnalytics/SmartRetryAnalytics/FailureSmartRetryDistribution/FailureSmartRetryDistribution.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessed.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SuccessfulSmartRetryDistribution/SuccessfulSmartRetryDistribution.res
  src/utils/LogicUtils.res
Labels: C-chore

#2683 chore: product type added in get production api payload
  src/IntelligentRouting/IntelligentRoutingScreens/IntelligentRoutingAnalytics.res
  src/Recon/ReconScreens/ReconOnboarding/ReconOnboardingHelper.res
  src/Recon/ReconScreens/ReconReports/ReconReports.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/SidebarValues.res
  src/screens/Home/ProdIntent/ProdIntentForm.res
  src/screens/Home/ProdIntent/ProdVerifyModal.res
Labels: S-waiting-on-review

#2793 chore: login and signup page view count
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/HyperSwitchEntry.res
Labels: S-waiting-on-review, C-chore

#2809 fix: safari dashboard ui fixes
  src/UIConifg/UIConfig.res
  src/components/DateRangeField.res
Labels: S-waiting-on-review, C-chore

#2818 fix: empty page issue on omp dropdown item click
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/Sidebar/OrgSidebar.res
Labels: C-bug

#2804 fix: Text overlap in Configure PMTs & Remove profile id and name
  src/screens/ConfigurePMTs/PaymentMethodConfig.res
  src/screens/ConfigurePMTs/PaymentMethodEntity.res
  src/screens/Connectors/PMAuthenticationProcessor/PMAuthenticationTableEntity.res
  src/screens/Connectors/PaymentProcessor/ConnectorTableUtils.res
  src/screens/Connectors/PayoutProcessor/PayoutProcessorTableEntity.res
  src/screens/Connectors/TaxProcessor/TaxProcessorTableEntity.res
  src/screens/Connectors/ThreeDsProcessors/ThreeDsTableEntity.res
  src/screens/Helpers/HelperComponents.res
  src/screens/PayoutRouting/PayoutHistoryTableEntity.res
  src/screens/Routing/HistoryEntity.res
  src/screens/Routing/RoutingTypes.res
Labels: S-waiting-on-review, C-bug, C-ui

#2705 feat: recon onboarding api integration
  src/Recon/ReconApp/ReconApp.res
  src/Recon/ReconApp/ReconSidebarValues.res
  src/Recon/ReconContainer/ReconConfigurationContainer.res
  src/Recon/ReconContainer/ReconOnBoardingContainer.res
  src/Recon/ReconContainer/ReconReportsContainer.res
  src/Recon/ReconScreens/ReconConfiguration/ConnectProcessors/ConnectProcessors.res
  src/Recon/ReconScreens/ReconConfiguration/ConnectProcessors/ConnectProcessorsHelper.res
  src/Recon/ReconScreens/ReconConfiguration/Final/Final.res
  src/Recon/ReconScreens/ReconConfiguration/OrderDataConnection/OrderDataConnection.res
  src/Recon/ReconScreens/ReconConfiguration/ReconConfiguration.res
  src/Recon/ReconScreens/ReconConfiguration/ReconConfigurationTypes.res
  src/Recon/ReconScreens/ReconConfiguration/ReconConfigurationUtils.res
  src/Recon/ReconScreens/ReconOnboarding/ReconOnboarding.res
  src/Recon/ReconScreens/ReconOnboarding/ReconOnboardingHelper.res
  src/Recon/ReconScreens/ReconReports/ReconReports.res
  src/Recon/ReconScreens/ReconReports/ReconReportsList.res
  src/Recon/ReconScreens/ReconReports/ReportStatus.res
  src/Recon/ReconScreens/ReconReports/ReportsTableEntity.res
  src/Recon/ReconScreens/ReconReports/ShowReconExceptionReport.res
Labels: S-waiting-on-review, C-feature, S-Recon, S-modularity

#2817 fix: overlap sidebar
  src/screens/Sidebar/Sidebar.res
Labels: S-waiting-on-review, C-ui

#2833 fix: refunds disable/enable in operations
  src/screens/Transaction/Order/OrderRefundForm.res
Labels: C-bug

#2826 chore: recon navigation and url changes
  src/Recon/ReconApp/ReconApp.res
  src/Recon/ReconApp/ReconSidebarValues.res
  src/Recon/ReconContainer/ReconConfigurationContainer.res
  src/Recon/ReconContainer/ReconOverviewContainer.res
  src/Recon/ReconScreens/ReconConfiguration/Final/Final.res
  src/Recon/ReconScreens/ReconConfiguration/ReconConfiguration.res
  src/Recon/ReconScreens/ReconOnboarding/ReconOnboardingHelper.res
  src/entryPoints/ProductUtils.res
Labels: S-waiting-on-review, C-chore, S-Recon, S-modularity

#2839 fix: analytics group by currency NA row fix
  src/screens/Analytics/PaymentsAnalytics/PaymentAnalytics.res
  src/screens/Analytics/RefundsAnalytics/RefundsAnalytics.res
Labels: S-waiting-on-review, S-analytics

#2840 fix: amount available to refund in payments page initiate refund
  src/screens/Transaction/Order/ShowOrder.res
Labels: S-waiting-on-review, C-bug

#2825 fix: Logs in payments details
  src/screens/Analytics/Logs/LogUtils/AuditLogUI.res
Labels: S-waiting-on-review, C-bug

#2842 fix: wrong metrics in the operations cards
  cypress/e2e/3-operations/paymentOperations.cy.js
  src/screens/HSwitchRemoteFilter.res
Labels: Closed

#2843 chore: changed merchant level api endpoint to profile level
  src/APIUtils/APIUtils.res
  src/screens/Developer/Webhooks/Webhooks.res
Labels: S-waiting-on-review

#2849 fix: connector metadata default
  src/screens/Connectors/ConnectorUtils.res
Labels: C-bug

#2850 fix: webhooks request response data interchange fix
  src/screens/Analytics/Logs/LogUtils/ApiDetailsComponent.res
  src/screens/Analytics/Logs/LogUtils/AuditLogUI.res
  src/screens/Analytics/Logs/LogUtils/LogTypes.res
Labels: S-waiting-on-review

#2854 chore: added time selection for payments and reports
  src/components/TimeInput.res
  src/screens/Analytics/Logs/LogUtils/AuditLogUI.res
  src/screens/GenerateReports/DownloadReportModal.res
  src/screens/Transaction/Order/OrderUIUtils.res
Labels: S-waiting-on-review, C-chore

#2859 chore: added country currency mapping with icons
  src/libraries/ReactHyperJs.res
  src/screens/Home/HomeUtils.res
  src/screens/SDKPayment/SDKPage.res
Labels: S-waiting-on-review

#2872 fix: rename webhooks request heading to event data
  src/screens/Analytics/Logs/LogUtils/LogTypes.res
Labels: S-waiting-on-review

#2875 chore: remove warnings
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingConnectorsSummary.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/RecoveryOnboardingBilling.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryOverview/RevenueRecoveryEntity.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryOverview/RevenueRecoveryOverview.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryOverview/ShowRevenueRecovery.res
  src/components/TableUtils.res
  src/fragments/ConnectorFragments/ConnectorHelperV2.res
  src/screens/Analytics/PaymentsAnalytics/PaymentAnalytics.res
  src/screens/Connectors/PaymentProcessor/ConnectorPaymentMethod.res
  src/screens/Connectors/PayoutProcessor/PayoutProcessorPaymentMethod.res
  src/screens/Home/ProdIntent/ProdIntentForm.res
  src/screens/Home/ProdIntent/ProdVerifyModal.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/SDKPayment/SDKPage.res
  src/screens/SDKPayment/WebSDK.res
Labels: S-waiting-on-review

#2877 chore: configurartion record type
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RecoveryProcessorsPaymentProcessors/RecoveryConnectorHome.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RecoveryProcessorsPaymentProcessors/RecoveryOnboardingPayments.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingConnectorsSummary.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/RecoveryOnboardingBilling.res
  src/Vault/VaultScreens/VaultOnboarding.res
  src/screens/ConnectorV2/PaymentProcessorSummary.res
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUtils.res
  src/screens/Connectors/PMAuthenticationProcessor/PMAuthenticationHome.res
  src/screens/Connectors/PaymentProcessor/ConnectorAccountDetails.res
  src/screens/Connectors/PaymentProcessor/ConnectorPreview.res
  src/screens/Connectors/PaymentProcessor/ConnectorUpdateAuthCreds.res
  src/screens/Connectors/PayoutProcessor/PayoutProcessorAccountDetails.res
  src/screens/Connectors/TaxProcessor/TaxProcessorHome.res
  src/screens/Connectors/ThreeDsProcessors/ThreeDsProcessorHome.res
Labels: S-waiting-on-review

#2871 fix: configure pmts filter issues
  src/components/Filter.res
  src/screens/ConfigurePMTs/paymentMethodList.res
Labels: S-waiting-on-review, C-bug

#2880 fix: new authentication analytics key and dimensions changes
  src/screens/NewAnalytics/NewAuthenticationAnalytics/NewAuthenticationAnalytics.res
Labels: S-waiting-on-review, C-bug

#2300 chore: themes release
  README.md
  config/config.toml
  src/APIUtils/APIUtils.res
  src/UIConifg/UIConfig.res
  src/context/ThemeProvider.res
  src/entryPoints/AuthModule/AuthUtils.res
  src/entryPoints/AuthModule/AuthWrapper.res
  src/entryPoints/AuthModule/Common/CommonAuthUtils.res
  src/entryPoints/AuthModule/TwoFaAuth/TwoFaAuth.res
  src/entryPoints/AuthModule/UserInfo/UserInfoProvider.res
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/HyperSwitchEntry.res
  src/entryPoints/HyperSwitchEntryUtils.res
  src/entryPoints/configs/HyperSwitchConfigTypes.res
  src/entryPoints/configs/HyperSwitchDefaultConfig.res
  src/hooks/AuthHooks.res
  src/screens/Helpers/PageLoaderWrapper.res
  src/screens/Hooks/MerchantSpecificConfigHook.res
  src/screens/Hooks/OMPSwitchHooks.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/Settings/HSwitchProfile/HSwitchProfileSettings.res
  src/screens/Sidebar/OrgSidebar.res
  src/screens/Sidebar/Sidebar.res
  tailwind.config.js
Labels: S-waiting-on-review, C-feature

#2891 chore: added send invite mixpanel event
  src/screens/UserManagement/UserRevamp/InviteMember.res
Labels: S-waiting-on-review

#2889 refactor: removed form values spy
  src/Recon/ReconScreens/ReconConfiguration/ConnectProcessors/ConnectProcessorsHelper.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RecoveryProcessorsPaymentProcessors/RecoveryConnectorHome.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RecoveryProcessorsPaymentProcessors/RecoveryOnboardingPayments.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingConnectorAuthKeys.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingProcessorsConfigureRetry.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingProcessorsConnectProcessor.res
  src/Vault/VaultScreens/VaultOnboarding.res
  src/components/Filter.res
  src/components/form/FormRenderer.res
  src/screens/ConfigurePMTs/PaymentMethodConfig.res
  src/screens/ConnectorV2/PaymentProcessorSummary.res
  src/screens/Connectors/FraudAndRisk/FRMIntegrationFields.res
  src/screens/Connectors/FraudAndRisk/FRMPaymentMethods.res
  src/screens/Connectors/PMAuthenticationProcessor/PMAuthenticationHome.res
  src/screens/Connectors/PaymentProcessor/ConnectPayPalFlow/ConnectPayPal.res
  src/screens/Connectors/PaymentProcessor/ConnectorAccountDetails.res
  src/screens/Connectors/PaymentProcessor/ConnectorMetaData/ApplePay/ApplePayIntegration.res
  src/screens/Connectors/PaymentProcessor/ConnectorMetaData/ApplePay/ApplePayManualFlow.res
  src/screens/Connectors/PaymentProcessor/ConnectorMetaData/ApplePay/ApplePaySimplifiedFlow.res
  src/screens/Connectors/PaymentProcessor/ConnectorMetaData/BankDebit/BankDebit.res
  src/screens/Connectors/PaymentProcessor/ConnectorMetaData/GooglePay/GPayFlow/GPayDirectFlow.res
  src/screens/Connectors/PaymentProcessor/ConnectorMetaData/GooglePay/GPayFlow/GPayPaymentGatewayFlow.res
  src/screens/Connectors/PaymentProcessor/ConnectorMetaData/GooglePay/GooglePayFlow.res
  src/screens/Connectors/PaymentProcessor/ConnectorMetaData/GooglePay/GooglePayZen.res
  src/screens/Connectors/PaymentProcessor/ConnectorPaymentMethod.res
  src/screens/Connectors/PaymentProcessor/ConnectorUpdateAuthCreds.res
  src/screens/Connectors/PaymentProcessor/ConnectorWalletDetails/Paze/PazeIntegration.res
  src/screens/Connectors/PaymentProcessor/ConnectorWalletDetails/SamsungPay/SamsungPayIntegration.res
  src/screens/Connectors/PayoutProcessor/PayoutProcessorAccountDetails.res
  src/screens/Connectors/PayoutProcessor/PayoutProcessorPaymentMethod.res
  src/screens/Connectors/TaxProcessor/TaxProcessorHome.res
  src/screens/Connectors/ThreeDsProcessors/ThreeDsProcessorHome.res
  src/screens/Developer/PaymentSettings/PaymentSettings.res
  src/screens/Developer/PaymentSettings/PaymentSettingsMetadata.res
  src/screens/GenerateReports/DownloadReportModal.res
  src/screens/Routing/AdvancedRouting/AdvancedRouting.res
  src/screens/Routing/BasicDetailsForm.res
  src/screens/Routing/VolumeSplitRouting/VolumeSplitRouting.res
  src/screens/SbxOnboardingSurvey/SbxOnboardingSurvey.res
  src/screens/Surcharge/Surcharge.res
  src/screens/ThreeDSFlow/HSwitchThreeDS.res
  src/screens/UserManagement/UserRevamp/CreateCustomRole.res
Labels: S-waiting-on-review, C-chore

#2890 fix: added success toast after updating connector credentials
  src/screens/Connectors/PaymentProcessor/ConnectorUpdateAuthCreds.res
Labels: S-waiting-on-review, C-bug

#2885 chore: Addition of letter spacing in tailwind
  tailwind.config.js
Labels: S-waiting-on-review, C-chore

#2881 fix: payment show details fetch when payment id changes
  src/screens/Transaction/Order/ShowOrder.res
Labels: S-waiting-on-review, C-chore

#2899 fix: webhook url not configured text update
  src/screens/Developer/Webhooks/Webhooks.res
Labels: S-waiting-on-review

#2893 chore: Typography standardisation Tokens initialisation
  src/Typography/Typography.res
  src/Typography/TypographyTypes.res
  src/Typography/TypographyUtils.res
  tailwind.config.js
Labels: S-waiting-on-review, C-chore, C-enhancement
