Repository juspay/hyperswitch-control-center, pull requests merged in 2025-03, with the labels that each got.

#2345 chore: customization for charts and tabs
  public/hyperswitch/Recon/landing.svg
  public/hyperswitch/icons/solid.svg
  src/components/Graphs/ColumnGraph/ColumnGraphTypes.res
  src/components/Graphs/ColumnGraph/ColumnGraphUtils.res
  src/components/Graphs/StackedBarGraph/StackedBarGraphTypes.res
  src/components/Graphs/StackedBarGraph/StackedBarGraphUtils.res
  src/components/LoadedTableWithCustomColumns.res
  src/components/Tabs.res
  src/components/Tabs.resi
  src/utils/LogicUtils.res
  src/utils/LogicUtilsTypes.res
  tailwind.config.js
Labels: S-waiting-on-review, chore

#2351 fix: overflow profile in SDK checkout page
  src/screens/SDKPayment/SDKPage.res
Labels: S-waiting-on-review, C-ui

#2353 chore: UI changes for vault
  src/Vault/VaultScreens/VaultConnectors/VaultConfiguration.res
  src/Vault/VaultScreens/VaultDefaultHome.res
  src/Vault/VaultScreens/VaultHome.res
  src/Vault/VaultScreens/VaultHomeUtils.res
Labels: chore

#2356 chore: Update wallet additional details for v2
  src/fragments/ConnectorFragments/ConnectorPaymentMethodv2/Sections/OtherPaymentMethod.res
  src/screens/Connectors/PaymentProcessor/ConnectorUIUtils/PaymentMethod.res
  src/screens/Connectors/PaymentProcessor/PaymentMethodAdditionalDetails/AdditionalDetailsSidebar.res
Labels: S-waiting-on-review

#2364 fix: fraud and risk connector list bug fix
  src/screens/Connectors/FraudAndRisk/FRMSelect.res
Labels: S-waiting-on-review, core

#2366 refactor: moved recon app, screens, container into Recon folder
  src/Recon/ReconApp/ReconApp.res
  src/Recon/ReconApp/ReconSidebarValues.res
  src/Recon/ReconContainer/ReconAnalyticsContainer.res
  src/Recon/ReconContainer/ReconConfigurationContainer.res
  src/Recon/ReconContainer/ReconHomeContainer.res
  src/Recon/ReconContainer/ReconOnBoardingContainer.res
  src/Recon/ReconScreens/ReconAnalytics/ReconAnalytics.res
  src/Recon/ReconScreens/ReconConfiguration/ConnectOrderData/ConnectOrderData.res
  src/Recon/ReconScreens/ReconConfiguration/ConnectOrderData/ConnectOrderDataHelper.res
  src/Recon/ReconScreens/ReconConfiguration/ConnectOrderData/ConnectOrderDataTypes.res
  src/Recon/ReconScreens/ReconConfiguration/ConnectOrderData/ConnectOrderDataUtils.res
  src/Recon/ReconScreens/ReconConfiguration/ConnectProcessorData/ConnectProcessorData.res
  src/Recon/ReconScreens/ReconConfiguration/ConnectProcessorData/ConnectProcessorDataHelper.res
  src/Recon/ReconScreens/ReconConfiguration/ManualMapping/ManualMapping.res
  src/Recon/ReconScreens/ReconConfiguration/ManualMapping/ManualMappingHelper.res
  src/Recon/ReconScreens/ReconConfiguration/ReconConfiguration.res
  src/Recon/ReconScreens/ReconConfiguration/ReconConfigurationHelper.res
  src/Recon/ReconScreens/ReconConfiguration/ReconConfigurationTypes.res
  src/Recon/ReconScreens/ReconConfiguration/ReconConfigurationUtils.res
  src/Recon/ReconScreens/ReconHome/ReconHome.res
  src/Recon/ReconScreens/ReconOnboarding/RecoOnbdConfiguration.res
  src/Recon/ReconScreens/ReconOnboarding/ReconOnbdLanding.res
  src/Recon/ReconScreens/ReconOnboarding/ReconOnboarding.res
Labels: S-waiting-on-review, C-feature

#2362 feat: hypersense product
  config/config.toml
  public/hyperswitch/assets/DefaultHomeHypersenseCard.svg
  public/hyperswitch/icons/solid.svg
  src/APIUtils/APIUtils.res
  src/APIUtils/APIUtilsTypes.res
  src/Hypersense/HypersenseApp/HypersenseApp.res
  src/Hypersense/HypersenseApp/HypersenseSidebarValues.res
  src/Hypersense/HypersenseContainer/HypersenseConfigurationContainer.res
  src/Hypersense/HypersenseContainer/HypersenseHomeContainer.res
  src/Hypersense/HypersenseScreens/HypersenseConfiguration.res
  src/Hypersense/HypersenseScreens/HypersenseHome.res
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/HyperSwitchEntry.res
  src/entryPoints/ProductTypes.res
  src/entryPoints/ProductUtils.res
  src/entryPoints/ProductsSidebarValues.res
  src/entryPoints/SidebarValues.res
  src/entryPoints/VaultApp/VaultApp.res
  src/entryPoints/configs/HyperSwitchConfigTypes.res
  src/screens/DefaultHome/DefaultHomeUtils.res
Labels: S-waiting-on-review, C-feature, chore

#2377 chore: authentication analytics revamp
  src/screens/Analytics/AnalyticsTypes.res
  src/screens/Analytics/AuthenticationAnalytics/AuthenticationAnalyticsEntity.res
Labels: analytics

#2381 feat: Add force 3ds challenge
  src/screens/Developer/PaymentSettings/PaymentSettings.res
  src/screens/Developer/PaymentSettings/PaymentSettingsListEntity.res
  src/screens/Settings/BusinessMapping/BusinessMappingEntity.res
  src/screens/Settings/HSwitchSettingTypes.res
  src/screens/Settings/MerchantAccountUtils.res
  src/utils/Mappers/BusinessProfileMapper.res
Labels: S-waiting-on-review, C-feature

#2374 feat: apm onboarding page
  public/hyperswitch/AlternatePaymentMethods/ApplePay.svg
  public/hyperswitch/AlternatePaymentMethods/GooglePay.svg
  public/hyperswitch/AlternatePaymentMethods/Klarna.svg
  public/hyperswitch/AlternatePaymentMethods/Paypal.svg
  public/hyperswitch/AlternatePaymentMethods/Paze.svg
  public/hyperswitch/AlternatePaymentMethods/SamsungPay.svg
  src/AlternatePaymentMethods/AlternatePaymentMethodsOnboarding.res
  src/AlternatePaymentMethods/AlternatePaymentMethodsSetup.res
  src/AlternatePaymentMethods/AlternatePaymentMethodsTypes.res
  src/AlternatePaymentMethods/AlternatePaymentMethodsUtils.res
  src/entryPoints/AlternatePaymentMethods/AlternatePaymentMethodsApp.res
Labels: S-waiting-on-review, core

#2387 feat: add juspaythreeds connector addition
  public/hyperswitch/Gateway/JUSPAYTHREEDSSERVER.svg
  public/hyperswitch/wasm/euclid_bg.wasm
  public/hyperswitch/wasm/package.json
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review

#2389 feat: authentication analytics page
  src/APIUtils/APIUtils.res
  src/APIUtils/APIUtilsTypes.res
  src/components/CustomCharts/FunnelChart.res
  src/container/AnalyticsContainer.res
  src/screens/Analytics/AuthenticationAnalyticsV2/AuthenticationAnalyticsV2.res
  src/screens/Analytics/AuthenticationAnalyticsV2/AuthenticationAnalyticsV2Helper.res
  src/screens/Analytics/AuthenticationAnalyticsV2/AuthenticationAnalyticsV2Types.res
  src/screens/Analytics/AuthenticationAnalyticsV2/AuthenticationAnalyticsV2Utils.res
Labels: S-waiting-on-review, chore

#2379 chore: Intelligent routing
  config/config.toml
  public/hyperswitch/IntelligentRouting/SAMPLEFILE.svg
  public/hyperswitch/IntelligentRouting/UPLOADFILE.svg
  public/hyperswitch/icons/solid.svg
  src/APIUtils/APIUtils.res
  src/APIUtils/APIUtilsTypes.res
  src/IntelligentRoutingScreens/IntelligentRoutingAnalytics.res
  src/IntelligentRoutingScreens/IntelligentRoutingConfiguration.res
  src/IntelligentRoutingScreens/IntelligentRoutingHome.res
  src/IntelligentRoutingScreens/IntelligentRoutingReviewFieldsEntity.res
  src/IntelligentRoutingScreens/IntelligentRoutingTypes.res
  src/IntelligentRoutingScreens/IntelligentRoutingUtils.res
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/IntelligentRouting/IntelligentRoutingApp.res
  src/entryPoints/IntelligentRouting/IntelligentaRoutingSidebarValues.res
  src/entryPoints/ProductTypes.res
  src/entryPoints/ProductUtils.res
  src/entryPoints/ProductsSidebarValues.res
  src/entryPoints/SidebarValues.res
Labels: S-waiting-on-review, core

#2391 fix: hypersense svg rendering on the home page
  src/Hypersense/HypersenseScreens/HypersenseHome.res
Labels: S-waiting-on-review, bug

#2395 fix: changed metrics calculations
  src/screens/Analytics/AuthenticationAnalyticsV2/AuthenticationAnalyticsV2.res
Labels: S-waiting-on-review, C-bug, bug

#2400 fix: Advanced routing responsiveness
  src/screens/Routing/AdvancedRouting/AdvancedRouting.res
Labels: C-ui

#2401 Chore: Intelligent routing transaction table
  public/hyperswitch/icons/solid.svg
  src/APIUtils/APIUtils.res
  src/APIUtils/APIUtilsTypes.res
  src/IntelligentRoutingScreens/IntelligentRoutingAnalytics.res
  src/IntelligentRoutingScreens/IntelligentRoutingConfiguration.res
  src/IntelligentRoutingScreens/IntelligentRoutingTransactionsEntity.res
  src/IntelligentRoutingScreens/IntelligentRoutingTypes.res
  tailwind.config.js
Labels: S-waiting-on-review

#2404 feat: added filters in the authentication analytics
  src/APIUtils/APIUtils.res
  src/APIUtils/APIUtilsTypes.res
  src/container/AnalyticsContainer.res
  src/screens/Analytics/AuthenticationAnalyticsV2/AuthenticationAnalyticsV2.res
  src/screens/Analytics/AuthenticationAnalyticsV2/AuthenticationAnalyticsV2Utils.res
  src/screens/NewAnalytics/NewAnalyticsTypes.res
  src/screens/NewAnalytics/NewAnalyticsUtils.res
  src/screens/NewAnalytics/NewAuthenticationAnalytics/NewAuthenticationAnalytics.res
  src/screens/NewAnalytics/NewAuthenticationAnalytics/NewAuthenticationAnalyticsHelper.res
  src/screens/NewAnalytics/NewAuthenticationAnalytics/NewAuthenticationAnalyticsTypes.res
  src/screens/NewAnalytics/NewAuthenticationAnalytics/NewAuthenticationAnalyticsUtils.res
Labels: S-waiting-on-review, chore

#2410 fix: custom orchestrator navigation
  src/APIUtils/APIUtils.res
  src/APIUtils/APIUtilsTypes.res
  src/Hypersense/HypersenseScreens/HypersenseConfiguration.res
  src/Hypersense/HypersenseScreens/HypersenseHome.res
  src/entryPoints/AuthModule/ProductSelection/ProductSelectionProvider.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/ProductTypes.res
  src/entryPoints/ProductUtils.res
  src/entryPoints/ProductsSidebarValues.res
  src/entryPoints/SidebarValues.res
  src/screens/DefaultHome/DefaultHomeTypes.res
  src/screens/DefaultHome/DefaultHomeUtils.res
  src/screens/OMPSwitch/MerchantSwitch.res
Labels: S-waiting-on-review, bug

#2414 chore: added version in user info
  src/APIUtils/APIUtils.res
  src/Vault/VaultScreens/VaultCustomersAndTokens/VaultCustomerSummary.res
  src/Vault/VaultScreens/VaultCustomersAndTokens/VaultCustomersAndTokens.res
  src/Vault/VaultScreens/VaultCustomersAndTokens/VaultPaymentMethodDetailsSidebar.res
  src/entryPoints/AuthModule/UserInfo/UserInfoTypes.res
  src/entryPoints/AuthModule/UserInfo/UserInfoUtils.res
  src/hooks/AuthHooks.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/ResultsTableUtils.res
  src/screens/OMPSwitch/OMPSwitchTypes.res
  src/screens/OMPSwitch/OMPSwitchUtils.res
  src/screens/OMPSwitch/ProfileSwitch.res
  src/screens/Payouts/PayoutsUtils.res
  src/screens/Transaction/Order/OrderUIUtils.res
  src/screens/Transaction/Refunds/RefundUtils.res
Labels: chore

#2419 chore: added v2 merchant creation and listing
  src/APIUtils/APIUtils.res
  src/APIUtils/APIUtilsTypes.res
  src/RevenueRecovery/RevenueRecoveryContainer/RecoveryConnectorContainer.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RecoveryProcessorsPaymentProcessors/RecoveryConnectorHome.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RecoveryProcessorsPaymentProcessors/RecoveryOnboardingPayments.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingConnectorsSummary.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/RecoveryOnboardingBilling.res
  src/Vault/VaultContainer/VaultContainer.res
  src/Vault/VaultScreens/VaultOnboarding.res
  src/entryPoints/AuthModule/ProductSelection/ProductSelectionProvider.res
  src/screens/ConnectorV2/PaymentProcessorSummary.res
  src/screens/Hooks/ConnectorListHook.res
  src/screens/OMPSwitch/MerchantSwitch.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
Labels: S-waiting-on-review, chore

#2415 chore: APM screen for orchestrator
  public/hyperswitch/AlternatePaymentMethods/AlternatePaymentMethodsOnboarding.svg
  public/hyperswitch/icons/solid.svg
  src/AlternatePaymentMethods/AlternatePaymentMethodsHome.res
  src/AlternatePaymentMethods/AlternatePaymentMethodsOnboarding.res
  src/AlternatePaymentMethods/AlternatePaymentMethodsSetup.res
  src/AlternatePaymentMethods/AlternatePaymentMethodsTypes.res
  src/AlternatePaymentMethods/AlternatePaymentMethodsUtils.res
  src/container/APMContainer.res
  src/entryPoints/AlternatePaymentMethods/AlternatePaymentMethodsApp.res
  src/entryPoints/AlternatePaymentMethods/AlternatePaymentMethodsSidebarValues.res
  src/entryPoints/AuthModule/ProductSelection/ProductSelectionProvider.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/ProductTypes.res
  src/entryPoints/ProductUtils.res
  src/entryPoints/ProductsSidebarValues.res
  src/entryPoints/SidebarValues.res
  src/screens/AlternatePaymentMethods/AltPaymentMethods.res
  src/screens/AlternatePaymentMethods/AltPaymentMethodsType.res
  src/screens/AlternatePaymentMethods/AltPaymentMethodsUtils.res
  src/screens/OMPSwitch/MerchantSwitch.res
Labels: S-waiting-on-review, C-feature

#2424 chore: routing design updates for ui
  public/hyperswitch/IntelligentRouting/STREAMLIVEDATA.svg
  src/IntelligentRoutingScreens/IntelligentRoutingAnalytics.res
  src/IntelligentRoutingScreens/IntelligentRoutingConfiguration.res
  src/IntelligentRoutingScreens/IntelligentRoutingHelper.res
  src/IntelligentRoutingScreens/IntelligentRoutingHome.res
  src/IntelligentRoutingScreens/IntelligentRoutingReviewFieldsEntity.res
  src/IntelligentRoutingScreens/IntelligentRoutingTypes.res
  src/IntelligentRoutingScreens/IntelligentRoutingUtils.res
Labels: S-waiting-on-review

#2433 feat: add generate reports for auth analytics
  src/APIUtils/APIUtils.res
  src/APIUtils/APIUtilsTypes.res
  src/screens/NewAnalytics/NewAuthenticationAnalytics/NewAuthenticationAnalytics.res
Labels: S-waiting-on-review

#2426 chore: added v2 merchant switch apis
  src/APIUtils/APIUtils.res
  src/APIUtils/APIUtilsTypes.res
  src/Hypersense/HypersenseApp/HypersenseApp.res
  src/Hypersense/HypersenseApp/HypersenseSidebarValues.res
  src/entryPoints/AuthModule/ProductSelection/ProductSelectionProvider.res
  src/entryPoints/AuthModule/ProductSelection/ProductSelectionState.res
  src/entryPoints/HyperSwitchApp.res
  src/entryPoints/ProductTypes.res
  src/entryPoints/ProductUtils.res
  src/entryPoints/ProductsSidebarValues.res
  src/entryPoints/SidebarValues.res
  src/hooks/AuthHooks.res
  src/screens/Hooks/MerchantDetailsHook.res
  src/screens/Hooks/OMPSwitchHooks.res
  src/screens/OMPSwitch/MerchantSwitch.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/OMPSwitch/OMPSwitchUtils.res
  src/screens/OMPSwitch/OrgSwitch.res
  src/screens/OMPSwitch/ProfileSwitch.res
  src/screens/Sidebar/OrgSidebar.res
  src/screens/UserManagement/UserRevamp/UserUtils.res
  src/utils/LogicUtils.res
  src/utils/Mappers/MerchantAccountDetailsMapper.res
Labels: chore

#2440 fix: add v1 - authentication analytics
  src/APIUtils/APIUtils.res
Labels: S-waiting-on-review

#2435 feat: recovery overview screen update and filters added
  public/hyperswitch/icons/solid.svg
  src/APIUtils/APIUtils.res
  src/APIUtils/APIUtilsTypes.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryOverview/RevenueRecoveryEntity.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryOverview/RevenueRecoveryOrderTypes.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryOverview/RevenueRecoveryOrderUtils.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryOverview/RevenueRecoveryOverview.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryOverview/ShowRevenueRecovery.res
  src/components/FilterSelectBox.res
  src/components/InputFields.res
  src/components/InputFields.resi
  src/screens/HSwitchRemoteFilter.res
  tailwind.config.js
Labels: S-waiting-on-review, Recovery

#2441 chore: disabled profile creation for v2 merchants
  src/entryPoints/AuthModule/ProductSelection/ProductSelectionProvider.res
  src/screens/OMPSwitch/MerchantSwitch.res
  src/screens/OMPSwitch/ProfileSwitch.res
  src/screens/UserManagement/UserRevamp/UserManagementHelper.res
Labels: C-feature

#2439 fix: smart routing values fix
  src/screens/Routing/AdvancedRouting/AdvancedRoutingUIUtils.res
Labels: C-bug

#2453 fix: connector name - unknown issue
  src/screens/Connectors/ConnectorUtils.res
  src/screens/Transaction/Order/OrderEntity.res
Labels: S-waiting-on-review

#2443 fix: column graph tooltip formatter listing
  src/IntelligentRoutingScreens/IntelligentRoutingHelper.res
  src/components/Graphs/ColumnGraph/ColumnGraphUtils.res
Labels: S-waiting-on-review, C-bug

#2461 revert: connector name - unknown issue
  src/screens/Connectors/ConnectorUtils.res
  src/screens/Transaction/Order/OrderEntity.res
Labels: S-waiting-on-review

#2463 fix: sort issue of insights
  src/screens/NewAnalytics/NewAuthenticationAnalytics/NewAuthenticationAnalyticsHelper.res
Labels: S-waiting-on-review

#2434 fix: vault product minor fixes
  src/Vault/VaultApp/VaultApp.res
  src/Vault/VaultContainer/VaultContainer.res
  src/Vault/VaultScreens/VaultConnectors/VaultConnectorEntity.res
  src/Vault/VaultScreens/VaultCustomersAndTokens/VaultCustomerSummary.res
  src/Vault/VaultScreens/VaultCustomersAndTokens/VaultPaymentMethodDetailsSidebar.res
  src/Vault/VaultScreens/VaultCustomersAndTokens/VaultPaymentMethodDetailsTypes.res
  src/Vault/VaultScreens/VaultCustomersAndTokens/VaultPaymentMethodDetailsUtils.res
  src/Vault/VaultScreens/VaultOnboarding.res
  src/entryPoints/AuthModule/ProductSelection/ProductSelectionProvider.res
  src/screens/OMPSwitch/MerchantSwitch.res
Labels: bug

#2469 chore: get production access
  src/IntelligentRoutingScreens/IntelligentRoutingAnalytics.res
Labels: S-waiting-on-review

#2467 fix: vault landing and connector api call changes
  src/APIUtils/APIUtils.res
  src/Vault/VaultScreens/VaultDefaultHome.res
  src/Vault/VaultScreens/VaultOnboarding.res
  src/entryPoints/AuthModule/ProductSelection/ProductSelectionProvider.res
  src/entryPoints/ProductUtils.res
  src/screens/ConnectorV2/PaymentProcessorSummary.res
Labels: bug

#2477 fix: added acl for get started in product home
  src/APIUtils/APIUtils.res
  src/Hypersense/HypersenseScreens/HypersenseConfiguration.res
  src/IntelligentRoutingScreens/IntelligentRoutingHome.res
  src/Recon/ReconScreens/ReconOnboarding/ReconOnboardingHelper.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryOnboarding/RevenueRecoveryOnboardingLanding.res
  src/Vault/VaultScreens/VaultCustomersAndTokens/VaultCustomersTotalDataView.res
  src/Vault/VaultScreens/VaultHome.res
Labels: bug

#2471 chore: recon mixpanel events
  src/Hypersense/HypersenseScreens/HypersenseConfiguration.res
  src/Hypersense/HypersenseScreens/HypersenseHome.res
  src/Recon/ReconScreens/ReconConfiguration/ConnectProcessors/ConnectProcessors.res
  src/Recon/ReconScreens/ReconConfiguration/Final/Final.res
  src/Recon/ReconScreens/ReconConfiguration/OrderDataConnection/OrderDataConnection.res
  src/Recon/ReconScreens/ReconOnboarding/ReconOnboardingHelper.res
  src/Recon/ReconScreens/ReconReports/ReconReports.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RecoveryProcessorsPaymentProcessors/RecoveryOnboardingPayments.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingProcessorsReviewDetails.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/RecoveryOnboardingBilling.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryOnboarding/RevenueRecoveryOnboardingLanding.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryOnboarding/RevenueRecoveryOnboardingUtils.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryOverview/RevenueRecoveryOverview.res
Labels: S-waiting-on-review

#2473 chore: api headers change for Dynamic Routing (Intelligent Routing) (Modularity)
  src/hooks/AuthHooks.res
Labels: S-waiting-on-review

#2485 fix: added acl changes
  src/Hypersense/HypersenseScreens/HypersenseConfiguration.res
  src/IntelligentRoutingScreens/IntelligentRoutingHome.res
  src/Recon/ReconScreens/ReconOnboarding/ReconOnboardingHelper.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryOnboarding/RevenueRecoveryOnboardingLanding.res
  src/Vault/VaultScreens/VaultHome.res
Labels: bug

#2492 chore: routing minor ui fixes
  src/IntelligentRoutingScreens/IntelligentRoutingConfiguration.res
  src/IntelligentRoutingScreens/IntelligentRoutingHelper.res
  src/IntelligentRoutingScreens/IntelligentRoutingReviewFieldsEntity.res
  src/IntelligentRoutingScreens/IntelligentRoutingTransactionsEntity.res
  src/components/Graphs/ColumnGraph/ColumnGraphUtils.res
  src/components/Graphs/LineAndColumn/LineAndColumnGraphTypes.res
  src/components/Graphs/LineAndColumn/LineAndColumnGraphUtils.res
  src/components/Graphs/LineGraph/LineGraphTypes.res
  src/components/Graphs/LineGraph/LineGraphUtils.res
Labels: S-waiting-on-review

#2497 fix: payout processor unknown issue
  src/screens/Payouts/PayoutsEntity.res
Labels: S-waiting-on-review

#2504 fix: metrics - frictionless flow count
  src/screens/NewAnalytics/NewAuthenticationAnalytics/NewAuthenticationAnalyticsUtils.res
Labels: S-waiting-on-review

#2511 fix: resolved issues when applying filters
  src/screens/NewAnalytics/NewAuthenticationAnalytics/NewAuthenticationAnalytics.res
Labels: S-waiting-on-review, bug

#2502 fix: recon tabs and mixpanel event changes
  src/Recon/ReconApp/ReconSidebarValues.res
  src/Recon/ReconHelper.res
  src/Recon/ReconScreens/ReconOnboarding/ReconOnboarding.res
  src/Recon/ReconScreens/ReconOnboarding/ReconOnboardingHelper.res
  src/Recon/ReconScreens/ReconReports/ReconReports.res
  src/entryPoints/AuthModule/AuthWrapper.res
Labels: S-waiting-on-review, C-bug

#2466 refactor: Add constraints in smart routing rule configuration
  src/screens/Routing/AdvancedRouting/AdvancedRouting.res
  src/screens/Routing/AdvancedRouting/AdvancedRoutingUtils.res
Labels: S-waiting-on-review, C-feature

#2519 fix: Connector list not updated on profile switch fix
  src/Vault/VaultScreens/VaultConnectors/VaultConnectorUtils.res
  src/Vault/VaultScreens/VaultConnectors/VaultProcessorList.res
  src/entryPoints/HyperSwitchApp.res
  src/screens/Analytics/GlobalSearch/GlobalSearchBar.res
  src/screens/OMPSwitch/MerchantSwitch.res
  src/screens/OMPSwitch/OMPSwitchUtils.res
  src/screens/OMPSwitch/ProfileSwitch.res
  src/utils/LogicUtils.res
Labels: bug

#2577 feat: added issuer filter - auth analytics
  src/screens/Analytics/HSAnalyticsUtils.res
Labels: S-waiting-on-review

#2515 fix: show edit and copy icon in MP dropdowns mobile
  src/screens/OMPSwitch/OMPSwitchHelper.res
Labels: S-waiting-on-review, bug

#2535 chore: routing minor ui fixes
  src/IntelligentRoutingScreens/IntelligentRoutingAnalytics.res
  src/IntelligentRoutingScreens/IntelligentRoutingConfiguration.res
  src/IntelligentRoutingScreens/IntelligentRoutingHelper.res
  src/IntelligentRoutingScreens/IntelligentRoutingReviewFieldsEntity.res
  src/IntelligentRoutingScreens/IntelligentRoutingTransactionsEntity.res
  src/IntelligentRoutingScreens/IntelligentRoutingTypes.res
  src/IntelligentRoutingScreens/IntelligentRoutingUtils.res
  src/components/Graphs/LineAndColumn/LineAndColumnGraphTypes.res
  src/components/Graphs/LineAndColumn/LineAndColumnGraphUtils.res
  src/entryPoints/AuthModule/ProductSelection/ProductSelectionProvider.res
  src/screens/OMPSwitch/MerchantSwitch.res
  src/screens/UserManagement/UserRevamp/UserUtils.res
  tailwind.config.js
Labels: S-waiting-on-review

#2505 chore: product type sidebar update on org switch
  src/APIUtils/APIUtils.res
  src/entryPoints/AuthModule/ProductSelection/ProductSelectionProvider.res
  src/entryPoints/AuthModule/ProductSelection/ProductSelectionState.res
  src/entryPoints/HyperSwitchApp.res
Labels: S-waiting-on-review, chore

#2585 fix: operations external url
  src/screens/Transaction/Order/HSwitchOrderUtils.res
  src/utils/GlobalVars.res
Labels: bug

#2641 fix: removed actions, text changes, date changes
  src/Recon/ReconScreens/ReconConfiguration/Final/Final.res
  src/Recon/ReconScreens/ReconReports/ReconReports.res
  src/Recon/ReconScreens/ReconReports/ReportsExceptionTableEntity.res
  src/Recon/ReconScreens/ReconReports/ReportsTableEntity.res
  src/Recon/ReconScreens/ReconReports/ReportsTypes.res
  src/Recon/ReconScreens/ReconReports/ShowAllReports.res
  src/Recon/ReconScreens/ReconReports/ShowReconExceptionReport.res
  src/Recon/ReconScreens/ReconReports/TempReportsData/ReportsData.res
Labels: S-waiting-on-review, C-feature, bug

#2640 fix: switch url redirection issue
  src/entryPoints/FeatureFlagUtils.res
  src/entryPoints/HyperSwitchApp.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/PaymentAttempt/PaymentAttemptEntity.res
  src/screens/Analytics/GlobalSearchResults/GlobalSearchTables/PaymentIntent/PaymentIntentEntity.res
  src/screens/Hooks/MerchantSpecificConfigHook.res
  src/screens/Hooks/OMPSwitchHooks.res
  src/screens/OMPSwitch/MerchantSwitch.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/Sidebar/OrgSidebar.res
  src/screens/Transaction/Order/HSwitchOrderUtils.res
  src/server/config.mjs
  src/utils/GlobalVars.res
Labels: bug, chore

#2606 chore: billing connector metadata update
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingProcessorsUtils.res
Labels: S-waiting-on-review, Recovery

#2629 chore: configure retry tooltip text
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingProcessorsConfigureRetry.res
Labels: S-waiting-on-review, Recovery

#2359 feat: added checkbox for allowed auth methods in google pay
  src/screens/Connectors/PaymentProcessor/ConnectorMetaData/GooglePay/GooglePayIntegration.res
  src/screens/Connectors/PaymentProcessor/ConnectorMetaData/GooglePay/GooglePayUtils.res
Labels: S-waiting-on-review, C-feature

#2643 chore: made chargebee webhooks details field as required
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/RecoveryOnboardingBilling.res
  src/screens/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review, Recovery

#2655 fix: logo aspect ratio
  src/entryPoints/HyperSwitchApp.res
Labels: S-waiting-on-review, C-ui

#2658 feat: added new connector redsys
  public/hyperswitch/Gateway/REDSYS.svg
  src/screens/Connectors/ConnectorTypes.res
  src/screens/Connectors/ConnectorUtils.res
Labels: S-waiting-on-review, core

#2659 feat: wasm update for redsys
  public/hyperswitch/wasm/euclid_bg.wasm
Labels: S-waiting-on-review, core

#2650 feat: added threeds requestor app url in payment settings
  src/screens/Developer/APIKeys/DeveloperUtils.res
  src/screens/Developer/PaymentSettings/PaymentSettings.res
  src/screens/Settings/HSwitchSettingTypes.res
  src/screens/Settings/MerchantAccountUtils.res
  src/utils/Mappers/BusinessProfileMapper.res
  tailwind.config.js
Labels: feature

#2664 refactor: recon ui changes in analytics
  public/hyperswitch/icons/solid.svg
  src/Recon/ReconScreens/ReconConfiguration/ReconConfigurationHelper.res
  src/Recon/ReconScreens/ReconOnboarding/ReconOnboardingHelper.res
  src/Recon/ReconScreens/ReconReports/ReconExceptionsList.res
  src/Recon/ReconScreens/ReconReports/ReconExceptionsUtils.res
  src/Recon/ReconScreens/ReconReports/ReconReportUtils.res
  src/Recon/ReconScreens/ReconReports/ReconReports.res
  src/Recon/ReconScreens/ReconReports/ReconReportsList.res
  src/Recon/ReconScreens/ReconReports/ReportStatus.res
  src/Recon/ReconScreens/ReconReports/ReportsExceptionTableEntity.res
  src/Recon/ReconScreens/ReconReports/ReportsTableEntity.res
  src/Recon/ReconScreens/ReconReports/ReportsTypes.res
  src/Recon/ReconScreens/ReconReports/ShowAllReports.res
  src/Recon/ReconScreens/ReconReports/ShowReconExceptionReport.res
  src/components/Graphs/StackedBarGraph/StackedBarGraphTypes.res
  src/components/Graphs/StackedBarGraph/StackedBarGraphUtils.res
Labels: S-waiting-on-review, C-feature

#2633 chore: remove profile level report - auth analytics
  src/screens/NewAnalytics/NewAuthenticationAnalytics/NewAuthenticationAnalytics.res
Labels: S-waiting-on-review

#2672 fix: analytics insights breaking fix
  src/IntelligentRoutingScreens/IntelligentRoutingAnalytics.res
  src/IntelligentRoutingScreens/IntelligentRoutingHelper.res
  src/Recon/ReconScreens/ReconOnboarding/ReconOnboardingHelper.res
  src/components/Graphs/LineGraph/LineGraphTypes.res
  src/screens/NewAnalytics/NewAuthenticationAnalytics/NewAuthenticationAnalyticsUtils.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsProcessed/RefundsProcessedUtils.res
  src/screens/NewAnalytics/NewRefundsAnalytics/RefundsSuccessRate/RefundsSuccessRateUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsProcessed/PaymentsProcessedUtils.res
  src/screens/NewAnalytics/PaymentAnalytics/PaymentsSuccessRate/PaymentsSuccessRateUtils.res
  src/screens/NewAnalytics/SmartRetryAnalytics/SmartRetryPaymentsProcessed/SmartRetryPaymentsProcessedUtils.res
  src/utils/LogicUtils.res
  src/utils/LogicUtilsTypes.res
Labels: S-waiting-on-review

#2677 fix: Payout routing default fallback connector label
  src/screens/PayoutRouting/PayoutRoutingConfigure.res
  src/screens/Routing/DefaultRouting/DefaultRouting.res
  src/screens/Routing/RoutingConfigure.res
Labels: S-waiting-on-review, C-bug

#2669 Chore: UI enhancements intelligent routing
  src/IntelligentRoutingScreens/IntelligentRoutingAnalytics.res
  src/IntelligentRoutingScreens/IntelligentRoutingConfiguration.res
  src/IntelligentRoutingScreens/IntelligentRoutingHelper.res
  src/IntelligentRoutingScreens/IntelligentRoutingTransactionsEntity.res
  src/IntelligentRoutingScreens/IntelligentRoutingTypes.res
  src/IntelligentRoutingScreens/IntelligentRoutingUtils.res
  src/Vault/VaultScreens/VaultCustomersAndTokens/VaultCustomerSummary.res
  src/screens/NewAnalytics/NewAnalyticsUtils.res
  tailwind.config.js
Labels: S-waiting-on-review

#2678 fix: sticky vertical step indicator in onboarding
  src/IntelligentRoutingScreens/IntelligentRoutingConfiguration.res
  src/Recon/ReconScreens/ReconConfiguration/ReconConfiguration.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RecoveryProcessorsPaymentProcessors/RecoveryOnboardingPayments.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingConnectorAuthKeys.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingProcessorsWebhooks.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryOnboarding/RevenueRecoveryOnboarding.res
  src/Vault/VaultScreens/VaultConnectors/VaultProceesorReview.res
  src/Vault/VaultScreens/VaultOnboarding.res
  src/fragments/VerticalStepIndicator/VerticalStepIndicator.res
Labels: S-waiting-on-review, C-feature

#2682 fix: switching merchants in modularity products
  src/entryPoints/HyperSwitchApp.res
  src/fragments/ConnectorFragments/ConnectorPaymentMethodv2/PMSelectAll.res
  src/screens/Hooks/OMPSwitchHooks.res
  src/utils/GlobalVars.res
Labels: S-waiting-on-review, bug

#2681 fix: rule based routing month issue in description
  src/screens/Routing/AdvancedRouting/AdvancedRoutingUtils.res
  src/screens/Routing/RoutingUtils.res
Labels: bug

#2638 feat: recovery dummy data flow
  src/Recon/ReconScreens/ReconConfiguration/ConnectProcessors/ConnectProcessorsHelper.res
  src/RevenueRecovery/RevenueRecoveryApp/RevenueRecoveryApp.res
  src/RevenueRecovery/RevenueRecoveryContainer/RecoveryConnectorContainer.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RecoveryProcessorsPaymentProcessors/RecoveryConnectorUtils.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RecoveryProcessorsPaymentProcessors/RecoveryOnboardingPayments.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingConnectorAuthKeys.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingConnectorsSummary.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/RecoveryOnboardingBilling.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryOnboarding/RevenueRecoveryData.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryOnboarding/RevenueRecoveryOnboardingUtils.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryOverview/RevenueRecoveryEntity.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryOverview/RevenueRecoveryOrderTypes.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryOverview/RevenueRecoveryOverview.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryOverview/ShowRevenueRecovery.res
  src/fragments/ConnectorFragments/ConnectorAuthKeys/ConnectorAuthKeys.res
Labels: S-waiting-on-review, Recovery

#2688 fix: recon ui changes and processor validation
  src/Recon/ReconScreens/ReconConfiguration/ConnectProcessors/ConnectProcessors.res
  src/Recon/ReconScreens/ReconConfiguration/ConnectProcessors/ConnectProcessorsHelper.res
  src/Recon/ReconScreens/ReconConfiguration/ConnectProcessors/ConnectProcessorsTypes.res
  src/Recon/ReconScreens/ReconConfiguration/ConnectProcessors/ConnectProcessorsUtils.res
  src/Recon/ReconScreens/ReconReports/ReconExceptionsList.res
  src/Recon/ReconScreens/ReconReports/ReconReportsList.res
Labels: S-waiting-on-review, C-bug

#2693 fix: hyperloader reinitialisation
  src/libraries/Window.res
  src/screens/SDKPayment/WebSDK.res
Labels: S-waiting-on-review

#2645 chore: recovery ui changes
  public/hyperswitch/index.html
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RecoveryProcessorsPaymentProcessors/RecoveryOnboardingPayments.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingConnectorAuthKeys.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingProcessorsConfigureRetry.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingProcessorsConnectProcessor.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingProcessorsReviewDetails.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingProcessorsWebhooks.res
  src/fragments/ConnectorFragments/ConnectorWebhookDetails/ConnectorWebhookPreview.res
  tailwind.config.js
Labels: S-waiting-on-review, Recovery

#2696 fix: close icon on merchant select modal
  src/entryPoints/AuthModule/ProductSelection/ProductSelectionProvider.res
Labels: C-bug

#2648 test: Add workflow tests
  cypress/e2e/6-workflow/PaymentRouting.cy.js
  cypress/e2e/8-settings/users.cy.js
  cypress/start_hyperswitch.sh
  cypress/support/commands.js
  cypress/support/pages/homepage/HomePage.js
  cypress/support/pages/workflow/paymentRouting/DefaultFallback.js
  cypress/support/pages/workflow/paymentRouting/PaymentRouting.js
Labels: C-Testing

#2707 chore: new design changes in intelligent routing
  public/hyperswitch/icons/solid.svg
  src/IntelligentRoutingScreens/IntelligentRoutingAnalytics.res
  src/IntelligentRoutingScreens/IntelligentRoutingHelper.res
  src/components/Graphs/ColumnGraph/ColumnGraphUtils.res
  src/components/Graphs/LineAndColumn/LineAndColumnGraphTypes.res
  src/components/Graphs/LineAndColumn/LineAndColumnGraphUtils.res
  src/components/Graphs/LineGraph/LineGraphTypes.res
  src/components/Graphs/LineGraph/LineGraphUtils.res
  src/components/Graphs/PieGraph/PieGraphTypes.res
  src/components/Graphs/PieGraph/PieGraphUtils.res
  src/screens/NewAnalytics/NewAnalyticsUtils.res
Labels: S-waiting-on-review

#2605 fix: recovery module bug fixes
  src/RevenueRecovery/RevenueRecoveryApp/RevenueRecoveryApp.res
  src/RevenueRecovery/RevenueRecoveryApp/RevenueRecoverySidebarValues.res
  src/RevenueRecovery/RevenueRecoveryContainer/RecoveryConnectorContainer.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RecoveryProcessorsPaymentProcessors/RecoveryOnboardingPayments.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingConnectorAuthKeys.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingConnectorsSummary.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/BillingProcessorsUtils.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryBillingProcessors/RecoveryOnboardingBilling.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryOnboarding/RevenueRecoveryOnboarding.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryOnboarding/RevenueRecoveryOnboardingLanding.res
  src/RevenueRecovery/RevenueRecoveryScreens/RecoveryProcessors/RevenueRecoveryOnboarding/RevenueRecoveryOnboardingUtils.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryOverview/RevenueRecoveryOrderUtils.res
  src/RevenueRecovery/RevenueRecoveryScreens/RevenueRecoveryOverview/RevenueRecoveryOverview.res
  src/entryPoints/ProductUtils.res
  src/screens/DefaultHome/DefaultHomeUtils.res
Labels: S-waiting-on-review, S-Recovery

#2709 refactor: Profile Merchant Labels
  public/hyperswitch/icons/solid.svg
  src/Recon/ReconScreens/ReconConfiguration/ConnectProcessors/ConnectProcessorsHelper.res
  src/Recon/ReconScreens/ReconOnboarding/ReconOnboardingHelper.res
  src/Recon/ReconScreens/ReconReports/ReconReportsHelper.res
  src/components/SelectBox.res
  src/components/SelectBox.resi
  src/screens/OMPSwitch/MerchantSwitch.res
  src/screens/OMPSwitch/OMPSwitchHelper.res
  src/screens/OMPSwitch/ProfileSwitch.res
  src/screens/Sidebar/Sidebar.res
  src/screens/Sidebar/SidebarSwitch.res
  tailwind.config.js
Labels: S-waiting-on-review, C-ui, S-adhoc

#2714 fix: remove resolve button after resolving
  src/Recon/ReconScreens/ReconConfiguration/ConnectProcessors/ConnectProcessorsHelper.res
  src/Recon/ReconScreens/ReconConfiguration/ConnectProcessors/ConnectProcessorsUtils.res
  src/Recon/ReconScreens/ReconConfiguration/OrderDataConnection/OrderDataConnection.res
  src/Recon/ReconScreens/ReconReports/ReconExceptionsUtils.res
  src/Recon/ReconScreens/ReconReports/ShowReconExceptionReport.res
Labels: S-waiting-on-review, C-bug, S-Recon, S-modularity
